### ISSUE TITLE
When the user has selected to have all breach alerts sent to a single email inbox, the email address shown in an alert email is wrong

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1003]
![image](https://user-images.githubusercontent.com/71928/58288089-3b8aa400-7d78-11e9-9187-e9ad7941137e.png)

STR:

1. Sign up/in with a Firefox Account
2. Add and verify a secondary email address (e.g.,  test2@mailinator.com)
3. On `/user/preferences`, select "Send all breach alerts to <primary-email@mailinator.com>
4. Trigger a breach alert to test2@mailinator.com (steps below)
5. Open the breach alert email in the Inbox for primary-email@mailinator.com

Expected results:
The alert email should say "Email address: test2@mailinator.com"

Actual results:
The alert email says "Email address: primary-email@mailinator.com"

Steps to trigger a breach alert for test2@mailinator.com:
```sh
curl http://localhost:6060/hibp/notify -H "Content-Type: application/json" -H "Authorization: Bearer unsafe-default-token-for-dev" -d "{\"breachName\": \"Adobe\", \"hashPrefix\": \"60e411\", \"hashSuffixes\": [\"8eb1c32080fa3ae1a6e3f258d3a25d8ed9\"]}"
```

**Comment by freaktechnik** [comment]
This appears to still be an issue in production. I just got an email saying my primary email was in a new breach, while it was a secondary address.
