### ISSUE TITLE
"fn is not a function" error on dev /hibp/breaches endpoint

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1008]
https://fx-breach-alerts.herokuapp.com/hibp/breaches

I use our endpoint to scrape the breach list, but I guess I've always used the monitor.firefox.com prod link, and maybe nothing internally uses the /hibp/breaches endpoint which is why we havent noticed this throwing an error.

![https___fx-breach-alerts_herokuapp_com_hibp_breaches](https://user-images.githubusercontent.com/557895/58345605-9b7f5a00-7e0d-11e9-8c3e-db5f4e65aa03.png)

**Comment by groovecoder** [comment]
Oh, I removed this endpoint, as we decided not to use it for the Firefox door-hanger UI.

**Comment by pdehaan** [comment]
So, is there any way to get a list of all the breaches, or should I just point all my scripts at HIBP's endpoint now?

**Comment by lesleyjanenorton** [comment]
Is there any harm in us bringing this back? Seems like it might be useful.
