### ISSUE TITLE
Check and set the breach categoryId once when loading breaches instead of at runtime

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1018]
Currently [`getBreachDetail()`](https://github.com/mozilla/blurts-server/blob/b6c5f1e97972ff1bb9f7ea366f3bbc0b81508ec3/template-helpers/breach-detail.js#L183) calls `getBreachCategory()` twice (and `getBreachCategory()` calls 1-5 `if` statements).

https://github.com/mozilla/blurts-server/blob/6c5951f60e795af0e879d45ec54bbcb26c8f5f9b/template-helpers/breach-detail.js#L185-L186

Since breach data never changes after it is loaded, not sure if it'd be worth just doing the check once and adding the breach category in the `app.locals.breaches[]` array. Something like `breach.categoryId = getBreachCategory(breach);`

https://github.com/mozilla/blurts-server/blob/b6c5f1e97972ff1bb9f7ea366f3bbc0b81508ec3/hibp.js#L81-L91

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
