### ISSUE TITLE
Sign up for alerts section has semi-randomized localizations

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1023]
## Steps to reproduce

https://monitor.firefox.com/breach-details/500px

### Actual results

Locales seem nearly random (or cached).

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58498476-f927e500-8132-11e9-8d1a-861a9e4fc46c.png)

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58498491-00e78980-8133-11e9-8448-863fc0d139d6.png)

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58498529-12c92c80-8133-11e9-9c54-39e2f1f2ceea.png)

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58498569-296f8380-8133-11e9-9ca6-f6233c005dd8.png)

**Comment by groovecoder** [comment]
FWIW I noticed the site is sending 2 `Vary` headers in its responses. This could cause an issue ... but it would have to be combined with a handlebars feature/bug/implementation.

**Comment by groovecoder** [comment]
Screenshot of multiple `Vary` headers.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/71928/58499017-d9012180-8144-11e9-8b1c-cc9b4e8b423b.png">

**Comment by groovecoder** [comment]
This happens in heroku too, but not on localhost.

**Comment by groovecoder** [comment]
Fixed by https://github.com/mozilla/blurts-server/pull/1028 ... deployed to https://fx-breach-alerts.herokuapp.com/ and going to stage & prod soon.
