### ISSUE TITLE
CSP violation for account avatars served by Gravatar

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/blurts-server#1032]
I’ve signed up on prod, and my user avatar is set from Gravatar. Because of the CSP violation, the image is blocked, so the menu is completely invisible

<img width="895" alt="Capture d’écran 2019-05-28 à 21 12 15" src="https://user-images.githubusercontent.com/1294206/58509135-be06cf80-818d-11e9-83a1-63570b353c08.png">

**Comment by groovecoder** [comment]
To reproduce, can you show how you set your Firefox Account avatar to be from gravatar.com ?

**Comment by pdehaan** [comment]
I'm not 100% certain, but I think gravatar support was deprecated in FxA, so not sure we can add to an existing FxA account.
But apparently some people may have some lingering avatars.
/cc @mozilla/fxa-devs

**Comment by shane-tomlinson** [comment]
> But apparently some people may have some lingering avatars.

That's a possibility, we never forcibly removed those avatars.

**Comment by shane-tomlinson** [comment]
In fact, we [have this nugget in our CSP rules](https://github.com/mozilla/fxa/blob/0fcb6b1239948b32dca2d0eff23463411b8eaa1f/packages/fxa-content-server/server/lib/csp/blocking.js#L71):

>        // Gravatar support was removed in #4927, but we don't want
>        // to break the site for users who already use a Gravatar as
>        // their profile image.
>        GRAVATAR,

**Comment by groovecoder** [comment]
Do we have an idea how many FxA users still use gravatar images? I'd rather not include sub-resources from gravatar.com.

**Comment by shane-tomlinson** [comment]
> Do we have an idea how many FxA users still use gravatar images? I'd rather not include sub-resources from gravatar.com.

Very few I imagine, though really I have no idea. This is a question for @jbuck.

@jbuck Is querying the profile server DB for how many people have gravatar profiles set something we can do?so, can you make it happen?

**Comment by jbuck** [comment]
1.67% of profiles have a gravatar URL

**Comment by groovecoder** [comment]
Okay, I'm going to close this on the assumption that number is going *down* over time, and we don't want to keep our CSP as tight as possible.
