### ISSUE TITLE
Copy refinements for V2 website

### ISSUE THREAD

**Issue by betsymi** [mozilla/blurts-server#1034]
These copy changes didn't make it in yet, so documenting them here. 

Location | New Copy | Old Copy | Done
-- | -- | -- | --
[Home](https://monitor.firefox.com/) | See if you’ve been part of an online data breach. | See if you’ve been in an online data breach. | ✅
[Home](https://monitor.firefox.com/) | Get ongoing breach monitoring for multiple email addresses. | Search all your email addresses for breaches and get alerts about new threats. | ✅
[Breach Detail: Website](https://monitor.firefox.com/breach-details/MyFitnessPal) | On January 1, 2018, MyFitnessPal was breached. Once the breach was discovered and verified, it was added to our database on February 2, 2019. | On January 1, 2018, MyFitnessPal suffered a breach. Once the breach was discovered and verified it was added to our database on February 2, 2019.
[Breach Detail: Website](https://monitor.firefox.com/breach-details/MyFitnessPal) | What to do after a website breach: | What to do after a data breach:
[Breach Detail: Data Aggregator](https://monitor.firefox.com/breach-details/exactis) | On June 1, 2018, Exactis was breached. Once the breach was discovered and verified, it was added to our database on July 25, 2018. | On June 1, 2018, Exactis suffered a breach. Once the breach was discovered and verified it was added to our database on July 25, 2018.
[Breach Detail: Data Aggregator](https://monitor.firefox.com/breach-details/exactis) | What to do after a data aggregator breach: | What to do after a data aggregator breach
[Breach Alert Promo ](https://monitor.firefox.com/?breach=DataCamp)| Firefox Monitor warns you if your online accounts were involved in a data breach. Find out if you’ve been part of a data breach, get alerts about new breaches, and take steps to protect your online accounts. Firefox Monitor is a service provided by Mozilla. | Firefox Monitor warns if your online accounts were involved in a data breach. Find out if you’ve been in a data breach, get alerts about new breaches, and take steps to protect your online accounts. Firefox Monitor is a service provided by Mozilla.
[Dashboard](https://monitor.firefox.com/user/dashboard) | Known data breaches have exposed your info | Data breaches have exposed your information
[Preferences](https://monitor.firefox.com/user/preferences) | Update link on Change Primary Email Address button | This should link to: https://support.mozilla.org/en-US/kb/change-primary-email-address-firefox-accounts
[Preferences ](https://monitor.firefox.com/user/preferences)| Breach Alert Notifications | Global Communication
[Breach Alert Promo Results](https://monitor.firefox.com/scan) | **This email did not appear in the Adobe breach.** However, it did appear in 3 other known breaches. | **This email did not appear in the Adobe breach.** However, it did appear in 3 other breaches. | ✅
Error-Must-Be-Signed-In from #966 | **You must be signed in to your Firefox Account.** To finish verifying this email for Firefox Monitor, you must be signed in under your primary account email. 
user-add-duplicate-email | **This email has already been added to Firefox Monitor.** Visit your Preferences to check the status of [email].

**Comment by groovecoder** [comment]
Can we also include this one? https://github.com/mozilla/blurts-server/issues/966

**Comment by groovecoder** [comment]
We also need a string for "user-add-duplicate-email"

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
