### ISSUE TITLE
Logos on /scan endpoint aren't lazy loaded

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1046]
## Steps to reproduce
0. Open Devtools Network monitor.
1. Go to https://monitor.firefox.com/
2. Enter your email address (test@test.com) and click "Check for breaches".
3. Check the number of requests in the Network monitor.

### Actual results
test@test.com was in 192 breaches, and the /scan endpoint attempts to load 195 images (about 1.0 MB), without the user even interacting with the page. The /breaches endpoint only loads 12 images (62 KB), with the rest being lazily loaded once they are within the viewport.

### Expected results
Lazy load images on the /scan page as well.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
