### ISSUE TITLE
Checkboxes behave like radio buttons in Preferences

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/blurts-server#1051]
The preferences page has the following section:

![image](https://user-images.githubusercontent.com/640949/58668405-13331480-8339-11e9-8e92-b6592e146df3.png)

Based on the visual design I expected these settings to behave like checkboxes. So I can have both or none checked, which would also make sense. However they appear to actually be radio buttons.

**Comment by MichaelKohler** [comment]
IMHO not only expected from the visual design, but also from logic. If I have multiple accounts being monitored, I might choose to only send emails to the "master" email address, or only the affected one, or both.
