### ISSUE TITLE
Password Do's and Don'ts

### ISSUE THREAD

**Issue by betsymi** [mozilla/blurts-server#1060]
Revisit Password do's and dont's. From @groovecoder:

> “Change letters to numbers or special characters”, “combination of upper- and lower-case letters, numbers, and symbols”, “spread various numbers and characters throughout your password”

> I understand they are essentially the opposite of the corresponding “Don’t”s, but they are also password advice that makes passwords harder for humans to remember without making them (much) harder for computers to crack.

> In the context of *all* the do’s and dont’s, those particular do’s aren’t bad. Just on their own they’re not great.

On the topic of pw managers:

> But I encounter a *lot* of not-digital-savvy attendees who are scared of password managers.

> To most of them I say:

> • Start using different longer passwords everywhere
> • It’s okay to write them down in a safe place (wallet, pin-protected phone, etc.) so long as you know to “freak out” if that safe place is ever lost.

**Comment by pdehaan** [comment]
> so long as you know to “freak out” if that safe place is ever lost.

You win, I laughed.
Bonus Internet points if we can build a monitor.firefox.com/how-to-freak-out page with solid tips.

**Comment by klausenbusk** [comment]
https://pages.nist.gov/800-63-3/sp800-63b.html#appA provide a rationale for why complexity requirements for memorized secrets should not be imposed.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
