### ISSUE TITLE
Make "Want to add another email?" functionality more apparent

### ISSUE THREAD

**Issue by betsymi** [mozilla/blurts-server#1062]
Currently the functionality to add another email lives under Logged In > Preferences. Here is the UX to move this functionality to the dashboard, immediately below last breach card.

![Add Another Email Step 1](https://user-images.githubusercontent.com/43555492/58822643-9be1d700-85fd-11e9-92a2-d2866d8bf6c6.png)

![Add Another Email Step 2](https://user-images.githubusercontent.com/43555492/58822642-9be1d700-85fd-11e9-8021-d10d18bb45c0.png)

![Add Another Email Step 3](https://user-images.githubusercontent.com/43555492/58822641-9be1d700-85fd-11e9-8f2a-644fd6759558.png)

### **Want to add another email?**
Enter Email Address
Send Verification Link

Email Sent!
Verify the link sent to [email] to add it to Firefox Monitor. Manage all email addresses in [Preferences.](https://monitor.firefox.com/user/preferences)

**Comment by lesleyjanenorton** [comment]
Closing since we've now merged this.
