### ISSUE TITLE
Confirm production locales

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1066]
According to OPs, our list of production locales is:

```ini
cak,cs,cy,da,de,el,en,en-CA,en-GB,es-AR,es-CL,es-ES,es-MX,fr,fy-NL,hu,ia,id,it,ja,ms,nl,nn-NO,pt-BR,pt-PT,ro,ru,sk,sl,sq,sv-SE,tr,uk,vi,zh-CN,zh-TW
```

According to [Pontoon](https://pontoon.mozilla.org/projects/firefox-monitor-website/), a few of those locales fall a bit short of 80%, notably:

```
el (Greek) = 72.2%
es-MX (Spanish (Mexico)) = 75.8%
ja (Japanese) = 66.9%
ms (Malay) = 52.0%
pt-PT (Portuguese (Portugal)) = 78.2%
sk (Slovak) = 68.3%
sq (Albanian) = 66.5%
uk (Ukrainian) = 75.2%
```

<details>
<summary>prod-locale-lint.js</summary>

```js
const pontoonql = require("pontoonql");

const PROD_LOCALES =
  "cak,cs,cy,da,de,el,en,en-CA,en-GB,es-AR,es-CL,es-ES,es-MX,fr,fy-NL,hu,ia,id,it,ja,ms,nl,nn-NO,pt-BR,pt-PT,ro,ru,sk,sl,sq,sv-SE,tr,uk,vi,zh-CN,zh-TW";

main("firefox-monitor-website", PROD_LOCALES);

async function main(slug, locales, minThreshold = 80) {
  if (!Array.isArray(locales)) {
    locales = locales.split(",").map(locale => locale.trim());
  }
  try {
    const languages = await pontoonql(slug);
    const prodLocales = languages
      .filter(({ locale: { code } }) => locales.includes(code))
      .sort(({ locale: { code: codeA } }, { locale: { code: codeB } }) => {
        if (codeA > codeB) return 1;
        if (codeB > codeA) return -1;
        return 0;
      });

    prodLocales
      .filter(lang => lang.progress < minThreshold)
      .forEach(lang => {
        const precision = Number(lang.progress < 100);
        const progress = lang.progress.toFixed(precision);
        console.log(`${lang.locale.code} (${lang.locale.name}) = ${progress}%`);
      });
  } catch (err) {
    console.error(err.message);
    process.exitCode = 1;
  }
}
```
</details>

**Comment by pdehaan** [comment]
I ran this again today after talking w/ @lesleyjanenorton and @betsymi and it looks like we do have a few interesting locales.

According to the current k8s config, production should support the following locales:

```js
firefoxMonitorSupportedLocales: "cak,cs,cy,da,de,el,en,en-CA,en-GB,es-AR,es-CL,es-ES,es-MX,fr,fy-NL,hu,ia,id,it,ja,ms,nl,nn-NO,pt-BR,pt-PT,ro,ru,sk,sl,sq,sv-SE,tr,uk,vi,zh-CN,zh-TW"
```

And out of those locales, here are the results that are live on production but less than 100%:

| LOCALE | PROGRESS |
|:-------|---------:| 
es-AR    | 99.5%
id       | 99.3%
ro       | 97.5%
es-MX    | 97.0%
sl       | 95.3%
es-ES    | 92.5%
tr       | 90.0%
cak      | 88.6%
**nn-NO**    | ⚠️ 75.4%
**ja**       | ⚠️ 73.4%
**el**       | ⚠️ 67.7%
**uk**       | ⚠️ 65.4%
**sq**       | ⚠️ 49.3%
**ms**       | ⚠️ 43.8%

Also, I tried diffing the above `firefoxMonitorSupportedLocales` list with the list of locales with at least 80% translations at https://pontoonql.now.sh/firefox-monitor-website and it looks like we don't have "kab" (Kabyle) enabled in production, but it is at 100% string translations.

Not sure if our website threshold should be 80% or 90% to be included in the website, or if we go for an aggressive "100% or nothing" approach.

**Comment by groovecoder** [comment]
Thanks @pdehaan for staying on top of this to keep us honest. @flodolo - any input or thoughts here? Should we plan to enable or disable any of these locales in the next production deployment?

**Comment by flodolo** [comment]
I kind of remember Japanese was a request from product? I'd cut below 50% at this point, since I expect the others to catch up at some point (there's a lot going on at the moment).

If we can commit to check regularly (e.g. once a week) and enable/re-enable locales to prod once they go above 80%, then we can cut deeper.

**Comment by pdehaan** [comment]
@groovecoder, how are you setting the production locales? Do you just tell bobm the latest locales in the deploy ticket and he updates the k8s configs?
We have https://pontoonql.now.sh/firefox-monitor-website/50 which should list all locales with at least 50% string translation. Easy enough to tweak 50% or 80% via the url too. Or if you have a better idea/format, I’m sure we can query the pontoon graphql endpoint and come up with a better formatter.

Also, how often are we pushing to prod? Weekly? After every breach, to add latest logos? Monthly?

**Comment by pdehaan** [comment]
Closing in favor of the newer, better, faster, stronger #1332; _"Review the list of locales enabled in production"_.
