### ISSUE TITLE
Wildcard match any + (plus) sign in emails

### ISSUE THREAD

**Issue by philshem** [mozilla/blurts-server#1071]
Many of use [plus-tagged](https://www.cs.rutgers.edu/~watrous/plus-signs-in-email-addresses.html) emails, which all resolve to the same mailbox/account. For example,

    myemail+ebay@example.com

It would be a great feature if when I search `myemail@example.com`, any sites with leaked logins that may include plus-tags would be returned. (I guess for privacy you can't return the actual tag.)

---

Also, it's also possible in email services like gmail to add "." (dot) characters to an email address without signifying a different account. Probably that's harder to strip than "+", but something to consider. `my.email@example.com` --> `myemail@example.com`

**Comment by hulkbulgur** [comment]
+1

This should also be bi-directional, i.e. adding someaddress+tag@example.com should match someaddress@example.com

Specific use case - my firefox account uses firstname.lastname+firefox@gmail.com as the address. I would like it if i did not have to add an extra email address firstname.lastname@gmail.com, but instead my primary email - firstname.lastname+firefox@gmail.com would implicitly cause all equivalent addresses to be added (firstname.lastname@gmail.com, firstname.lastname+anytaghere@gmail.com, firstnamelastname@gmail.com, firstnamelastname+anytaghere@gmail.com)

**Comment by tinoism** [comment]
I'd like to take on this issue. I'm new to this project.

**Comment by lesleyjanenorton** [comment]
@groovecoder do we know if the status of this issue changed since https://github.com/mozilla/blurts-server/issues/467 ? @tinoism is an intern on the performance team.

**Comment by madb1lly** [comment]
Hi all,
Thanks for linking the issues. It would be nice to get an update on this considering how long my issue has been open now.
Cheers :)

**Comment by groovecoder** [comment]
Since scans and subscriptions are based on hash range queries, we can't predictably and reliably scan or subscribe `+` aliases or other address schemes like various `.` characters. Closing this issue unless/until our breach data endpoint supports such a feature.
