### ISSUE TITLE
Change our CSS properties to logical properties

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1082]
_Originally posted by @groovecoder in https://github.com/mozilla/blurts-server/pull/1081#discussion_r291649451_:

> Just a note: at some point we should go thru and change our properties to [logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts). But that's a bigger project.

**Comment by Shivansh2407** [comment]
Can I work on this @pdehaan ?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
