### ISSUE TITLE
Inconsistent link formatting on /about page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1083]
## Steps to reproduce

1. Go to https://fx-breach-alerts.herokuapp.com/about
1. Scroll to the bottom of the page and compare the link styling on each of the three links.

### Actual results
The middle link, **Sign up for Alerts**, is bold.

![About_Firefox_Monitor](https://user-images.githubusercontent.com/557895/59127142-ab259500-891b-11e9-86ce-00c302eb3527.png)

### Expected results
All three links should use the same formatting.
They all look the same on production, https://monitor.firefox.com/about, so I'm guessing this is a recent CSS change.

**Comment by betsymi** [comment]
I think these were supposed to be buttons, right? If so, the casing should remain.

If these remain in in-text links, these should read:
Search your email
Sign up for alerts
Download Firefox (no change)

**Comment by lesleyjanenorton** [comment]
There was never a spec for this page, but they can certainly become buttons.

**Comment by pdehaan** [comment]
@betsymi Here's the latest UI for the /about page. Does this look right?

![About_Firefox_Monitor](https://user-images.githubusercontent.com/557895/60375112-8d989800-99bc-11e9-912b-4692d2a8dfa8.png)
