### ISSUE TITLE
Kabyle locale activation

### ISSUE THREAD

**Issue by mozillakab** [mozilla/blurts-server#1085]
Please, would you like activate kab locale on the production server ( I think there is no staging server for monitor) to see strings and correct them. We reached 81%. 
Localization is ongoing.

**Comment by groovecoder** [comment]
Our dev server is here:

https://fx-breach-alerts.herokuapp.com/

I've added `kab` to its `SUPPORTED_LOCALES` so you should be able to see the translations live on https://fx-breach-alerts.herokuapp.com/.

I'll make a note to update SUPPORTED_LOCALES in the next production deployment.

Thank you for your contributions!

**Comment by mozillakab** [comment]
Thanks for help.
