### ISSUE TITLE
Improve UX for Verifying 2nd Email

### ISSUE THREAD

**Issue by betsymi** [mozilla/blurts-server#1087]
What's happening:

1. People add an additional email on their desktop (where they are signed in)
2. They check the verification email on a different browser or on mobile
3. They get a confusing error

**Error**
You must be signed in to your Firefox Account. 
![Image from iOS](https://user-images.githubusercontent.com/43555492/59213784-48323900-8b7b-11e9-80bf-cfe4bad8b1db.png)

## Designs

**InVision:** https://mozilla.invisionapp.com/share/RGRIETZ7NAJ#/385241249_email_Verified_From_Other_Device  
**Zeplin:** https://zpl.io/aXXlAE8

**Comment by betsymi** [comment]
If we can't repurpose existing strings, here's copy for this:

**[email address] successfully verified and added to Firefox Monitor**
Sign in to view your breach summary on this browser. 

^ Link "sign in" to sign in flow.

**Comment by groovecoder** [comment]
To fix this, don't require the same session when the user visits the verification link.

**Comment by changecourse** [comment]
Added design approach to description, assigning to @betsymi for content.

**Comment by betsymi** [comment]
Strings for this message. 

Email Successfully Verified!

We’ll alert you if emailaddress@email.com appears in a data breach. To see and manage all emails you’ve signed up for breach monitoring, [sign in](url).
