### ISSUE TITLE
At the bottom of the user dashboard, the "What to do after a data breach" link has a trailing colon

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#1092]
It looks wrong to me, I don't think it's there intentionally. Let me know if I'm wrong.

cc. @betsymi @lesleyjanenorton

**Comment by betsymi** [comment]
Because this string appears in two places (one that requires a colon and one that does not), the colon is appearing in both places. I've filed new copy in issue #1034 that would correct this issue, but it hasn't been pushed yet. This has also been called out in issue #1024 @nhnt11 @lesleyjanenorton

**Comment by nhnt11** [comment]
Ah, thank you! Apologies for not catching the dupe. :)

For posterity, to be clear, this issue is a dupe of #1024
