### ISSUE TITLE
Missing logo for new WienerBuchereien breach.

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1104]
_Originally posted by @pdehaan in https://github.com/mozilla/blurts-server/pull/1102#issuecomment-506873781_

> Unrelated (but semi-related), but there was a new HIBP breached loaded today that we'll need a logo for. Not sure if you want me to file new issues for these every time we see a new breach loaded.
>
> - https://haveibeenpwned.com/api/v2/breach/WienerBuchereien
> - https://monitor.firefox.com/breach-details/WienerBuchereien

**Comment by lesleyjanenorton** [comment]
Thank you for filing, I missed your earlier comment!
