### ISSUE TITLE
/user/unsubscribe: invalid csrf token

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1108]
STR:
1. Click the "unsubscribe" link in an email (I used the "Firefox Monitor found your info in these breaches" email)
2. On the /user/unsubscribe page, click the big "Unsubscribe" button

Expected results:
The email address is unsubscribed

Actual results:

Error

invalid csrf token

**Comment by Shivansh2407** [comment]
can I help with this issue?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
