### ISSUE TITLE
Add a .well-known/change-password route for chancing FxA password?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1120]
Ref #1112 

Q: Should https://monitor.firefox.com/.well-known/change-password work and redirect you to FxA change password form?

Currently https://accounts.firefox.com/.well-known/change-password cleverly redirects to https://accounts.firefox.com/settings/change_password, which is pretty cool.

We could potentially set up a /.well-known/change-password Express route which redirects to the FxA's .well-known/change-password route.

**PROS:** Probably more future-safe than trying to redirect to their /settings/change_password route directly (in the slight chance they change that endpoint in the future).
**CONS:** One extra redirect.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
