### ISSUE TITLE
Check for an appropriate scope on FxA access tokens

### ISSUE THREAD

**Issue by rfk** [mozilla/blurts-server#1128]
The `/breach-stats` endpoint added in https://github.com/mozilla/blurts-server/pull/1111 accepts an FxA OAuth bearer token for authorization, but it does not check anything about the token beyond "is it valid". This means that anyone who can get any OAuth token to access anything on the user's account (e.g. other FxA reliers like AMO or Pocket, and potentially third-party RPs in future) could use their token to access this endpoint and read the user's breach-protection status.

Instead, we should check that the received token is actually intended for accessing this service.

The way we do that in FxA currently is via scopes. We should allocate a unique scope value for this service, e.g. "https://identity.mozilla.com/apps/monitor", and then:

* Have the client code generate a token with this scope when accessing monitor
* Have the server code explicitly check that this value is in the list of scopes returned when verifying the OAuth token

/cc @shane-tomlinson; does that line up with your expectations for how this should work?

**Comment by shane-tomlinson** [comment]
> /cc @shane-tomlinson; does that line up with your expectations for how this should work?

Very much so!

**Comment by rfk** [comment]
While we work through the details here, I'm going to suggest that the client send both `profile:uid` and `https://identity.mozilla.com/apps/monitor` scopes, which should be backwards-compatible with current server behaviour and forwards-compatible with the change suggested above.

**Comment by groovecoder** [comment]
@rfk we merged the fix for this and are now seeing these errors:
https://sentry.prod.mozaws.net/operations/firefox-monitor/issues/6104533/?environment=prod

Could the response coming back from FxA be `undefined` if there's no `https://identity.mozilla.com/apps/monitor` scope defined?

**Comment by rfk** [comment]
> Could the response coming back from FxA be undefined if
> there's no https://identity.mozilla.com/apps/monitor scope defined?

I don't think so, we basically let clients make up their own scopes if they have sufficient permissions (which Firefox does).

I mentioned in slack but duplicating here for completeness: I think #1139 has a bug where it changed `verifyOAuthToken` from returning the response body, to returning a bool, so you end up trying to access `true.body.user` or similar and producing the above error.
