### ISSUE TITLE
Delete any previous `refresh_token` when processing a new user signin

### ISSUE THREAD

**Issue by rfk** [mozilla/blurts-server#1131]
As described in https://github.com/mozilla/fxa/issues/1802, each time a user signs in to the Monitor website we end up generating a new FxA `refresh_token` and storing it in the Monitor backend DB, overwriting any existing `refresh_token` that was generated by a previous login.  Over time, this results in an accumulation of orphaned `refresh_token`s that are held by the FxA server, but have been deleted from Monitor.

Please consider destroying any existing `refresh_token` when writing a new one to the db.

**Comment by pdehaan** [comment]
+1. Can confirm I have a ton (or at least 20) of orphaned sessions/devices:

![Firefox_Accounts__Devices___apps](https://user-images.githubusercontent.com/557895/62800078-4f03fc00-ba97-11e9-9053-2421b98cc621.png)
