### ISSUE TITLE
Firefox Monitor logo is missing from the confirmation email

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#1133]
**Affected versions**
* latest Nightly 70.a1

**Affected platforms**
* Windows 10 x64
* Ubuntu 18.04 x64
* macOS 10.13

**Steps to reproduce**
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Sign in with a valid account.
3. In the "Add a new email address" field write a valid email.
4. Verify the confirmation email.

**Expected result**
* The Firefox Monitor logo is displayed in the confirmation email.

**Actual result**
* The Firefox Monitor logo is missing from the confirmation email.

**Regression range**
N/A

**Additional notes**
* note that even after allowing the remote content in the email client the image is still not shown.
* please see screenshot:
![image](https://user-images.githubusercontent.com/43886441/61464989-e639d000-a97f-11e9-85f2-974ed822f6b1.png)

**Comment by lesleyjanenorton** [comment]
Fixed on Heroku and possibly now Prod.
