### ISSUE TITLE
Email field is not focused after sending verification link via email

### ISSUE THREAD

**Issue by davidolahsv** [mozilla/blurts-server#1134]
Affected versions
- latest Nightly 70.a1

Affected platforms
- Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

Steps to reproduce
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Sign in with a valid account.
3. Click on the "Enter Email Address" field and write down a valid email address.
4. Click on the "Send Verification Link" button.

Expected result
- The page should remain focused on the email field with the green message “Email sent”

Actual result
- The page is being scrolled up.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
