### ISSUE TITLE
Update to HIBP v3 API?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1136]
https://github.com/mozilla/blurts-server/blob/d99aa8133628202a15ce2471869bf5e3714ed04f/.env-dist#L49

https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/ outlines some new changes and rate limiting.

V3 API docs at https://haveibeenpwned.com/API/v3

**Comment by klausenbusk** [comment]
> Versions 1 and 2 of the API for searching breaches and pastes by email address will be disabled in 4 weeks from today on August 18.

That isn't much time.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
