### ISSUE TITLE
Cant sign in to monitor.firefox.com. Error - "You must be signed in to your Firefox Account."

### ISSUE THREAD

**Issue by ashishthukral** [mozilla/blurts-server#1146]
On trying to sign in to https://monitor.firefox.com/user/dashboard, it simply keeps giving error "You must be signed in to your Firefox Account."

been facing this since 07/22, even though i was able to add multiple emails to monitoring service initially. but been unable to login to the monitor service on chrome or firefox.

**Comment by lissyx** [comment]
Looks like you are not alone: https://bugzilla.mozilla.org/show_bug.cgi?id=1559718

I'm also hit by this.

**Comment by ddurst** [comment]
(Carrying over NI from bugzilla for @groovecoder and @lesleyjanenorton just for completeness.)

**Comment by ashishthukral** [comment]
linked PR - https://github.com/mozilla/blurts-server/pull/1139

**Comment by rfk** [comment]
As far as I can tell, the change in #1139 (and corresponding desktop patch in https://phabricator.services.mozilla.com/D38228) don't seem related to this issue; they are for access monitor data within Firefox UI as part of the protection report, but this issue seems to be something to do with the state of the monitor website.

Just to confirm: @lissyx and @ashishthukral, this happens to you every time you try to sign in with your Firefox Account? You click on "sign in", go through the Firefox Accounts OAuth flow successfully, it lands you on https://monitor.firefox.com/user/dashboard, and you get an error message displayed on that page?

I *think* this means that something on the monitor side is failing to set `session.user`, or perhaps setting `session.user` to a falsey value, at the end of the FxA OAuth flow. But I can't see any obvious code paths that would do that (without throwing some other unrelated error first).

**Comment by rfk** [comment]
One thing that would be valuable to check is, after you do the OAuth flow and get this signin error, open the dev console, go to the "storage" tab, and see what cookies you have for monitor.firefox.com. There should be a cookie there named "session" and it would be useful to know how big the value is that it contains (the actual value is encrypted).

**Comment by ashishthukral** [comment]
> As far as I can tell, the change in #1139 (and corresponding desktop patch in https://phabricator.services.mozilla.com/D38228) don't seem related to this issue; they are for access monitor data within Firefox UI as part of the protection report, but this issue seems to be something to do with the state of the monitor website.
> 
> Just to confirm: @lissyx and @ashishthukral, this happens to you every time you try to sign in with your Firefox Account? You click on "sign in", go through the Firefox Accounts OAuth flow successfully, it lands you on https://monitor.firefox.com/user/dashboard, and you get an error message displayed on that page?
> 
> I _think_ this means that something on the monitor side is failing to set `session.user`, or perhaps setting `session.user` to a falsey value, at the end of the FxA OAuth flow. But I can't see any obvious code paths that would do that (without throwing some other unrelated error first).

Yes, after sign in directly shows Error message.

**Comment by ashishthukral** [comment]
> One thing that would be valuable to check is, after you do the OAuth flow and get this signin error, open the dev console, go to the "storage" tab, and see what cookies you have for monitor.firefox.com. There should be a cookie there named "session" and it would be useful to know how big the value is that it contains (the actual value is encrypted).

Size 288,  [see screenshot](https://imgur.com/a/m3ISHZj)

**Comment by lissyx** [comment]
> Just to confirm: @lissyx and @ashishthukral, this happens to you every time you try to sign in with your Firefox Account? You click on "sign in", go through the Firefox Accounts OAuth flow successfully, it lands you on https://monitor.firefox.com/user/dashboard, and you get an error message displayed on that page?

Yes. Worst, it worked well yesterday morning, I could do a lot of things (change Firefox Accounts password, add dozen of emails to Monitor) and then, one or two hour after, boom.



> One thing that would be valuable to check is, after you do the OAuth flow and get this signin error, open the dev console, go to the "storage" tab, and see what cookies you have for monitor.firefox.com. There should be a cookie there named "session" and it would be useful to know how big the value is that it contains (the actual value is encrypted).

FTR I've already tried cleaning up all cookies.

**Comment by lissyx** [comment]
> One thing that would be valuable to check is, after you do the OAuth flow and get this signin error, open the dev console, go to the "storage" tab, and see what cookies you have for monitor.firefox.com. There should be a cookie there named "session" and it would be useful to know how big the value is that it contains (the actual value is encrypted).

This is an array of 5 elements for me.

**Comment by LucasDiTomase** [comment]
You are not alone. 

#1084

**Comment by rfk** [comment]
Aha, thank you, that bug brought the key clue to what's happening here: https://github.com/mozilla/blurts-server/issues/1084#issuecomment-515242813

**Comment by lissyx** [comment]
@groovecoder Thanks! How long until this goes into production ?

**Comment by LucasDiTomase** [comment]
Still experiencing the issue here

**Comment by GecoMynx** [comment]
I'm also still expiriencing the issue.

**Comment by groovecoder** [comment]
Planning to deploy today ...

**Comment by groovecoder** [comment]
The fix for this issue is now deployed. Thank you everyone for your patience!

**Comment by LucasDiTomase** [comment]
I can confirm on my end, fix is working as intended ( with 14 email addresses ) on Chrome latest stable version. Thanks so much!

**Comment by ashishthukral** [comment]
yep working. thanks.
