### ISSUE TITLE
Switch to server-side session storage

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1148]
https://github.com/mozilla/blurts-server/issues/1146 and https://github.com/mozilla/blurts-server/issues/1084 show that we can't rely on client-sessions forever. As we put more data into user session objects, we need to move it to server-side session storage.

@mozilla/svcops - what are the suggested storage backends for (node) sessions?

**Comment by Micheletto** [comment]
> @mozilla/svcops - what are the suggested storage backends for (node) sessions?

We should use Google's [MemoryStore](https://cloud.google.com/memorystore/) (which is Redis) for this type of data.
