### ISSUE TITLE
Website Styling Updates

### ISSUE THREAD

**Issue by changecourse** [mozilla/blurts-server#1167]
Matching site to latest design spec: updated typography, type scales, padding, and slight tweaks/optimization of link styles and button styles throughout the site. 

## Acceptance criteria
- [x] Form field updates (email address & search) | 320px for all email address fields, placeholder text color (match to breaches search) | https://zpl.io/2yqgE7o
- [ ]  Typography Overhaul
   - consistent type scales (including letter and line spacing)
   - https://app.zeplin.io/project/5c93a4e0eb472f24e353125a/dashboard?seid=5d8b878865a7831666001e92
- [x] Button consistency across website
   - Large (check for breaches)
   - Medium (FxA callouts)
   - Small (Preferences)
- [x] Hover/interaction states for buttons
   - need to regroup and determine
- [x] Tweaks to breach cards
   - minor adjustments to align to spec (icon positioning, and type tweaks for margins and padding) 
   - https://zpl.io/aNmNnOD
- [x] Latest Breach Added' Card Styling
   - revise to match spec in Zeplin (sizing and padding)
   - https://zpl.io/2yqgE7o
- [x] Sign up for breach monitoring with a Firefox Account, on home page
   - matching to spec, button style, resizing/balancing tout images
   - https://zpl.io/2yqgE7o
- [x] Footer updates
   - change from light to dark, and update link styling
   - https://zpl.io/2yqgE7o
- [ ] Authenticated Dashboard - Updates
   - align to spec
   - https://zpl.io/bA7gJJn
- [ ] Monitor Preferences - Updates
   - align to spec
   - https://zpl.io/aMWEgKd
- [x] Breach Detail Updates
   - one column for compromised data, adjustments to padding between sections and subsections, adjustments to type scales of content
   - https://zpl.io/a7WP5m8
- [x] Breaches - Updates
   - decide on standard card size vs. truncation of compromised data, update title placement and padding to spec
   - https://zpl.io/bLdvnj7
- [x] Breaches - No Breaches Found
   - instead of tooltip copy, create placeholder text at base of field for 0 breaches found
   - https://zpl.io/V4oNN4X
- [x] Align breach promo landing pages to spec
   - https://zpl.io/aX3jO1g

## Visual design
InVision: https://mozilla.invisionapp.com/share/RGRIETZ7NAJ
Zeplin: https://zpl.io/VDBgQ7w

**Comment by lesleyjanenorton** [comment]
- Typography overhaul is in progress
- Signed in dashboard updates are also in progress

**Comment by changecourse** [comment]
@lesleyjanenorton & @maxxcrawford great work on the updates thus far! This is looking beautiful! My first pass review is included below.

Initial review of the site on staging:

**Global**
- [ ] On the primary Nav, if someone hovers over a section, but is already on an active section (Home, Breaches, or Security Tips landing page) can we fade in/out the active bar? That way, only one zap can ever be present at any given time? 
- [ ] Use bold text for all primary (solid blue) and secondary buttons (the purple and white outlined btns) as defined here: https://zpl.io/2yP33kq 
- [ ] Confirm standardized heights, padding, and widths on all secondary buttons across site matches to spec: https://zpl.io/2yP33kq 
- [ ] The global variable line height is too much on desktop (calculated as 180%) it should be closer to 150% on desktop viewports if possible
- [ ] Ensure that all instances of breach cards are using the same CSS styling (I'm seeing some minor discrepancies across the home page, scan results, dashboard, and breaches landing page) 

**Home: https://zpl.io/2yqgE7o**
- [ ] Security tips links should be white, and will need to have the same hover state (#000 at .15 opacity) and hyperlink underline on hover as other white links
- [ ] Tighten up vertical spacing on latest breach card to match spec (ideally just match everything on the styling of cards in the scan results cards)
- [ ] Add vertical padding to "Take back control of your personal data" section to match spec (120px top and bottom)
- [ ] Add background opacity to FxA panel (bg-white gradient-inset) of .95
- [ ] Remove the animations of scaling the svgs in the FxA panel (since we use this type of animation as a click affordance on the cards, I worry that this animation is misleading from a usability perspective)

**Scan Results: https://zpl.io/aNmNnOD**
- [ ] Have "Have I Been Pwned" link bold, and darker grey/underlined on hover (instead of blue) 
- [ ] The svg for the "Get ongoing alerts with a Firefox Account." section is appearing solid black

**Breach Detail: https://zpl.io/a7WP5m8**
- [ ] Tighten up header section (60px top/bottom padding) to match spec
- [ ] Overview title is missing
- [ ] Tighten up the vertical spacing of data bullet points to match spec
- [ ] Consistent style for "Have I been pwned" link (bold text, hover styling)
- [ ] SVGs should only animate on link hover for each section in "What to do"; same for only animating the FxA tout on button hover
- [ ] Sections under the FxA tout are secondary, and should be smaller sized headers (20px)

**Breaches Landing**
- [ ] The clear X is not properly aligned appropriately to the search box (when field is filled)
<img width="366" alt="Screen Shot 2019-10-15 at 10 29 31 AM" src="https://user-images.githubusercontent.com/6164801/66850789-b6767600-ef36-11e9-8ba1-65aa362fc3d9.png">

**User Dashboard: https://zpl.io/bA7gJJn**
- [ ] Match vertical padding of Breach Summary section to spec
- [ ] Secondary buttons (Manage Email Addresses, See Additional Breaches) are different sizes. Ideally we can define this style once and ensure it's used in every instance
- [ ] Double check header colors to spec
- [ ] Match styling of subsections to updated spec (email address, # of breaches)
- [ ] Breach cards look different (widths) on dashboard compared to other sections

**Monitor Preferences: https://zpl.io/aMWEgKd**
- [ ] Align updated text treatments (headers/subheaders) to spec
- [ ] Decrease max-width of this page to 620px
- [ ] Change style of "Remove Firefox Monitor" from link to secondary btn in red

**Comment by lesleyjanenorton** [comment]
@changecourse thank you for combing through these!  Don't worry about de-duping - the level of detail is helpful. I'll keep checking these off as they're done and ready for review.

**Comment by lesleyjanenorton** [comment]
@changecourse  I'm running into some spacing issues working on some of `/preferences` text changes (see below). Can we consider leaving the email address / "Appears in X breaches" number on two separate lines as they are? On mobile, these would have to wrap anyway.

<img width="772" alt="Screen Shot 2019-11-04 at 2 41 24 PM" src="https://user-images.githubusercontent.com/22355127/68156459-7ee56300-ff11-11e9-9d53-2e40d6de0e98.png">

**Comment by changecourse** [comment]
Yes, absolutely! I'll update the designs. Can we also tweak the strings to no longer have em dashes and the space then, if we drop them to the second line? (this also would allow us to introduce our Delete label link alongside the trash icon too, right?

**Comment by lesleyjanenorton** [comment]
Yep! Will drop the space and dash, and add the "Delete" in alongside the trashcan icon. Thanks!

**Comment by ddurst** [comment]
Closing this in favor of a (shortened) remaining scope of outstanding items in #1340
