### ISSUE TITLE
Unsubscribing does not unsubscribe from monitor or monitor emails

### ISSUE THREAD

**Issue by shaneknysh** [mozilla/blurts-server#1171]
Using the unsubscribe link in the emails or using the remove monitor link does not remove email from monitor and you still receive updates for new breaches.

**Comment by lesleyjanenorton** [comment]
@shaneknysh thanks for flagging this. A few questions: Do you remember when you first signed up for Monitor? Are you able to still log in to your dashboard?

**Comment by groovecoder** [comment]
I'm unable to reproduce this - when I click the unsubscribe link in a Monitor breach alert, I land on the /user/preferences page where I can "Remove Firefox Monitor" and then I no longer receive breach alert emails.

Please re-open if you have some more detailed steps to reproduce this error.

**Comment by shaneknysh** [comment]
The only indication I get of this issue is when I receive an email from Monitor on a breach. I will comment if I receive another email breach from Monitor.
