### ISSUE TITLE
Monitor entire domains (wildcard-support)

### ISSUE THREAD

**Issue by JoeryZegers** [mozilla/blurts-server#1183]
It would be great if Firefox Monitor offers support to monitor entire domain names. This can be done the same way haveibeenpwned does it, by verifying webmaster@example.com.

**Comment by lanesawyer** [comment]
Came here to request the same thing!

I use a different email address per service I sign up with so I know exactly who leaked my data if I ever get spam. A wildcard to monitor a whole domain name would be phenomenal.

**Comment by groovecoder** [comment]
This is a duplicate of https://github.com/mozilla/blurts-server/issues/1137 ... please upvote and comment there.
