### ISSUE TITLE
XKCD doesn't even have accounts?

### ISSUE THREAD

**Issue by macgyver** [mozilla/blurts-server#1186]
![image](https://user-images.githubusercontent.com/1163/64265549-1e31ae00-cf01-11e9-96ae-2ac53da2054d.png)

Maybe this is a nightly issue - I'm using Firefox Nightly 71.0a1 (2019-09-04) (64-bit)

**Comment by ddurst** [comment]
There was a data breach on xkcd's forum (https://www.engadget.com/2019/09/03/xkcd-forum-breach-exposes-details-from-over-560-000-user-account), which has since been taken offline. The forum was (and I assume, will be, once patched) accessible at https://forums.xkcd.com.

**Comment by macgyver** [comment]
oh wow! thanks for the quick response
