### ISSUE TITLE
CSS bug: longer nav link striked out by active-link-underline

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/blurts-server#1190]
<img width="914" alt="Screen Shot 2019-09-10 at 12 37 07 PM" src="https://user-images.githubusercontent.com/30483988/64727311-6fa3e500-d48d-11e9-8ab7-7af580fc39fe.png">

`active-link-underline` strikes out "security tips" nav link when view-port shrinks because it is a longer string.

**Comment by pdehaan** [comment]
I was able to reproduce this on Firefox Release and Nightly, but not on Chrome. 
The magic breakpoint seems to be 801-975px (any smaller and we collapse the menu).

Adding a low-tech `<nobr>` seems to work, but I'm sure we can do something better w/ CSS).

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/64736005-8d2d7a80-d49e-11e9-897e-95f7001424cb.png)

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/64736143-d7aef700-d49e-11e9-9967-50713eaa82d9.png)

**Comment by pdehaan** [comment]
![Firefox_Monitor](https://user-images.githubusercontent.com/557895/64736443-7b98a280-d49f-11e9-85b2-b7e4a4a8f7fb.png)

**Comment by Shivansh2407** [comment]
Can I help on this issue?

**Comment by lesleyjanenorton** [comment]
@Shivansh2407 Are you able to reproduce this? If so, you're certainly welcome to work on it. We've made some changes to the way we handle these links since this issue was filed and I think we may have inadvertently fixed this in the process.
