### ISSUE TITLE
Ping FxA metrics for visits to the Monitor website from a breach alert email

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1191]
Monitor’s primary value to users is sending emails, and they may get all of the value they want out of their Monitor/FxA with that - may never come back to sign into the site at all.

We're not currently recording email notifications for FxA accounts. We should start recording this.

**Comment by groovecoder** [comment]
@sandysage - can you get a decision on whether to count email opens as FxA Monitor engagement? Then we can implement whatever we decide.

**Comment by sandysage** [comment]
@groovecoder I don't think we can reasonably count email opens as FxA Monitor engagement. But we should consider 'click throughs' as engagement. Is this something we can do by passing FxA a specific Monitor email parameter?

**Comment by groovecoder** [comment]
We can already see how many people are visiting Monitor from our emails. They show up in GA in the `fx-monitor-email` source report:

https://analytics.google.com/analytics/web/#/report/trafficsources-all-traffic/a77033033w177898028p180612539/_u.date00=20190926&_u.date01=20191002&explorer-table.filter=fx-monitor-email&explorer-table.plotKeys=%5B%5D

If they go on to sign in, it should attribute the sign-in to the `fx-monitor-email`. I'm digging into whether or not we can send an "engagement" ping from monitor.firefox.com if the visitor is signed into their account.

**Comment by sandysage** [comment]
Data Collection Review Request has been seen by and approved by a Data Steward, so the Data Collection can now proceed in compliance with our own data collection policies
