### ISSUE TITLE
Update Fluent dependencies

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#1206]
```
    "fluent": "^0.10.0",
    "fluent-langneg": "^0.1.0",
```

I just noticed that Fluent is quite behind, to the point that it's using the deprecated package
https://www.npmjs.com/package/@fluent/bundle

Not urgent, with Skyline work happening, but it would be nice to update to a more recent version. CC @pike

**Comment by Pike** [comment]
I guess the changes will be constrained to the utils function?

Note that we changed the `FluentBundle` and `FluentResource` APIs, https://github.com/projectfluent/fluent.js/releases/tag/%40fluent%2Fbundle%400.14.0 has the relevant release notes.

**Comment by Patil2099** [comment]
@flodolo @Pike Can I work on this issue?

**Comment by flodolo** [comment]
None of us owns this project, so it would be for someone else to answer. TBH, I don't expect it to be an easy pick, it might be trivial or really complicated.

**Comment by flodolo** [comment]
Just to confirm that the packages were updated in the meantime.

```
    "@fluent/bundle": "^0.18.0",
    "@fluent/langneg": "^0.7.0",
    "@fluent/react": "^0.15.2",
```

**Comment by rhelmer** [comment]
@dependabot now automatically opens PRs for this dependency.
