### ISSUE TITLE
Can't dismiss Bento menu by pressing the "Esc" key

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/blurts-server#1207]
[Affected versions]:
- Firefox 69.0.1, Chrome 77.0.3865.90 and Safari 13.0.1

[Affected Platforms]:
- Windows 10 x64, macOS 10.14 and Ubuntu 18.04

[Steps to reproduce]:
1. Navigate to the Monitor website "https://monitor-v2.herokuapp.com/".
2. Click the "bento menu" button.
3. Press the "Esc" key.

[Expected result]:
Bento menu should by dismissed by pressing the "Esc" key

[Actual result]:
Can't dismiss Bento menu by pressing the "Esc" key

**Comment by lesleyjanenorton** [comment]
This should be fixed as of last push to the heroku server.

**Comment by sv-hyacoub** [comment]
Verified as fixed on Windows 10 x64, macOS 10.14 and Ubuntu 18.04 on Firefox 69.0.1, Chrome 77.0.3865.90 and Safari 13.0.1.
