### ISSUE TITLE
[Microsoft Edge] Bento box is missing from the Firefox Monitor page

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#1208]
[Affected versions]:
- Microsoft Edge 44.18362.329.0

[Affected Platforms]:
- Windows 10 x64

[Steps to reproduce]:
1. Open Microsoft Edge.
1. Navigate to  https://monitor-v2.herokuapp.com/

[Expected result]:
- Bento box is displayed.

[Actual result]:
- Bento box is missing.  

[Regression]:
- N/A

**Comment by marniepw** [comment]
For our first release, we will not be supporting Edge. Instead, we'll be purposely hiding the bento from Edge users, so this issue can be closed. @lesleyjanenorton I don't have perms to close this.

**Comment by pdehaan** [comment]
Closing per @marniepw's comment above. ❤️
