### ISSUE TITLE
"Firefox Lockwise" option is redirecting to App Store

### ISSUE THREAD

**Issue by gpalko-SV** [mozilla/blurts-server#1209]
[Affected versions]:

    Firefox 69.0.1, Chrome 77.0.3865.90 and Safari 13.0.1

[Affected Platforms]:

    Windows 10 x64, macOS 10.14 and Ubuntu 18.04

[Steps to reproduce]:

    Navigate to the Monitor website "https://monitor-v2.herokuapp.com/".
    Click the "bento menu" button.
    Click the "Firefox Lockwise" option.

[Expected result]:
https://lockwise.firefox.com/ page is opened

[Actual result]:
https://apps.apple.com/app/id131400027 page is opened(App Store-Firefox Lockwise)

**Comment by lesleyjanenorton** [comment]
The Lockwise landing page is being reworked and by the end of the week this link (`https://app.adjust.com/6tteyjo?&campaign=Skyline&adgroup=InProduct&creative=Bento&fallback=https%3A%2F%2Fwww.mozilla.org%2Ffirefox%2Flockwise`) should open either the website, the app, or the correct app store.

**Comment by lesleyjanenorton** [comment]
closing in favor of #1229
