### ISSUE TITLE
[Windows] Bento menu button and all the icons in the menu are not visible when using High Contrast Theme

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#1210]
[Affected versions]:
- Firefox 69.0.1

[Affected Platforms]:
- Windows 10 x64

[Steps to reproduce]:
1. Turn on the High Contrast theme on your OS.
2. Navigate to  https://monitor-v2.herokuapp.com/

[Expected result]:
- Bento menu button is visible.

[Actual result]:
- Bento menu button is not visible.  

[Regression]:
- N/A

[Additional Notes]:
- The icons for all the elements in the Bento menu are not visible either.
- Please look at the attached image. 
![high contrast - bento box](https://user-images.githubusercontent.com/42799381/65882194-48aa4600-e39d-11e9-9ceb-9a368691d5ca.png)

**Comment by lesleyjanenorton** [comment]
The icons are considered decorative and their visibility is not mandatory. Please verify that an outline of the bento is visible in high contrast modes. thanks!

**Comment by obotisan** [comment]
There is an outline at the moment, but there is no hover effect. 
Is this what you were refering to? 
![bento 2](https://user-images.githubusercontent.com/42799381/66185245-7803d000-e687-11e9-8fc7-30aa5168a86b.png)
