### ISSUE TITLE
Accept email scan requests from www.mozilla.org

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1211]
We would like to add an email input field to the Firefox What’s New Page "WNP" hosted on www.mozilla.org (www). When a user enters their email, we would like to send them straight to Firefox Monitor (monitor) scan results page for the email.

To fight against abusive bot scans on the Monitor scan endpoint, we use IP rate-limiting and check both a CSRF token and another encrypted token of our own implementation on the back-end. These tokens will also prevent these scan requests from mozilla.org.

So, we would need to add a way to authenticate scans coming from www.mozilla.org:

1. www and monitor both have a shared secret on the back-end
2. www WNP asks for a user’s email
3. www WNP puts the user’s email and a timestamp in the payload[1] of a JWT with an hmac sha256 using the shared secret
4. www WNP sends the user to monitor. with the JWT in a url (or POST?) param (or Authorization header?)
5. monitor verifies the JWT, retrieves the user’s email, performs a scan, and shows the results

[1] proposed JWT payload claims:
```
{
  "iss": "www.mozilla.org",
  "aud": "monitor.firefox.com",
  "iat": "2019-10-22T00:00:00Z"
  "email": "test@mailinator.com"
}
```
Where:
* `iat` ("Issued At") contains the timestamp when the email was entered on www.mozilla.org
* `email` contains the email address entered by the user

**Comment by hoosteeno** [comment]
In order to make this work measurable, we'll need to pass through some parameter from the upstream source (e.g. WNP) to the registration button that refers visitors to the FxA server for registration. On www we pass through utm parameters, since `entrypoint` is evolving to become last touch attribution.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
