### ISSUE TITLE
[Mobile] The Bento menu size is too big(a floating menu should be displayed) 

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1215]
## Steps to reproduce
1. Install and Launch the app.
2. Access `https://monitor-v2.herokuapp.com/`
3. Open the Bento menu

### Expected behavior
The `Bento` menu size should be smaller and looking like a prompt/floating menu.
### Actual behavior
The `Bento` menu is way too big and it doesn't look like a floating menu.
* Android device: `Samsung Galaxy S10+(Android 9), Samsung Galaxy Note 9(Android 8)`
* Fenix version: `Latest Firefox and Chrome` versions.
### Notes
For more details please see the attachment.
![Screenshot_20190930-174536_Firefox](https://user-images.githubusercontent.com/42831109/65889836-98433e80-e3aa-11e9-9d0e-676f77cefe7d.jpg)

**Comment by lesleyjanenorton** [comment]
Closing since this is the intended appearance on device screens and window sizes narrower than 500px.
