### ISSUE TITLE
[Safari] Pages from bento-menu are opened in new window

### ISSUE THREAD

**Issue by gpalko-SV** [mozilla/blurts-server#1216]
[Affected versions]:
  
  Safari 12.1

[Affected Platforms]:
 
   macOS 10.14

[Steps to reproduce]:

    Navigate to https://monitor-v2.herokuapp.com/
    Open the Bento menu.
    Click any option from the menu, except "Firefox Monitor"

[Expected result]:

    The pages are opened in new tab.

[Actual result]:

    The pages are opened in new window.

[Note]

   "Firefox Monitor" page is opened in the same tab, as expected.

**Comment by lesleyjanenorton** [comment]
Unfortunately I don't think we can control this as it's decided by how 1.) How a browser interprets `window.open()` and 2.) the user's preferences about how new pages are opened.

**Comment by sandysage** [comment]
Since we can't control this behavior, closing this issue.
