### ISSUE TITLE
Cross-promote the Firefox Ecosystem in Firefox Monitor

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#1223]
Cross-promoting the Firefox ecosystem within Monitor. 

## Product Recommendations & Ranking
0. Firefox Accounts (sign-up for Monitor alerts)
1. Firefox Lockwise
2. Firefox Private Network
3. Firefox Mobile
4. Our Family of Products

## Display Logic & Content
- https://docs.google.com/spreadsheets/d/1Lw8Lp6lK9-ohKZA8nIiLL8AfYcNCzNH-1bNZ69gmlCg/edit?usp=sharing

## Logic & Design
- https://mozilla.invisionapp.com/share/RGRIETZ7NAJ#/376033857_Monitor_Promo_Varients
- https://zpl.io/V19X0GX

**Comment by sandysage** [comment]
Visual design provided here is an early spec for how we might approach this. I'm adding the 'needs-design' label to finalize the approach. Starting this issue largely so we can start scoping all the effort involved

**Comment by marniepw** [comment]
Trello card: https://trello.com/c/RJEwcjjT/890-firefox-monitor-cross-promote-the-firefox-ecosystem
PI Request: https://jira.mozilla.com/browse/PI-502

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
