### ISSUE TITLE
Security Tips styling updates

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#1226]
- [ ] align to spec: https://zpl.io/agQmjAD
- [ ] styling updates | matching spec for link list and button for reading all tips: https://zpl.io/2yqgE7o

**Comment by lesleyjanenorton** [comment]
Are we no longer waiting on illustrations/graphic pieces for these articles?

**Comment by changecourse** [comment]
@betsymi submitted the request to Sean Martell, but I believe it has yet to be prioritized. I'm fine moving forward without them, assuming that's the case still.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
