### ISSUE TITLE
[Mobile] The Bento menu can be dismissed by tapping on the top side

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1227]
## Steps to reproduce
1. Install and Launch the app.
2. Access `https://monitor-v2.herokuapp.com/`
3. Open the Bento menu
4. Tap anywhere on the top screen in the left part of `X` button.

### Expected behavior
The `Bento` menu should not be closed.
### Actual behavior
The `Bento` menu is closed/dismissed. 
* Android device: `Samsung Galaxy S10+(Android 9), Samsung Galaxy Note 9(Android 8)`
* Fenix version: `Latest Firefox and Chrome` versions.
### Notes
Note that by tapping anywhere on the white space it doesn't dismiss the Bento Menu. Only by tapping on the top.
![20191001_103404](https://user-images.githubusercontent.com/42831109/65943175-8d82bb00-e437-11e9-82bd-d74ded61fc52.gif)

**Comment by lesleyjanenorton** [comment]
This is as-designed since the clickable area of the close button on mobile would otherwise be quite small.
