### ISSUE TITLE
[Mobile] Pocket and Lockwise options from Bento menu redirect to Play Store instead of app(while app is installed)

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1229]
#### Preconditions
Pocked and Lockwise must be installed from the Play Store.
## Steps to reproduce
1. Install and Launch the app.
2. Access `https://monitor-v2.herokuapp.com/`
3. Open the Bento menu
4. Tap on Pocked or Lockwise options.

### Expected behavior
The Pocket or Lockwise apps should open.
### Actual behavior
The Pocket and Lockwise are opened in Play Store while the apps are installed.
* Android device: `Samsung Galaxy S10+(Android 9), Samsung Galaxy Note 9(Android 8)`
* Fenix version: `Latest Firefox and Chrome` versions.
### Notes:
Note that even if I was logged in, I was still redirected to the Play Store.
For more details please see the attachment.
![20191001_114515](https://user-images.githubusercontent.com/42831109/65948219-7eedd100-e442-11e9-8816-01be7b188b52.gif)

**Comment by hollycollier** [comment]
I'm having the same issue on iOS.

**Comment by lesleyjanenorton** [comment]
My understanding was that the adjust links for Lockwise and Pocket would handle this but if they aren't, we'll just need to get "deep links" for these apps.

**Comment by hollycollier** [comment]
Me too - let's bring this up with the Pocket & Lockwise teams.

**Comment by lwa-moz** [comment]
I'm following up with our reps at Adjust to understand how we can provide the best experience here.
