### ISSUE TITLE
[Mobile] The account panel is not opened if accessing it while Bento menu is expanded in landscape mode

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1235]
### Steps to reproduce
1. Install and Launch the app.
2. Access `https://monitor-v2.herokuapp.com/`
3. Open the Bento menu
4. Rotate the device in landscape mode.
5. Tap on the account panel/menu.

### Expected behavior
The Bento menu is closed and the account panel/menu is expanded.
### Actual behavior
The Bento menu is closed but the account panel/menu is not expanded.
* Android device: `Samsung Galaxy S10+(Android 9), Samsung Galaxy Note 9(Android 8), Samsung Galaxy Tab A(Android 9)`
* Fenix version: `Latest Firefox and Chrome` versions.
### Notes:
Please note that if opening the account panel/menu first and the accessing Bento menu, it will open and work correctly.
For more details please see the attachment.
![20191001_151553](https://user-images.githubusercontent.com/42831109/65961258-e4e85180-e45e-11e9-8868-8e45205c8543.gif)

**Comment by lesleyjanenorton** [comment]
Fixed in #1282
