### ISSUE TITLE
[Mobile] The account menu cannot be closed by tapping again on the menu icon

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1237]
## Steps to reproduce
1. Install and Launch the app.
2. Access `https://monitor.firefox.com
3. Login with valid credentials 
4. Tap on the account icon in order to open the menu.
5. Tap again on the account icon in order to close the menu.

### Expected behavior
The account menu is closed.
### Actual behavior
The account menu is not closed.
* Android device: `Samsung Galaxy S10+(Android 9), Samsung Galaxy Note 9(Android 8), Samsung Galaxy Tab A(Android 9)`
* Fenix version: `Latest Firefox and Chrome` versions.
### Notes:
For more details please see the attachment.
![20191001_152639](https://user-images.githubusercontent.com/42831109/65962374-3265be00-e461-11e9-86d9-af3c5cda55e5.gif)

**Comment by abodea** [comment]
Note that I added this issue as a general one but it happens on the `https://monitor-v2.herokuapp.com/` too. The only way to dismiss the menu is to tap on a specific part in the page. It would be more easy to dismiss it by tapping again on the icon.

**Comment by lesleyjanenorton** [comment]
Fixed in #1282
