### ISSUE TITLE
[Mobile] The Bento menu should be rearranged for portrait mode on devices with window sizes narrower than 500px

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1238]
### Why/User Benefit/User Problem
As a Firefox user, I to have a better arrangement on the Bento menu as there are many big spaces.
### What/Requirements
The Bento menu elements to be rearranged.
### Acceptance Criteria (how do I know when I’m done?)
The Bento menu elements are rearranged.
I made an example, but I'm sure it can be done way better.
![Screenshot_20191001-154810_Firefox - Copy](https://user-images.githubusercontent.com/42831109/65966156-64c6e980-e468-11e9-9121-938c00534cae.jpg)

**Comment by pwalm** [comment]
We added some white space at the top and bottom of the list to keep it (more or less) centred on the screen. This will allow us to add/remove services and products in the future while keeping everything balanced.
