### ISSUE TITLE
[Mobile]Bento button not visible when the "Hide Images" option is enabled

### ISSUE THREAD

**Issue by csuciu** [mozilla/blurts-server#1244]
iPad Air 3 (iOS 12.3)
Firefox v20.0

Steps: 
1. Visit https://monitor-v2.herokuapp.com/.
2. Open hamburger menu and enable the "Hide Images" option.
3. Refresh the page and check the "Bento" button.

Expected: The "Bento" button is visible.

Actual: The "Bento" button is no longer visible.

Note: This issue is reproducible on Android also.

**Comment by groovecoder** [comment]
RESOLVED:WONTFIX
