### ISSUE TITLE
Bento menu has scroll bars inside

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#1247]
[Affected versions]:
- Firefox 69.0.1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x 64

[Steps to reproduce]:
1. Navigate to  https://monitor-v2.herokuapp.com/
2. Click on the Bento box.

[Expected result]:
- Bento menu is correctly displayed.

[Actual result]:
- Bento menu has scroll bars.  

[Regression]:
- N/A

[Additional Notes]:
- On macOS the issue is reproducing a little diferent, only the scroll bar's border is present. 
- On macOS, it might depend on resolution, because on some macBook we can reproduce the issue and on others we can't. 
- Please look at the attached image. 
![bento 1](https://user-images.githubusercontent.com/42799381/66189110-abe3f300-e691-11e9-84f3-7355c38822ff.png)

**Comment by lesleyjanenorton** [comment]
Thank you for flagging - this should now be fixed! If you have time, please verify this is resolved.

**Comment by obotisan** [comment]
I verified the fix on Windows 10 x64, macOS 10.13 and Ubuntu 18.04 x64. The issue is not reproducing anymore.
