### ISSUE TITLE
Scrolling the Bento menu, scrolls the entire page 

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1248]
[Affected versions]:

- Firefox 69.0.1, Chrome 77.0.3865.90 and Safari 13.0.1

[Affected Platforms]:

- Windows 10 x64, macOS 10.14 and Ubuntu 18.04

[Steps to reproduce]:

1. Navigate to the Monitor website "https://monitor-v2.herokuapp.com/".
2. CIick the "bento menu" button.
3. Zoom in until the scrolls bar of the bento menu are enabled.
4. Start scrolling in the bento menu.

[Expected result]:
Scrolling is done in the bento menu, making all the options reachable.

[Actual result]:
Scrolling is done to the entire Firefox Monitor page. 

![2019-10-04_07h48_38](https://user-images.githubusercontent.com/56026823/66191975-2adc2a00-e698-11e9-8c81-fc28c15acb7a.gif)

**Comment by lesleyjanenorton** [comment]
Closing - the ability to scroll the page while the bento is open is intentional. Thanks!
