### ISSUE TITLE
[Safari] Bento menu changes behaviour after zooming in

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/blurts-server#1249]
[Affected versions]:
- Safari 13.0.1

[Affected Platforms]:
- macOS 10.14

[Steps to reproduce]:

1. Navigate to the Monitor website "https://monitor-v2.herokuapp.com/".
2. Click the "bento menu" button.
3. Zoom in the page.
4. Observe "Firefox is tech that fights for your online privacy." text and the options after the first zoom in.

[Expected result]:
-  "Firefox is tech that fights for your online privacy." text dimensions on the menu shouldn't change after zooming in(shouldn't extend on all bento box width).
- All options shouldn't flicker after zooming in.

[Actual result]:
-  "Firefox is tech that fights for your online privacy." text dimensions on the menu are changing after zooming in(extends on all bento box width).
- All options are flickering after zooming in.
https://imgur.com/a/N011NFe

[Note]:
-  The issue is not reproducible on Firefox and Chrome

**Comment by lesleyjanenorton** [comment]
The elements in the bento should grow in size as the page is zoomed.
