### ISSUE TITLE
Rename repo'n'stuff to firefox-monitor-server?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#125]
Possibly mildly disruptive, but may be nice to do before this goes out as a study or project.

**Comment by pdehaan** [comment]
We'd need to make sure we sync up w/ @Micheletto before renaming anything, as he'll need to make tweaks in #135; "Complete Dockerflow setup for stage & prod deployment pipelines".

From bobm:
> It has some minimal impact to the Dockerflow puppet I've got started, but not much that a find and replace can't fix.  The most time consuming changes would be changing the Docker hub and CircleCI configuration.  If the dev team can handle the CircleCI stuff, I can worry about the hub configuration.

**Comment by pdehaan** [comment]
We decided (offline) that this can/should wait until post shield study to be less disruptive as we try and wrap everything up in time for the Shield Study.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
