### ISSUE TITLE
[Mobile] Incorrect behavior when scrolling the Bento menu in landscape mode

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1250]
## Steps to reproduce
1. Install and Launch the app.
2. Access `https://monitor-v2.herokuapp.com/`
3. Open the Bento menu
4. Scroll up and down.

### Expected behavior
The `Bento` menu should be scrollable without problems.
### Actual behavior
The `Bento` menu flickers when scrolling, and the entire page is also scrolled.
* Android device: `Samsung Galaxy S10+(Android 9), Samsung Galaxy Note 9(Android 8)`
* Fenix version: `Latest Firefox and Chrome` versions.
### Notes
@lesleyjanenorton note the following:
 - There are scroll bars in Bento menu. 
 - The size of Bento menu changes depending of the zoom of the page - sometimes it gets very small.
 - If zooming in the scrolling bars disappears and
![20191004_124644](https://user-images.githubusercontent.com/42831109/66198824-e9eb1200-e6a5-11e9-9da8-3c2001d4e380.gif)

**Comment by lesleyjanenorton** [comment]
Closing in favor of #1237
