### ISSUE TITLE
[Mobile] The bottom scroll bar is not displayed on Bento menu(while zoomed in)

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1255]
## Steps to reproduce
1. Install and Launch the app.
2. Access `https://monitor-v2.herokuapp.com/`
3. Open the Bento menu
4. Zoom In.
5. Scroll until the bottom.

### Expected behavior
The bottom scroll bar should be displayed.
### Actual behavior
The bottom scroll bar is not displayed.
* Android device: `Samsung Galaxy S10+(Android 9), Samsung Galaxy Tab A(Android 9)`
* Fenix version: `Latest Firefox and Chrome` versions.
### Notes:
For more details please see the attachment.
![Screenshot_20191007-165138_Firefox](https://user-images.githubusercontent.com/42831109/66317901-0b0c6680-e923-11e9-9438-1733b3503bd0.jpg)

**Comment by lesleyjanenorton** [comment]
Without zooming, does the content bleed off the edge of the screen or do the links wrap? If not, I'm not sure a scroll bar should be visible as there is really nothing to scroll.

**Comment by abodea** [comment]
Without zooming, the content of the Bento menu is displayed correctly and it doesn't really require a scroll bar.
