### ISSUE TITLE
Bento menu becomes invisible when clicked multiple times

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1260]
[Affected Platforms and versions]:

- Windows 10 x64 (Firefox and Chrome)
- Ubuntu 18.04 x64 (Firefox and Chrome)
- MacOS 10.14 (Firefox and Safari)

[Steps to reproduce]:

1. Navigate to the Monitor website "https://monitor-v2.herokuapp.com/".
2. Click the "bento menu" button more rapidly and successively for a couple of times (5 times).
   
[Expected result]:

- The bento menu is opened and visible.

[Actual result]:

- The bento menu is not visible.

Video recording: https://www.screencast.com/t/K5GAifHHHKy

**Comment by lesleyjanenorton** [comment]
Closing - I think this was fixed with the other bento issues but in any case I can't currently reproduce.
