### ISSUE TITLE
The bento menu box flickers when the menu is clicked

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1262]
[Affected versions]:

- Firefox 69.0.2, Chrome 77.0.3865.90 and Safari 11.1.2

[Affected Platforms]:

- Windows 10 x64, macOS 10.14 and Ubuntu 18.04

[Steps to reproduce]:

1. Navigate to the Monitor website "https://monitor-v2.herokuapp.com/".
2. CIick the bento menu box.
3. In the opened menu, click on the "Firefox is tech that fights for your online privacy." text.
   
[Expected result]:

- The bento menu box is not affected when the text is selected.

[Actual result]:

- The bento menu box flickers when any click is made in the opened menu.

![Screencast1](https://user-images.githubusercontent.com/56026823/66392903-d3acc100-e9d9-11e9-9fa1-fe5d5d384687.gif)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
