### ISSUE TITLE
The Enter your email  field is populated with a "null" string 

### ISSUE THREAD

**Issue by dcicas** [mozilla/blurts-server#1264]
[Affected Platforms and versions]:
Windows 10 x64 (Firefox)
Ubuntu 18.04 x64 (Firefox)
MacOS 10.13 (Firefox)

[Steps to reproduce]:
1. Open Firefox with a clean profile.
2. Open www.reddit.com.
3. Click on the Shield icon.
4. Click on Show Report.
5. Click on Sign Up for Breach Alerts.
6. In the top right corner click on Sign In.

[Expected result]:
The Enter you email field is empty.
[Actual result]:
The Enter your email  field has the string "null" in it  and  the error Valid email required is visible.

![NULL](https://user-images.githubusercontent.com/56347786/66477220-39638080-eaa0-11e9-8066-8948f8ac7107.gif)

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa/issues/2840
