### ISSUE TITLE
[Non-FxA Subscriber Email] The avatar image for breach accounts is not displayed

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#1279]
[Affected versions]:
- Firefox 70.0 RC2

[Affected Platforms]:
- Windows 7, 10 x64
- macOS 10.14
- Ubuntu 18.04 x64

[Preconditions]:
- Have a non-FxA breach email opened in Inbox.
- Click on the "Firefox Monitor found your email in a new data breach" email subject.

[Steps to reproduce]:
1. Inspect the avatar image for "LinkedIn" account.
   
[Expected result]:
- The avatar image for "LinkedIn" account is correctly displayed, see the specs for [reference](https://mozilla.invisionapp.com/share/4ZSDCA33WDM#/screens/380787104_Unauthenticated_User_-_New_Breach_). 

[Actual result]:
- A placeholder is displayed for the "LinkedIn" account.

[Additional notes]:
- please observe the attached 
![image](https://user-images.githubusercontent.com/43886441/67090664-58a29200-f1b3-11e9-9cd7-ff3d146effe7.png)

**Comment by lesleyjanenorton** [comment]
Thank you for filing! This is (unfortunately) a known issue and expected for the time being, until we have a system in place for either 1.) delaying the breach alert emails until we can load in a curated image or 2.) configure out set up to default to this placeholder image until the actual image is loaded in.

**Comment by lesleyjanenorton** [comment]
closing in favor of #1469
