### ISSUE TITLE
[Non-FxA Subscriber Email] The "NEW" element is not displayed in the email alert

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#1280]
[Affected versions]:
- Firefox 70.0 RC2

[Affected Platforms]:
- Windows 7, 10 x64
- macOS 10.14
- Ubuntu 18.04 x64

[Preconditions]:
- Have a non-FxA breach email opened in Inbox.
- Click on the "Firefox Monitor found your email in a new data breach" email subject.

[Steps to reproduce]:
1. Inspect the upper right corner of the Breach account.
   
[Expected result]:
- The "NEW" element is displayed in the upper right corner of the non-FxA breach account.

[Actual result]:
- The "NEW" element is missing from the non-FxA breach account.

[Additional notes]:
- please observe the attached 
![image](https://user-images.githubusercontent.com/43886441/67091555-a0c2b400-f1b5-11e9-86c6-4b0e4af3790d.png)

**Comment by lesleyjanenorton** [comment]
Closing - we removed this label due to concerns about the limited space inside breach cards and the label competing for space with the breach title.
