### ISSUE TITLE
monitor.firefox.com has failed the web security baseline

### ISSUE THREAD

**Issue by mozcloudsec** [mozilla/blurts-server#1293]
Site https://monitor.firefox.com has failed the web security baseline scan.

The failing tests are:

 Absence of Anti-CSRF Tokens [10202] x 1 
 * https://monitor.firefox.com/breaches (200 OK)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=monitor.firefox.com) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by lesleyjanenorton** [comment]
Screen capping from the Security Baseline Dashboard...<img width="1001" alt="Screen Shot 2019-10-22 at 9 51 16 AM" src="https://user-images.githubusercontent.com/22355127/67298959-ab30c680-f4b1-11e9-87d4-0f794f5fbd87.png">

**Comment by psiinon** [comment]
You can definitely ignore the warning :)

**Comment by mozcloudsec** [comment]
The web security baseline for site https://monitor.firefox.com is still failing, this issue should stay open.

**Comment by mozcloudsec** [comment]
Unable to change this issue state to "open" due to lack of permissions - please do this manually

**Comment by moz-hwine** [comment]
The web security baseline scan for site https://monitor.firefox.com now passes - well done team!
