### ISSUE TITLE
stage.firefoxmonitor.nonprod.cloudops.mozgcp.net has failed the web security baseline

### ISSUE THREAD

**Issue by mozcloudsec** [mozilla/blurts-server#1294]
Site https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net has failed the web security baseline scan.

The failing tests are:

 Absence of Anti-CSRF Tokens [10202] x 1 
 * https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/breaches (200 OK)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=stage.firefoxmonitor.nonprod.cloudops.mozgcp.net) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by mozcloudsec** [comment]
The web security baseline for site https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net is still failing, this issue should stay open.

**Comment by mozcloudsec** [comment]
Unable to change this issue state to "open" due to lack of permissions - please do this manually

**Comment by psiinon** [comment]
Yeah:

> This issue was automatically raised.
> 
> This issue is managed automatically by the baseline scan:
> 
>     * If the failing tests change then it will be updated
> 
>     * If it is closed before the tests pass then a new one will be opened
> 
>     * When all of the tests pass then it will be closed

I think it was actually my fault it was closed - I thought I'd worded the 'fixes' comment in https://github.com/mozilla/blurts-server/pull/1296 to avoid that but looks like I got it wrong :P

**Comment by moz-hwine** [comment]
The web security baseline scan for site https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net now passes - well done team!

**Comment by psiinon** [comment]
FYI we've changed to use the @moz-hwine account for baseline issues as this has permissions to private repos :)
