### ISSUE TITLE
Add nb-NO localization

### ISSUE THREAD

**Issue by estensen** [mozilla/blurts-server#1297]
Most people in Norway have nb as their preferred language over nn.
I'm a native speaker and can add it.

**Comment by havarh** [comment]
I've just submitted a request for this project. When the request goes trough, the translation will take place on Pontoon at this url:
https://pontoon.mozilla.org/nb-NO/firefox-monitor-website/

**Comment by havarh** [comment]
It's now available on Pontoon as of 3 days ago. Feel free to help with the localization.

**Comment by pdehaan** [comment]
Thanks @estensen and @havarh!
We'll watch the upstream _nb-NO_ strings in Pontoon and add it to the production site once it hits 100%-ish translation.

**Comment by havarh** [comment]
nb-NO is now 100% translated.
