### ISSUE TITLE
Global Communication Preferences: UI/UX Improvements

### ISSUE THREAD

**Issue by changecourse** [mozilla/blurts-server#1300]
Options for global communication should be styled as radio buttons, not checkboxes. Additionally, there should be a visual affordance for a successful change between the two options, so let's fade in the same type of green status indicator as we use for adding a new email, when someone changes this. (Fade in, hold for 5 seconds, fade out) 

Zeplin: https://zpl.io/aMWEgKd

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
