### ISSUE TITLE
Measure success of 'change password'

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#1301]
As we look to introduce this new 'call to action', we'll want to include event tracking.

We believe Monitor users want to be able to take action upon learning about a breach. We will know this to be true when 5% or more site visitors click to change their password.

Roughly 3-4% of all site visitors navigate to /security-tips, which is where we send any intent to take a 'next step' ("What to do after a website breach"): https://analytics.google.com/analytics/web/#/report/content-overview/a77033033w177898028p180612539/_u.date00=20190501&_u.date01=20191021 

We expect a more actionable 'change your password' option that is more visible on the breach detail to convert a higher number of visitors to take an action. But also we know the 'gold standard' for conversion on changing a password is ~26% (per [Google UR in this space](https://www.usenix.org/conference/usenixsecurity19/presentation/thomas), which is based on in-context breach notifications.

@irrationalagent I'd like your thoughts on how we should measure intent here as well. Let me know if there is a better way we might evaluate the success of this initial feature.

child of #1225

**Comment by sandysage** [comment]
From discussions today, we're looking for a range of engagement between what we see of all site visits to security tips (5% conversion total) and intent on desktop (24% conversion from a specific breach). We'll want to intentionally monitor total conversions as outlined in the description as well as conversions from breach detail pages (the common path after a scan or account registration).

We may consider a follow up test to include the change password option at the card level to see if there is more intent introduced earlier in the flow. But for now, we just want to understand if people really do take an intentional action after finding out they've been involved in a breach.

**Comment by maxxcrawford** [comment]
I have a solution for this, based on @lesleyjanenorton's [commit](https://github.com/mozilla/blurts-server/commit/f425d48d9578e8cf536073a714d2476d63cd0e09) but want to confirm the specific Google Analytics attributes involved in measuring this: 

- `event-label`
- `event-action`
- `event-category`

Is there someone who can provide what these attributes need to be exactly so that this metric shows up clearly in GA?
