### ISSUE TITLE
Flash of unstyled html on initial page load

### ISSUE THREAD

**Issue by changecourse** [mozilla/blurts-server#1302]
The raw html content is seen in an unstyled manner for a short (1 second or less) time on initial load (and subsequent reloads)

This happens on the following pages:
- Home (unauthenticated)
- Home (authenticated)
- Breach Detail
- Security Tips
- Monitor Preferences

It does not, however, happen on the Breaches landing page. 

I imagine this has something to do with progressive enhancement loading of the page, but I'd like to address the visual pop of unstyled content in some sort of graceful manner.

**Comment by lesleyjanenorton** [comment]
@changecourse I am getting this too (not to the extent of raw html) but there's a definite content "wiggle". Are you also seeing this on the Heroku sites? The issue seems worse on prod. To really fix this I think we may need to 1.) use a CDN and 2.) do cleanup - js/css audit and use sprite sheets.

**Comment by changecourse** [comment]
>Are you also seeing this on the Heroku sites?

A bit of content wiggle, but no massive jump, as seen on prod. 

It's also interesting to me that there is no browser caching to prevent this flash/pop from happening on revisits to the page/reloads.

**Comment by ddurst** [comment]
I don't see it after the initial load. @changecourse do you see it on every load?

**Comment by changecourse** [comment]
@ddurst yes, each and every time, for  every page listed above.

**Comment by changecourse** [comment]
Screen cap: [reload.zip](https://github.com/mozilla/blurts-server/files/3763344/reload.zip)

**Comment by lesleyjanenorton** [comment]
@changecourse  Two questions: Does this also happen on the heroku server? and do you have any dev tools open at the same time?

**Comment by changecourse** [comment]
> Does this also happen on the heroku server?
Nope. I see a little bit of content wiggle, but no massive flash/pop.

> Do you have any dev tools open at the same time?
Nope.

**Comment by lesleyjanenorton** [comment]
@changecourse  thanks. I think we need a CDN. 

Possibly unrelated but I'm wondering what this `https://members.galvanize.com` thing is doing at 00:20? @groovecoder any thoughts?
<img width="151" alt="Screen Shot 2019-10-23 at 11 23 17 AM" src="https://user-images.githubusercontent.com/22355127/67413949-c4a44200-f587-11e9-989f-1fbd92162594.png">

**Comment by changecourse** [comment]
That is strange... 

`https://members.galvanize.com` is our wifi handling for our office in Denver... but I'm not in the office today, I'm working from home... 0_0

**Comment by lesleyjanenorton** [comment]
![](https://media.giphy.com/media/sBl8Fowq0ErFC/giphy.gif)

**Comment by changecourse** [comment]
The plot thickens: restarting Firefox in safe mode alleviates the issue... 

Upon going through my add-ons, disabling one at a time, it is AdBlocker Ultimate that appears to be causing this...

**Comment by lesleyjanenorton** [comment]
That culprit! I wonder why this wasn't happening on `/breaches`?

**Comment by lesleyjanenorton** [comment]
Do we want to leave this open or is this now safe to close?

**Comment by changecourse** [comment]
@ddurst had followed up on this with our add-on folks. What do you think, Durst?

**Comment by ddurst** [comment]
This is specific to something that the AdBlocker Ultimate extension is doing, which is unlike some other adblockers.

I want to say that anyone using ABU is seeing this elsewhere, but I don't see this level of FOUC on any other site (after checking sites that I would assume would also have strict CSPs set). So I think there is something in here to figure out.

**Comment by ddurst** [comment]
(Also, since ABU is a recommended extension -- it's more significant that a web property of ours be alone in showing adverse effects.)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
