### ISSUE TITLE
Create release signoff document

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1306]
Before doing a stage/production release, we should probably write up some document (./docs/RELEASE_CHECKLIST.md?) for what steps need to be done before we deploy.

Some suggestions are:

1. Verify new tables/columns have appropriate indexes. Not sure how/if we can automate this, or how to test it. There was some Slack conversations about a "postgres EXPLAIN" command, but I haven't tried digging in yet.
1. Verify assets are minified (images, etc).
1. Verify latest breaches have logos.
1. Verify latest 100% (90%?) locales are enabled on production (w/ coordination w/ OPs whom I believe have to set the locales in some k8s config files somewhere).
1. \<other\>

**Comment by pdehaan** [comment]
re: locales, here's part of the recent Slack thread:

- Peter deHaan  3 minutes ago
  https://pontoonql.now.sh/firefox-monitor-website/80 if you need an easy-ish web UI to Pontoon stats

- Peter deHaan  2 minutes ago
  <kbd>npx pdehaan/pontoonql firefox-monitor-website 80</kbd> if you want more of an artisinal CLI experience.
  or https://github.com/pdehaan/pontoonql if you want to just use a wrapper API.

**Comment by pdehaan** [comment]
Also, make sure we have zero pending breaches in the Kinto queue.
We have a handy <kbd>npx pdehaan/blurts-kinto</kbd> helper here, which should either return a JSON blob of pending/missing records, or a "RemoteSettings is up to date!" message.

<details>
<summary>Missing breaches output (if any)</summary>

```js
[
  {
    "Name": "HookersNL",
    "Title": "Hookers.nl",
    "Domain": "hookers.nl",
    "BreachDate": "2019-10-10",
    "AddedDate": "2019-10-23T09:51:59Z",
    "ModifiedDate": "2019-10-23T09:51:59Z",
    "PwnCount": 290955,
    "Description": "In October 2019, the Dutch prostitution forum <a href=\"https://www.forbes.com/sites/thomasbrewster/2019/10/10/dutch-prostitution-site-hookersnl-hacked--250000-users-data-leaked/#3e3f231522f8\" target=\"_blank\" rel=\"noopener\">Hookers.nl suffered a data breach</a> which exposed the personal information of sex workers and their customers. The IP and email addresses, usernames and bcrypt password hashes of 291k members were accessed via an unpatched vulnerability in the vBulletin forum software.",
    "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/HookersNL.png",
    "DataClasses": [
      "Email addresses",
      "IP addresses",
      "Passwords",
      "Usernames"
    ],
    "IsVerified": true,
    "IsFabricated": false,
    "IsSensitive": true,
    "IsRetired": false,
    "IsSpamList": false
  },
  {
    "Name": "Zooville",
    "Title": "Zooville",
    "Domain": "zooville.org",
    "BreachDate": "2019-09-27",
    "AddedDate": "2019-10-19T21:22:44Z",
    "ModifiedDate": "2019-10-20T21:58:16Z",
    "PwnCount": 71407,
    "Description": "In September 2019, the zoophilia and bestiality forum <a href=\"https://www.zooville.org/threads/security-incident-and-site-rebuild-september-2019.9/\" target=\"_blank\" rel=\"noopener\">Zooville suffered a data breach</a>. The usernames and email addresses of 71k members were accessed via an unpatched vulnerability in the vBulletin forum software then subsequently distributed online. A second data set was later provided to HIBP which contained a complete vBulletin database dump including IP addresses, dates of birth and passwords stored as bcrypt hashes. The site administrator advised that following the breach, all data had been deleted from the forum and a new one had been stood up on the XenForo platform. The data was provided to HIBP by a source who requested it be attributed to &quot;burger vault&quot;.",
    "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Zooville.png",
    "DataClasses": [
      "Dates of birth",
      "Email addresses",
      "IP addresses",
      "Passwords",
      "Usernames"
    ],
    "IsVerified": true,
    "IsFabricated": false,
    "IsSensitive": true,
    "IsRetired": false,
    "IsSpamList": false
  }
]
```

</details>

**Comment by pdehaan** [comment]
OPs is already flagged as reviewers on any new ./db/migrations/* _scripts_ added, per the CODEOWNERS file: https://github.com/mozilla/blurts-server/blob/4a183ebea27af32de5b0f1ee343402e43535c6c5/docs/CODEOWNERS#L4-L5

Not sure if we should also mark them as reviewers on any potential _query_ changes in the [/db/DB.js](https://github.com/mozilla/blurts-server/blob/master/db/DB.js) file as well, or if that'd be too noisy.

**Comment by pdehaan** [comment]
I think @groovecoder also maintains some Locust-based loadtests in the /loadtests directory (unsurprisingly). We should probably at a minimum run those against Heroku. Up for debate on whether we want to load test stage (with OPs blessing) before deploying to production.

**Comment by EMMLynch** [comment]
Closing
