### ISSUE TITLE
Audit Postgres indexes

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1309]
Index All The Things!

I'm trying to come up with a semi-comprehensive list of queries and indexes to try and identify any problem areas (and get a better sense of DB indexing w/ Postgres in general).

So far I've tried trolling through all the ./db/migrations/* and come up with a lost of anything marked `.primary()` or mentions `.index()`. Here's what I've come up with:

| TABLE.COLUMN | TYPE | NOTES
|:-------------|:-----|------
| `email_addresses.id` | .primary()
| `email_addresses.sha1` | .primary()
| `email_addresses.verification_token` | .unique()
| `subscribers.created_at` | .index()
| `subscribers.email` | .index()
| `subscribers.id` | .primary()
| `subscribers.sha1` | .index()
| `subscribers.verification_token` | .unique()
| `subscribers.verified` | .index()

I feel like I'm missing a few things here.

Renamed columns:

| OLD TABLE.COLUMN | NEW TABLE.COLUMN
|:----|:----
| `subscribers.email` | `subscribers.primary_email`
| `subscribers.sha1` | `subscribers.primary_sha1`
| `subscribers.verification_token` | `subscribers.primary_verification_token`
| `subscribers.verified` | `subscribers.primary_verified`

---

Next, I tried to find all queries with a `.where()`, `.whereIn()`, `.whereRaw()`, or `.andWhere()` reference (and did my best to de-knex them into a more readable SQL-esque format, then sorted and deduped):

- [ ] `email_addresses.email = $email`
- [x] `email_addresses.id = $emailId`
- [x] `email_addresses.sha1 in $hashes`
- [ ] `email_addresses.subscriber_id = $userId`
- [x] `email_addresses.verification_token = $token`
- [ ] `email_addresses.verified = true`
- [x] `subscribers.created_at < $expiredTimeStamp`
- [ ] `subscribers.fxa_uid = $fxaUID`
- [x] `subscribers.id = $id`
- [x] `subscribers.primary_email = $email`
- [x] `subscribers.primary_sha1 = $emailSha1`
- [x] `subscribers.primary_verification_token = $token`
- [x] `subscribers.primary_verified = true`

The ✅ above represent a match between a select.where() clause and the `.index()` or `.primary()` in the preceeding table. But doesn't take into account possible column renames.

I'm guessing this is inaccurate and full of holes, but hopefully a decent-adjacent starting point.

**Comment by pdehaan** [comment]
Also, I think we had a recent issue w/ missing indexes on production earlier this week, but the most recent migration in ./db/migrations/* seems to be from 2019-07-13T19:38:52 (20190713193852_add_email_sha1_index.js).

**Comment by pdehaan** [comment]
OK, I did some hacking this afternoon and it looks like I can query Postgres directly for table indexes, which might be more bulletproofer:

TABLE | KEY[S] | INDEX
------|--------|-------
email_addresses | id | CREATE UNIQUE INDEX
email_addresses | sha1 | CREATE INDEX
email_addresses | verification_token | CREATE UNIQUE INDEX
knex_migrations | id | CREATE UNIQUE INDEX
subscribers | created_at | CREATE INDEX
subscribers | primary_email | CREATE INDEX
subscribers | id | CREATE UNIQUE INDEX
subscribers | primary_sha1 | CREATE INDEX
subscribers | primary_verification_token | CREATE UNIQUE INDEX
subscribers | primary_verified | CREATE INDEX

```js
"use strict";

const DB = require("../db/DB");

(async () => {
  await DB.columninfo();
  process.exit();
})();
```

Where I monkey patched db/DB.js and added the following dumpster fire code:

```js
  async columninfo() {
    // const r = await DB.sql("SELECT * FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'");
    const r = await knex.raw(`SELECT
        indexdef
      FROM
        pg_indexes
      WHERE
        schemaname = 'public'
      ORDER BY
        tablename,
        indexname;`);
    const indexes = r.rows
      .map((row) => row.indexdef
        .replace(/(CREATE.*?\sINDEX).*?ON public\.(.*?) USING btree \((.*?)\)$/, "$2 | $3 | $1"));
  
    console.log("TABLE | KEY[S] | INDEX\n------|--------|-------");
    console.log(indexes.join("\n"));
  },
```

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
