### ISSUE TITLE
Security terms glossary

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#1318]
When I'm reading about breaches and security tips, I want to better understand the terms being used (eg credential stuffing) without leaving the context of the breach or the advice.

## Acceptance criteria
- [ ] Should offer easy to understand explanations for the terms:
   - [ ] credential stuffing
   - [ ] data breach
   - [ ] sensitive website breach
   - [ ] master password
- [ ] Should offer these definitions without removing the user out of the context of their reading

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
