### ISSUE TITLE
Ability to Sort/Filter Breaches 

### ISSUE THREAD

**Issue by changecourse** [mozilla/blurts-server#1325]
Currently the breach cards within /breaches are sorted by recency. It may be nice to consider future enhancements around sorting (alphabetical vs. recent) or filtering (by breach type)

I know we previously had some of this already included; this is a placeholder for considering how we'd want to do it specifically.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
