### ISSUE TITLE
Evolve monitor.firefox.com/user/dashboard to be more user friendly 

### ISSUE THREAD

**Issue by cherrypsf** [mozilla/blurts-server#1329]
When logged into the Monitor site, the direct link to /dashboard looks great, but for those logged out, the first thing a user sees is "Error" (with login copy below - see screenshot)

Can we evolve the page to make it clearer to users that they just simply need to login so that any promotional communications that speak directly about the dashboard or targeted to known Monitor users (like via email) can be linked to this URL?

<img width="1201" alt="Screen Shot 2019-10-31 at 1 46 54 PM" src="https://user-images.githubusercontent.com/57236990/67985773-d371a100-fbe6-11e9-83c8-812914d2ea64.png">

**Comment by lesleyjanenorton** [comment]
We absolutely can and should. Let's make sure to cover this in the meeting tomorrow.

**Comment by groovecoder** [comment]
Discussed in today's meeting ...

When a user needs to be signed in, we will redirect them directly into the OAuth flow.
