### ISSUE TITLE
Review the list of locales enabled in production

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#1332]
Not sure if a new issue is better than https://github.com/mozilla/blurts-server/issues/1066 (which should probably be closed at this point).

From a quick look, we're missing a few locales in production, and have some locales that fell below the 80% completion.

Locales below threshold (4):
- el (67.67%)
- ja (71.68%)
- ms (39.35%)
- nn-NO (78.2%)

Missing locales (2):
- fi (100.0%)
- kab (100.0%)

We should definitely remove `ms`, I would keep the other 3 around for now.

**Comment by pdehaan** [comment]
@groovecoder In the next production deploy ticket, can we add the **"fi"** and **"kab"** locales (both 100% translated) and remove **"ms"** (currently 40% translated)?

**Comment by pdehaan** [comment]
@flodolo I believe this was completed in our latest 9.0.3 production deploy (per https://bugzilla.mozilla.org/show_bug.cgi?id=1594852).

```js
{
  commit: "3f135f71e99f534043398905042c074cfd5df9cb",
  version: "v9.0.3",
  source: "https://github.com/mozilla/blurts-server",
  build: "https://circleci.com/gh/mozilla/blurts-server/7503"
}
```

Your current list of production locales (per the private OPs repo) should be:

```yaml
firefoxMonitorSupportedLocales: "cak,cs,cy,da,de,el,en,en-CA,en-GB,es-AR,es-CL,es-ES,es-MX,fi,fr,fy-NL,hu,kab,ia,id,it,ja,nl,nn-NO,pt-BR,pt-PT,ro,ru,sk,sl,sq,sv-SE,tr,uk,vi,zh-CN,zh-TW"
```

**Comment by groovecoder** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1594852 updated locales with the latest supported languages.

**Comment by pdehaan** [comment]
FWIW, here's a crappy script to diff the production locales (which we'll need to copy-paste from the private cloudops repo) and diffs them against the [80%+] locales from Pontoon:

```js
// npm i pdehaan/pontoonql simple-array-diff
const pontoonql = require("pontoonql");
const diff = require("simple-array-diff");

// NOTE: grab the current list of prod locales from the private cloudops repo.
const opsSupportedLocales = listToArray(
  "cak,cs,cy,da,de,el,en,en-CA,en-GB,es-AR,es-CL,es-ES,es-MX,fi,fr,fy-NL,hu,kab,ia,id,it,ja,nl,nn-NO,pt-BR,pt-PT,ro,ru,sk,sl,sq,sv-SE,tr,uk,vi,zh-CN,zh-TW"
);

main(opsSupportedLocales);

async function main(ops = [], project = "firefox-monitor-website", pct = 80) {
  try {
    const currentSupportedLocales = await pontoonql(project, pct)
      .then(res => res.map(item => item.locale.code).sort());
    const res = diff(currentSupportedLocales, opsSupportedLocales);
    console.log(res);
    // console.log(JSON.stringify(res, null, 2));
  } catch (err) {
    console.error(err.message);
    process.exitCode = 1;
  }
}

function listToArray(list) {
  return list
    .split(",")
    // .map(item => item.trim())
    .sort();
}
```

### OUTPUT

```js
{
  added: [ 'el', 'en', 'ja', 'nn-NO' ],
  removed: [],
  common: [
    'cak',   'cs',    'cy',    'da',
    'de',    'en-CA', 'en-GB', 'es-AR',
    'es-CL', 'es-ES', 'es-MX', 'fi',
    'fr',    'fy-NL', 'hu',    'ia',
    'id',    'it',    'kab',   'nl',
    'pt-BR', 'pt-PT', 'ro',    'ru',
    'sk',    'sl',    'sq',    'sv-SE',
    'tr',    'uk',    'vi',    'zh-CN',
    'zh-TW'
  ]
}
```

**Comment by flodolo** [comment]
I have already a local Python script that queries Pontoon, the problem is having the prod locales information available somewhere ;-)

**Comment by pdehaan** [comment]
> the problem is having the prod locales information available somewhere

Ha, yeah, sorry. I'm still hoping we can get #1333 implemented for Stage/Prod.

I was just trying to write this script as an easier way for me to check for unexpected diffs between the current Pontoon locales and what we have supported in production so we can get 100% locales up on production sooner. I remember we have #1297 for enabling "nb-NO" locale once it hits 80-100% on Pontoon (currently 66%; but I am trying to keep an eye on it).

We have https://pontoonql.now.sh/firefox-monitor-website/80 which shows all 80%ish locales, but it isn't the easiest to see added/removed locales vs a "known" production list.

**Comment by flodolo** [comment]
What  I use is here
https://gist.github.com/flodolo/897175807acc679ba08c1251c5c3735a

```
Locales below 80% threshold (3):
el (66.42%)
ja (69.59%)
nn-NO (76.4%)

No locales missing from production.
```

**Comment by pdehaan** [comment]
It ain't pretty, but here's my script: https://github.com/pdehaan/pontoon-l10n-lint

```sh
npx pdehaan/pontoon-l10n-lint --pontoon-config=./.l10n-lint.json

{
  added: [ 'el', 'ja', 'nn-NO' ],
  removed: [],
  common: 'cak,cs,cy,da,de,en,en-CA,en-GB,es-AR,es-CL,es-ES,es-MX,fi,fr,fy-NL,hu,ia,id,it,kab,nl,pt-BR,pt-PT,ro,ru,sk,sl,sq,sv-SE,tr,uk,vi,zh-CN,zh-TW'
}
```

Output isn't nearly as nice as yours, but I should be able to specify 
`"extraLocales": ["en", "el", "ja", "nn-NO"]` in my local config file and suppress those `added` values.
