### ISSUE TITLE
Add supported locales to stage/production /__version__ endpoint

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1333]
Ref #609 and #1245 PR and https://github.com/mozilla/blurts-server/pull/1245#issuecomment-538105086

Currently the production [`/__version__`](https://monitor.firefox.com/__version__) endpoint has the following:

```js
{
  "commit": "6280822d4db00ed58a3d149e5abd51a3df443c83", 
  "version": "v9.0.2",
  "source": "https://github.com/mozilla/blurts-server",
  "build": "https://circleci.com/gh/mozilla/blurts-server/7318"
}
```

But the Heroku [`/__version__`](https://fx-breach-alerts.herokuapp.com/__version__) endpoint also has a jazzy `languages` string of supported locales:

```js
{
  "commit": "46fc20a687a39fa4588ec1934f80791cb9ed8222",
  "version": "46fc20a687a39fa4588ec1934f80791cb9ed8222",
  "source": "https://github.com/mozilla/blurts-server",
  "languages": "cs,cy,da,de,en,en-CA,es-AR,es-CL,es-ES,es-MX,fr,fy-NL,hu,ia,id,it,ja,kab,ms,nl,pt-BR,pt-PT,ro,ru,sk,sl,sq,sv-SE,tr,uk,vi,zh-CN,zh-TW"
}
```

It'd be great if we can find a way to add the "languages" string/array to the stage/production endpoints as well so QA/l10n can know exactly which languages are supported. I know we have a Top Secret OPs repo (URL redacted) with configs and the `firefoxMonitorSupportedLocales` array, but not everybody has security clearance access to that repo, and somehow shimming the `firefoxMonitorSupportedLocales` config into the `/__version__` endpoint would solve that issue and give l10n people a definitive way of seeing what locale support is currently in production, and know if the locale list is stale or not.

/cc @flodolo @Micheletto

**Comment by Micheletto** [comment]
The version.json file is created [here](https://github.com/mozilla/blurts-server/blob/master/.circleci/config.yml#L11-L19).

**Comment by pdehaan** [comment]
@flodolo If we move the list of supported locales into this repo, do you think it makes more sense in the [l10n.toml](https://github.com/mozilla/blurts-server/blob/master/l10n.toml) file, or should we maybe just add it to the package.json file? I'm not exactly sure how the l10n.toml file is used by the l10n tools.

**Comment by flodolo** [comment]
Let's add them to `packages.json`.

The TOML file could have a list of locales, but that's used to determine against which locales to run `compare-locales` ([example](https://searchfox.org/mozilla-central/source/browser/locales/l10n.toml)).

**Comment by flodolo** [comment]
Who would own the next steps to make it happen? I feel like we resurface this periodically, but it loses traction very quickly.

**Comment by pdehaan** [comment]
@groovecoder @lesleyjanenorton Can you two help me understand how the locales stuff works currently?

My understanding is that we're currently getting the list of supported locales via an env var (conveniently named `SUPPORTED_LOCALES`):

https://github.com/mozilla/blurts-server/blob/804d67cc42a301b36f2c8474c1e250e2f7588e9e/.env-dist#L69-L70

So, is the only change here that we switch from an `process.env.SUPPORTED_LOCALES` to scraping the value from a new package.json `supportedLocales` key (and then adding a special case for Heroku/wherever to set the supported locales to "*"), or is there a better approach?

**Comment by flodolo** [comment]
Hi, periodic ping :)

**Comment by pdehaan** [comment]
@flodolo On a possible bright side, I did make this issue one of my H1 goals for this year, so I'll be motivated to get this fixed to help you and your team.
I'm hoping this is as easy as hardcoding the list of supported locales into package.json (or somewhere) and then copying over into version.json and working with @Micheletto or somebody in OPs to make sure they can pull the values from there instead of the current secret ops repo value, and then making sure I override to "*" for Heroku and other environments where we want all locales to be supported, regardless of their actual translation %.

**Comment by flodolo** [comment]
Thanks for the fix :)

Just to confirm: if I need to add a new locale to production (or drop it), now I could simply open a PR against packages.json, and the next deployment to prod would make it happen?
