### ISSUE TITLE
Additional email disappears

### ISSUE THREAD

**Issue by vers-one** [mozilla/blurts-server#1334]
1. I log into Firefox Monitor.
2. Add an additional email.
3. Go to the inbox and click on the confirmation button. This brings me to the Firefox Monitor page listing the breaches associated with this email. I also get an email listing these breaches.
4. I go to the main page of the Firefox Monitor and notice that the new email is gone.
5. If I try to add it again, it sends a new confirmation email.

I tried this three times in a row (with the same email) and got the same result — disappearing email — with the exception that the breach list email was sent only once on the first try.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
