### ISSUE TITLE
Can't login to Firefox Monitor after adding 30+ addresses

### ISSUE THREAD

**Issue by Flux3PO** [mozilla/blurts-server#1335]
Steps to reproduce:

Login to Firefox Monitor with my Firefox Sync account website

Actual results:

Error Message stating that I need to login to access this site

Expected results:

Successful login to Firefox Monitor

![Screenshot_20191103_102107_org mozilla firefox](https://user-images.githubusercontent.com/11157007/68083517-a82ac400-fe29-11e9-8c64-7c6690390efb.jpg)

**Comment by lesleyjanenorton** [comment]
@Flux3PO thanks for filing and sorry you're experiencing this. One question: Were these 30+ emails added recently?

**Comment by Flux3PO** [comment]
Hi @lesleyjanenorton, no this was a while ago.. I was hoping that this got fixed itself, but it wasn't.

**Comment by groovecoder** [comment]
Hi @Flux3PO. I'm afraid you're hitting https://github.com/mozilla/blurts-server/issues/1084. I squashed the session data size down so that ~15 email addresses should fit into a cookie size. I'll have to think what kind of update/fix we can make to do this many email addresses.

**Comment by pdehaan** [comment]
@Flux3PO Our of curiosity, how many email addresses were you planning on adding? 40+? 50+?

**Comment by Flux3PO** [comment]
Thanks @groovecoder for letting me know.

Well I'm a bit surprised by this limit. I know it's not common, but I got a lot of alias addresses I wanted to add.... when I say a lot I mean 350+ @pdehaan . 
I create one alias per service... to protect me from spam and to easily switch compromised addresses. Again I know this is not common but I hope you find a workaround for this. I'm monitoring the other ticket and will close this here.
As said, thanks !

**Comment by Flux3PO** [comment]
Well, I can say, the below Bugfix fixed this. Thanks for everyone who was involved.

https://bugzilla.mozilla.org/show_bug.cgi?id=1656539

I now found out, that I had 53 Email Aliasses added :)

**Comment by Flux3PO** [comment]
Sadly, I am still blocked from adding more Email addresses. There still seems to be a hard limit :(

**Comment by pdehaan** [comment]
@Flux3PO Correct, I believe there is a hard limit specified in https://github.com/mozilla/blurts-server/pull/1780#discussion_r482092503.
