### ISSUE TITLE
New icon for "IP Address" within data types

### ISSUE THREAD

**Issue by changecourse** [mozilla/blurts-server#1337]
Our current icon is not particularly clear as an iconographic representation of IP Addresses. 

This is a placeholder to replace this icon:

<img width="189" alt="Screen Shot 2019-11-04 at 10 46 01 AM" src="https://user-images.githubusercontent.com/6164801/68144190-56993c80-fef0-11e9-95b6-cbdf80fb1943.png">

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
