### ISSUE TITLE
Mark breach as resolved per email address

### ISSUE THREAD

**Issue by tgburgin** [mozilla/blurts-server#1344]
My email address is associated with 10 breaches. If I've already changed that password, I don't really care about the breach any more as it's no longer a problem (assuming I've changed the password to something secure and not the same as before). I'd like the ability to then mark that breach as resolved so I don't have to check all the breaches each time.

**Comment by changecourse** [comment]
Hi @tgburgin, this work is already being accounted for in #1224 

Feel free to track it there! Closing as duplicate.
