### ISSUE TITLE
Add GA event ping when user adds or removes an email address

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1345]
Let's add a GA event pings when users add or remove email addresses, so we can report on that.

**Comment by lesleyjanenorton** [comment]
Subsequent email adds are already being tracked:
<img width="1413" alt="Screen Shot 2019-11-12 at 3 23 39 PM" src="https://user-images.githubusercontent.com/22355127/68712050-8388c780-0560-11ea-8d84-b0a63157ede2.png">
