### ISSUE TITLE
Send all breach alerts to X" set but got email on secondary email anyway

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#1348]
_**This issue was originally filed on [BMO](https://bugzilla.mozilla.org/show_bug.cgi?id=1591068). The STR below have not been verified.**_

---

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

Steps to reproduce:

In Firefox Monitor preferences, I set "Send all breach alerts to X" to my primary email address. I then added a secondary email address, and verified the secondary email

Actual results:

I received a breach alert on the secondary email.

Expected results:

Should have received the breach alert on the primary email, cause that is what I configured in preferences!

**Comment by groovecoder** [comment]
I was ~able to reproduce this bug:

1. Go to http://localhost:6060/user/preferences
2. Allow session to time out
3. Select "Send all breach alerts to X"
4. The request silently fails 😢 so the user has no indication that the breach alerts are still being sent to the breached address.

@lesleyjanenorton do we have UI to display back-end errors during the dashboard/preferences operations?

I found another bug related to sending breach alerts to primary addresses ...

1. Set all breach alerts to send to primary@address.com
2. Trigger a breach for secondary@address.com
3. Receive breach alert email at primary@address.com

Expected results:
Headline should say "secondary@address.com appeared in a new data breach"

Actual results:
Headline says "primary@address.com appeared in a new data breach"

I've sent [a PR with a fix](https://github.com/mozilla/blurts-server/pull/1350), AND with a new script for sending test breach alerts! No more `curl` commands!

**Comment by tomac4t** [comment]
Reopen? Luke's PR fix the another issue he found, but not the origin bug. I still have a same experience with [Bug 1591068](https://bugzilla.mozilla.org/show_bug.cgi?id=1591068).
