### ISSUE TITLE
Complete Dockerflow setup for stage & prod deployment pipelines

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#135]
* [x] Security Checklist (https://github.com/mozilla/blurts-server/issues/55)
* [x] Fix [Circle CI deployment](https://circleci.com/gh/mozilla/blurts-server/20?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) to hub.docker.com
* [x] (Ops) Set up Postgres service for the app
* [x] Set all [required environment](https://github.com/mozilla/blurts-server/blob/master/app-constants.js) variables with Ops
  * Note: We can use empty values for `SMTP_*` and `OAUTH_*` vars for the shield study
* ~[ ] Add (cron?) job to run `node run scripts/load-breaches.js` every day~

**Comment by Micheletto** [comment]
I've added the relevant dockerhub environment variables to the circleci configuration.  Please test.

**Comment by groovecoder** [comment]
It still says `unauthorized: authentication required` ?

**Comment by groovecoder** [comment]
https://circleci.com/gh/mozilla/blurts-server/29

**Comment by Micheletto** [comment]
> It still says unauthorized: authentication required ?

Fixed this by correcting the permissions on Dockerhub.

**Comment by pdehaan** [comment]
@Micheletto What's the status on the stage env?
I spotted https://github.com/mozilla/blurts-addon/issues/6 ("Change links to server to monitor.firefox.com"), so I was _assuming_ the stage URL would be something like: https://monitor.stage.mozaws.net/, but that's just me guessin'.

**Comment by groovecoder** [comment]
I believe this is done now? We have stage and the prod site up now.

**Comment by pdehaan** [comment]
I think the related checklist bug https://github.com/mozilla/blurts-server/issues/55 is still open.

Plus I think we still need to resolve the "Add (cron?) job to run node run scripts/load-breaches.js every day" list item (although I'm fine w/ a separate bug for that if we don't already have one).

**Comment by groovecoder** [comment]
Done.
