### ISSUE TITLE
Invalid session error is displayed if the user opens the website in two different tabs

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#1358]
[Affected versions]:
* Firefox 70.0.1

[Affected Platforms]:
* Windows 10 x64
* Windows 7 x64
* macOS 10.13
* Ubuntu 18.04 x64

[Steps to reproduce]:
1. Access https://mail.google.com/ with Firefox 70.0.1 on a clean profile.
2. Login with the following credentials:
     username: dennisronny4@gmail.com
     password: bugattiveyron19
3. Click on the “An update from Firefox Monitor” email subject.
4. Click on the "Create Account" button.
5. Click on "Sign in" button and enter the the password: bugattiveyron
6. Close all the tabs expect for gmail tab.
7. Right click on the "Create Account" button and open the link in two separate tabs.
8. Click on the "Sign in" button on each two tabs that were opened above.

[Expected result]:
* There is no error displayed on the page, or, if the user is not allowed to use the website in two different tabs on the same session, a more detailed message would be helpful.

[Actual result]:
 * An "Invalid session" error is displayed.

[Additional notes]:
* Please observe the attached screencast:

![fsf](https://user-images.githubusercontent.com/43886441/68870146-15303a80-0703-11ea-9cad-762b3e99566c.gif)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
