### ISSUE TITLE
Update deps (Nov 2019 edition)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1370]
Looks like CI is failing due to an old **handlebars** vuln.

```
> blurts-server@0.0.1 lint:audit /home/travis/build/mozilla/blurts-server
> npm-audit-ci-wrapper -t 'high'
There are vulnerable dependencies which exceed the selected threshold and scope:
                        handlebars(4.3.0               ): https://www.npmjs.com/advisories/1316              (high >= high)
```

Per https://www.npmjs.com/advisories/1316,

> Remediation: Upgrade to version 4.5.2 or later

Currently we're using 4.3.0 via **express-handlebars** and **jest**.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
