### ISSUE TITLE
The user is redirected to different pages when clicking on the Unsubscribe button 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#1372]
[Affected versions]:
* Firefox 70.0.1

[Affected Platforms]:
* Windows 10 x64
* Windows 7 x64
* macOS 10.13
* Ubuntu 18.04 x64

[Steps to reproduce]:
1. Access https://mail.google.com/ with Firefox 70.0.1 on a clean profile.
2. Login with the following credentials:
     username: dennisronny4@gmail.com
     password: bugattiveyron19
3. Click on the “An update from Firefox Monitor” email subject.
4. Click on the "Unsubscribe" button.
5. Login with the following credentials:
     username: dennisronny4@gmail.com
     password: bugattiveyron
6. Sign out from the Monitor website.
7. Click on the “Unsubscribe” button again from the gmail account.

[Expected result]:
* The user is redirected to the same pages on Step 5 and 7 https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/user/preferences

[Actual result]:
 * Step 5, the user is redirected to https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/user/dashboard
* Step 7, the user is redirected to https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/user/preferences

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
