### ISSUE TITLE
Bonus browser redirect when navigating to HIBP (www.)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1373]
Per #1371, I noticed I was getting a 403 when scraping `https://www.haveibeenpwned.com` (and it redirects to lose the `www.` subdomain) when I visit directly.

```
[403] https://www.haveibeenpwned.com/
```

Not sure if it's worth it to "fix" the URL in our HBS views and save a browser redirect.

```
git grep -Eno "https://.*\.haveibeenpwned\.com"

.env-dist:49:https://stage.haveibeenpwned.com
.env-dist:53:https://api.haveibeenpwned.com
views/partials/email_partials/email_disclaimers.hbs:10:https://www.haveibeenpwned.com
views/partials/hibp-attribution.hbs:2:https://www.haveibeenpwned.com
```

**Comment by EMMLynch** [comment]
@pdehaan , is this still an issue? For context, I'm reviewing old tickets now to see what can be closed.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
