### ISSUE TITLE
The FM cards are not generated inside the about:protections page

### ISSUE THREAD

**Issue by asoncutean** [mozilla/blurts-server#1374]
[Affected versions]: 
- 71.0b10
- 72.0a1 (2019-11-18)

[Affected platforms]:
- Windows 10 x64
- Windows 7 x64
- macOS 10.15
- Ubuntu 18.04 x64

[Steps to reproduce]:
[Preconditions]:
 -  The user is sign in to FxA using a compromised or an uncompromised acccount. compromised account: username: login-manager-monitor@mailinator.com password: loginmanagermonitor
- The user is sign in to https://monitor.firefox.com/ with the same account.

1. Access "about:protections" in a new tab
2. Observe if Firefox Monitor cards are displayed below “Look out for data breaches” section

[Expected result]:
- Firefox Monitor cards are displayed inside the about:protections page

[Actual result]:
- No cards are displayed on the about:protections page

[Regression range]: 
- Not sure what is going on here exactly, if something was implemented between Beta 9 and Beta 10. Right now, I can reproduce this issue on Fx 71.0b9 also, but this test was ran on Beta 9 before the Beta 10 was release and the cards were displayed without any issue then. 

[Additional notes]:
- Note that https://monitor-v2.herokuapp.com/  shows no cards either inside the about:protections page

**Comment by groovecoder** [comment]
Can you send a screenshot too please?
