### ISSUE TITLE
Implement real db query for /?breach=<domain.com>

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#138]
STR:

1. Go to https://fx-breach-alerts.herokuapp.com/?breach=adobe.com

Expected results:

Page should show the breach data for adobe.com

Actual results:

Page shows the breach data for AllMusic.com - our test breach.

**Comment by pdehaan** [comment]
I'm confused... https://fx-breach-alerts.herokuapp.com/?breach=adobe.com only seems to show the homepage with no mention of Adobe anywhere... Am I missing something?
