### ISSUE TITLE
Unsubscribe Improvements

### ISSUE THREAD

**Issue by changecourse** [mozilla/blurts-server#1387]
_Based on some feedback in sync fest and via RFeeley:_
If someone clicks unsubscribe from one of our emails, we'd like to make the process more streamlined. 

Ideally, we'd just automatically unsubscribe them and open a page with the confirmation, but if that presents issues, then at the very least I'd want to give a user a fast track authentication from the email (bypassing all or some of the FxA authentication flow)

Looking to @groovecoder and @lesleyjanenorton to help provide some potential options here :)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
