### ISSUE TITLE
Clean up usage of `req.app.locals` to replace with `AppConstants`

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1390]
_Originally posted by @groovecoder in https://github.com/mozilla/blurts-server/pull/1359_

> Can you file a follow-up issue to clean up our usage of `req.app.locals` to replace with `AppConstants` wherever we can?

Re: @pdehaan's brilliant https://github.com/mozilla/blurts-server/pull/1359#discussion_r346444248,

Interesting change... Here's a list of all the other unique instances where we use a `req.app.locals.<something>`:

```sh
git grep -Eho "req\.app\.locals\.\w*" | sort | uniq

req.app.locals.AVAILABLE_LANGUAGES
req.app.locals.FLUENT_BUNDLES
req.app.locals.SERVER_URL
req.app.locals.breaches
req.app.locals.mostRecentBreachDateTime
```

Looks like we have another `req.app.locals.SERVER_URL` instance in:

```
scan-results.js:48: req.app.locals.SERVER_URL
```

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
