### ISSUE TITLE
Update empty signup_language values with FxA profile locale value during FxA sign-ins

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1391]
I think the TL;DR version is that early in Monitor's lifecycle, we weren't capturing user's locales. Now we're sending them emails in English, even though their locale is 99.5% translated (ie: es-MX and es-ES). User's also have no way of seeing/updating their preferred locales, so once we have it (or not) you're in that bucket for life (or stuck with fallback en-US).

It would be nice to be able to retroactively determine missing user locales, either via FxA or just the next time a logged in user visits the site.

Step 1 would be to run a DB query and determine how many people were super early Monitor adopters and signed up but we weren't capturing locales yet.

---

Via [Slack](https://mozilla.slack.com/archives/C93K0MBM5/p1574433398281900)

Luke Crouch 8:07 AM
@pdehaan oh, that’s a good idea. we don’t [backfill locales] right now, but we could try to use their fxa profile data locale …
@flodolo - is it pretty safe to assume that FxA’s locale value would be the “right” locale to use for Monitor too?

Francesco Lodolo 8:08 AM
Sorry, I have zero info on FxA. It might be

Luke Crouch 8:10 AM
@pdehaan can you file an issue for that? To update empty signup_language values with FxA profile locale value during FxA sign-ins.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
