### ISSUE TITLE
Update Breach Alert Email to include "resolve this breach"

### ISSUE THREAD

**Issue by changecourse** [mozilla/blurts-server#1395]
Pending our new epic for resolving breaches, we need to update the breach alert email to appropriately route folks to the appropriate page (breach detail instead of dashboard) in an authenticated state. 

Design and approach TBD

Tied to #1224

**Comment by changecourse** [comment]
<img width="959" alt="Screen Shot 2019-12-09 at 10 24 12 AM" src="https://user-images.githubusercontent.com/6164801/70457829-16d4f000-1a6e-11ea-88e2-2c582e404591.png">

Changes Include:
- Changing the link copy within the card to "Resolve this breach" to match the new breach cards within the user dashboard
- Changing the primary CTA to "Go to Dashboard" 

Both the link and the button should check if a user is logged in (we need to adjust via #1342) and pending a successful authentication, either route the user to an authenticated breach detail page (for Resolve this breach) or the authenticated dashboard (for Go to Dashboard)

@betsymi please review and let me know if you'd like to adjust anything.

**Comment by lesleyjanenorton** [comment]
Do we want to do this on the "report" email as well? Or just the breach alert?

**Comment by changecourse** [comment]
Mmmmm, good question. My thought would be on both. @betsymi what do you think?

**Comment by betsymi** [comment]
Yes, sure.
