### ISSUE TITLE
Make it clear in security-tips that passwords are cracked automatically

### ISSUE THREAD

**Issue by devurandom** [mozilla/blurts-server#1400]
I believe the current security-tips page does not make it clear enough that passwords are not cracked by some evil person sitting in their dark room, who thinks hard and then tries to type in someone's password. It should be emphasized that this is done by automated programs within fractions of seconds for thousands of people's passwords using dictionaries and clever guesses that work for most people's passwords.

**Comment by devurandom** [comment]
Just to make it clear: #1399 does not close this issue.

**Comment by groovecoder** [comment]
Closing these individual content issues in favor of the consolidated https://github.com/mozilla/blurts-server/issues/1407 issue. We will look at the details of these issues when we do our next content updates.
