### ISSUE TITLE
Promote auto generated passwords in security-tips

### ISSUE THREAD

**Issue by devurandom** [mozilla/blurts-server#1401]
In the security-tips, password managers are being promoted, which is good. What appears to be missing or not emphasized enough is that, if you already use a password manager, you should use it to auto generate truly random passwords. I do not really see a benefit in "combin[ing] two or more unrelated words" and then storing them in a password manager, if that very tool already has a function built in to create a much stronger password.

You can basically divide the page into two parts: "Use a password manager! If you do, then ..." and "If you cannot use a password manager, then ..."

This somewhat relates to #1060.

**Comment by groovecoder** [comment]
Closing these individual content issues in favor of the consolidated https://github.com/mozilla/blurts-server/issues/1407 issue. We will look at the details of these issues when we do our next content updates.
