### ISSUE TITLE
Mention FIDO2 in security-tips

### ISSUE THREAD

**Issue by devurandom** [mozilla/blurts-server#1402]
FIDO2 appears to be missing in the security-tips.

It should probably be described separately from tips for password managers and tips when a password manager cannot be used. (See also #1401.)

**Comment by groovecoder** [comment]
Closing these individual content issues in favor of the consolidated https://github.com/mozilla/blurts-server/issues/1407 issue. We will look at the details of these issues when we do our next content updates.
