### ISSUE TITLE
Add UI for resolving breaches to /breach-details

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#1403]
Add UI for resolving breaches to `/breach-details` pages. Signed in users visiting a `/breach-details` page for a breach that has exposed their info should see this UI and be able to "resolve" the breach for each of their affected emails.

**Comment by tdechangy** [comment]
+1 (vote)
similar to : 
https://github.com/mozilla/blurts-server/issues/1224
https://github.com/mozilla/blurts-server/issues/1405
