### ISSUE TITLE
Modify and expand recommendation logic `/breach-details` pages.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#1404]
Expand/modify existing logic on `/breach-details` pages to show recommendations based on a breach's exposed data classes instead of the breach "type". Update `/breach-details` UI to reflect changes.

Recommendations: https://docs.google.com/spreadsheets/d/1MlRHSs5PVEO0baDduWLTBJWWSQuwOCVZewhPuDN3ZKE/edit#gid=0

New / revised copy: https://docs.google.com/document/d/1DHQytRPHF8xPa-VE_PrCqJTIDIGwQ6TiMRui09lgdNs/edit#heading=h.yt4u26dg3ru9

**Comment by pdehaan** [comment]
I love this idea. Do we have any rules yet, or a list of data classes we're targeting?
According to <kbd>npx pdehaan/blurts-data-classes-stats</kbd>, we currently have 120 unique data classes &mdash; so this might be a bit tricky to verify that the UI looks good for each distinct breach (since data classes are so random).

**Comment by lesleyjanenorton** [comment]
I'm fishing around the proposed rules and working copy and will share the with you when I find them but IIRC, the proposed rules are along these lines:

- Provide 4 recommendations for each breach, regardless of total number of exposed data classes.
- Provide specific recommendations for exposed "priority" data classes. Current list is [here](https://github.com/mozilla/blurts-server/blob/d3f8b89e70a3ce5e9ee5cbabd22587937345fee6/template-helpers/breach-detail.js#L45)
- If there are greater than 4 priority data classes exposed, pick the four with the highest weight.
- If there are fewer than 4 priority data classes exposed, back-fill with more generic recommendations.
- When the exposed data classes are less actionable, and zero priority data classes have been exposed, show 4 general digital hygiene recommendations.

**Comment by lesleyjanenorton** [comment]
@pdehaan new recommendations here: https://docs.google.com/spreadsheets/d/1MlRHSs5PVEO0baDduWLTBJWWSQuwOCVZewhPuDN3ZKE/edit#gid=0

**Comment by pdehaan** [comment]
Future notes for Future @pdehaan:
Here's a list of the priority data classes and the top breached site with said data class:

```js
// npm i pdehaan/hibp-chain-api -S
const HIBP = require("hibp-chain-api");

const priorityDataClasses = {
  "government-issued-ids" : {
    weight: 101,
    pathToGlyph: "svg/glyphs/social-security-numbers",
  },
  "social-security-numbers" : {
    weight: 101,
    pathToGlyph: "svg/glyphs/social-security-numbers",
  },
  "passwords": {
    weight: 100,
    pathToGlyph: "svg/glyphs/passwords",
    actions: "", // future functionality?
  },
  "bank-account-numbers": {
    weight: 99,
    pathToGlyph: "svg/glyphs/bank-account-numbers",
  },
  "credit-cards": {
    weight: 98,
    pathToGlyph: "svg/glyphs/credit-cards",
  },
  "credit-card-cvv": {
    weight: 97,
    pathToGlyph: "svg/glyphs/credit-card-cvvs",
  },
  "partial-credit-card-data": {
    weight: 96,
    pathToGlyph: "svg/glyphs/partial-credit-card-data",
  },
  "ip-addresses": {
    weight: 95,
    pathToGlyph: "svg/glyphs/ip-addresses",
  },
  "historical-passwords": {
    weight: 94,
    pathToGlyph: "svg/glyphs/historical-passwords",
  },
  "security-questions-and-answers": {
    weight: 93,
    pathToGlyph: "svg/glyphs/security-questions-and-answers",
  },
  "phone-numbers": {
    weight: 92,
    pathToGlyph: "svg/glyphs/phone-numbers",
  },
  "email-addresses": {
    weight: 91,
    pathToGlyph: "svg/glyphs/email-addresses",
  },
  "dates-of-birth": {
    weight: 90,
    pathToGlyph: "svg/glyphs/dates-of-birth",
  },
  "pins": {
    weight: 89,
    pathToGlyph: "svg/glyphs/pins",
  },
  "phsyical-addresses": {
    weight: 88,
    pathToGlyph: "svg/glyphs/physical-addresses",
  },
};

main();

async function main() {
  for (const [key, value] of Object.entries(priorityDataClasses)) {
    const breaches = (await new HIBP().getBreaches())
      .hasDataClass(key)
      .sort("-PwnCount")
      .pluck(["Name"])
      .breaches(1)
      .map(breach => breach.Name);
    console.log(`${key} => ${JSON.stringify(breaches)}`);
  }
}
```

### OUTPUT

```
government-issued-ids => ["JobStreet"]
social-security-numbers => ["GoldSilver"]
passwords => ["Collection1"]
bank-account-numbers => ["GoldSilver"]
credit-cards => ["Stratfor"]
credit-card-cvv => ["BlueSnapRegpack"]
partial-credit-card-data => ["EatStreet"]
ip-addresses => ["VerificationsIO"]
historical-passwords => ["CannabisForum"]
security-questions-and-answers => ["AshleyMadison"]
phone-numbers => ["VerificationsIO"]
email-addresses => ["Collection1"]
dates-of-birth => ["VerificationsIO"]
pins => ["Yatra"]
phsyical-addresses => []
```

(**NOTE:** the lack of breach results for "phsyical-addresses" is due to #1408 typo.)

**Comment by groovecoder** [comment]
Uplifting thread from https://github.com/mozilla/blurts-server/pull/1434/files#r355700316 to here ...

With modified and expanded recommendation logic including many data classes that are part of data aggregators, can we consider permanently restoring breach emails for all data aggregators?
