### ISSUE TITLE
Bento menu has a vertical scroll bar inside

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/blurts-server#1416]
[Affected versions]:
* Firefox 70.0.1

[Affected Platforms]:
* Windows 10 x64
* MacOS 10.14
* Ubuntu 18.04 x64

[Steps to reproduce]:

1. Navigate to: https://monitor-v2.herokuapp.com/
2. Click on the bento box
3. Zoom in/Zoom out using the mouse wheel 

[Expected result]:
* Bento menu is correctly displayed

[Actual result]:
* Bento menu has scroll bars inside

![bento](https://user-images.githubusercontent.com/15101135/69733452-051e4f00-1136-11ea-9f8c-df34b59e7462.png)

**Comment by Shivansh2407** [comment]
Can I fix this issue?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
