### ISSUE TITLE
Text should not be underlined on mouse hover 

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1417]
[Affected versions]:
 - Firefox 71

[Affected Platforms]:
 - Windows 10 x64
 - MacOS 10.14
 - Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to: https://monitor-v2.herokuapp.com/
2. In the upper side of the page, click on "Security Tips" 
3. Place your mouse over the "Home" option 
4. Slightly move your mouse from the Home option to the bottom side of the page

[Expected result]:
 - On mouse hover, the option should not be underlined, should only change color (hover effect). The options from the header should get underlined only when that particular option is clicked.

[Actual result]:
 - In step 2, Security Tips is underlined, since it's the focused option. But when the "Home" option is mouse hovered it becomes underlined taking the focus from the actually selected option (this could get confusing since at this point you don't know which option is selected). In step 4, the selection animation jumps back on the "Security Tips" option.

![HoverEffect](https://user-images.githubusercontent.com/56026823/69734048-0308c000-1137-11ea-8069-f2dca7b890b1.gif)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
