### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1418]
Looking at the coveralls results in recent PRs, it looks like our code coverage is roughly 46%. Not sure how difficult it would be to backfill some tests and get the code coverage numbers up around 75-90%, or if that's a full Q1 worth of work.

> **RUN DETAILS**
> 213 of 524 branches covered (40.65%)
> Branch coverage included in aggregate %.
> 0 of 4 new or added lines in 1 file covered. (0.0%)
> 783 of 1637 relevant lines covered (47.83%)
> 3.7 hits per line

But it'd be nice if we could increase the coverage numbers so we have more confidence in adding new code or refactoring existing code while adding new features/functionality.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
