### ISSUE TITLE
The highlight of the focused "Remove Firefox Monitor" button is not visible

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1421]
[Affected versions]:
- Firefox 71

[Affected Platforms]:
- Windows 10 x64
- MacOS 10.14
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to: https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account
3. Click on your profile picture and select "Preferences"
4. Use the "Tab" key to reach the "Remove Firefox Monitor" button. 

[Expected result]:
"Remove Firefox Monitor" button is easily reached and the button is properly highlighted.

[Actual result]:
The highlight of the "Remove Firefox Monitor" button is not visible when it's in focus.

**Comment by sbadau** [comment]
The highlight not being visible when an option or button is focused via the keyboard is also reproducing on the Home section for: 
Latest Breach Added
Understand how hackers work
Hoe to create strong passwords
Read more Security Tips.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
