### ISSUE TITLE
Add Support for Email Address Patterns

### ISSUE THREAD

**Issue by naydichev** [mozilla/blurts-server#1436]
Hello!

Being a _savvy_ internet user, I try not to use my exact same email address. There are three email schemes that I use, which I would like to be able to monitor by adding patterns.

1. Gmail ignores dots, so all of these effectively resolve to the same inbox:
   a. `foo@gmail.com` 
   b. `f.o.o@gmail.com`
   c. `f.o..o@gmail.com`
2. Gmail (and other email providers) support the `+` in the email address, ignoring everything after the `+` when finding a relevant user. The following also effectively resolve to the same inbox:
  a. `foo@gmail.com`
  b. `foo+bar@gmail.com`
  c. `f.o.o+bar@gmail.com`
  d. `foo+bar+baz@gmail.com`
3. I use a catchall email address subdomain. The following are effectively resolve to the same inbox:
  a. `foo@sub.domain.com`
  b. `bar@sub.domain.com`
  c. `baz@sub.domain.com`

I'd really like to know if any of my email addresses are involved in any breaches, but it's not feasible for me to add all the different variations. Would it be possible to enable an email pattern? Given the following regexes, it should be possible to generate a random email address matching the pattern for validation:

1. `((\w)+\.*)@{domain matching}`
2. `((\w)+\.*)\+(\w)*@{domain matching}`
3. `(\w)+@sub\.{domain matching}`

Assuming `{domain matching}` uses some existing domain verification rules.

Thanks.

**Comment by pdehaan** [comment]
Ref: #1137

**Comment by groovecoder** [comment]
Since scans and subscriptions are based on hash range queries, we can't predictably and reliably scan or subscribe `+` aliases or other address schemes like various `.` characters. Closing this issue unless/until our breach data endpoint supports such a feature.
