### ISSUE TITLE
Add a doc w/ dates of when email alerts are sent out (starting with 2019-11-25)

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/blurts-server#1438]
The instrumentation that was added to measure return visits to the Monitor site via breach email has had a noticeable impact on the FxA MAU timeseries, which is an important KPI. Going forward, starting with the first instrumented breach alert (2019-11-25), could we add a simple  document to the repo that is updated (preferably) before each new email breach that is sent? This would allow @jmccrosky to handle these dates as as regressor in his forecasting model, potentially allowing it produce more accurate MAU forecasts.  I think this could be a simple as a one-date-per-line doc, dates formatted YYYY-MM-DD (the dates will be pulled into the model automatically).

**Comment by jklukas** [comment]
One-date per line, or CSV if we want to include a brief description of the alert, seems like a reasonable format. If such a file is committed to this repository and it's public, we can pull it from GitHub via an http request in the forecasting code.

**Comment by jmccrosky** [comment]
Cool.  Will mention this on that issue.

**Comment by groovecoder** [comment]
Do we need historical data for this? Or is it okay to start recording this for future metrics?

Does amplitude have an API we could use to send an annotation? We could call that when we process a new breach.

**Comment by groovecoder** [comment]
HIBP also serves a JSON endpoint of the breaches, which includes the `AddedDate` for each. We could use that as the data source here?

https://haveibeenpwned.com/api/v2/breaches

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
