### ISSUE TITLE
robots.txt is not valid

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#145]
via #141 report:

> **Lighthouse was unable to download your robots.txt file**
> If your robots.txt file is malformed, crawlers may not be able to understand how you want your website to be crawled or indexed.

Not sure if there is any explicit endpoints we may not want spidered by engines... 🕷

**Comment by pdehaan** [comment]
```sh
$ git rev-parse --short HEAD # cdda1a9
$ git grep "router\."

routes/dockerflow.js:router.get("/__version__", (req, res) => {
routes/dockerflow.js:router.get("/__heartbeat__", (req, res) => {
routes/dockerflow.js:router.get("/__lbheartbeat__", (req, res) => {
routes/home.js:router.get("/", handleIndexRoute);
routes/home.js:router.get("/monitor", handleIndexRoute);
routes/oauth.js:router.get("/init", jsonParser, (req, res) => {
routes/oauth.js:router.get("/confirmed", jsonParser, async (req, res) => {
routes/scan.js:router.post("/", urlEncodedParser, async (req, res) => {
routes/user.js:router.post("/add", urlEncodedParser, async (req, res) => {
routes/user.js:router.get("/verify", jsonParser, async (req, res) => {
routes/user.js:router.post("/remove", jsonParser, async (req, res) => {
```

Just a guess, but I'm wondering if we should try and set a disallow/noindex on the following:

```
/__version__
/__heartbeat__
/__lbheartbeat__
/init
/confirmed
/add
/verify
/remove
```

**Comment by gaurav9825** [comment]
Hey, @pdehaan I would like to work on this issue!

**Comment by groovecoder** [comment]
Hi @gaurav9825. This may be a tricky one to try to fix as a first issue. @lesleyjanenorton and I were talking about needing a `robots.txt` the other day, but it's not necessarily a simple fix.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
