### ISSUE TITLE
Implement UITour or set up a WebChannel so Monitor can open about:logins.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#1450]
The recommendation `Update other logins using the same password` should be followed by a CTA that says `View logins in Firefox` and opens `about:logins` if the user's browser is Firefox. To open `about:logins` we need to add Monitor to the list of websites allowed to do this, and then set up a WebChannel or use UITour to open `about:logins` in a new tab.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
