### ISSUE TITLE
Redesign "Security Tips" to a scalable format

### ISSUE THREAD

**Issue by cherrypsf** [mozilla/blurts-server#1451]
There is promising content generated on Moz.org that could co-existing on Monitor's Security Tips page to make it easier for our Monitor users to learn more about or educate themselves around privacy without anyone having to reinvent the wheel. 

We could leverage a platform like WordPress or change the design to make it easier for us to carry over existing Mozilla-created content by embedding or sharing articles/blog posts that make sense. Also understanding what kind of content does well on Monitor can be supporting data points to help guide strategy.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
