### ISSUE TITLE
Add gn, nb-NO to production locales

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#1460]
We should have two new locales basically complete:
- gn (96.15%)
- nb-NO (100.0%)

But when I visit the [dev server](https://fx-breach-alerts.herokuapp.com/), I get English. Did something break recently?

**Comment by flodolo** [comment]
Additional note: I don't have a full install locally (missing DB), but both languages work fine. I guess the dev server is not updating, or not tracking master.

**Comment by havarh** [comment]
nn-NO is also missing from dev server, even though it's available on the production server

**Comment by havarh** [comment]
Maybe this file is to blame?
https://fx-breach-alerts.herokuapp.com/__version__
The file lists all available languages, but no nn-NO, nb-NO or gn.

**Comment by pdehaan** [comment]
@lesleyjanenorton @groovecoder Interesting... I thought that the Heroku server used `SUPPORTED_LOCALES=*` on dev and all locales were supported, but maybe I'm misunderstanding something (or looking at the wrong server).

Sample .env-dist
https://github.com/mozilla/blurts-server/blob/f4fb689a84abd67893333340236f8ba6120dac53/.env-dist#L67-L68

**Comment by groovecoder** [comment]
Oh, hmm ... the dev server wasn't running with `SUPPORTED_LOCALES="*"`

I updated the dev server config and changed my browser to accept Guarani [gn] and Norwegian [nb] and saw the site translated:

![image](https://user-images.githubusercontent.com/71928/71912668-8c9aad00-313b-11ea-9075-c02cfd1f8bbb.png)

![image](https://user-images.githubusercontent.com/71928/71912691-9c19f600-313b-11ea-919c-4374bffb8299.png)

I'm going to leave this open and put it into our board to remind me to update the stage & prod environments' `SUPPORTED_LOCALES` during our next deploy.

**Comment by flodolo** [comment]
> I'm going to leave this open and put it into our board to remind me to update the stage & prod environments' `SUPPORTED_LOCALES` during our next deploy.

Amending the subject then.

**Comment by flodolo** [comment]
I guess this is done.

**Comment by pdehaan** [comment]
:+1: Latest top-secret config file has the following value for `firefoxMonitorSupportedLocales`:

```yaml
firefoxMonitorSupportedLocales: "cak,cs,cy,da,de,el,en,en-CA,en-GB,es-AR,es-CL,es-ES,es-MX,fi,fr,fy-NL,gn,hu,kab,ia,id,it,ja,nb-NO,nl,nn-NO,pt-BR,pt-PT,ro,ru,sk,sl,sq,sv-SE,tr,uk,vi,zh-CN,zh-TW"
```
