### ISSUE TITLE
False negatives: Firefox Monitor found no known breaches (e-mail) when adding an address for which there are breaches

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/blurts-server#1461]
### Steps

1. https://monitor.firefox.com/user/dashboard
2. add (another) e-mail address

### Expected

3. an e-mail that tells the true number of breaches for the address

### Actual result

3. an e-mail that gives a false sense of security

#### E-mail view of things

![image](https://user-images.githubusercontent.com/192271/71760643-a9737e00-2eb8-11ea-9144-dc54f05fa338.png)

> **Firefox Monitor found no known breaches**

> … appeared in 0 known  data breaches
> 
> Firefox Monitor warns you about data breaches involving your personal info. So far, no breaches were found. We’ll send you an alert if your email address appears in a new breach. …

### A subsequent dashboard view of the two addresses that are reportedly breach-free

![image](https://user-images.githubusercontent.com/192271/71760674-19820400-2eb9-11ea-9660-44c121337c2c.png)

**Comment by groovecoder** [comment]
Hard to diagnose without the specific email addresses, but some things that have made differences in the past:

* Do you have any mixedCase characters in the addresses?
* Do you have any alias characters (`+` `.`) in the addresses?

**Comment by grahamperrin** [comment]
In both cases: 

`G.J.Pe…@…`

– and to reaffirm: Firefox Monitor _did_ find the breaches. The breaches were visible immediately when taking the dashboard view of things. 

Both notification e-mails were bugged; each notification stated "no known breaches".

**Comment by lesleyjanenorton** [comment]
I was able to reproduce this by changing up the casing in an email I know to be breached `lesleyjanenorton@***...` -> `LesleyJaneNorton@***...` and adding it via the form at the bottom of `/dashboard`. 

The breach results appeared correctly for both versions of the email address in the dashboard, but the version with some uppercase letters triggered an incorrect breach report email.

False negative breach report for email address with some uppercase letters:
<img width="352" alt="Screen Shot 2020-01-17 at 3 11 05 PM" src="https://user-images.githubusercontent.com/22355127/72646419-bc1b9780-393b-11ea-974a-d84a1b7fcd55.png">




**VS**
Accurate breach report for the same email address using all lowercase letters:
<img width="407" alt="Screen Shot 2020-01-17 at 3 15 37 PM" src="https://user-images.githubusercontent.com/22355127/72646677-4c59dc80-393c-11ea-87e8-8268424354be.png">


Just submitted #1488 to fix this.
