### ISSUE TITLE
How to report a breach?

### ISSUE THREAD

**Issue by JoelJ** [mozilla/blurts-server#1462]
Hello, I have discovered a breach to a niche website. All names, emails, and passwords. I would like to work with Mozilla to get this breach properly disclosed since you're a company I trust and I'm not entirely sure of a better route to report this. 

Thanks!

**Comment by groovecoder** [comment]
Our upstream breach data provider is Have I Been Pwned, so you should contact Troy Hunt about it to get it analyzed and potentially loaded to Monitor.

https://www.troyhunt.com/contact/
