### ISSUE TITLE
strengthen-pin-security.svg is 404ing

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1471]
https://monitor.firefox.com/breach-details/vtech

Failed to load resource: the server responded with a status of 404 (strengthen-pin-security.svg:1)

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/72199077-85012f80-33eb-11ea-81cd-799473079be9.png)

**Comment by Shivansh2407** [comment]
I would like to work on this issue.

**Comment by Shivansh2407** [comment]
.rec-dob must need to be added to the css styling . I am submitting a PR for the same .Please check and let me know.

**Comment by pdehaan** [comment]
@Shivansh2407 Thanks for the investigation. I have another theory about possibly just incorrect case in the icon name in https://github.com/mozilla/blurts-server/pull/1472#issuecomment-573362248.

❤️

**Comment by lesleyjanenorton** [comment]
Fixed in #1472
