### ISSUE TITLE
Additional breach detail data classes need,more,spacing

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1476]
While looking at the [GateHub](https://monitor.firefox.com/breach-details/GateHub) breach, I also noticed that the spacing between additional elements feels a bit tight. Not sure if it was always like that, or if there was a recent change.

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/71845632-95c54480-307d-11ea-9898-207e0f2b1d08.png)
&mdash; via https://monitor.firefox.com/breach-details/PDL

_Originally posted by @pdehaan in https://github.com/mozilla/blurts-server/issues/1465#issuecomment-571294973_

**Comment by pdehaan** [comment]
As close as I can figure, the issue is that the additional non-priority data classes are possibly being passed as an array named `lowerPriority` around L45:

https://github.com/mozilla/blurts-server/blob/5095da29cf8bb8a178d2642aef5dc690611498a4/views/partials/breach-detail-content-group.hbs#L39-L50

But when the .HBS template tries to render `{{ dataTypes.lowerPriority }}`, it doesn't account for adding spaces after commas.

I'm not well versed enough in l10n matters to know if we could just do a `.join(", ")` somewhere in the bowels of the code and if comma+space works in each locale, or if some locales prefer different list delimiters, etc.
But at any rate, the current output is kinda tight and non-visually-pleasing(tm).

**Comment by Shivansh2407** [comment]
Can I please work on this issue @lesleyjanenorton and @pdehaan ?

**Comment by pdehaan** [comment]
@Shivansh2407 looks like @lesleyjanenorton already expertly fixed this with the pending #1480 PR.

**Comment by Shivansh2407** [comment]
Ok Sir
