### ISSUE TITLE
Audit our usage of sha1() and .toLowerCase() when scanning emails.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#1489]
We occasionally run into issues (most recently, #1461) stemming from our usage of `sha1()` and `.toLowerCase()` causing false negative scan results when the scanned email address contains uppercase letters. Let's audit/standardize/demystify/betterify the `sha1()`/`.toLowerCase()` steps in all the places we scan emails so that we don't unintentionally confuse someone or give them a false sense of security by providing incorrect scan results in the future.

**Comment by Shivansh2407** [comment]
Can I help by fixing this issue?

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/blurts-server/pull/1488#pullrequestreview-344880808 (for more context on the current `sha1()` usage).

@Shivansh2407 Not sure this is a good contributor bug at the moment. I think we'll need one of the core devs to manually review each usage and see if we're `sha`ing correctly.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
