### ISSUE TITLE
Add good-first-bug GitHub label to qualifying issues

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#1491]
Re: https://github.com/mozilla/blurts-server/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Agood-first-issue

It might be nice to tag a few appropriate issues with "good-first-bug" labels so we can direct contributors to some good, quality issues.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
