### ISSUE TITLE
Consider adding alternate "Email Successfully Verified!" messaging for signed in users.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#1496]
Right now this is what users see when they verify a secondary email, even if they're signed in. 
<img width="957" alt="Screen Shot 2020-01-22 at 10 59 25 AM" src="https://user-images.githubusercontent.com/22355127/72916416-9a3d5e80-3d07-11ea-81ad-d9fd8ae76aea.png">

#1495 hides the `To see and manage all emails you've signed up for breach monitoring, sign in` message from signed in users but it might be nice to replace this with some alternate "next step"/"go to your dashboard" messaging.

**Comment by Shivansh2407** [comment]
Can I help in fixing this @lesleyjanenorton ?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
