### ISSUE TITLE
[breach-resolution] Can't mark a breach as resolved

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#1497]
When clicking the button, nothing happens and I get a `ReferenceError: ga is not defined`.

Tried disabling Tracking Protection but it didn't change.

**Comment by lesleyjanenorton** [comment]
Thanks for catching this - this should be fixed in https://github.com/mozilla/blurts-server/pull/1481/commits/41530089b628da35483e36173eca79a01341d5a5 and the update has been deployed to Heroku.

**Comment by flodolo** [comment]
As noted on Slack, now the console error is gone, but clicking the button/link to mark a data breach as resolved doesn't do anything (no errors at all). From a quick look at the code, it should do an XHR, but the DevTools-Network doesn't show any traffic when I click.

**Comment by lesleyjanenorton** [comment]
Closing as fixed.
