### ISSUE TITLE
API is not documented

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#15]
We should start an api.md file containing detailed documentation for API endpoints, usage, errors, request/response structures, etc.

**Comment by groovecoder** [comment]
We've dropped the "API" portion. HTTP endpoints are in the routes.

**Comment by pdehaan** [comment]
@groovecoder Does that mean we can nuke this not-very-useful [/api.md](https://github.com/mozilla/blurts-server/blob/master/api.md) file?

**Comment by groovecoder** [comment]
It does! PR welcome ... or I'll get to it when I have a chance.
