### ISSUE TITLE
Remove the 'AllMusic' test fixture breach?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#150]
Randomly spotted, but something feels weird to me...

- https://fx-breach-alerts.herokuapp.com/?breach=AllMusic has some details, and a logo.
- https://mozilla.invisionapp.com/share/KEIV66OTS23#/screens/297625875 lists a description (but is just a Photoshop mockup, so not 100% reliable as a data source -- but seems odd that the description looks so legit)
- https://haveibeenpwned.com/PwnedWebsites doesn't seem to any mention of "AllMusic" or "All Music", so I can't even find the breach on HIBP site to see what description they have (if any).

![firefox_monitor_-_allmusic](https://user-images.githubusercontent.com/557895/40991505-d4296d1c-68a8-11e8-9e1a-ba81e7669848.png)

**Comment by lesleyjanenorton** [comment]
I will investigate this. I thought the AllMusic Breach was an invented breach, created for test purposes only but it definitely doesn't need to be popping up at fx-breach-arlerts/herokuapp if that is the case.

**Comment by pdehaan** [comment]
I don't see it on https://github.com/mozilla/blurts-addon/blob/54b42fc67071b023a1af808a4a32d76293a302e0/src/breaches.json either.

Yeah, this feels sketchy. If it _is_ a dummy breach, we definitely do NOT want to use a real company name and logo, because that's wrong and rude (even if it is difficult to randomly find).

**Comment by pdehaan** [comment]
But I think you're right, https://github.com/mozilla/blurts-server/blob/da9a81d48a2696ce1c7c721f67a4380ee85632fb/scripts/load-breaches.js#L22-L28

I think we should definitely change the name/flag/logo and rename it something less legit sounding like "Firefox Monitor Test Breach", and make sure it doesn't appear on production.

**Comment by lesleyjanenorton** [comment]
We'll get rid of it!
