### ISSUE TITLE
[breach-resolution] Wrong spacing in bullet list for completely resolved breaches

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#1507]
Once I resolve all the breaches, a bullet list of suggestions shows up. If the translation is longer than one line, line height looks off

<img width="620" alt="Schermata 2020-01-26 alle 07 25 25" src="https://user-images.githubusercontent.com/3644868/73131592-1be60280-400e-11ea-956f-2ad5c574f744.png">

**Comment by lesleyjanenorton** [comment]
Closing - The green check marks are part of the image and are not actually bullets.

**Comment by flodolo** [comment]
> Closing - The green check marks are part of the image and are not actually bullets.

Uh, I completely misunderstood that.
