### ISSUE TITLE
The image is not displayed for the first resolved breach on a newly created profile.

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#1508]
Affected versions]:
-  Firefox 72.0.2

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/
2. Create a new Firefox Monitor account with a breached email. 
3.  Click on "Resolve this breach" link.
4. Click on the "Mark as Resolved" button.

[Expected result]:
- This image is displayed:
![2020-01-10_12h05_32](https://user-images.githubusercontent.com/42799381/73164895-7a3cdf00-40fb-11ea-9575-d8b2e960794e.png)

[Actual result]:
- This image is displayed:
![Screenshot from 2020-01-23 14-48-16](https://user-images.githubusercontent.com/42799381/73165017-b4a67c00-40fb-11ea-8c03-c4a4aafe671f.png)

[Regression]:
- N/A

[Additional Info]:
- This reproduces on Chrome, too. 
- It only happens on the first resolved breach on a newly created profile.

**Comment by LaurentiuApahideanSV** [comment]
The issue also occurs on Android under the same behavior and repro steps.
### Affected versions
Firefox Release 68.4.2, Beta 68.5b5
Chrome Chrome 79.0.3945.136
### Devices used
OnePlus 6t (Android 9)

**Comment by LaurentiuApahideanSV** [comment]
The issue also occurs on iOS under the same behavior and repro steps.
### Affected versions
Firefox for iOS 22 (17157)
Safari
### Devices used
iPhone XS MAX iOS 12.4

**Comment by obotisan** [comment]
We verified the fix on Windows 10 x64, macOS 10.15 and Ubuntu 18.04 x64. We can't reproduce the issue anymore.

**Comment by lesleyjanenorton** [comment]
Thank you @obotisan!
