### ISSUE TITLE
A scrollbar is needed in order to access all the buttons from the resolved breaches page when it's zoomed in

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#1510]
Affected versions]:
-  Firefox 72.0.2

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/ and zoom in at least until 150%. 
2. Log into a Firefox Monitor account with a breached email. 
3. Click on "Resolve this breach" link.
4. Click on the "Mark as Resolved" button.
5. Observe the scroll bar. 

[Expected result]:
- All the button are accessible.

[Actual result]:
- There "Return to breach details" link is not accessible. 

[Regression]:
- N/A

[Additional Info]:
- This reproduces on Chrome, too. 
- On Windows 10 you have to zoom in until 170% to see the issue reproducing. 
- Please look at the attached image:
![Screenshot from 2020-01-27 11-29-43](https://user-images.githubusercontent.com/42799381/73166051-bec97a00-40fd-11ea-80b6-1d97a498e5cd.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
