### ISSUE TITLE
[Enhancement] No progress bar shown - if the percent of the resolved breaches is smaller than 1%

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1511]
[Affected versions]: 

- Firefox 72.0.2

[Affected Platforms]:

- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:

1. Navigate to https://monitor-v2.herokuapp.com/ 
2. Log into a Firefox Monitor account that has multiple breaches (more than 100) and none of them resolved
3. Click on "Resolve this breach" link.
4. Click on the "Mark as Resolved" button.
5. Click on the "Go to Dashboard" button.
6. Observe the progress bar of the resolved breaches.

[Expected result]:

Even if the percent of the resolved breaches is smaller than 1%, the progress bar should show some progress. 

[Actual result]:

There is no shown progress and the percent of the resolver breaches is still 0%.

[Additional Info]:

This reproduces on Chrome, too.

Please look at the attached image:

![2020-01-27_13h54_51](https://user-images.githubusercontent.com/56026823/73173439-0952f280-410e-11ea-972f-b6d3790c4712.png)

**Comment by Shivansh2407** [comment]
Any work that can be done by me here ? I would love to contribute

**Comment by pdehaan** [comment]
@Shivansh2407 Looks like this has already been tentatively fixed in the pending #1481 PR!

**Comment by sbadau** [comment]
Verified as fixed on https://monitor-v2.herokuapp.com/ using Firefox 72.0.2, Chrome 80, Safari 13.0.3 and Microsoft Edge 44.18362.449.0 on Ubuntu 18.04, Mac OS X 10.15 and Windows 10 x64.

**Comment by lesleyjanenorton** [comment]
Thanks!
