### ISSUE TITLE
"Undo" should not be in the same button as "Marked as Resolved"

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1512]
[Affected versions]:

- Firefox 72.0.2

[Affected Platforms]:

- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account that has unresolved breaches.
3. Click on "Resolve this breach" link.
4. Click on the "Mark as Resolved" button.
5. Click on the "Return to breach details" button.
6. Hover your mouse over the Undo option.
7. Click on "Marked as Resolved".
 
[Expected result]:

In step 6, Undo should be underlined since it looks like a link.
In step 7, nothing should happen. 

[Actual result]:

After a breach is resolved, "Marked as Resolved" and "Undo" are performing the same action and undo the resolving of a breach. This might be misleading for the users that might accidentally click on the "Marked as Resolved" option. 

[Additional Info]:

This issue is reproducible on all the browsers.

For more details, please look at the attached video:

![2020-01-27_16h07_53](https://user-images.githubusercontent.com/56026823/73181906-c2bac380-4120-11ea-967d-4c7b97f0b50b.gif)

**Comment by lesleyjanenorton** [comment]
Closing in favor of #1506
