### ISSUE TITLE
The number of addresses that appeared in a breach is not properly updated

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1513]
[Affected versions]:

- Firefox 72.0.2

[Affected Platforms]:

- Windows 10 x64
- Windows 7 x64
- MacOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account that monitors multiple email addresses
3. Find a breach that is common for more than one email address (5 in my case).
4. Resolve one by one and look at the yellow bar from the upper side of the breach's detail page.
5. Undo the resolving of the breaches one by one
6. Observe the number of emails from the yellow bar of the breach's detail page. 

[Expected result]:

The number of emails that have the same breach is constant (it's not influenced by the number of breaches that are resolved or not) or if it decreases, it should decrease gradually (in my case 5, 4, 3, 2, 1). 

[Actual result]:

The number of emails that have the same breach is constant until there is still one breach resolved or unresolved. So in my case is either five or one. 

[Additional Info]:

This issue is reproducible on all the browsers.

Please look at the attached video:

![2020-01-27_17h32_10](https://user-images.githubusercontent.com/56026823/73188492-9eb0af80-412b-11ea-86e5-89a5f1b20b1c.gif)

**Comment by lesleyjanenorton** [comment]
Closing - the number at the top should reflect the total number of email addresses the user has that were involved in the breach, not the number of emails for which the breach is unresolved.

**Comment by sbadau** [comment]
> Closing - the number at the top should reflect the total number of email addresses the user has that were involved in the breach, not the number of emails for which the breach is unresolved.

Does this mean that if I have a total number of 5 breaches and I resolve 4 of them, then the number reflected on the yellow bar should still be 5? Because the number that reflects the total number of breaches becomes an email address right before the last breach is resolved. Is this behavior intended?
