### ISSUE TITLE
"Hide Resolved" - not properly displayed on Windows

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1517]
[Affected versions]:

- Firefox 72.0.2

[Affected Platforms]:

- Windows 10 x64
- Windows 7 x64

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/ and resolve one breach
2. Go to the main dashboard and from the "Email Addresses" section, click on "Show Resolved"
3. Observe the "Hide Resolved" option
4. Zoom the page to 110% and observe the "Hide Resolved" option.

[Expected result]:

In steps 3 and 4, the "Hide Resolved" option is properly displayed.

[Actual result]:

"Hide Resolved" option is not properly displayed on the default settings (100% zoom). 

[Additional Info]:

This issue is reproducible only on Windows - it's not reproducible on Mac OS X or on Ubuntu.
Reproducible also on Chrome on Windows OS'es.

For more details, please look at the attached video:
![2020-01-28_10h36_54](https://user-images.githubusercontent.com/56026823/73248162-1da0f900-41bb-11ea-986f-22b7138c59b9.gif)

**Comment by lesleyjanenorton** [comment]
Are the resolved breaches appearing at the bottom of the list? I can't tell from this screencast exactly what is happening.

**Comment by sbadau** [comment]
> Are the resolved breaches appearing at the bottom of the list? I can't tell from this screencast exactly what is happening.

Yes, the resolved breaches appear at the end of the list. But that is not the issue. "Hide Resolved" option is not spelled right, it appears "HIde" (reproducible only on Windows when the "Scale and Layout" of the system are set to recommended - 100%)

**Comment by lesleyjanenorton** [comment]
Thanks for the clarification. The spelling does not actually change so I think this is just an issue with the font itself and the space between the dot and body of the letter "i" becoming more or less distinguishable at various resolutions.
