### ISSUE TITLE
Check outbound emails w/ a service like litmus?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#152]
http://litmus.com/

I just saw this on a [different project](https://github.com/mozilla/email-tabs/issues/35), but vaguely recall us using it for other projects as well (maybe FxA?). May be worth considering once we start firing off breach emails... 🤷‍♀️

**Comment by ianb** [comment]
Note that per the other ticket, [Mozilla has an account we can use](https://docs.google.com/document/d/17TWKutMwke3K4sdJryMr23BVYAvWIK9CjaK34I9H42s/edit#)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
