### ISSUE TITLE
[Android] Triggering the header menu will collapse expanded breaches

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla/blurts-server#1520]
### Affected versions
Firefox Release 68.4.2, Beta 68.5b5
Chrome Chrome 79.0.3945.136
### Devices used
OnePlus 6t (Android 9)
Samsung Galaxy S8+ (Android 8.0.0)

## Steps to reproduce
1. Go to https://monitor-v2.herokuapp.com/user/dashboard
2. Login with a valid Firefox account that has breaches
3. Go to the "Email Adresses" section
4. Tap on the dropdown of an email adress in order to see the breaches
5. Swipe down the page in order to see the breaches
6. Swipe up the page

### Expected behavior
Navigation throw the breaches should be smooth
### Actual behavior
When swiping up and triggering the header menu the expanded breaches section collapses
![behavior](https://user-images.githubusercontent.com/50983519/73269406-71c0d300-41e5-11ea-99e3-631b3b666336.gif)

**Comment by LaurentiuApahideanSV** [comment]
The issue also occurs on iOS under the same behavior and repro steps.
### Affected versions
Firefox for iOS 22 (17157)
Safari
### Devices used
iPhone XS MAX iOS 12.4

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on Chrome 79.0.3945.136, Firefox 68.5.0, Beta 68.5b6 and Firefox Preview Nightly 2/6 using OnePlus 6T (Android 9) and on Firefox for iOS 20 and Safari using iPhone 8 (13.2.3).

**Comment by lesleyjanenorton** [comment]
Thanks @LaurentiuApahideanSV  - have you tried hard refreshing the page or opening the page in a new private browsing tab? I am no longer able to reproduce this.

**Comment by lesleyjanenorton** [comment]
As of 5a4956b I can no longer reproduce this.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Chrome 80.03987.87, Firefox 68.5.0, Beta 68.5b6 and Firefox Preview Nightly 2/7 using OnePlus 6T (Android 9), Samsung Galaxy S8+ (Android 8.0.0) and on Firefox for iOS 20 and Safari using iPhone 8 (13.2.3).

**Comment by lesleyjanenorton** [comment]
Thanks for the update 🎉
