### ISSUE TITLE
Resolved breaches are no longer displayed on zoom

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1521]
[Affected versions]:
- Firefox 72.0.2

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- MacOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account that monitors an email account with all the breaches resolved and another email account that has resolved and unresolved breaches.
3. Zoom over 240% (until the Show Resolved option is no longer available).
4. For the email with resolved and unresolved breaches, click on the "˅" button.
5. For the email with all the breaches resolved, click on the "˅" button.

[Expected result]:

In steps 4 and 5, all the breaches resolved and unresolved are shown.

[Actual result]:

In step 5, the resolved breaches are no longer displayed. 

[Additional Info]:

This issue is reproducible on all the browsers.
For more details, please see the attached video.

![2020-01-28_16h02_50](https://user-images.githubusercontent.com/56026823/73271495-61aaf280-41e9-11ea-95ab-95545bcb1cad.gif)

**Comment by lesleyjanenorton** [comment]
Closing - this is expected. Thank you for filing though!
