### ISSUE TITLE
[Android]The show/hide resolved breaches option option is not present

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla/blurts-server#1522]
### Affected versions
Firefox Release 68.4.2, Beta 68.5b5
Chrome Chrome 79.0.3945.136
### Devices used
OnePlus 6t (Android 9)
Samsung Galaxy S8+ (Android 8.0.0)

## Steps to reproduce
1. Go to https://monitor-v2.herokuapp.com/user/dashboard
2. Login with a valid Firefox account that has several breaches
3. Resolve all breaches
4. Return to the Dashboard

### Expected behavior
A show/hide resolved breaches option should be present
### Actual behavior
The show/hide resolved option in not present and solved breaches cannot be accessed
![behavior2](https://user-images.githubusercontent.com/50983519/73279055-2dd5ca00-41f5-11ea-992d-9ab303d2fe7b.gif)

**Comment by lesleyjanenorton** [comment]
The Hide/Show buttons aren't visible on mobile. The resolved breaches are visible by default at the end of the breach list.
