### ISSUE TITLE
The same email account isn't synced if it is monitored on two different Firefox accounts

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/blurts-server#1523]
[Affected versions]:
- Firefox 72.0.2

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- MacOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:

1. Navigate to https://monitor-v2.herokuapp.com/.
2. Log into a Firefox Monitor account that monitors multiple email addresses.
3. Log into another Firefox Monitor account that monitors multiple email addresses (same as in step 2).
4. Resolve some of the breaches for any of the monitored account.
5. Observe the monitored email accounts.

[Expected result]:

- The same email account should be synced if it is monitored on two different Firefox accounts.

[Actual result]:

- The same email account isn't synced if it is monitored on two different Firefox accounts.

**Comment by lesleyjanenorton** [comment]
This is as designed. It's unlikely, but possible, that two people could be monitoring the same email address. In that scenario, one individual should not be able to see which breaches the other individual has resolved.
