### ISSUE TITLE
Breaches are not arranged properly when the window is resized

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1524]
[Affected versions]:
- Firefox 72.0.2

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- MacOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account that monitors multiple email accounts and has multiple breaches
3. Having the Home page in focus resize the browser's window

[Expected result]:

The breaches are properly displayed.

[Actual result]:

The breaches are re-arranged.

[Additional Info]:

This is reproducible on all the browsers.
For more details,0 please see the attached video.

![2020-01-29_11h31_16](https://user-images.githubusercontent.com/56026823/73346277-4219d580-428e-11ea-9411-89ea98d874ed.gif)

**Comment by sbadau** [comment]
I can no longer reproduce this issue on https://monitor-v2.herokuapp.com/ using Firefox 72.0.2, Chrome 80, Safari 13.0.3 and Microsoft Edge 44.18362.449.0 on Ubuntu 18.04, Mac OS X 10.15 and Windows 10 x64.

**Comment by lesleyjanenorton** [comment]
Cool, thanks!
