### ISSUE TITLE
[Windows] The confirmation images are not rendered on HCM 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#1525]
[Affected versions]:
- Firefox 72.0.2

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64

[Prerequisites]:
- Turn on High contrast mode from Control Panel 

[Steps to reproduce]:

1. Navigate to https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account that monitors an email account with a couple of breaches unresolved.
3. From  the Home page,  under the accounts click on "Resolve this breach".
4. Scroll down the page and click on the "Mark as Resolved" button.
5. Inspect the image confirmation received. 

[Expected result]:
- The confirmation image is not displayed.

[Actual result]:
- The confirmation image is correctly displayed in HCM.

[Additional Info]:
- This issue are not reproducible on macOS and Ubuntu.
- Please observe the attached screenshot.

![image](https://user-images.githubusercontent.com/43886441/73346863-42ff3700-428f-11ea-9950-e91927eba9ac.png)

**Comment by lesleyjanenorton** [comment]
Thanks for catching this. Closing as wontfix - the images are decorative and not essential to understanding the experience.
