### ISSUE TITLE
[Android] The breaches list can not be expanded if all breaches are resolved

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla/blurts-server#1528]
### Affected versions
Firefox Release 68.4.2, Beta 68.5b5
Firefox Preview Nightly (Build #20290608) GV: 74.0a1-20200126094816 1/29
Chrome Chrome 79.0.3945.136
### Devices used
Google Pixel 3a (Android 9)
Samsung Galaxy Note9 (Android 9)

## Steps to reproduce
1. Go to https://monitor-v2.herokuapp.com/user/dashboard
2. Login with a valid Firefox account that has breaches
3. For an email address mark all breaches as resolved
4. Go to the Dashboard
5. Expand the breaches for the email from step 3

### Expected behavior
The breaches list should expand
### Actual behavior
The breaches list does not expand and the status of resolved breaches can no longer be modified

**Comment by LaurentiuApahideanSV** [comment]
The issue also occurs on iOS under the same behavior and repro steps.
### Affected versions
Firefox for iOS 22 (17157)
Safari
### Devices used
iPhone XS MAX iOS 12.4

**Comment by lesleyjanenorton** [comment]
Could you add a screencast or screencap for this please? Thanks!

**Comment by LaurentiuApahideanSV** [comment]
I have attached a short video detailing the issue.
![behavior2](https://user-images.githubusercontent.com/50983519/73758130-e5795780-4772-11ea-923d-c8e77e37a08e.gif)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox 68.5.0, Beta 68.5b6 and Firefox Preview Nightly 2/6 using OnePlus 6T (Android 9) and on Firefox for iOS 20 and Safari using iPhone 8 (13.2.3).

**Comment by lesleyjanenorton** [comment]
Thank you @LaurentiuApahideanSV !
