### ISSUE TITLE
The progress of the resolved breaches - is jumping on page reload

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1529]
[Affected versions]:
- Firefox 72.0.2

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- MacOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account that has multiple breaches resolved
3. Observe the progress bar of the resolved breaches
4. In the upper side of the page, click on Breaches to change the section
5. Click back on the Home section
6. Repeat steps 4 and 5 for a couple of times.

[Expected result]:

The progress bar of the resolved breaches should not be affected by changing the sections or by reloading the page.

[Actual result]:

The progress is jumping. Please see the video for more details.

[Additional Info]:
This issue is reproducible on all the browsers.

![2020-01-29_14h05_25](https://user-images.githubusercontent.com/56026823/73365648-49a0a500-42b5-11ea-87f7-952c264928f3.gif)

**Comment by sbadau** [comment]
Verified as fixed on https://monitor-v2.herokuapp.com/ using Firefox 72.0.2, Chrome 80, Safari 13.0.3 and Microsoft Edge 44.18362.449.0 on Ubuntu 18.04, Mac OS X 10.15 and Windows 10 x64.

**Comment by lesleyjanenorton** [comment]
Cool, thank you @sbadau !
