### ISSUE TITLE
Make sure we cleverly specify if a breach has an SVG or PNG logo

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#153]
Per https://github.com/mozilla/blurts-server/pull/151#discussion_r193541535...

This may be in some `meta.LogoType` property somewhere, but according to `https://stage.haveibeenpwned.com/api/v2/breaches`, it looks like the value will be either "png" or "svg".

**Comment by lesleyjanenorton** [comment]
I don't know if it counts as 'cleverly specified', given the amount of time it took me to arrive at a solution, but this should be resolved in #154

**Comment by pdehaan** [comment]
Super clever, love it!

**Comment by pdehaan** [comment]
Ingeniously fixed via #154, closing.

https://github.com/mozilla/blurts-server/blob/cdda1a945c8b495bb3ee5a68ae35ad926b344c5a/views/partials/banner_breach.hbs#L5
https://github.com/mozilla/blurts-server/blob/cdda1a945c8b495bb3ee5a68ae35ad926b344c5a/views/partials/compromised_accounts.hbs#L6
