### ISSUE TITLE
The appearance of the progress bar on Microsoft Edge is not according to the specifications

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1530]
[Affected versions]:

Microsoft Edge 44.18362.449.0

[Affected Platforms]:
Windows 10

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account that has resolved and unresolved breaches.
3. Observe the progress bar of the resolved breaches.

[Expected result]:

The progress bar has the same appearance as on Firefox and Chrome.

[Actual result]:

The progress bar is blue. 
For more details, please see the attached picture
![2020-01-30_10h49_21](https://user-images.githubusercontent.com/56026823/73435043-8ec5e500-4350-11ea-9cd0-229fbf0ea887.png)
.

**Comment by lesleyjanenorton** [comment]
Can this still be reproduced?

**Comment by sbadau** [comment]
> Can this still be reproduced?

This issue is no longer reproducible, verified on Windows 10 using Microsoft Edge 44.18362.449.0.
