### ISSUE TITLE
The Marked as resolved breaches confirmation page is flickering

### ISSUE THREAD

**Issue by rpopovici9** [mozilla/blurts-server#1531]
[Affected versions]:

Firefox 72.0.2, Safari, Chrome

[Affected Platforms]:

Windows 10 x64
MacOS 10.14

[Steps to reproduce]:

1. Navigate to https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account that monitors multiple email accounts and has multiple breaches
3. Choose a breach from the "Email Addresses" section and click on Resolve this breach link.
4. Click on the "Mark as Resolved" button.
5. Having the "Marked as resolved" breaches confirmation page in focus, resize the browser's window

[Expected result]:

The Marked as resolved breaches confirmation page is properly displayed.

[Actual result]:

The Marked as resolved breaches confirmation page is flickering.

[Additional Info]:

For more details, please see the attached video. 
![2020-01-30_11h10_22](https://user-images.githubusercontent.com/60425738/73435552-89b56580-4351-11ea-85c3-a238f429c667.gif)

**Comment by lesleyjanenorton** [comment]
Thanks for catching - closing as wontfix
