### ISSUE TITLE
On Microsoft Edge, email address and breaches are dubled

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1532]
[Affected versions]:

- Microsoft Edge 44.18362.449.0

[Affected Platforms]:
- Windows 10

[Steps to reproduce]:
1. Navigate to https://monitor-v2.herokuapp.com/
2. Log into a Firefox Monitor account that monitors only one account.
3. To the existing one, add another account
4. Check the email for the confirmation and confirm
5. Go to the main dashboard, check the number of breaches and the number of monitored email addresses.

[Expected result]:

In step 4, an email confirmation is received and the confirmation is successful.
In step 5, there are 2 monitored email accounts with the corresponding breaches.

[Actual result]:

In steps 4 and 5, two email confirmations are received and the email account is added twice to the Firefox account.

For more details, please see the attached video.
![2020-01-30_14h05_03](https://user-images.githubusercontent.com/56026823/73448511-b37a8680-4369-11ea-807b-9bb533b08906.gif)

**Comment by Shivansh2407** [comment]
Is this an issue on Microsoft Edge Only? Can you please tell the possible areas to work on so that I can Pull a request.

**Comment by groovecoder** [comment]
FWIW, I was unable to reproduce this with Mac (Chromium) Edge Version 81.0.413.0 (Official build) Canary (64-bit). The new email was only added once.

**Comment by groovecoder** [comment]
This is reproducible with Windows 10 Edge 44.18362.387.0 on fx-breach-alerts.herokuapp.com, so I don't think it's related to breach resolution changes.

**Comment by groovecoder** [comment]
I think I tracked this down to form double-submits in Edge.

* The page's regular HTML `<form>` submit fires
* `monitor.js` `handleFormSubmits` also submits the form

(I'm not sure why the `preventDefault` in `handleFormSubmits` doesn't stop the page's regular HTML `<form>` submit - just an Edge bug maybe?)

The fix may be to use `sendForm` like the other "forms" on the preferences page do.

**Comment by pdehaan** [comment]
Need to do some more research, but this popped up via Google:
https://support.microsoft.com/en-ca/help/3176755/preventdefault-doesn-t-work-in-internet-explorer-11-or-microsoft-edge
https://css-tricks.com/return-false-and-prevent-default/

Its amazing how most of the results from any combination of Google searches seem to be from 2010-2012.

**Comment by lesleyjanenorton** [comment]
@pdehaan @groovecoder thank you for the detective work here

**Comment by sbadau** [comment]
Verified as fixed on Windows 10 x 64 using Microsoft Edge 44.18362.449.0.

**Comment by lesleyjanenorton** [comment]
Thanks @sbadau !
