### ISSUE TITLE
Email relay test

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1535]
PRD: https://docs.google.com/document/d/1rJI8orhfnyW_QNAtAWtqd-PB3T-L02vZTq-Jpg4C6nM/edit#heading=h.1pfk0qobe7xa
Mockups: [Dashboard](https://mozilla.invisionapp.com/share/RGRIETZ7NAJ#/screens/400510284) and [Landing page](https://mozilla.invisionapp.com/share/RGRIETZ7NAJ#/screens/400519235)
Copy draft: https://docs.google.com/document/d/1uLROV2egtJ0tuiej2s-SQIrcfiwOjTTop6Q-4uaV-bc/edit#

Tasks:
* Add custom dimensions in GA
* Add dashboard call-out
* Add landing page
* Add relay signup field to DB

**Comment by betsymi** [comment]
Question: Do we also need to write/design a confirmation email and/or modal?

**Comment by lesleyjanenorton** [comment]
@betsymi good point. I would think so?

**Comment by changecourse** [comment]
We're designing for an on-page, confirmation replacement state for the fxa section, as seen here: https://mozilla.invisionapp.com/share/RGRIETZ7NAJ#/405057095_Email_Relay-_Landing_Page_-Confirmation-

Final copy tbd
