### ISSUE TITLE
Verification email: only text within blue button is click-able

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1537]
Reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1612989

Steps to reproduce:

1. Login to Firefox Monitor
2. Add a second email address.
   * A verification email is sent to the primary address. In my email app (Gmail), open the verification email from Firefox Monitor.
3. Click the blue area of the "Verify Email" button (not the text).

Actual results:
Nothing happens.

Expected results:
Link should open when clicking anywhere on the blue button

**Comment by Shivansh2407** [comment]
Can I work on this @groovecoder , @lesleyjanenorton ?

**Comment by lesleyjanenorton** [comment]
@Shivansh2407 This might not be a very fun one. HTML for emails is a notoriously thorny and convoluted business.
