### ISSUE TITLE
The same email address can be added to a single account many times.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#1540]
The same email can be added added to a single account many times as long as the letter casing is unique.

For instance:
<img width="661" alt="Screen Shot 2020-02-06 at 4 04 41 PM" src="https://user-images.githubusercontent.com/22355127/73982768-88a8a900-48fa-11ea-9bc9-04088760e8f6.png">

**Comment by Shivansh2407** [comment]
@lesleyjanenorton can I work on this . Also please help me on how to proceed with this issue.

**Comment by lesleyjanenorton** [comment]
Hey @Shivansh2407 - There are probably a few ways to do this but I'd start with taking a look at ` _checkForDuplicateEmail` which is responsible for checking whether or not an email address has already been added and making some adjustments there. You could try converting the values being compared `.toLowerCase()`.   https://github.com/mozilla/blurts-server/blob/a5c19c2fe13fb4084273db6155c0b7cc713d6de1/controllers/user.js#L75

**Comment by sandysage** [comment]
Do we know the implications of this issue? For instance, does a user get multiple breach emails? Or is this primarily a display issue?

**Comment by lesleyjanenorton** [comment]
Pretty sure they are treated as unique email addresses and the user would receive an alert for each one.
