### ISSUE TITLE
The message under the Break Summary status bar is grammatically incorrect

### ISSUE THREAD

**Issue by MPeter91** [mozilla/blurts-server#1541]
**[Affected versions]:**
All

**[Affected Platforms]:**
All

**[Steps to reproduce]:**
1. Navigate to https://monitor-v2.herokuapp.com/
2. Create a new Firefox Monitor account with a breached email.
3. Click on "Resolve this breach" link.
4. Click on the "Mark as Resolved" button.
5. Repeat Steps 3-4 until you get to least 75% complete on the breach summary status bar

**[Expected result]:**
Message should say "You're nearly at the finish line" or maybe "You're close to the finish line"

**[Actual result]:**
Message says "You're nearly to the finish line"

![image](https://user-images.githubusercontent.com/60887101/74160236-c3c21980-4c25-11ea-8839-874dc0959416.png)

**Comment by betsymi** [comment]
We can change it to `You're close to the finish line.` The current is not grammatically incorrect, however the suggested string change reads more nicely.

**Comment by lesleyjanenorton** [comment]
@flodolo can we modify the existing string for this?

**Comment by flodolo** [comment]
Yes, I would modify the English strings without a new ID, and possibly fix other en-*

No point in losing existing translations, since the content was clear.

**Comment by lesleyjanenorton** [comment]
sounds good, thank you!
