### ISSUE TITLE
Wrong plural form in call-out box for resolved breaches

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#1542]
It's showing the plural for Italian, but there's only 1 resolved breach. Something wrong with the passed value maybe?

<img width="813" alt="Schermata 2020-02-10 alle 18 34 14" src="https://user-images.githubusercontent.com/3644868/74174341-0e4a9280-4c34-11ea-847e-6a0d971c7e8f.png">

**Comment by pdehaan** [comment]
I think these are the strings in question:

https://github.com/mozilla/blurts-server/blob/e3c1bfb88aa6ff0142576e61a1d5b6af82d9ba09/locales/it/app.ftl#L462-L466

Still trying to figure out why it's going the `[other]` path though. 🤷‍♂

**Comment by flodolo** [comment]
One possible thought is that the value is passed with the wrong type, so it falls back to the default form.

**Comment by lesleyjanenorton** [comment]
Also happening in English.

**Comment by pdehaan** [comment]
FWIW, I tried this <kbd>git grep</kbd> command which should hopefully pull all instances of `localize(.*)` where we're passing a third [Object] argument, and I did a quick manual verification of the keys vs values being used in the locales/en/app.ftl files and I didn't see any other mismatches.

```sh
git grep -Eno "localize\(.*\)" | grep ", {"

template-helpers/breach-detail.js:198: localize(locales, "resolve-top-notification-plural", { numAffectedEmails: numAffectedEmails })
template-helpers/breach-detail.js:199: localize(locales, "resolve-top-notification", { affectedEmail: unresolvedAffectedEmails[0].emailAddress })
template-helpers/breach-stats.js:21: localize(locales, "email-addresses-being-monitored", { emails: verifiedEmails.length })
template-helpers/breach-stats.js:31: localize(locales, "unresolved-passwords-exposed", { numPasswords: remainingExposedPasswords })
template-helpers/breach-stats.js:35: localize(locales, "known-data-breaches-resolved", { numResolvedBreaches: breachesStat.numResolved })
template-helpers/breach-stats.js:39: localize(locales, "passwords-exposed", { passwords: passwordStat.count })
template-helpers/breach-stats.js:42: localize(locales, "known-data-breaches-exposed", { breaches: breachesStat.count })
template-helpers/breach-stats.js:107: localize(locales, "progress-percent-complete", { "percentComplete": percentBreachesResolved})
```

As always, great catch @flodolo!
