### ISSUE TITLE
Review and remove any 3rd party libs not required

### ISSUE THREAD

**Issue by psiinon** [mozilla/blurts-server#156]
Jquery looks like a good candidate to remove :)

**Comment by pdehaan** [comment]
Currently, I believe the only 3rd party code we're bundling is **jQuery** and **Foundation**.

- https://github.com/mozilla/blurts-server/issues/165 &mdash; "Uncaught ReferenceError: $ is not defined" at monitor.js:71
- https://github.com/mozilla/blurts-server/pull/154#pullrequestreview-126647921 &mdash; and I think @lesleyjanenorton was looking at whether we could do away w/ Foundation CSS framework.

**Comment by pdehaan** [comment]
jQuery and Foundation (JavaScript) were deleted from the repo in PR #176 (but were unused on site before that).
I believe we're still using Foundation's CSS via https://github.com/mozilla/blurts-server/tree/master/public/css/vendor, but with plans to rewrite the relevant CSS bits ourselves and remove that dependency as well.

I think we're fine to close this issue. Thanks for the heads up, @psiinon!

**Comment by pdehaan** [comment]
Note, I have a PR to add back a vendor script from GitHub in #196 (for DNT code; via [**schalkneethling/dnt-helper**](https://github.com/schalkneethling/dnt-helper).
