### ISSUE TITLE
Plan loadtesting

### ISSUE THREAD

**Issue by psiinon** [mozilla/blurts-server#157]

**Comment by pdehaan** [comment]
I would call this blocked on #135; "Complete Dockerflow setup for stage & prod deployment pipelines".
Once we can get a stage env set up on AWS, I think it's reasonable that we could begin some preliminary load testing and general debauchery.

**Comment by pdehaan** [comment]
@nhnt11 Did you have a change to work on the load tests using [**molotov**](https://github.com/loads/molotov)?

**Comment by groovecoder** [comment]
I'm going to close this issue and open a new one for a comprehensive load-testing plan including:

* Massive spike of web visitors
  * Some % performing scans (hits HIBP API)
  * Some % performing sign-ups (hits DB and HIBP API)
    * Some % also opting into Firefox newsletter (hits Basket)
