### ISSUE TITLE
Consider connection pooling

### ISSUE THREAD

**Issue by psiinon** [mozilla/blurts-server#158]
Recommendation from the RRA

**Comment by pdehaan** [comment]
@psiinon I'm intrigued, what's "The RRA"?

**Comment by psiinon** [comment]
@pdehaan Rapid Risk Assessment: https://infosec.mozilla.org/guidelines/risk/rapid_risk_assessment.html
We ran one for the Blurts server - I've just shared it with you Mozilla account :)
