### ISSUE TITLE
Drag and drop functionality on ecosystem banners is not the same on all the browsers

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/blurts-server#1590]
* Affected versions
Chrome Version 80.0.3987.132 (Official Build) (64-bit)
Safari  Version 13.0.5

* Affected platforms:
MacOS 10.14
Windows 10 and 7 x64
Ubuntu 

* Steps to reproduce
1. Go to https://blurts-server-review.herokuapp.com
2. Enter any valid email address with breaches and click on "Check for Breaches".
3. Observe "Monitor Sign Up Promo" banner.
4. Try to drag and drop the banner to the url bar.

* Expected behaviour:
Drag and drop should function accordingly and the whole banner should be visible while trying to drag and drop

* Actual behaviour:
On Chrome: Banner can't be dragged and dropped
On Safari: While trying to drag and drop only the text is visible not the whole banner
On Firefox: The whole banner is visible while trying to drag and drop
On Edge: Drag and drop is not possible

![Safari](https://user-images.githubusercontent.com/15101135/76853564-37bf9500-6856-11ea-92e4-a0c9748d1062.png)

**Comment by sandysage** [comment]
Given the necessary flows into FxA, this is not something we can address in a reasonable amount of time. Closing as 'wont-fix'
