### ISSUE TITLE
Firefox Monitor: Cross-promote the Firefox Ecosystem banners work like buttons

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#1591]
Affected versions]:
-  Firefox 74.0
- Safari
- Chrome

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://blurts-server-review.herokuapp.com/
2. Without signing in, enter any email address (ex. john@mailinator.com) and click on "Check for Breaches" button.
3. Click on any of the breaches.
4.  Click anywhere on the "Monitor Sign Up Promo" banner, except the "Sign Up for Alerts".

[Expected result]:
- Nothing happens. 

[Actual result]:
- The login page is loaded. 

[Regression]:
- N/A

[Additional Info]:
- This issue is reproducing with "Firefox Mobile Promo" banner too.

**Comment by sandysage** [comment]
Works as expected. This increases the clickable space on mobile. Closing as 'wont-fix'
