### ISSUE TITLE
[Android] The Firefox Private Network promo is not displayed

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla/blurts-server#1594]
### Affected versions
Firefox Release 68.6.0, Beta 68.7b1
### Devices used
OnePlus 6T (Android 9)
Huawei MediaPad M3 (Android 7.0)

## Steps to reproduce
1. Go to https://blurts-server-review.herokuapp.com/
2. Login with a valid Firefox account that has breaches.
3. Expand the breaches list and select a breach that exposed IP addresses to resolve.
4. Scroll down the page.

### Expected behavior
The Firefox Private Network promo should be displayed at the bottom of the page.
### Actual behavior
The promo to download Firefox Mobile is displayed instead.

**Comment by lesleyjanenorton** [comment]
Closing - If I'm understanding the issue correctly, this is actually the expected behavior. The banner for Firefox Mobile should only _not_ be shown the user's browser is Firefox Mobile.

**Comment by LaurentiuApahideanSV** [comment]
I retested the issue on Firefox Release 68.6.0 and Beta 68.7b1 using a OnePlus 6T (Android 9) and Huawei MediaPad M3 Lite 10 (Android 7.0) and the Firefox Private Network promo is displayed when inspecting a security breach that exposed IP adresses.
