### ISSUE TITLE
In my reginal language, header not displaying correctly

### ISSUE THREAD

**Issue by petreleon** [mozilla/blurts-server#1597]
![Screenshot 2020-03-17 at 18 40 06](https://user-images.githubusercontent.com/13880012/76880274-1ecbd980-6880-11ea-957b-c98fe88ad15d.png)
As it seems in this image, the line is over text.

**Comment by groovecoder** [comment]
This language is `ro` but it happens for any non-en language with word breaks in these titles. e.g., `cy` too:
![image](https://user-images.githubusercontent.com/71928/117505912-6e6cd900-af4a-11eb-93bf-601f493a4cb2.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
