### ISSUE TITLE
[iOS]Firefox Ecosystem Promo banner-The font text color for "Sign Up" button is black instead of white

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla/blurts-server#1599]
**Affected version:**
Firefox Release Version 23.0 (17297)

**Devices used:**
iPad - Model MH0W2HC/A -> Version 11.4 (15F79)

**Steps to reproduce:**
1. Go to https://blurts-server-review.herokuapp.com/ .
2. Make a search after an email address with breaches.
3. Scroll down the page.
4. Inspect the banner and it's elements.

**Expected Result:**
All the elements are correctly displayed, the text, font and color is the same with the one from the banner.
![Screenshot_20200318-121944](https://user-images.githubusercontent.com/49859863/76952871-6c932100-6916-11ea-938b-d1297d3aa05a.jpg)

**Actual Result:**
The font's color  for the "Sign Up for Alerts" button is different than the one from the mock-up. Instead of being white is black.
![1584527425370](https://user-images.githubusercontent.com/49859863/76953001-a401cd80-6916-11ea-99b0-e601a6e72ef1.JPEG)

**Note:**
**- "Firefox Mobile Promo" - Mock-Up**
![Screenshot_20200318-122001](https://user-images.githubusercontent.com/49859863/76955154-55eec900-691a-11ea-8664-0221512af579.jpg)

**Actual Result:**
![1584529971067](https://user-images.githubusercontent.com/49859863/76955223-73bc2e00-691a-11ea-845d-c820e981f65a.JPEG)

**- "Firefox Private Network Promo" - Mock-Up:**
![Firefox_FPN](https://user-images.githubusercontent.com/49859863/76955377-b7169c80-691a-11ea-9e9d-5ee1860d20ad.jpg)

**Actual Result:**
![1584530301397](https://user-images.githubusercontent.com/49859863/76955500-fc3ace80-691a-11ea-984b-8d5a60873d94.JPEG)

**-Firefox Ecosystem Promo - Actual Result**
![1584530621577](https://user-images.githubusercontent.com/49859863/76955907-bb8f8500-691b-11ea-9f90-a47bebdfa83e.JPEG)

**Comment by lesleyjanenorton** [comment]
Are you still able to reproduce this? I'm unable to on my iPad Pro.
