### ISSUE TITLE
Implement an elegant system to register API handlers

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#16]
Currently API handlers are added direction with app.get/app.post. We should implement a handler registration system that will allow organized, versioned API handling for better maintainability and readability.

**Comment by bhavyaagg** [comment]
Hello @nhnt11 
I can refactor the code with routes if no one is working on it.

**Comment by nhnt11** [comment]
Hey @bhavyaagg, sorry for the late response. I had a WIP already which I just pushed to the routes branch, see PR #29. If you'd like to help out, you can look at that commit and leave review comments - that would be a really useful contribution.

**Comment by pdehaan** [comment]
@nhnt11 Is this fixed with #29, or are we aiming for more elegance?

**Comment by nhnt11** [comment]
Fixed a while ago (#29 and others)
