### ISSUE TITLE
When resizing the browser the QR Code is not displayed anymore.

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#1604]
Affected versions]:
-  Firefox 74.0
- Chrome

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://blurts-server-review.herokuapp.com/
2. Sign in with a breached email. 
3. Click on any of the breaches.
4. Resize the page. 

[Expected result]:
- The banners has the same format. 

[Actual result]:
- The QR code disappears. 

[Regression]:
- N/A

**Comment by lesleyjanenorton** [comment]
Closing - thank you for filing, this is as-designed.
