### ISSUE TITLE
Pontoon sync is broken

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#1606]
Just noticed by pure chance, while looking at the log for another project.

```
Failed to sync locale zh-TW for project firefox-monitor-website due to commit error: remote: error: GH006: Protected branch update failed for refs/heads/master.        
```

All locales are now failing, because apparently master is protected. When was this changed made? Pontoon needs to be able to commit, you can't protect it :-\

**Comment by hwine** [comment]
> Pontoon needs to be able to commit, you can't protect it :-\

On a technical note, it _is_ completely possible to both allow pontoon to commit, and have the branch be protected. If anyone needs help with that, contact [github-admins](https://chat.mozilla.org/#/room/#github-admin:mozilla.org)

**Comment by flodolo** [comment]
I believe the protection blocking this was "require pull request reviews before merging", not sure that can be set?

**Comment by groovecoder** [comment]
I think we got this fixed up now.
