### ISSUE TITLE
[Experiment] The “Must be a valid email.” error message of the “Enter Email Address” field is not displayed if the checkbox is ticked

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1607]
**[Affected Versions]:**
- Firefox Release 74.0, Build ID 20200309095159
- Firefox Beta 75.0b7 Build ID 20200322132212
- Firefox Preview (Fenix) 4.1.0 Build #207711637

**[Affected Platforms]:**
- Windows 10 (x64) 
- Mac 10.15.3
- Motorola One Vision - Android 10

**[Prerequisites]:**
- You are on the  https://monitor-v2.herokuapp.com/ page.
- You are enrolled in the Version C: Opt Out treatment of the Firefox Monitor Growth Experiment.

**[Steps to reproduce]:**
1. Enter an invalid input in the “Enter Email Address” field (e.g. 123).
2. Click the “Check for Breaches” button.

**[Expected results]:**
-  The “Must be a valid email.” error message is displayed and the “Enter Email Address” field is highlighted in a red outline. 
-  The FxA sign-in process is not triggered. 

**[Actual results]:**
- No error message is displayed and the “Enter Email Address” field is not highlighted.
- The FxA sign-in process is triggered.

**[Notes]:**
- This issue is also reproducible for Version B: Opt In, if the checkbox is ticked.
- This issue is not reproducible for Version A: Control.
- Attached is a recording of the issue.

![monitor front-end validation](https://user-images.githubusercontent.com/53752296/77333847-b02dc680-6d2c-11ea-80dc-f5ce00d3b9fe.gif)

**Comment by maxxcrawford** [comment]
@heres-maria Added a fix for this. Please verify on the [test site](https://monitor-v2.herokuapp.com/?experimentBranch=vc).

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible using Firefox Release 74.0 Build ID 20200309095159 and Chrome v. 80.0.3987.149 on Windows 10 (x64) as well as Firefox Preview 4.1.0 Build #20771637 on Android 10 (Motorola One Vision).
The "Must be a valid email"  error message is now displayed.
As a result, I am closing this issue.
