### ISSUE TITLE
[Experiment] The FxA Registration page is not pre-filled after performing a breach search with the checkbox ticked

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1608]
**[Affected Versions]:**
- Firefox Release 74.0, Build ID 20200309095159
- Firefox Beta 75.0b7 Build ID 20200322132212
- Firefox Preview (Fenix) 4.1.0 Build #207711637

**[Affected Platforms]:**
- Windows 10 (x64) 
- Mac 10.15.3
- Motorola One Vision - Android 10

**[Prerequisites]:**
- You are on the  https://monitor-v2.herokuapp.com/ page.
- You are enrolled in the Version C: Opt Out treatment of the Firefox Monitor Growth Experiment.

**[Steps to reproduce]:**
1. Enter an email not associated with an existing account in the “Enter Email Address” field.
2. Click the “Check for Breaches” button.

**[Expected results]:**
- The “Create a Firefox Account” page is displayed, with the email pre-filled. 

**[Actual results]:**
- The “Enter your email” page is displayed.

**[Notes]:**
- This issue is also reproducible for Version B: Opt In, if the checkbox is ticked.
- This issue is also reproducible for emails associated with existing accounts, due to the Account Found Overlay not being implemented yet.
- This issue is not reproducible if a breach search has been previously performed with the checkbox unticked.
- This issue is not applicable for Version A: Control.
- Attached is a recording of the issue.

![monitor email not pre-filled final](https://user-images.githubusercontent.com/53752296/77337671-df930200-6d31-11ea-9227-caf5442c9a2c.gif)

**Comment by maxxcrawford** [comment]
@heres-maria Resolved! Please verify on the [test site](https://monitor-v2.herokuapp.com/).

**Comment by heres-maria** [comment]
This issue is still reproducible using Firefox Release 74.0 Build ID 20200309095159 and Chrome  v. 80.0.3987.149 on Windows 10 (x64) as well as Firefox Preview 4.1.0 Build #20771637 on Android 10 (Motorola One Vision).
This issue is still reproducible for some emails other than mozilla.com ones. 
For emails associated with an account, another issue has been filed: #1616.

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible using Firefox Beta 75.0b1 Build ID 20200309155231 on Windows 10 (x64) as well as Firefox 68.6.0 on Android 9 (Samsung Galaxy S8).
The right email is prefilled even with emails other than mozilla.com ones.
As a result, I am closing this issue.
