### ISSUE TITLE
[Experiment] The Account Found Overlay is not displayed when performing a breach search with the checkbox ticked

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1609]
**[Affected Versions]:**
- Firefox Release 74.0, Build ID 20200309095159
- Firefox Beta 75.0b7 Build ID 20200322132212
- Firefox Preview (Fenix) 4.1.0 Build #207711637

**[Affected Platforms]:**
- Windows 10 (x64) 
- Mac 10.15.3
- Motorola One Vision - Android 10

**[Prerequisites]:**
- You are on the [Version C: Opt Out](https://monitor-v2.herokuapp.com/?experimentBranch=vc) page.

**[Steps to reproduce]:**
1. Enter an email associated with an existing account in the “Enter Email Address” field.
2. Click the “Check for Breaches” button.

**[Expected results]:**
- The Account Found Overlay is displayed. 

**[Actual results]:**
- The “Enter your email” page is displayed.

**[Notes]:**
- This issue is also reproducible for[ Version B: Opt In](https://monitor-v2.herokuapp.com/?experimentBranch=vb), if the checkbox is ticked.
- If a breach search using the email associated with an account has been previously performed with the checkbox unticked, the “Sign in” page is displayed.
- This issue is not applicable to [Version A: Control](https://monitor-v2.herokuapp.com/?experimentBranch=va).
- Attached is a recording of the issue.
![monitor overlay missing](https://user-images.githubusercontent.com/53752296/77403954-adc57e00-6db9-11ea-9bf3-d5c5095b8054.gif)

**Comment by maxxcrawford** [comment]
Confirmed with the team – this is a non-blocking issue for this experiment.

**Comment by heres-maria** [comment]
I am closing this issue as the experiment is no longer active.
