### ISSUE TITLE
Add site footer?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#161]
I feel like we should have one that at least points to our Privacy Policy and Terms of Service (since we're [eventually] collecting email addresses and async emailing people, etc).

<details>
<summary>Old footer.png placeholder. Ignore this.</summary>

> We have this image, [blurts-server/public/img/footer.png](https://github.com/mozilla/blurts-server/blob/master/public/img/footer.png) (added in d5bce11df7a5dfc29d3738ed20508215c92d0148), which shows a fairly standard looking footer.
>
> ![](https://raw.githubusercontent.com/mozilla/blurts-server/d5bce11df7a5dfc29d3738ed20508215c92d0148/public/img/footer.png)

~~Follow up nit, that footer.png should be deleted once we have an actual footer.~~ I already deleted this file.
</details>

**Comment by lesleyjanenorton** [comment]
I can drop something in. Are there docs for footer style guides / requirements for what goes in there? I will fish around.

**Comment by pdehaan** [comment]
@lesleyjanenorton I don't know nothin' about nothin'.
But, I'd say we ping a UX person, or just steal some code/UI from https://testpilot.firefox.com/ and ask for forgiveness later.

**Comment by lesleyjanenorton** [comment]
or do both!

**Comment by pdehaan** [comment]
Alternate proposal, minimal footer like https://color.firefox.com/ which at least has links to legal, Privacy Policy, Terms of Service and Mozilla Cookies policies (as well as a link to the repo)

![firefox_color_footer](https://user-images.githubusercontent.com/557895/41129515-49756bf6-6a67-11e8-8d4e-066119389c46.png)

**Comment by e-pang** [comment]
Created a minimal version of a footer here: https://e-pang.github.io/breach-alerts

"Privacy" link goes here: https://www.mozilla.org/en-US/privacy/websites/   
"Terms" link goes here: https://www.mozilla.org/en-US/about/legal/ 

"Creative Commons license" links to https://www.mozilla.org/en-US/foundation/licensing/website-content/

Thanks!

**Comment by lesleyjanenorton** [comment]
nice- thank you!

**Comment by e-pang** [comment]
@lesleyjanenorton np!
