### ISSUE TITLE
[Experiment] The wrong branch homepage is displayed after account logout

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1610]
**[Affected Versions]:**
- Google Chrome version 80.0.3987.149 (x64)
- Firefox Release 74.0, Build ID 20200309095159
- Firefox Preview (Fenix) 4.1.0 Build #207711637

**[Affected Platforms]:**
- Windows 10 (x64) 
- Linux Mint 19.2 Tina
- Android 10 (Motorola One Vision)

**[Prerequisites]:**
- You are on the  https://monitor-v2.herokuapp.com/ page, on any branch.

**[Steps to reproduce]:**
1. Click the “Sign In” button from the header.
2. Complete the sign in process.
3. Click the Profile button from the header.
4. Click the “Sign Out” button.
5. After you are redirected, observe the homepage.

**[Expected results]:**
-  The same branch homepage is displayed.

**[Actual results]:**
- A random branch homepage is displayed. 

**[Notes]:**
- This issue is reproducible for all the branches, whether randomly assigned or accessed using the “?experimentBranch=`branch`” query string (Where `branch` can be “va”, “vb” or “vc”)
- Refreshing the homepage after signing out will sometimes change the page to yet another branch.
- This issue is reproducible regardless of the sign-in path used.
- Attached is a recording of the issue. 
![branch changing](https://user-images.githubusercontent.com/53752296/77422170-b75cdf00-6dd5-11ea-930e-82654fd1e7d9.gif)

**Comment by maxxcrawford** [comment]
@heres-maria I have a fix for this in place. Please verify on the [test site](https://monitor-v2.herokuapp.com/).

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible using Firefox Release 74.0 Build ID 20200309095159 and Chrome  v. 80.0.3987.149 on Windows 10 (x64) as well as Firefox Preview 4.1.0 Build #20771637 on Android 10 (Motorola One Vision).
The right branch homepage is now accessed at account logout. 
As a result, I am closing this issue.
