### ISSUE TITLE
[Experiment] The wrong email is pre-filled when performing a breach search with the checkbox ticked after account logout/another breach search

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1613]
**[Affected Versions]:**
- Google Chrome version 80.0.3987.149 (x64)
- Firefox Release 74.0, Build ID 20200309095159
- Firefox Preview (Fenix) 4.1.0 Build #207711637

**[Affected Platforms]:**
- Windows 10 (x64) 
- Android 10 (Motorola One Vision)

**[Prerequisites]:**
- You are on [Branch C: Opt In](https://monitor-v2.herokuapp.com/?experimentBranch=vc).
- You have signed into an account.

**[Steps to reproduce]:**
1. Click the Profile button from the header.
2. Click the “Sign Out” button.
3. Enter a different email in the “Enter Email Address” field.
4. Click “Check for Breaches”.
5. Observe the email address that has been pre-filled.

**[Expected results]:**
-  The email used for the breach search has been pre-filled.

**[Actual results]:**
- The last email used for sign-in is pre-filled.

**[Notes]:**
- This issue is also reproducible for [Branch B: Opt In](https://monitor-v2.herokuapp.com/?experimentBranch=vb).
- This issue is also reproducible after having performed a breach search with the checkbox unticked.
- This issue is reproducible regardless of the sign-in path used.
- Possibly related to issues #1608 and #1609.
- Attached is a recording of the issue.

![wrong pre-filled email](https://user-images.githubusercontent.com/53752296/77449594-ca35da80-6dfa-11ea-8a1d-50aa16a51fb3.gif)

**Comment by maxxcrawford** [comment]
@heres-maria This has been fixed. Please verify on the [test site](https://monitor-v2.herokuapp.com/?experimentBranch=vc).

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible using Firefox Release 74.0 Build ID 20200309095159 and Chrome  v. 80.0.3987.149 on Windows 10 (x64) as well as Firefox Preview 4.1.0 Build #20771637 on Android 10 (Motorola One Vision).
The right email is prefilled even after logout or another breach search.
As a result, I am closing this issue.
