### ISSUE TITLE
[Experiment][Intermittent][iOS] The “Invalid parameter:metricsContext.utmSource” error is displayed on the “Create Firefox Account” page when trying to create an account from the branch C opt-out page

### ISSUE THREAD

**Issue by srosu** [mozilla/blurts-server#1617]
[Affected versions]:
 - Firefox 23 

[Affected Platforms]:
 - iOS 13.3.1

[Prerequisites]:
 - Have the Firefox app installed.

[Steps to reproduce]:
1. Open the Firefox app.
2. Navigate to the “https://monitor-v2.herokuapp.com/?experimentBranch=vc” page.
3. Enter a valid email address in the "Email" field that is not associated with an existing account. 
4. Click the "Check for breaches" button.
5. Fill the three mandatory fields with valid data and click the "Create Account" button.

[Expected result]:
 - The “Enter verification code” page is displayed.

[Actual result]:
 - An “Invalid parameter:metricsContext.utmSource” error is displayed.

[Notes]:
- This issue is also reproducible when changing the email with another new email or an existing account.
- I was able to reproduce this issue 2 times from 3 attempts.
- Attached a screenshot of the issue.

![FXA_ErrorMessage](https://user-images.githubusercontent.com/51699965/77550687-12680200-6eba-11ea-833e-f7907c54bdae.jpeg)

**Comment by maxxcrawford** [comment]
I was having issues reproducing this – I was using an emulator (on MacOS) and was able to create three new accounts without issue.

**Comment by srosu** [comment]
I have tried to reproduce this issue 10 times, but I haven't been able to reproduce it anymore. Maybe it had the same root cause as another issue logged and it was fixed along the way with it.
- Testing was performed using Firefox 23 on IOS 13.3.1.
