### ISSUE TITLE
Add server tests

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#162]
I think we had some old Sequelize-based tests, but those got lost in the Knex+Objection cutover. It'd be nice to have some level of automated testing to make sure we aren't breaking any functionality.

https://github.com/mozilla/blurts-server/blob/f8acf17bd556341196bb2cada8d08006eb5241f9/tests/test-user.js#L4-L10

**Comment by pdehaan** [comment]
@groovecoder We now have some tests (and coverage reports), can we close this?

**Comment by groovecoder** [comment]
Yes, that's fair. We'll improve coverage on an on-going basis.
