### ISSUE TITLE
[Mobile] The “Menu” dropdown is not dismissed when tapping outside of it

### ISSUE THREAD

**Issue by srosu** [mozilla/blurts-server#1621]
[Affected versions]:
 - Firefox 23 for IOS
 - Firefox 68.6.0 for Android
 - Firefox Preview 4.1.0 for Android

[Affected Platforms]:
 - IOS 13.3.1
 - Android 10 (Motorola One Vision)
 - Android 9  (Samsung Galaxy S8) 

[Prerequisites]:
- Have the Firefox app installed.

[Steps to reproduce]:
1. Open the Firefox app.
2. Navigate to the "monitor.firefox.com" page.
3. Tap on the “Menu” button. 
4. Tap outside of it and observe what happens.

[Expected result]:
 - The “Menu” dropdown is dismissed.

[Actual result]:
 - The “Menu” dropdown is still expanded.

[Notes]:
- Attached a [screen recording](https://drive.google.com/open?id=1yNevRXfMyYKlF2tvNjZm_Tu8m1NU6895) with the issue.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
