### ISSUE TITLE
[Mobile] The “Must be a valid email” tooltip is still displayed after pasting a valid email inside the email field 

### ISSUE THREAD

**Issue by srosu** [mozilla/blurts-server#1622]
[Affected versions]:
 - Firefox 23 for IOS
 - Firefox 68.6.0 for Android
 - Firefox Preview 4.1.0 for Android

[Affected Platforms]:
 - IOS 13.3.1
 - Android 10 (Motorola One Vision)
 - Android 9  (Samsung Galaxy S8) 

[Prerequisites]:
- Have the Firefox app installed.
- Have a valid email copied to the clipboard.

[Steps to reproduce]:
1. Open the Firefox app.
2. Navigate to the "monitor.firefox.com" page.
3. Type an invalid email inside the Email field.
4. Click on the “Check for Breaches” button.
5. Select the invalid email and paste the copied valid email from prerequisites.
5. Observe what happens.

[Expected result]:
 - The tooltip is no longer displayed.

[Actual result]:
 - The “Must be a valid email” tooltip is still displayed 

[Notes]:
- Attached a [screen recording](https://drive.google.com/open?id=1gVEfCuifDlKMDXNX_m0Vb_8Epq_d1-Bb) with the issue.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
