### ISSUE TITLE
The “monitor.firefox.com” page is refreshed when clicking on the right side of the logo 

### ISSUE THREAD

**Issue by srosu** [mozilla/blurts-server#1623]
[Affected versions]:
 - Firefox Release 74.0 (Build ID: 20200309095159)
 - Chrome 80.0.3987.149
 - Firefox 23 for IOS
 - Firefox 68.6.0 for Android
 - Firefox Preview 4.1.0 for Android

[Affected Platforms]:
 - Windows 10 x64
 - IOS 13.3.1
 - Android 10 (Motorola One Vision)
 - Android 9  (Samsung Galaxy S8) 

[Prerequisites]:
 - Have the Firefox browser installed.

[Steps to reproduce]:
1. Open the Firefox browser.
2. Navigate to the “monito.firefox.com” page.
3. Click on the right side of the logo.
4. Observe what happens.

[Expected result]:
 - Nothing happens.

[Actual result]:
 - The page is refreshed.

[Notes]:
- The issue is reproducible on desktop and mobile devices.
- Attached a [screen recording](https://drive.google.com/open?id=1YI9XGh3IiPlTwZbKxx-n50hHHAv6v7va) with the issue.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
