### ISSUE TITLE
Add icon/code for Firefox monitor to work with Safari ‘add to home screen’ function

### ISSUE THREAD

**Issue by OddHouseGames** [mozilla/blurts-server#1628]
Firefox Monitor is missing an icon that allows iOS users to add to home screen to appear like a native app. (Currently the icon just lookS like a string of text.)

FireFox Send is setup correctly, and it would be great to have FireFox monitor app on my iOS too because I love the way all the apps are presented in a dashboard.

Ideally I would always prefer to work in Firefox, but until links are added in Firefox iOS to Send and Monitor (similar to how desktop is now) Having these links/apps close at hand is a great work around until that time.

Proposed Process:

- Update line of code and icon on Firefox Monitor website to allow for proper use of Safari ‘Add to home screen’ function.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
