### ISSUE TITLE
Changing Firefox account email cleared my Firefox Monitor data

### ISSUE THREAD

**Issue by OddHouseGames** [mozilla/blurts-server#1629]
I updated my email address for my Firefox account and when I logged into Firefox Monitor using updated credentials, all my previous data was gone.

**Comment by shepswitcher** [comment]
I recently experienced the same problem. Now 6 of the emails/aliases can't be verified as I no longer have access to those accounts. Guess there's no way to know if there are breaches on any old accounts using those addresses now? 
I tried changing my email back to the last primary email I had and while they didn't get wiped this time, the old addresses were still gone

**Comment by ceiphr** [comment]
Same issue here. This should be high priority.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
