### ISSUE TITLE
[Experiment] Missing email field in the treatment branch after navigating to the “Latest Breach Added” page

### ISSUE THREAD

**Issue by Martin-Robert** [mozilla/blurts-server#1644]
**[Affected Versions]:**
- Firefox Release 75.0, Build ID 20200403170909
- Firefox Beta 76.0b5 Build ID 20200415234430
- Firefox Nightly 77.0a1 Build ID 20200415103

**[Affected Platforms]:**
- Windows 10 (x64)
- Mac 10.15
- Linux Mint 19.2

**[Prerequisites]:**
- https://monitor-v2.herokuapp.com/?experimentBranch=vb page is opened

**[Steps to reproduce]:**
- Click the “See if you were in this breach” link from the “LATEST BREACH ADDED” section.
- Observe the page.
- Press the “Find Out” button.

**[Expected results]:**
- Step 2 - The “Enter Email Address” field is displayed above the “Find Out” button.
- Step 3 - The “Must be a valid email.” message is displayed.

**[Actual results]:**
- Step 2 - The “Enter Your Address” field is not displayed.
- Step 3 - Nothing happens if the “Find out” button is pressed.

**[Notes]:**
- This issue only randomly reproduces if the “See if you were in this breach” text link is opened in a New Private Window.
- This issue is not reproducible on the control https://monitor-v2.herokuapp.com/?experimentBranch=va page.
- Attached is a recording of the issue.

![2020-04-16_15h55_32](https://user-images.githubusercontent.com/55738964/79466580-71c2b900-8005-11ea-86a8-02adbfc4276b.gif)

**Comment by maxxcrawford** [comment]
Confirming expected behavior with @changecourse. We're discussing two possible paths and I have fixes for both. We'll comment back with further expectations and I'll code it to those requirements. 

- Path A – As described above. 
- Path B – The button opens the same OAuth flow as the homepage button.

**Comment by maxxcrawford** [comment]
When on the treatment branch, it should now look like: 

![image](https://user-images.githubusercontent.com/2692333/79919768-a2836380-83f4-11ea-95a2-ade8a0b86b37.png)

**Comment by Martin-Robert** [comment]
I have verified that clicking/tapping the “Find Out” button starts the same OAuth flow as the “Get Started” button from the homepage by using Firefox Release 75 (Build ID:20200403170909), Firefox Beta 76.0b7 (Build ID:20200421231527), Firefox Nightly 77.0a1 (Build ID:20200420214939), Firefox for iOS 24.1 (17574), Firefox 68.7.0 (fennec), Firefox Preview 4.2.1 (Build #20941431) and latest Google Chrome (Version 81.0.4044.113 Official Build) on Windows 10 x64, macOS 10.15, Linux Mint 19.2, Android 9, Android 10, iOS 12.4.5.

I am closing this issue as a result.
