### ISSUE TITLE
[Experiment] The Homepage FxA Experiment is active on locales other than en-US

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1651]
**[Affected Versions]:**
- All desktop
- All Android Firefox
- Partially Firefox for iOS 24.1

**[Affected Platforms]:**
- All 

**[Prerequisites]:**
- You are using a Firefox desktop build other than en-US (e.g. de, en-CA) in its default state.
OR
- You are using Chrome, Safari or Edge (desktop) set to a language other than English (US) or English (e.g. German).
OR
- You are using a Firefox for Android browser on a device set to a language-region pair other than English-US (e.g. German-Italy).

**[Steps to reproduce]:**
1. Go to https://monitor-v2.herokuapp.com/?experimentBranch=vb.
2. Observe the page.

**[Expected results]:**
- The experiment is not active.

**[Actual results]:**
- The experiment is active and the treatment page is displayed.

**[Notes]:**
- The Inspector tool displays `data-experiment=”vb”`.
- This issue is also reproducible for the [control branch](https://monitor-v2.herokuapp.com/?experimentBranch=va).
- This issue is not reproducible on iOS 12.4.5 (iPhone 5S) using Firefox for iOS 24.1 (the French-France, German-Romania and Romanian-US language-region combinations were used to test this), though the experiment is entered if the language chosen is a non-US version of English or an English(US)-non-US language-region combination.
![experiment de](https://user-images.githubusercontent.com/53752296/79867622-4d8d2080-83e7-11ea-8a2a-66582d830249.png)

**Comment by maxxcrawford** [comment]
Please verify. We revised the logic to show to users who have selected English as an acceptable language. As long as the user has an English version set, they can be enrolled. 

### Should work: 
![image](https://user-images.githubusercontent.com/2692333/79879199-fe79c800-83b3-11ea-9507-16cac073df71.png)

![image](https://user-images.githubusercontent.com/2692333/79879718-b1e2bc80-83b4-11ea-8c43-76cc38cd495e.png)

### Should not work: 
![image](https://user-images.githubusercontent.com/2692333/79879712-b018f900-83b4-11ea-9477-b242bf96b7d8.png)

**Comment by heres-maria** [comment]
I have verified this issue and it is still partially reproducible.
The issue is no longer reproducible on Windows 10 (x64) using google Chrome v. 81.0.4044.113 and Edge v. 81.0.416.58.
The issue is still reproducible on Firefox Beta 76.0b6 Build ID 20200420031429 as long as the list of languages contains English, even if it not selected as the first language.  
The issue is still reproducible on Android 10 (Motorola One Vision) using Firefox 68.0.7.

**Comment by heres-maria** [comment]
After retesting on Windows 10 (x64) using google Chrome v. 81.0.4044.113 and Edge v. 81.0.416.58, the issue is still reproducible if English (regardless of region) is on the "Preferred languages" list (with a non-English language in the first place on the list)

**Comment by maxxcrawford** [comment]
@heres-maria We added a fix. There's new logic in place that now only enrolls users if they have a English variant language set as their FIRST requested language. Even if they have English as the secondary/fall back image, they will not be enrolled in the study. They aren't enrolled even if they were to use the URL query (`?experimentBranch=vb`). If for some reason their browser doesn't send `Accept-Language` ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)) in the HTTP Header, we don't enroll them.

**Expectations TLDR: Users are only enrolled in the experiment if they have an English language set as the primary/default language.** 

## Testing Steps: 
1. Reset/create clean profile on browser/device
1. Set language/locale to English/US 
1. Navigate to https://monitor-v2.herokuapp.com/?experimentBranch=vb 
1. **Expected results:**  No email field, clicking "Get started" button to start FxA/OAuth flow. 
1. Go app settings (or OS settings where applicable) and change language to Spanish (Non-EN). If there is an order, move that language to the TOP of the list. 
1. Close/restart app (or OS) 
1. Open browser, create NEW tab and navigate tohttps://monitor-v2.herokuapp.com/?experimentBranch=vb.
1. **Expected results:**  Email field **visible**, not enrolled in experiment. Blue button should say "Check for Breaches" in preferred/set language. _(Not English, unless language not localized)_ 

### Verified Browser List

I verified the fix on the following browser/devices using the testing steps listed above.

- Mobile
  - Android 10/Firefox 68
  - Android 10/Chrome 81
  - iOS 13.3/Safari (Required OS setting change)

- Desktop (All completed under Mac OSX 14/Mojave)
  - Firefox 77/Nightly 
  - Firefox 75 (Release) 
  - Chrome 81 (Release)
  - Safari 13.1 (Required OS setting change)

Please verify!

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible. Users using a variant of English regardless of region are enrolled in the experiment, while users using any other language will not be enrolled regardless of region and the UI will not be affected.
Tessted on Android 9 and 10 - Firefox 68.7.0, Firefox Preview 4.3.0, iOS 12.4.5 - Firefox 24.1, Windows 10 - Firefox Release 75,  Firefox Beta 76.0b7, Chrome 81.0.4044.122,  Linux Mint 19.2 - Firefox Release 75 and Mac - Firefox Beta 76.0b7 and Safari 13.0.2.
As a result I am closing this issue.
