### ISSUE TITLE
POST https://fx-breach-alerts.herokuapp.com/__cspreport__ 404 (Not Found)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#166]
### Steps to reproduce:
1. Go to https://fx-breach-alerts.herokuapp.com/__version__ (in Google Chrome, can't repro in Firefox)
1. Open devtools console 

### Actual results:
```
POST https://fx-breach-alerts.herokuapp.com/__cspreport__ 404 (Not Found)
```

**Comment by Micheletto** [comment]
> POST https://fx-breach-alerts.herokuapp.com/__cspreport__ 404 (Not Found)

Typically we handle this inside of the Nginx configuration for our apps.

**Comment by pdehaan** [comment]
Closing this as "ain't no thing once we move to AWS". Thanks @Micheletto! ❤️
