### ISSUE TITLE
The latest breach added box content slightly changes position on hover in Firefox

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [mozilla/blurts-server#1662]
**[Affected Versions]:**
- Firefox Release 75 (Build ID 20200403170909)
- Firefox Beta 76.0b8 (Build ID 20200421231527)
- Firefox Nightly 77.0a1 (Build ID 20200423214309)

**[Affected Platforms]:**
- Windows 10 (x64)
- Linux Mint 19.2
- macOS 10.15

**[Prerequisites]:**
- You are on https://blurts-server-review.herokuapp.com/
OR
- You are on https://monitor-v2.herokuapp.com/
OR
- You are on https://monitor.firefox.com/

**[Steps to reproduce]:**
1. Slowly hover the content of the “LATEST BREACH ADDED” box.

**[Expected results]:**
- The content keeps its position when hovered.

**[Actual results]:**
- The content slightly changes its position when hovered.

**[Note]:**
- This issue is reproducible on all of the available Monitor pages, including in production.
- This issue is not reproducible on Google Chrome 81.0.4044.122, Microsoft Edge 81.0.416.64, Safari 13.0.2, Firefox for iOS 24.1 or Android Firefox (Fennec) 67.7.0.

![content position](https://user-images.githubusercontent.com/53752296/80198670-17d77a00-8629-11ea-8bb1-51ef9a47b54d.gif)

**Comment by maxxcrawford** [comment]
@lesleyjanenorton This issue was found by PI during testing for one of the growth team experiments, but applies across the board.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
