### ISSUE TITLE
Add check-box for Firefox Account on the Monitor homepage

### ISSUE THREAD

**Issue by winstonbowden** [mozilla/blurts-server#1665]
Graduate Monitor Experiment 1 - Issue #1587 

![Screen Shot 2020-05-04 at 9 55 08 AM](https://user-images.githubusercontent.com/6164801/80986191-76e97b80-8ded-11ea-8164-a28a49538ac8.png)

**Comment by maxxcrawford** [comment]
- Copy will need to be localized

**Comment by winstonbowden** [comment]
EN only for now.

**Comment by changecourse** [comment]
@betsymi would you be willing to do a drive-by review of the string associated with the checkbox? This string ran for our experiment 1 already, and thus we didn't do a formal review, but since the data came back positively, we're wanting to do our due diligence now.

**Comment by betsymi** [comment]
> @betsymi would you be willing to do a drive-by review of the string associated with the checkbox? This string ran for our experiment 1 already, and thus we didn't do a formal review, but since the data came back positively, we're wanting to do our due diligence now.

Sure, thanks for asking. Has legal had eyes on it as well? Are you asking for me to comment my drive-by string, right here in this thread? Or do I need to put it somewhere else?

**Comment by changecourse** [comment]
Legal has approved it (correct @winstonbowden?) 

Right here on this thread is perfect, and I can work with the team from there.

**Comment by winstonbowden** [comment]
Thanks for asking about legal. They did have a request, which is call it out as a "known" breach.  Something like this:
Stay Safe: get automated alerts when we know about an account breach.

**Comment by changecourse** [comment]
Updated string from @betsymi 

>Get email alerts when your info appears in a known breach

@winstonbowden let's discuss whether or not we need to re-run vs. moving forward with this. IMHO, I don't think we're at risk to limit impact with this string vs. our original experiment string, with regards to impact/growth.

**Comment by winstonbowden** [comment]
@changecourse thanks! I'm good with the proposed string as long as we keep "Stay safe" in front of it.

**Comment by changecourse** [comment]
"Final" string: 
Stay safe: get email alerts when your info appears in a known breach

![Screen Shot 2020-05-04 at 9 13 37 AM](https://user-images.githubusercontent.com/6164801/80981740-9bdaf000-8de7-11ea-8104-0475c80c64d6.png)

Ready for graduation, @winstonbowden @maxxcrawford

**Comment by maxxcrawford** [comment]
The string is now in `master` and will get localized.
