### ISSUE TITLE
Exception in the monitoring dashboard

### ISSUE THREAD

**Issue by NedkoHristov** [mozilla/blurts-server#1666]
I'm logging-in with valid credentials in https://monitor.firefox.com, when redirected to the Dashboard I receive exception - `Cannot read property 'includes' of undefined`.

Screenshot attached.

Firefox - latest
OS - Windows 10, Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/5328274/80354700-c2e17100-887f-11ea-81e1-036d1efb9d2a.png)

**Comment by groovecoder** [comment]
Do you have cookies disabled?

Is your browser "accept language" setting empty?

**Comment by NedkoHristov** [comment]
@groovecoder:
* My cookies are enabled (but I've deleted all cookies and tried to log-in again (+ cache));
* Accept language is empty.

NB - Since I'm logged-in in my Firefox account I login in https://monitor.firefox.com/ with just the "Sign-In button".

**Comment by NedkoHristov** [comment]
I've rechecked and the issue is not reproducible anymore.

Thanks, @groovecoder 🍻
