### ISSUE TITLE
Exception in /protect-my-email

### ISSUE THREAD

**Issue by jens1o** [mozilla/blurts-server#1668]
Navigating to https://monitor.firefox.com/protect-my-email results into the following error:

```
Error:
Failed to lookup view "private-relay" in views directory "/app/views"
```

![image demonstrating the error message](https://user-images.githubusercontent.com/11234139/80501715-0b785780-8970-11ea-8640-7edcbfe68396.png)

**Comment by groovecoder** [comment]
Sorry, I forgot we removed this and I sent some folks to this url to join the relay waitlist.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
