### ISSUE TITLE
Ignore email tags

### ISSUE THREAD

**Issue by fefas** [mozilla/blurts-server#1676]
Hi,

I use to add tags for registering to a website (for example me+service-a@domain.com or me+service-b@domain.com), but I still have only one email (me@domain.com).

That means it becomes hard to me to use Firefox Monitor since I would need to inform all tagged email addresses I have over the web. That is why it would be quite a feature if the monitoring would ignore the tag part of the email address.

So, my question is: would it make sense or be possible to implement?

Thanks

**Comment by fefas** [comment]
Just to give an example to make my question clear:

I should be notified in case I have the email me@mydomain being monitored and there is a leak where the email me+service-a@mydomain is exposed.

**Comment by bbagnall** [comment]
It looks like it's not currently possible to search for emails that differ only by their plus alias. Firefox Monitor is currently using the first few characters of the hash of your address https://github.com/mozilla/blurts-server/blob/492d4a95e15c649229204c2c3c5c69a50ed57c7a/hibp.js#L109-L112

The [Have I Been Pwned (HIBP) API ](https://haveibeenpwned.com/API/v3) doesn't currently support it, but it has been [requested](https://haveibeenpwned.uservoice.com/forums/275398-general/suggestions/6774229-enable-search-and-notifications-for-email-addresse) and it sounds like it's planned to eventually be implemented.

If you happen to be using a custom domain for your email, they do offer searching/notifying by domain. https://haveibeenpwned.com/DomainSearch

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
