### ISSUE TITLE
Localize all the things?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#168]
I'm guessing we'll be en-US only for Shield launch, but not sure how final a lot of the strings currently are, and if we want to try and get them localized sooner rather than later [assuming we want to support more locales in subsequent server releases].

Which also brings up an interesting point on how we would potentially localize emails in the future (meaning we'd have to capture the user's preferred locale when we get their email address).

**Comment by lesleyjanenorton** [comment]
Localized in #543 and #539
