### ISSUE TITLE
The hover effect cuts the text when hovering the “Security Tips” and the “Breaches” links if the strings are rendered on 2 rows on resizing

### ISSUE THREAD

**Issue by SoftVision-SimonaRosu** [mozilla/blurts-server#1682]
[Affected versions]:
- Firefox Beta 77.0b2 (Build ID: 20200505174119)
- Firefox Nightly 78.0a1(Build ID: 20200505213825)
- Firefox Release 76 (Build ID: 20200429185419)

[Affected Platforms]:
- Windows 10 x64
- Mac 10.15 
- Linux Mint 19.2 Tina

[Prerequisites]:
- Have the Firefox fr build installed.

[Steps to reproduce]:
1. Open the Firefox browser.
2. Navigate to the “monitor.firefox.com” page. 
3. Resize the browser until the “Security Tips” and the “Breaches” links are rendered on two rows.
4. Hover the links and observe the behavior.

[Expected result]:
 - The hover effect is correctly displayed.

[Actual result]:
 - The hover effect is wrongly displayed.

[Notes]:
- I was able to reproduce this issue on the following builds that I have tested so far: fr, ja, es-ES, and ru.
- Also, this issue is not reproducible on the en-US and en-GB builds.
- Attached a screen recording with the issue.

![wronglyHoverEffect_FirefoxMonitor](https://user-images.githubusercontent.com/50919288/81190715-de0b5980-8fc0-11ea-8393-622c56ee6c6b.gif)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
