### ISSUE TITLE
Performing a breach search with the checkbox ticked will open the Scan Results page instead of the FxA page if en-US or en are not in the website languages list

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1696]
**[Affected Versions]:**
- Firefox Release 76.0.1 (Build ID 20200507114007) 
- Firefox Nightly 78.0a1 (Build ID 20200520033931)
- Firefox Beta 77.0b8 (Build ID 20200519220135)
- Google Chrome 83.0.4103.61
- Firefox Preview 5.0.0
- Firefox for iOS 25.1 

**[Affected Platforms]:**
- All

**[Prerequisites]:**
- You are on https://monitor-v2.herokuapp.com/?experimentBranch=va
- OR You are on https://monitor.firefox.com/
- Desktop: the browser’s list of languages used for displaying websites doesn’t contain en-US or en.
- Mobile: the system’s list(s) of languages-region(s) doesn’t contain English(US) or English.

**[Steps to reproduce]:**
1. Enter an email in the “Enter Email Address” field.
2. Check the checkbox.
2. Click the “Check for Breaches” button.
3. Observe the behavior.

**[Expected results]:**
- The FxA sign-in/create an account page is displayed.

**[Actual results]:**
- The Scan Results page is displayed.

**[Notes]:**
- This issue is not reproducible on Firefox 68.8.1, regardless if the browser is set to follow the system language or is manually set to a language other than en-US or en.
- This issue is reproducible on other browsers on Android and iOS as long as en-US or en are not on the list of web page languages of the system or browser.

**Comment by maxxcrawford** [comment]
A fix for this is up on https://monitor-v2.herokuapp.com. This PR fixes this issue. 

https://github.com/mozilla/blurts-server/pull/1693

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible on https://monitor-v2.herokuapp.com/?experimentBranch=va and https://monitor.firefox.com/ using FF Release 76.0.1 (Windows 10), Google Chrome 81.0.4044.138 (Mint 19.2), Firefox/Fennec 68.8.1 (Android 9), Firefox for iOS 25.1 (iOS 12.4.6). The mobile browsers had the language settings set to follow the system language.

Performing the breach search with the checkbox ticked will now redirect to the correct FxA page.
Additionally, the checkbox is no longer displayed on the homepage or on the latest breach added page regardless if the list of languages used for displaying websites contains en-US or en.
