### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#17]
The README document should link to the API docs and contain detailed instructions for:

* [x] local development
* [x] deployment (to heroku) 
* [ ] contribution

**Comment by groovecoder** [comment]
I can take this one.

**Comment by pdehaan** [comment]
Related: #22 (Add LICENSE file)

**Comment by pdehaan** [comment]
@groovecoder I don't have merge/close permissions to this repo. But this may be completed with your #25 PR.

**Comment by groovecoder** [comment]
Oops. I still need to add more steps for deployment and contribution. I'll keep this open and add those items in a check-list.

**Comment by pdehaan** [comment]
Also, the README references some ominous /test.html URL (on localhost).
This failed for me locally on localhost and on the stage server: https://blurts-server.stage.mozaws.net/test.html

IIRC, this endpoint may have been removed by an earlier commit, and we should probably reword the README.

**Comment by groovecoder** [comment]
Done. We'll update README ongoing.
