### ISSUE TITLE
Logos and text can get misaligned on scan results page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#170]
### Steps to reproduce:
1. Go to https://fx-breach-alerts.herokuapp.com/
1. Enter "test@example.com" and click the Search button.
1. Scroll down to AshleyMadison

### Actual results:
The text for AshleyMadison is indented and not aligned with the other breaches.

![firefox_breach_alerts__scan_results](https://user-images.githubusercontent.com/557895/41130668-b2826b08-6a6c-11e8-82f5-79553f6d1db4.png)

**Comment by pdehaan** [comment]
![firefox_breach_alerts__scan_results_-_mate1](https://user-images.githubusercontent.com/557895/41130760-fdc81f40-6a6c-11e8-894d-025b667b7ea2.png)

**Comment by lesleyjanenorton** [comment]
weird! looking into it right now...

**Comment by lesleyjanenorton** [comment]
<img width="1110" alt="screen shot 2018-06-08 at 9 53 35 am" src="https://user-images.githubusercontent.com/22355127/41164931-f5e798e2-6b01-11e8-9ca5-eeac9336a7ef.png">

**Comment by lesleyjanenorton** [comment]
trying to recreate with no luck. is this still happening on your end?

**Comment by lesleyjanenorton** [comment]
ah wait, I'm on localhost. heroku needs an update.

**Comment by lesleyjanenorton** [comment]
fixed, needed a min-width

**Comment by pdehaan** [comment]
I'm not able to repro on latest Heroku.
I believe this was fixed via #175. Closing.
