### ISSUE TITLE
Add new breach logos

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#1705]
- [Petflow](https://haveibeenpwned.com/PwnedWebsites#PetFlow)
- [Artsy](https://haveibeenpwned.com/PwnedWebsites#Artsy)
- [Lifebear](https://haveibeenpwned.com/PwnedWebsites#Lifebear)
- [Nulled.ch](https://haveibeenpwned.com/PwnedWebsites#NulledCH)

**Comment by maxxcrawford** [comment]
@pdehaan Am I missing any?

**Comment by pdehaan** [comment]
Add missing Covve logo #1697
