### ISSUE TITLE
I10N Homepage FxA Experiment 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#1722]
This experiment is an extension of the already successful EN-only [FxA homepage opt-in experiment](https://github.com/mozilla/blurts-server/issues/1587).

The strings required for this are already merged in [a month ago](https://github.com/mozilla/blurts-server/pull/1681) and have been localized in 27 different language variations. 

Languages (as of Mon, June 1) include: 
Chinese (China, Taiwan), Czech, Dutch, English (Canada, Great Britain), Finnish, French, Frisian, German, Guarani, Hungarian, Italian, Kabyle, Norwegian (Bokmål, Nynorsk), Portuguese (Brazil, Portugal), Slovak, Spanish (Argentina, Chile, Mexico, Spain), Swedish, Ukrainian, Vietnamese, Welsh

**Note - we will only include localization that have been localized. All other languages will not be included in the experiment.**

**Comment by pdehaan** [comment]
Per @maxxcrawford 

> Also, the issue out of sync somewhat. We are only including French and German languages into the experiment.
