### ISSUE TITLE
"Check Firefox Monitor" may lead to a 404 page

### ISSUE THREAD

**Issue by EtienneM** [mozilla/blurts-server#1723]
I visited the Covve website (https://covve.com) and saw the notification from Firefox. Then I clicked on this notification on the "Check Firefox Monitor" button. It leads to this page: https://monitor.firefox.com/?breach=Covve. Which is a 404:

![Screenshot_2020-06-03 Vérifiez si vous êtes concerné·e par une fuite de données](https://user-images.githubusercontent.com/1567651/83634298-91f10c00-a5a2-11ea-8a06-82df8e3a817c.png)

**Comment by groovecoder** [comment]
Thanks for the bug report!

**Comment by pdehaan** [comment]
@EtienneM Thanks again for the bug report. This should be fixed and on the production server if you go to https://monitor.firefox.com/?breach=covve.

**Comment by EtienneM** [comment]
That was a quick fix!! :smile: 

Thanks a lot for the hard work, on this issue and more generally!
