### ISSUE TITLE
Create Experiment Utilities module

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#1738]
Just to cut down on code churn from future experiments ... we could push a lot of this logic up into some kind of `ExperimentUtils.init()` module + call. That way the linter will like it but we won't have to keep adding and removing lines like this. And then `ExperimentUtils.getExperimentBranch()`, `ExperimentUtils.getExperimentFlags()`, etc.

_Originally posted by @groovecoder in https://github.com/mozilla/blurts-server/pull/1726_

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
