### ISSUE TITLE
Link from the scan results to the breach details page(s)?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#174]
### Steps to reproduce:
1. Go to https://fx-breach-alerts.herokuapp.com/
1. Search for "test@example.com"
1. Note that we only say the breach name, date, data, and number of accounts, but not the breach description. 

### Actual results:
Possibly link the breach name from the scan results page to the individual [breach details pages](https://fx-breach-alerts.herokuapp.com/?breach=Kickstarter) so users can read the descriptions of what happened in the breach.

The only immediate downside I can think of, is that there is no easy "back" solution to get back to the list of breaches associated with that email address, so the user may end up searching again and causing some round trip request to the server again (unless we open details in separate tabs, which may get messy).

**Comment by lesleyjanenorton** [comment]
Might be worth running this back up the flag pole since we are no longer going to be displaying descriptive paragraphs about each breach.

**Comment by lesleyjanenorton** [comment]
Done!
