### ISSUE TITLE
The translation is incomplete.

### ISSUE THREAD

**Issue by xiaopangju** [mozilla/blurts-server#1740]
In the case of language set to Chinese, access to some pages shows English (Chinese part only a little bit), I would like to ask why? 
the page link is https://monitor.firefox.com/security-tips#strong-passwords

**Comment by maxxcrawford** [comment]
![image](https://user-images.githubusercontent.com/2692333/84676942-a5ca3580-aef3-11ea-8a33-0c5e59ab6cf4.png)

@lesleyjanenorton @flodolo Looks like portions of the tips page [is not localized](https://github.com/mozilla/blurts-server/blob/master/template-helpers/articles.js#L108). Is this expected?

**Comment by flodolo** [comment]
All the content of tips page is not localized, and that's a very long and old conversation ;-)

So, it's a known problem, and fixing it requires both code changes and discussions.

**Comment by xiaopangju** [comment]
> All the content of tips page is not localized, and that's a very long and old conversation ;-)
> 
> So, it's a known problem, and fixing it requires both code changes and discussions.

Can anyone slove this issue

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
