### ISSUE TITLE
Update VPN and Proxy content

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1766]
VPN is becoming "Mozilla VPN", so let's update the FPN blurb copy to:

Your Internet Protocol address (IP address) can reveal your location and internet service provider. A service like Firefox Private Network hides your IP address and location for Firefox and a service like Mozilla VPN hides your IP address and location for your entire device

(Approved already by Legal and Content)

**Comment by maxxcrawford** [comment]
Looks like this will require localization: 

https://github.com/mozilla/blurts-server/blob/master/locales/en/app.ftl#L14

```
-brand-fpn = Firefox Private Network
```

https://github.com/mozilla/blurts-server/blob/master/locales/en/recommendations.ftl#L60-L67
```
# Recommendation subhead
rec-ip-subhead = Use a service that masks your IP address
# Link title
rec-ip-us-cta = Try { -brand-fpn }
rec-ip-us =
  Your Internet Protocol address (IP address) pinpoints your location 
  and internet service provider. A service like { -brand-fpn } 
  masks your IP address to hide your location.
```

**Comment by groovecoder** [comment]
I tried to start this, but it may need some additional template code & logic to enable 2 CTA's in a promo. @lesleyjanenorton - how hard is that do you think?

**Comment by lesleyjanenorton** [comment]
Not hard but I just need more context: Why the two CTAs in a single promo?

**Comment by groovecoder** [comment]
I believe this is done.
