### ISSUE TITLE
Landing page design broken in Internet Explorer

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/blurts-server#1768]
I was doing some testing in Windows 10 IE11 and followed a link to monitor.firefox.com when I noticed that the landing page design is visually broken.

<img width="1409" alt="Screen Shot 2020-06-29 at 4 36 37 PM" src="https://user-images.githubusercontent.com/30483988/86066522-32621100-ba27-11ea-9510-d4a0c8cefa12.png">
<img width="1409" alt="Screen Shot 2020-06-29 at 4 36 20 PM" src="https://user-images.githubusercontent.com/30483988/86066530-368e2e80-ba27-11ea-95df-1cfc073dae45.png">

**Comment by groovecoder** [comment]
We might fix this, but we might just do what Send does and put up a banner for IE users to upgrade to a modern browser.

**Comment by amychurchwell** [comment]
thanks @groovecoder! :)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
