### ISSUE TITLE
Email Verification Link does not expire after 24 hours

### ISSUE THREAD

**Issue by ghost** [mozilla/blurts-server#1770]
I added one of my emails on May 31. The verification link was received. But I open the link after more than a month, on July 05, and I am able to add the email to my Firefox Monitor account.

This should not happen. The verification link is should **expire** 24 hours after it is sent, and the Dashboard should **allow re-sending** the verification link.

Was this intended? Any reasoning?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
