### ISSUE TITLE
 [Experiment] The User Dashboard CTA is displayed after each email address of an account

### ISSUE THREAD

**Issue by srosu** [mozilla/blurts-server#1818]
[Affected versions]:
- Firefox for IOS 27.0 (18428)
- Firefox for Android 68.10.1
- Firefox Release 78.0.1 (Build ID: 20200630195452)
- Google Chrome 84.0.4147.89

[Affected Platforms]:
-  IOS 13.5.1 (iPhone 7+)
- Android 10 (Motorola One Vision)
- Windows 10 x64

[Prerequisites]:
- Have the Firefox browser installed and opened.
- Have a new Firefox profile.

[Steps to reproduce]:
1. Open the Firefox browser with the profile A from prerequisites and navigate to the “https://monitor-v2.herokuapp.com/?experimentBranch=vb” page. 
2. Sign in to Firefox Monitor using a valid email.
3. Scroll down to the "Want to add another email?" section and add another new email.
4. Refresh the User Dashboard page
5. Observe the email sections from the page.

[Expected result]:
 - The CTA is displayed only under the first email added in the Firefox Monitor.

[Actual result]:
 - The CTA is displayed under each email added in the Firefox Monitor

[Notes]:
- Attached is the screen recording with the issue.

![Multiple_CTA](https://user-images.githubusercontent.com/51699965/88643919-fcb65380-d0ca-11ea-9672-fa03ad8b7b40.gif)

**Comment by maxxcrawford** [comment]
This was a regression when fixing #1800 

Revised: 
![image](https://user-images.githubusercontent.com/2692333/88685560-ac83c500-d0bb-11ea-8241-700cbed48494.png)

**Comment by srosu** [comment]
I have verified this issue and is no longer reproducible.
- The User Dashboard CTA is displayed only under the first email added in the Firefox Monitor.
- Tested using Firefox Nightly 80.0a1 (Linux Mint 19.2, Windows 10), Firefox Beta 79.0 (Windows 10, Linux Mint 19.2), Firefox Release 78.0.2 (Windows 10), Firefox for Android 68.10.1 (Android 10), Firefox for iOS 27.0 (iOS 13.5.1).
