### ISSUE TITLE
 [Experiment] The Share Monitor text field and Copy button are different from the mockups

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1819]
**[Affected Versions]:**
- Firefox Release 78.0.2 (Build ID: 20200708170202)
- Firefox Beta 79.0 (Build ID: 20200720193547)
- Chrome 84.0.4147.89
- Firefox for Android 68.10.1 
- Firefox for iOS 27.0

**[Affected Platforms]:**
- Windows 10
- Linux Mint 19.2
- Android 10
- iOS 12.4.6

**[Prerequisites]:**
- You are on the [Treatment](https://monitor-v2.herokuapp.com/?experimentBranch=vb) branch.

**[Steps to reproduce]:**                                        
1. Click the “Share Monitor” button from the footer.
2. Observe the text field and “Copy” button.

**[Expected results]:**
- The proportions of the text field and button are similar to the ones observable in the mockups.

**[Actual results]:**
- The proportions of the text field and button are different from the ones in the documentation:
    - They are thinner compared to the text they contain.
    - The text of the text field is closer to the left margin.
    - The border-radius is larger.

**[Notes};**
- This is also reproducible for the Specific Message modal.
- The radius of the corners of the field and button on mobile devices also looks larger, while the margins appear correct.
- Attached is a screenshot of the issue.

![padding + radius](https://user-images.githubusercontent.com/53752296/88680824-939a0480-d0f9-11ea-845c-bd9acc168416.png)

**Comment by maxxcrawford** [comment]
Revised: 

<img width="629" alt="image" src="https://user-images.githubusercontent.com/2692333/88684899-f61fe000-d0ba-11ea-8495-e81f0cfb7470.png">

**Comment by heres-maria** [comment]
The issue is no longer reproducible.
The text field and button are now consistent with the mockups. The mobile version now has the text field and the button of different sizes, issue documented in issue #1802.
Tested on Firefox Beta 80.0b1 (Windows 10, Linux Mint 19.2), Firefox Release 79.0 (Windows 10, Linux Mint 19.2), Firefox Nightly (Windows 10, Linux Mint 19.2), Firefox for Android 68.11.0 (Android 10), Firefox for iOS 27.0 (iOS 12.4.6).
As a result, I am closing this issue.
