### ISSUE TITLE
Change "hackers" term

### ISSUE THREAD

**Issue by maxwinkler07** [mozilla/blurts-server#1824]
By now it should be known that hackers do not have a malicious intent. Those who have are called cybercriminals. I know the term hacker is "easier" to use and people already know it, but a product as used as Firefox can have an impact on people who use this software. We should try to use proper language to refer to what we actually want to say, and hacker is not the correct term.

Of course this issue is not of the highest priority but still, it would set a good example for other companies or FOSS to follow. I am willing to submit a PR with translations with the correct term in English, Spanish and German.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
