### ISSUE TITLE
 [Experiment] The text field and Copy button have different sizes on mobile devices

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1825]
**[Affected Versions]:**
- Firefox Beta 80.0b1 (build ID: 20200728204253) 
- Firefox Nightly  81.0a1 (build ID: 20200728213249)
- Firefox Release  79.0  (build ID: 20200720193547)
- Chrome 84.0.4147.105
- Firefox for Android 68.11.0
- Firefox for iOS 27.0

**[Affected Platforms]:**
- Windows 10
- Linux Mint 19.2
- Android 10
- iOS 12.4.6

**[Prerequisites]:**
- You are using a mobile device or a desktop browser window small enough to display the mobile version of the website.
- You are on the [Treatment](https://monitor-v2.herokuapp.com/?experimentBranch=vb) branch.

**[Steps to reproduce]:**                                        
1. Click the “Share Monitor” button from the footer.
2. Observe the text field and the “Copy” button.

**[Expected results]:**
- The button is the same size as the text field.

**[Actual results]:**
- The button and the text field are of different sizes.

**[Notes]:**
- This is also reproducible for the Specific Message modal.
- Attached is a screenshot of the issue.

![mobile](https://user-images.githubusercontent.com/53752296/88793518-97836080-d1a5-11ea-85f9-873fcae2223d.png)

**Comment by maxxcrawford** [comment]
Fixed! 

<img width="445" alt="image" src="https://user-images.githubusercontent.com/2692333/88801318-1dd08000-d16f-11ea-9ee5-4a281fe26ce5.png">

**Comment by heres-maria** [comment]
The issue is no longer reproducible.
The two have been modified to have almost the same dimensions. Using the inspector tool will reveal a slight difference (e.g. 312.59 x 50 vs 312.59 x 48), but it is not observable with the naked eye.
Tested on Firefox for Android 68.11.0 (Android 10), Firefox for iOS 27.0 (iOS 12.4.6), Firefox Beta 80.0b1 (Windows 10, Linux Mint 19.2), Firefox Release 79.0 (Windows 10), Firefox Nightly (Windows 10), Chrome 84.0.4147.105.
As a result, I am closing this issue.
