### ISSUE TITLE
[Experiment] The texts of the Share Modal use the normal line height instead of fixed px

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1838]
**[Affected Versions]:**
- Firefox Release  79.0  (build ID: 20200720193547)
- Firefox Beta 80.0b1 (build ID: 20200728204253)
- Firefox Nightly 81.0a1 (build ID: 20200729213824)
- Chrome 84.0.4147.105

**[Affected Platforms]:**
- Windows 10
- Linux Mint 19.2

**[Prerequisites]:**
- You are on the [Treatment](https://monitor-v2.herokuapp.com/?experimentBranch=vb) branch.
- You have the Inspector devtool open

**[Steps to reproduce]:**                                        
1. Click the “Share Monitor” link from the footer.
2. Observe the line height of the text.

**[Expected results]:**
- The text uses the following line heights:
    - 36 px for the “Share Monitor” title
    - 24 px for the main text
    - 18 px for the text under the text field.

**[Actual results]:**
- The “normal” line height is used.
    
**[Notes]:**
- The issue is reproducible for the Specific Message as well.
- Attached is a recording of the issue.

![line-height](https://user-images.githubusercontent.com/53752296/88945048-28396980-d296-11ea-94f2-eeb247687af3.gif)

**Comment by maxxcrawford** [comment]
Per @changecourse, this can be disregarded.
