### ISSUE TITLE
[Experiment] The maximum height of the modal is smaller than 328 px

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1840]
**[Affected Versions]:**
- Firefox Release  79.0  (build ID: 20200720193547)
- Firefox Beta 80.0b1 (build ID: 20200728204253)
- Firefox Nightly  81.0a1 (build ID: 20200729213824)
- Chrome 84.0.4147.105

**[Affected Platforms]:**
- Windows 10
- Linux Mint 19.2

**[Prerequisites]:**
- You are on the [Treatment](https://monitor-v2.herokuapp.com/?experimentBranch=vb) branch.
- You have the Inspector devtool open.

**[Steps to reproduce]:**                                        
1. Click the “Share Monitor” link from the footer.
2. Observe the size of the modal.

**[Expected results]:**
- The maximum height of the modal is 328px.

**[Actual results]:**
- The maximum height varies, it has been observed as 282.783 on Linux Mint 19.2 and 275.183 on Windows 10 (the same monitor, set on the resolution 1920 x 1080).
    
**[Notes]:**
- The issue is reproducible for the Specific Message as well.
- Attached is a screenshot of the issue.

![modal size](https://user-images.githubusercontent.com/53752296/88945067-3091a480-d296-11ea-8a9d-e6aaec162198.png)

**Comment by maxxcrawford** [comment]
Per @changecourse, this can be disregarded.
