### ISSUE TITLE
[Experiment] The font of the “Share Monitor” title from the modal is too small in the mobile version

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1856]
**[Affected Versions]:**
- Firefox Beta 79.0.0-beta.4
- Firefox for iOS 27.0
- Firefox Nightly 81.0a1 (Build ID 20200802214843)

**[Affected Platforms]:**
- Android 9
- iOS 12.4.6
- Windows 10 

**[Prerequisites]:**
- You are using a mobile device, the Responsive Design Mode of a browser, or have a small enough desktop window that the website is displayed in the mobile version.
- You have the Inspector tool open if available.
- You are on the [Treatment](https://monitor-v2.herokuapp.com/?experimentBranch=vb) branch.

**[Steps to reproduce]:**                                        
1. Click the “Share Monitor” button from the footer.
2. Observe the “Share Monitor” title.

**[Expected results]:**
- The font has a larger size (if the sizes for the mobile version are the same as the ones on desktop -  size 32 px).

**[Actual results]:**
- The font has the size 24 px.

**[Notes]:**
- This is also reproducible for the Specific Message modal.
- Attached are screenshots of the issue.

![title mobile](https://user-images.githubusercontent.com/53752296/89180775-1e1bb180-d59b-11ea-956b-ddcdc4bf90c9.png)
![title mobile font](https://user-images.githubusercontent.com/53752296/89180768-1bb95780-d59b-11ea-838b-bfdc60f4f009.png)

**Comment by maxxcrawford** [comment]
This has been adjusted to `28px`. `32px` breaks into two lines for me on mobile. This gets it closer there. Thanks!

**Comment by heres-maria** [comment]
I have verified that the font size has been changed to 28px. 
Tested using Android 9 - Firefox Beta 79.1.0-beta.1, Firefox Release 79.0.2, iOS 12.4.6 - Firefox 28.0, Windows 10 - Responsive Design Mode (Firefox Release 80.0b4).
As a result, I am closing this issue.
