### ISSUE TITLE
[Experiment] The width of the Copy button is 80 instead of 82

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1857]
**[Affected Versions]:**
- Firefox Nightly 81.0a1 (Build ID 20200802214843)
- Firefox Beta 80.0b2 (Build ID 20200730152159)
- Firefox Release 79.0 (Build ID 20200720193547)
- Chrome  84.0.4147.105

**[Affected Platforms]:**
- Windows 10 
- Linux Mint 19.2

**[Prerequisites]:**
- You have the Inspector tool open.
- You are on the [Treatment](https://monitor-v2.herokuapp.com/?experimentBranch=vb) branch.

**[Steps to reproduce]:**                                        
1. Click the “Share Monitor” button from the footer.
2. Observe the width of the Copy button using the Inspector.

**[Expected results]:**
- The width of the button is 82 px.

**[Actual results]:**
- The width of the button is 80 px.

**[Notes]:**
- This is also reproducible for the Specific Message modal.
- Attached is a screenshot of the issue.

![copy button width comparison](https://user-images.githubusercontent.com/53752296/89181990-6cca4b00-d59d-11ea-9a15-2d03bc1d9734.png)

**Comment by maxxcrawford** [comment]
Marking this as `wonftfix`.
