### ISSUE TITLE
[Experiment] The first line of the Dashboard CTA uses an older version of the string

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1858]
**[Affected Versions]:**
- Firefox Release 79.0 (Build ID 20200720193547)
- Firefox Beta 80.0b2 (Build ID 20200730152159)
- Firefox Nightly 81.0a1 (Build ID 20200802214843)
- Firefox Beta 79.0.0-beta.4
- Firefox for iOS 27.0

**[Affected Platforms]:**
- Windows 10 
- Linux Mint 19.2
- Android 9
- iOS 12.4.6

**[Prerequisites]:**
- You are on the [Treatment](https://monitor-v2.herokuapp.com/?experimentBranch=vb) branch.
- You have signed into a Monitor Fx account.

**[Steps to reproduce]:**                                        
1. Go to the User Dashboard.
2. Observe the first line of the User Dashboard CTA.

**[Expected results]:**
- The text is the new version of the string: "Share Monitor with family and friends".

**[Actual results]:**
- The text is the old version of the string: "Help protect your family and friends".

**[Notes]:**
- Attached is a screenshot of the issue.

![new first line](https://user-images.githubusercontent.com/53752296/89184568-b61c9980-d5a1-11ea-8dc8-93a330f382c0.png)

**Comment by maxxcrawford** [comment]
@heres-maria Spoke to @kiiirby and we're actually gonna go with the current text. (Updating the copy doc to match)
