### ISSUE TITLE
[Experiment] The main text of the General Message modal has the size 550x56.25 px instead of 561x50 px

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1859]
**[Affected Versions]:**
- Firefox Release 79.0 (Build ID 20200720193547)
- Firefox Beta 80.0b2 (Build ID 20200730152159)
- Firefox Nightly 81.0a1 (Build ID 20200802214843)

**[Affected Platforms]:**
- Windows 10 
- Linux Mint 19.2

**[Prerequisites]:**
- You are on the [Treatment](https://monitor-v2.herokuapp.com/?experimentBranch=vb) branch.
- Have the Inspector tool open.

**[Steps to reproduce]:**                                        
1. Click the “Share Monitor” link from the footer.
2. Observe the number of rows of text displayed for the General Message modal.
3. Use the Inspector tool to observe the size of the container of the text.

**[Expected results]:**
- There are only 2 rows of text.
- The container is 561x50 px.

**[Actual results]:**
- There are 3 rows of text.
- The container is 550x56.25 px.

**[Notes]:**
- Attached are screenshots of the issue.

![text cont](https://user-images.githubusercontent.com/53752296/89194691-5a0d4180-d5b0-11ea-8828-5f93324bb928.png)
![3 instead of 2](https://user-images.githubusercontent.com/53752296/89193878-49100080-d5af-11ea-9a51-d53a7beab9b0.png)

**Comment by maxxcrawford** [comment]
Increased max-width to `560px`

**Comment by heres-maria** [comment]
I have verified that the max-width has been changed to 560px.
Tested on Firefox Nightly 81.0a1 (Build ID 20200806033456) (Windows 10, Linux Mint 19.2), Firefox Beta 80.0b4 (Build ID 20200804180257) (Windows 10), Firefox Release 79.0 (Build ID 20200720193547) (Windows 10, Linux Mint 19.2), Chrome 84.0.4147.105 (Windows 10).
As a result, I am closing this issue.
