### ISSUE TITLE
Homepage FxA Checkbox Experiment - All locales

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#1873]
This experiment is a continuation of the already successful EN-only FxA homepage opt-in experiment (#1627 ) and FR/DE experiment. (#1722). 

Notes: 
- This experiment will exclude EN, DE and FR locales. 
- We will only include localization that have been localized. (As listed [here](https://pontoon.mozilla.org/projects/firefox-monitor-website/)) All other languages will not be included in the experiment. 
- Monitor does not currently support RTL languages (#569), so RTL testing is not required.  

The strings required for this are already merged in a back in May (#1681) and have been localized in over 27 different language variations.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
