### ISSUE TITLE
Revise Experiment Branch Setting/Getting Function Names

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#1884]
This function returns `assignedCohort` but we're not assigning that to anything here? If this function is mainly to *set* the experiment for the session, the function should probably be re-named to `setExperimentBranch`?

_Originally posted by @groovecoder in https://github.com/mozilla/blurts-server/pull/1797_

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
