### ISSUE TITLE
refactor `getExperimentFlags` to not need `EXPERIMENTS_ENABLED` as an argument

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#1885]
Could probably refactor `getExperimentFlags` to not need `EXPERIMENTS_ENABLED` as an argument? I.e., just use the value from `AppConstants.EXPERIMENTS_ACTIVE` in `controllers/utils` ?

_Originally posted by @groovecoder in https://github.com/mozilla/blurts-server/pull/1797/files_

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
