### ISSUE TITLE
Not the same number of leaks between Firefox Monitorr and HaveIBeenPwned

### ISSUE THREAD

**Issue by QuentinDouarre** [mozilla/blurts-server#1888]
Hi
I don't have the same number of data leaks between Firefox Monitor and HaveIBeenPwned. I wonder if it does not come from the capital letter in the email address in Firefox Monitor

In Firefox Monitor : 
![image](https://user-images.githubusercontent.com/47181935/90313798-94ab9e00-df0f-11ea-9c68-40bb76b51e62.png)

In HaveIBeenPwned :
![image](https://user-images.githubusercontent.com/47181935/90313802-a1c88d00-df0f-11ea-9af8-1a8a7bf76630.png)

**Comment by QuentinDouarre** [comment]
I have the same problem on another email address when there is no capital letter (my first assumption was therefore wrong)

Firefox Monitor :
![image](https://user-images.githubusercontent.com/47181935/90315626-1eae3380-df1d-11ea-9a1c-1bc37a5ffbbc.png)

HaveIBeenPwned :
![image](https://user-images.githubusercontent.com/47181935/90315639-4ac9b480-df1d-11ea-99d7-df0b45ba40c0.png)

**Comment by pdehaan** [comment]
@QuentinDouarre Yeah, it can be a bit tricky to diagnose without the email address (not that I'm suggesting you post your email address here) and specific breach names, but let's take a shot...

Depending on where you're searching and if you're logged in, etc, you might see differences in results between Monitor and HIBP depending on some additional filtering that Monitor does.

I believe in some places we filter out sensitive breaches, and in other places we might filter out fabricated or unverified results or spam list results with no domains (although the exact logic around when/where escapes me at the moment so I'd either need to dig through the code a lot closer or wait for somebody else to chime in with the details).

https://github.com/mozilla/blurts-server/blob/492d4a95e15c649229204c2c3c5c69a50ed57c7a/hibp.js#L160-L168

HIBP reports my primary email address been in 18 breaches, whereas Monitor says I've been in 15 (in this case whether I'm logged in or not). The 3 results from HIBP that are _not_ in Monitor are:

1. [B2BUSABusinesses](https://haveibeenpwned.com/api/v3/breach/b2busabusinesses)
	- **`Domain: ""`**
	- **`IsVerified: true`**
	- _`IsFabricated: false`_
	- _`IsSensitive: false`_
	- _`IsRetired: false`_
	- **`IsSpamList: true`**
1. [LeadHunter](https://haveibeenpwned.com/api/v3/breach/leadhunter)
	- **`Domain: ""`**
	- **`IsVerified: true`**
	- _`IsFabricated: false`_
	- _`IsSensitive: false`_
	- _`IsRetired: false`_
	- _`IsSpamList: false`_
1. [YouveBeenScraped](https://haveibeenpwned.com/api/v3/breach/youvebeenscraped)
	- **`Domain: ""`**
	- **`IsVerified: true`**
	- _`IsFabricated: false`_
	- _`IsSensitive: false`_
	- _`IsRetired: false`_
	- _`IsSpamList: false`_

The one thing these breaches all seem to have in common is the empty domain name. Only one was a spam list, but not the other two.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
