### ISSUE TITLE
Restrict API access to HTTPS

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#19]

**Comment by nhnt11** [comment]
Hmm, this might not be needed depending on where this gets deployed - if it's behind a reverse proxy that only accepts HTTPS, we're fine. I'll leave this open for now though.

**Comment by groovecoder** [comment]
As part of the [security checklist](https://github.com/mozilla/blurts-server/issues/55), we will restrict all access to HTTPS (with HSTS and HPKP).
