### ISSUE TITLE
 Email field default text appears cut in [es-ES] language

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/blurts-server#1902]
**[Affected Versions]:**
- Firefox Nightly 81.0a1 (Build ID: 20200820212107);
- Firefox Release 79.0.5
- Firefox 28.0;

**[Affected Platforms]**:
- Linux Debian 9;
- Windows 10;
- Android 10 ;
- iOS 12.4.6; 

**[Prerequisites]**:
- Use “es-ES” Latest Nightly build, or set the first language in the list of website languages to be “es”.

**[Steps to reproduce]**:
1. Open the browser with the profile from prerequisites.
2. Go to https://monitor-v2.herokuapp.com/?experimentBranch=vb or https://monitor.firefox.com/
3. Observe the default text from e-mail field;

**[Expected results]**:
- Default text has no display or layout issues.

**[Actual results]**:
- Default text is not wrapped up.

**[Notes]**:
- Reproducing in all pages where the email field appears.
- Reproducing in production also.
- Verified also for “de”, “fr” and “zn-CN” and it is not reproducing.

![defaulttext](https://user-images.githubusercontent.com/15685960/90866828-1cc0f600-e39d-11ea-991e-c9d135575005.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
