### ISSUE TITLE
User Dashboard: Send Verification Link Interaction

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#1914]
When a user clicks "send verification" CTA on the user dashboard, the page is refreshed and loaded from the top not showing in the verification link area that an email was successfully sent. The user needs to scroll down to see that the email was successfully sent. This could be jarring to a user and confusing as well. 

Can we show the "Email Sent!" successfully indicator without refreshing the page and without jumping to the top?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
