### ISSUE TITLE
Search isn't populated after pressing back

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#1926]
Expected Result: 
Search for a breach.
Click on a breach details page.
Press Back.
the Search Bar should still be populated with what was searched. 

Actual Result: 
Search for a breach.
Click on a breach details page.
Press Back.
the Search Bar is empty.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
