### ISSUE TITLE
Add link to GitHub repo in footer?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#193]
It makes the repo a bit more discoverable, shows off our extreme open sourcey-ness, and may be a nice way to get some contributors to the site/service.

**Comment by lesleyjanenorton** [comment]
I like this. Are we linking to both the add on and the server or just the server? Who does this need clearing with?

**Comment by pdehaan** [comment]
Personally I'd just link to the **blurts-server** repo. The README.md doc in this repo has a link to the add-on, if a person is so inclined.

As for permission, maybe @e-pang (since I think he gave guidance on the footer in https://github.com/mozilla/blurts-server/issues/161#issuecomment-395913896)

**Comment by e-pang** [comment]
That sounds good to me! We can add it next to the terms and privacy links.

**Comment by e-pang** [comment]
checking with Michelle with what the string should be

**Comment by pdehaan** [comment]
My vote is to just use the GitHub svg logo (which we’ve done on TestPilot and Firefox Colorand Screenshots site, iirc)

**Comment by lesleyjanenorton** [comment]
:::Casting ballot for logo:::

**Comment by e-pang** [comment]
@pdehaan @lesleyjanenorton good with the icon!  Lesley can you space it to the right of the links? Try it at 20px height. Thanks!

**Comment by lesleyjanenorton** [comment]
@pdehaan @epang yep- sounds good!
