### ISSUE TITLE
Firefox Monitor: Firefox Desktop Doorhanger 

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#1934]
On Firefox Desktop Browser: When a user visits a website for the first time that is in our breach database we present the following doorhanger. This doorhanger is the same for all users regardless if they are signed into firefox accounts/firefox monitor. When you’re signed into firefox monitor, the message feels like marketing and is not contextual. Can we detect if you were or were not in a breach and then show a more contextual message to users that would be more useful in terms of next steps?  

Note: Ensure this is done in a privacy preserving way. 
We need to figure out what to do for sensitive sites to ensure we’re protecting our users. 
<img width="439" alt="Screen Shot 2020-09-10 at 4 52 02 PM" src="https://user-images.githubusercontent.com/42650399/92827969-5aef7b00-f387-11ea-9681-9eec938a98a2.png">

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
