### ISSUE TITLE
Firefox Monitor: Breach Info Card Ordering

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#1935]
### Decision(s)

**XD**

- Sorting breaches by [date added] is a good solution since the breach info cards display [date added]. Breach notifications sent to users via email also display cards with [date added]. Sorting by [date added] attribute is a good paradigm to maintain throughout the Firefox Monitor experience.

### Proposed project plan

**Goal**

- Is ordering breach info cards by [date added] the best way to sort all breaches?

**Additional Context**

- On https://monitor.firefox.com/breaches we surface the breach added date, but the breaches are not sorted by this date. If we are surfacing this date, does it make sense to order the breaches by this date?

**Comment by tcinotto** [comment]
@lesleyjanenorton Hi, what is the current logic for the ordering on https://monitor.firefox.com/breaches?

**Comment by pdehaan** [comment]
Related: #1455

**Comment by tcinotto** [comment]
Just a FYI @lesleyjanenorton has updated this to be ordered by breach added date. But want to confirm from a UX perspective if that makes sense? Or if we should explore when the breach actually occurred date?

**Comment by malqinneh** [comment]
@lesleyjanenorton @tcinotto based on the current breakdown of information in the breach info card; sorting by [date added] makes most sense. We also display [date added] when we notify users of a breach via email.

Website breach info card:
![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/39f29637-5041-47d9-8a45-a61dca1420e8)

Email breach info card:
![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/7df1ce2f-57bd-486e-bd3c-72a98346509d)

**Comment by tcinotto** [comment]
Thanks @malqinneh for looking into this. That makes sense. I just reviewed @lesleyjanenorton's update and looks great! Going to close this.
