### ISSUE TITLE
Streamline 'resolve issue' workflow to decrease number of clicks.

### ISSUE THREAD

**Issue by jeremymeyers** [mozilla/blurts-server#1948]
Currently, marking an issue as "resolved' involves

- going to dashboard
- clicking on issue (or clicking on 'resolve this breach' which does the same thing
- scrolling down to the bottom of the page
- clicking 'mark as resolved'
- clicking 'go to dashboard'.

If one is aiming at resolving multiple issues, this is... a lot of clicks.  Might there be a workflow streamlining implemented?  Being able to mark issues as resolved from the dashboard? Or selecting multiple issues to mark as resolved?

**Comment by tcinotto** [comment]
Thank you for filing this. We are investigating this here: https://github.com/mozilla/blurts-server/issues/1932
