### ISSUE TITLE
Email input rendering above bento menu on mobile

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/blurts-server#1951]
👋 Hey there, I'm building out a version of the bento menu for FXA using the monitor version as my reference.

The email input with id of `#scan-email` is showing up above the bento menu when I switch to mobile in responsive design view. It's covering up the "Made by Mozilla" link

Looks like it could be fixed by bumping down the `z-index` of `.fx-relay-email-input-wrapper` (it's currently set at 99999999999999999) and bumping up the index on `.fx-bento-content-wrapper`.

![](https://user-images.githubusercontent.com/1844554/94509431-3ea26980-01e2-11eb-977a-65e99e790d2c.png)

**Comment by tcinotto** [comment]
Discussed with team. This is a known bug with the firefox relay add-on please see: https://github.com/mozilla/fx-private-relay/issues/525
