### ISSUE TITLE
Implement A/B testing into Firefox Monitor 

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#1952]
To be able to optimize and offer a better experience for our users, implement A/B testing capabilities into Firefox Monitor website. We must ensure that this experience protects users privacy and meets our privacy standards.

**Comment by tcinotto** [comment]
When/if we do move forward with this please reach out to Legal to ensure that all of our documents are updated accordingly.

**Comment by EMMLynch** [comment]
We have tracked this work in another ticket. Closing this out.
