### ISSUE TITLE
In the bento, remove all links to Firefox Lockwise

### ISSUE THREAD

**Issue by marniepw** [mozilla/blurts-server#1953]
On monitor.firefox.com, please remove all links to Firefox Lockwise. 

In the meatball menu, there are links to Firefox Lockwise. Depending on what platform a user is on, different links to the app stores are shown. Please remove any/all of these links from the meatball menu. These apps are no longer supported and we should not be directing users to them.

<img width="294" alt="Screen Shot 2020-10-05 at 11 29 39 AM" src="https://user-images.githubusercontent.com/33703387/95118068-82273700-06fe-11eb-9417-ca795c236ab8.png">

**Comment by tcinotto** [comment]
@lesleyjanenorton Would you be able to help make this change? This would be across anywhere that the Bento menu is shown.

**Comment by groovecoder** [comment]
This change is landed in master.
