### ISSUE TITLE
Remove links to firefox lockwise in "what to do after this breach" 

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#1954]
Related to https://github.com/mozilla/blurts-server/issues/1953 We need to remove mentions to firefox lockwise apps. Example: https://monitor.firefox.com/breach-details/LiveAuctioneers

**Comment by pdehaan** [comment]
💯 
I just came here to report this.
https://github.com/mozilla/blurts-server/search?l=JavaScript&q=lockwise&type=code shows a few places where we mention Lockwise in next steps or promos.

**Comment by tcinotto** [comment]
Thank you @pdehaan!!! @marniepw JFYI to @pdehaan's comment above

**Comment by dougmellon** [comment]
@tcinotto @pdehaan I can work on this today

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
