### ISSUE TITLE
Add FAQ for "missing results" and a link from dashboard

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1963]
When Monitor subscribers [opt out of HIBP public searches](https://haveibeenpwned.com/OptOut), their results will disappear from Monitor too. It's a very small number right now, but we should add an FAQ to [the SUMO page](https://support.mozilla.org/en-US/kb/firefox-monitor-faq#w_how-comprehensive-is-firefox-monitors-breach-database), and a link from a dashboard with empty results like, "My breach results are missing."

We should implement a best-first-attempt now, to address immediate confusion, but we should iterate on this copy/messaging, as there are a few reasons that people may not see breaches ...

* They may have opted out of public searches on HIBP
* We/HIBP don't cover all breaches - e.g., if someone was notified that they were in the Marriott breach, they may be confused as to why Marriott doesn't show up in their Monitor report
* We don't show all breaches - e.g., if someone was in the "Collection #1" breach, they may have received a notification from HIBP but not from us, as we don't show combo-list nor data aggregator breaches

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
