### ISSUE TITLE
Start a concept flow for: "Add a Family member"

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#1965]
In research, we've learned one reason people add more email addresses to Monitor is to monitor their family's addresses. We should prototype a UX flow that encourages people to add family members' addresses.

**Comment by heaversm** [comment]
Spoke with @groovecoder yesterday in further detail about this and wanted to add some additional context and relevant info from our discussion (Luke, feel free to edit or add to this as necessary):

In Monitor currently there is no messaging specifically mentioning family members. For any given Monitor account, you can currently add up to 5 email addresses at which point the ability to add addresses goes away. There is currently no messaging surfaced as to why this ability has gone away. The goal is that

**Comment by heaversm** [comment]
A deck for the potential workflow of this feature [can be found here](https://docs.google.com/presentation/d/1QQaEsUIeDFDWbphjxv0PXcSfQSiJN-Gl_-qQX7CSUw8/edit#slide=id.g9ef87241c5_0_37) and will be presented to the S&P team today (10/29) at 10am PST.

[WIP Figma files can be found here](https://www.figma.com/file/sJhXA6pgckz3b4xEnrxp6K/Family-Sign-Up)

**Comment by heaversm** [comment]
Closing this issue. MVP prototyping continued as part of issue #26.
