### ISSUE TITLE
Add Minted breach logo

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#1970]
https://haveibeenpwned.com/PwnedWebsites#Minted

**Comment by pdehaan** [comment]
Oddly, this doesn't seem to be in Monitor yet.

https://monitor.firefox.com/hibp/breaches
https://haveibeenpwned.com/api/v3/breach/Minted

**Comment by maxxcrawford** [comment]
2fast :monorail:

**Comment by pdehaan** [comment]
@maxxcrawford Yes, but the RSS bot posted in our Slack last night at 10:39pm. So we're at like 11h now. Suspiciously suspicious.
But hey, can't ever go wrong with preemptive logo additions.
