### ISSUE TITLE
Didn't see the notification box when I visited linkedin.com

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#2]
STR:

1. `./package.sh`
2. Run Firefox Nightly 58.0a1 (2017-11-07) (64-bit) Mac
3. In `about:config` set:
  * `xpinstall.signatures.required` to `false`
  * `extensions.legacy.enabled` to `true`
4. In `about:addons`, choose "Install Add-on from File"
5. Select the packaged `BreachAlerts.xpi`
6. Visit linkedin.com

Expected result:

Notification bar with an alert: "You visited hacked site ..."

Actual result:

Nothing is shown

**Comment by nhnt11** [comment]
This is likely because the XHR that downloads the breach list hasn't completed by the time the site loads.

We could implement a queue for sites that are loaded while we're waiting for the XHR and process them when we're ready.

**Comment by groovecoder** [comment]
This doesn't apply anymore? The add-on code is moved elsewhere?

**Comment by nhnt11** [comment]
Yeah, let's close this.
