### ISSUE TITLE
Move to mozilla (or mozilla-services) GitHub org

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#20]

**Comment by groovecoder** [comment]
To enable more Mozillians (like me!) to organize issues into milestones and to help maintain issues & pull requests, we should move this into a mozilla GitHub org.

**Comment by nhnt11** [comment]
I moved it to the mozilla org. Now that I think about it mozilla-services might be better, what do you think?

**Comment by groovecoder** [comment]
Doesn't much matter to me.
