### ISSUE TITLE
Add missing favicon.ico?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#200]
Noticed this while just browsing an asset like http://localhost:6060/img/firefox.png

My DevTools says I have a 404 on POST `/__cspreport__` (which is expected for localhost), and a 404 on GET `/favicon.ico`.

We may want to add a fallback ico file so the 404s don't clutter our logs (or whatever).

@lesleyjanenorton Thoughts?

**Comment by lesleyjanenorton** [comment]
Sounds good! I'll make one and add it to my pile of burnt offerings to the CircleCi Powers That Be.
