### ISSUE TITLE
[Firefox Monitor] "Made by Mozilla" link leads to a locale site

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#2008]
[Affected Platforms]:
- Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.14

[Steps to reproduce]:
1. Navigate to  https://monitor.firefox.com/
2. Click on the Bento Box button.
3. Click on "Made by Mozilla" link. 

[Expected result]:
- The https://mozilla.org/ website is displayed in a new tab.

[Actual result]:
- The https://www.mozilla.org/pl/?utm_campaign=bento&utm_medium=referral&utm_source=fx-monitor is displayed, but in locale language. 

[Regression]:
- N/A

[Additional Notes]:
- Please look at the attached image. 
![Screenshot_4](https://user-images.githubusercontent.com/42799381/104158411-ff490300-53f5-11eb-99a7-5a9590d6df79.png)

**Comment by pdehaan** [comment]
Interesting, mine went to https://www.mozilla.org/en-US/?utm_campaign=bento&utm_medium=referral&utm_source=fx-monitor

I wonder if it's a weird caching issue.

@obotisan Does your link ALWAYS go to the /pl/ locale? (or maybe the better question is, is your browser language/locale set to PL?)

**Comment by flodolo** [comment]
Just saw the issue, and tried out of curiosity: mine went to Persian, while it should have gone to Italian. And it persisted even in private mode.

**Comment by niazally** [comment]
Mine went correctly to the en-US local. @obotisan as @pdehaan mentioned, check the language setting on your browser and operating system.

Also try in incognito mode.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
