### ISSUE TITLE
Add ability to search from /scan page if no breaches were found for an email

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#203]
### Steps to reproduce:
1. Go to https://blurts-server.stage.mozaws.net/ and search for an email address which presumably isn't in the breach results (or a dummy email-esque address). I tried "test@test.ca".
1. Note that it says "So far, so good.", you have a "Sign up for alerts" button that goes to a false door, and then a big tips section at the bottom.
1. Go back to the https://blurts-server.stage.mozaws.net/ and search for an email address which IS in the breach results (like test@example.com).
1. Note that it says "Oh, no! This might be a problem.", the same button to the false door, a "Your Compromised Accounts" section, and a "What to Do" section which includes the ability to scan another email address.

### Expected results:
Ability to scan for another email address from the "So far, so good." flow.
It looks like it may be from within the https://github.com/mozilla/blurts-server/blob/78fa262ac28eb0406558d9d929f7981f3a3b2875/views/scan.hbs template or something. But it may be nice to be able to scan again from the results page without needing to jump back to the home page. 

### Actual results:
A less dead-endy "So far, so good." results page?

**Comment by lesleyjanenorton** [comment]
Yes yes yes. Another form could be easily plugged in below the "So far, so good" blurb, without much effort on anyone's part. Would feel much less dead-endy and much more useful.

**Comment by pdehaan** [comment]
I like it in practice, but not sure if we need designer approval or if we want to delay until post-Shield, given the bug count and limited time (and the fact you are currently _THE_ only licensed Developer on the project). I'm mostly just here for comic relief via Zoidberg GIFs.

![](https://cdn-images-1.medium.com/max/2000/1*wRSOh_u31UIacaIZJ9Nojg.jpeg)

**Comment by groovecoder** [comment]
The "Scan Another Email" section is now displayed under the "No Results" section of /scan. (See https://fx-breach-alerts.herokuapp.com/)
