### ISSUE TITLE
A few files w/ suspect file permissions

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#2030]
Per https://pdehaan.github.io/repo-lint-www/repo/mozilla/blurts-server/

> ### Suspicious permissions
> - .env-dist — 100755; 2.57KB
> - public/fonts/Metropolis/Metropolis-Bold.woff2 — `100755`; 16.34KB
> - public/fonts/Metropolis/Metropolis-Medium.woff2 — `100755`; 16.11KB
> - public/fonts/Metropolis/Metropolis-SemiBold.woff2 — `100755`; 16.19KB
> - public/img/svg/resolution-overlays/another-breach-resolved.svg — `100755`; 5.69KB
> - public/img/svg/resolution-overlays/marked-as-resolved.svg — `100755`; 4.75KB
> - public/img/svg/resolution-overlays/resolved-first-breach.svg — `100755`; 9.75KB

Not sure why any of those files need `755` permissions, but 🤷 .

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Comment by pdehaan** [comment]
LGTM. 
Current status:
```sh
git ls-files -s | grep -Ev "^100644\s"

100755 7082aa4816b83d4a51014d4d1ed94d61814fad9e 0	.circleci/scripts/sync-static
100755 bb816303467ec8d62c8143ffc4e74781e3eb917a 0	.env-dist
100755 d24fdfc601b9ffe8ccc3fca5d3b873109dc56c4a 0	.husky/pre-commit
```
