### ISSUE TITLE
Unsubscribe error invalid csrf token

### ISSUE THREAD

**Issue by carloabelli** [mozilla/blurts-server#2034]
I am trying to unsubscribe from firefox monitor emails. I click the "Unsubscribe" link at the bottom of the page. This takes me to the page https://monitor.firefox.com/user/unsubscribe. I click the "Unsubscribe" button and get an error saying "invalid csrf token".

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
