### ISSUE TITLE
Consider adding SQL Commenter.

### ISSUE THREAD

**Issue by Micheletto** [mozilla/blurts-server#2035]
[SQL Commenter](https://cloud.google.com/blog/topics/developers-practitioners/introducing-sqlcommenter-open-source-orm-auto-instrumentation-library) + [Query Insights](https://cloud.google.com/sql/docs/postgres/insights-overview) would be a great way to diagnose, resolve, and prevent slow queries from cropping up in our production environment.  There is [Knex.js specific instrumentation](https://github.com/google/sqlcommenter/blob/master/nodejs/sqlcommenter-nodejs/packages/sqlcommenter-knex/README.md).

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
