### ISSUE TITLE
6 email addresses monitored in Monitor

### ISSUE THREAD

**Issue by bfyee** [mozilla/blurts-server#2036]
I have 6 email addresses monitored currently despite a limit of 5.  I had 3 email addresses monitored previously and then added 3 more without confirming them.  Then was able to confirm all three to go above the limit.  No ability to add any additional email addresses.

**Comment by Denise611** [comment]
trying to figure out how reliable this is. Intruders on my email leave no trace, and use my IP adderss.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
