### ISSUE TITLE
Breached emails are wrongly marked as "safe" on "Firefox Monitor" page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#204]
Per https://github.com/mozilla/blurts-addon/issues/41

This issue is reproducible regardless if the search was made from the doorhanger of from the "Firefox Monitor" page.

Cross filing here. I can test w/ my email (peter@deseloper.com) from the HIBP site and it shows that my email has been in several "incidents" although the Blurts server says that "Your email address does not appear in our list of compromised accounts."

**Comment by lesleyjanenorton** [comment]
first thought is it's an environment variables issue. are you searching from the heroku or stage site?

**Comment by pdehaan** [comment]
Both https://fx-breach-alerts.herokuapp.com/scan (dev) and https://blurts-server.stage.mozaws.net/scan (stage) say "So far, so good." when searching my email address from their respective homepages.

**Comment by lesleyjanenorton** [comment]
Yep and just recreated on localhost with your email. I'm looking at it right now.

**Comment by lesleyjanenorton** [comment]
Five hours and two kettles of green tea later : sha1Prefix = sha1.slice(0, 6).toUpperCase();

**Comment by groovecoder** [comment]
Hmm ... there seems to be a bug in the hibp.js code either matching the `hashSuffix` or finding the breaches in the `breaches` table.

**Comment by groovecoder** [comment]
looks like @lesleyjanenorton found it!
