### ISSUE TITLE
Disable dependency updater?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#2069]
Not sure anybody is actively watching this repo and merging the PRs.
Might make sense to disable the renovate-bot to save us some PRs and CI churn in the short term.

Thoughts @groovecoder @jrbenny35?

**Comment by groovecoder** [comment]
I'd be happy to disable it. Our `npm audit` in CI will fail for the "high" or "critical" security vulns.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
