### ISSUE TITLE
Breach domain logos can appear "transparent" if on a light/white background

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#208]
https://fx-breach-alerts.herokuapp.com/?breach=AshleyMadison
https://blurts-server.stage.mozaws.net/?breach=AshleyMadison

![firefox_monitor-ashley](https://user-images.githubusercontent.com/557895/41612972-2838d2c0-73a9-11e8-82a9-a3f1eb8e1beb.png)

![firefox_monitor_-_adobe](https://user-images.githubusercontent.com/557895/41613033-5299e2b6-73a9-11e8-8a74-7c35757442ad.png)

**Comment by pdehaan** [comment]
Oh, actually, I think this is due to logos having transparent backgrounds and white contents.
https://fx-breach-alerts.herokuapp.com/?breach=2fast4u

| name | logo | 
|:----|:----|
| 2fast4u | ![](https://fx-breach-alerts.herokuapp.com/img/logos/2fast4u.png) | 
| AshleyMadison | ![](https://fx-breach-alerts.herokuapp.com/img/logos/AshleyMadison.svg) |

**Comment by lesleyjanenorton** [comment]
That is exactly what it is. What is even better is some of them have inline css styling and can get overwritten by each other.

**Comment by pdehaan** [comment]
I'm no designer, but I still think we should float the logos on the right and the name/etc on the left so it doesn't look so bizarre if a logo is essentially "transparent". (although I think we'd need to do the same w/ the blurts-addon repo, https://github.com/mozilla/blurts-addon/issues/15 &mdash; although that issue is slightly different)

**Comment by lesleyjanenorton** [comment]
We can potentially close this. In the new visual specs the background is a considerably darker gradient throughout and the white banner feature is gone.
