### ISSUE TITLE
Add ability to Pin a featured breach?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#2094]
In certain cases, there might be a high-visibility breach that we want to feature on the homepage and not risk having a smaller breach replace it randomly if a new record is added to upstream HIBP.

Not sure if we want to have some "isFeatured" flag somewhere so we can hardcode a specific breach so it sticks on the homepage (if no featured breach is found, we revert back to the same "use latest" logic).

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
