### ISSUE TITLE
Add CSS Cache-busting String

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#2095]
When deploying new CSS, we should add a cache-busting string on the end of the CSS link:
```
<link rel="stylesheet" href="/dist/app.min.css?v=1617991325870">
```

**Comment by groovecoder** [comment]
Could do this by concat, minify, then hash the resulting css file and append the hash as url param.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
