### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla/blurts-server#2096]
Found at https://monitor.firefox.com/remove-my-data:

Incorrect: It’s not available yet, but blick below if you are interested in finding out more.

Correct: It’s not available yet, but click below if you are interested in finding out more.

![Screenshot 2021-04-09 at 22-43-32 Find out if you’ve been part of a data breach](https://user-images.githubusercontent.com/31939113/114243760-12338b00-9985-11eb-97ca-4b64d63dd9e6.png)

**Comment by htwyford** [comment]
I'm still seeing this. Has this fix been deployed yet?
