### ISSUE TITLE
Add Dockerflow standard endpoints

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#21]
I.e., [`/app/version.json` object](https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md) at `/__version__`, `/__heartbeat__`, and `/__lbheartbeat__` as described here:

https://github.com/mozilla-services/Dockerflow#containerized-app-requirements

**Comment by pdehaan** [comment]
This may be a decent enough starting point:

```js
"use strict";

const fs = require("fs");
const path = require("path");
const router = require("express").Router();

let commmit;
try {
  commit = require("git-rev-sync").short();
} catch (err) {
  // ignore
}

const { version, homepage } = require("../package.json");

const versionJsonPath = path.join(__dirname, "..", "public", "version.json");
const versionJson = {
  commit,
  source: homepage,
  version,
};

fs.writeFileSync(versionJsonPath, JSON.stringify(versionJson, null, 2) + "\n");

router.get("/__version__", (req, res) => {
  return res.sendFile(versionJsonPath);
});

router.get("/__heartbeat__", (req, res) => {
  return res.send("OK");
});

router.get("/__lbheartbeat__", (req, res) => {
  return res.send("OK");
});

module.exports = router;
```

This should create a ./public/version.json file which gets generated at startup and then visiting `/__version__` will just return that static file. By wrapping it in a `try..catch`, I _think_ it should also work if the target stage/production server doesn't have Git installed but OPs or somebody manually creates a ./public/version.json file during their build process.

Or, I'm way off and this is just stupid. 🤷‍♀️
