### ISSUE TITLE
Heading and description can get truncated when you have long headings

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#210]
### Steps to reproduce:

1. Go to https://blurts-server.stage.mozaws.net/?breach=CouponMomAndArmorGames
1. Read it.
1. Weep.

### Actual results:

![firefox_monitor](https://user-images.githubusercontent.com/557895/41619321-b123a680-73ba-11e8-9b98-191b8571afb0.png)

**Comment by pdehaan** [comment]
I wrote a little webdriverio scraper which takes screenshots of all the breaches on the server, and I think this only impacts 2 breaches:

1. https://blurts-server.stage.mozaws.net/?breach=CouponMomAndArmorGames
    ![couponmomandarmorgames](https://user-images.githubusercontent.com/557895/41676489-91d7266a-747a-11e8-8c9a-e742a579970d.png)

1. https://blurts-server.stage.mozaws.net/?breach=MinecraftPocketEditionForum
    ![firefox_monitor](https://user-images.githubusercontent.com/557895/41676468-6f6997ca-747a-11e8-9be7-f4c36a6742d3.png)

---

The next widest screenshot was https://blurts-server.stage.mozaws.net/?breach=ModernBusinessSolutions, which doesn't seem to crop any info.

![firefox_monitor](https://user-images.githubusercontent.com/557895/41676587-df1a71e8-747a-11e8-9e13-46afdb3193c1.png)

Interestingly, it looks like the longest `Title` attribute in the breaches.json is ["Telecom Regulatory Authority of India"](https://blurts-server.stage.mozaws.net/?breach=TRAI) but the server only displays "TRAI Breach", and not the actual title.

```js
  {
    "Domain": "trai.gov.in",
    "Title": "Telecom Regulatory Authority of India",
    "BreachDate": "2015-04-27",
    "PwnCount": 107776,
    "DataClasses": ["Email addresses", "Email messages"],
    "LogoFilename": "TRAI.svg"
  },
```

**Comment by pdehaan** [comment]
Actually, here's my repo, and a list of all the element screenshots for each breach (as reported by [**mozilla/blurts-addon** /src/breaches.json](https://github.com/mozilla/blurts-addon/blob/d330ef81b0367cf5f7c888b98d7c33c8cb7bc886/src/breaches.json)): 
https://github.com/pdehaan/blurts-webdriverio/blob/master/README.md

It also gives a good indication of the number of breaches with a white-on-white logo.

**Comment by lesleyjanenorton** [comment]
I think we're going to have to flip the logo and title or figure something else out.

**Comment by pdehaan** [comment]
Whatever we decide, we’ll need to do on add on repo as well. But the add on icons are still stretched and skewed, so those need tweaking regardless.

**Comment by groovecoder** [comment]
Fixed on https://fx-breach-alerts.herokuapp.com/?breach=CouponMomAndArmorGames
