### ISSUE TITLE
Add limit/cap notification to users monitoring more than 5 emails 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#2106]
## Issue

Once a user monitors 5 email address, the form to add additional emails is removed. We need to tell the user that they have reached the maximum amount allowed. 

<img width="460" alt="image" src="https://user-images.githubusercontent.com/2692333/115452199-bc13e280-a1e3-11eb-91b8-148cdaba3281.png">

**Comment by lsm5** [comment]
Hello @maxxcrawford , is there a reason to only allow 5 emails? Does one need to set multiple accounts for more than 5 emails in that case? Alternatively, would it be possible to add a domain / wildcard for alerts?

**Comment by nunesgh** [comment]
I find this new limit quite frustrating and I do not remember being informed about any change. As an early user, I had added 13 e-mail addresses to Firefox Monitor and was unaware of any sort of limitation. Today I went back to the Dashboard hoping to add another e-mail address, but I could not find any way of doing so or any information on (new) limits being imposed.

I understand that allowing users to add 350+ e-mail addresses (as in https://github.com/mozilla/blurts-server/issues/1335) would be a bit too much. But why allow only 5?

**Comment by lsm5** [comment]
@maxxcrawford I'd be happy to pay for unlimited email address support as part of a premium plan like you have for Relay Premium.

**Comment by maxxcrawford** [comment]
Hey everyone! I reached out to the product owner for a response on this and will report back.

There seemed to already be an account cap (15) and then a year ago [it was revised](https://github.com/mozilla/blurts-server/commit/23d6a29bf7c1a0a24391f62da49d18d5ce87c032#diff-782628b47d666d5d551e040815ca3f80c0704397258718f0e0f31164608ea7be) to 5. This bug was filed to help folks understand why the "add another email" disappeared. 

cc/ @groovecoder @tcinotto

**Comment by maxxcrawford** [comment]
As an immediate work-around, I recommend creating a separate FxA account if you need to monitor additional accounts.

However, I would like to note that this request/feature is on our roadmap! I'll post feedback from the product owner when I have an answer.

**Comment by Kn0p3XX** [comment]
Yes, there you can add 5 more e-mail addresses, before the form just disappears. I had it once for 9 e-mails on one account, though.

**Comment by nunesgh** [comment]
Hi, @maxxcrawford!

Thank you for contacting the product owner! Have they replied to you with any additional information on this?

**Comment by SaezSays** [comment]
I have 13 email addresses in Monitor but I can't add more, that's why I find out about the limit of only five accounts. I ask, will there be an increase or will it stay that way?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Comment by SaezSays** [comment]
> Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

Yes, i still thinking this is a necessary function, more accounts to verify, it's possible?
