### ISSUE TITLE
Update VPN Banner language gate.

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#2108]
## Issue
The VPN banner only is shown for users who have their preferred browser language set to English. (locale)

Note - We need to determine the best way to determine if the user should be shown banner (based on language). Specifically, VPN is available by COUNTRY, rather than language. We need to explore privacy-preserving ways to determine country location. 

## Success
- [ ] VPN is shown to the following languages: English, French, German, TBD
- [ ] Selected [language strings](https://github.com/mozilla/blurts-server/blob/main/locales/en/app.ftl#L795-L797) are localized within [Pontoon](https://pontoon.mozilla.org/projects/firefox-monitor-website/)

Banner: 
![image](https://user-images.githubusercontent.com/2692333/115452514-2593f100-a1e4-11eb-8bd1-d645e7e9cce9.png)

**Comment by maxxcrawford** [comment]
@tcinotto Can you confirm which countries/lanugages should be shown this banner?

**Comment by maxxcrawford** [comment]
@groovecoder Any ideas on how to geo-target politely? Here is our [current method for browser-set locale/language](https://github.com/mozilla/blurts-server/blob/main/public/js/monitor.js#L523-L524)

**Comment by tcinotto** [comment]
@maxxcrawford Thanks! In order to gauge interest from users in different locales, I would like to show this banner to all locales **except** for users in the following countries:

- China
- Russia
- Turkey
- Iran
- Iraq
- United Arab Emirates
- Belarus
- Oman 
- Turkmenistan

**Comment by groovecoder** [comment]
Technical limitations only allow to gate by language and not locale. 😢 Please re-open if this becomes a priority and we'll estimate it to compare to other items in the backlog.
