### ISSUE TITLE
Add issue templates to Github

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#2109]
Examples: 
- https://github.com/mozilla/bedrock/tree/master/.github
- https://github.com/mozilla/contain-facebook/tree/master/.github

**Comment by Amod02-prog** [comment]
Hi I would like to work on this issue.

**Comment by Amod02-prog** [comment]
./assign

**Comment by maxxcrawford** [comment]
Resolved by https://github.com/mozilla/blurts-server/pull/2756
