### ISSUE TITLE
Remove adjust.com links

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#2119]
Per https://github.com/mozilla/bedrock/issues/8309#issuecomment-819324507, these links should be replaced. 

https://github.com/mozilla/blurts-server/blob/f24b72e44ec977f352894724148c29357c4c660a/public/js/fx-bento.js#L8

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
