### ISSUE TITLE
"Please enter a valid email" message is not displayed if trying to submit an invalid email by pressing the "Enter" key

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#213]
Via @Softvision-MariusComan in https://github.com/mozilla/blurts-addon/issues/54:

---

**[Affected versions]:**
- Firefox Release 60.0.2
- Firefox Beta 61.0b14

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 20.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "https://fx-breach-alerts.herokuapp.com/" page.
3. Enter an invalid email in the input field.
4. Press the "Enter" key and observe the behavior.

**[Expected result]:**
- The "Please enter a valid email" message is displayed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- This issue is not reproducible if clicking the search button from the right side of the email field.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41658002-c60b7a58-749d-11e8-8001-eec99b65e86e.gif)

**Comment by Softvision-MariusComan** [comment]
I have retested this issue and it seems that it is partially fixed. Now, the invalid email message is displayed after the "Enter/Return" key (from the edge of the alphanumeric part of the keyboard) is pressed, but is not displayed if the "Enter" key from the numpad is pressed.
Considering this, please reopen this issue.
