### ISSUE TITLE
The "Thank you" pop up is not correctly rendered if the browser is resized

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#214]
Via @Softvision-CristinaBadescu in https://github.com/mozilla/blurts-addon/issues/55

---

[Affected versions]:
- Firefox Release 60.0.2
- Firefox Beta 61.0b14
- Firefox Monitor 0.01, All Branches

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Monitor v0.01 (custom built on 2018-06-20) installed.

[Steps to reproduce]:
1. Open the browser and navigate to the "https://fx-breach-alerts.herokuapp.com/" page.
2. Click the "Sign up for alerts" button.
3. Resize the browser to its half height and observe the "Thank you" pop-up.

[Expected result]:
- The pop up is rendered and completely visible.

[Actual result]:
- The pop up is not correctly rendered and the "Close" button is out of sight, even if you scroll down.

[Notes]:
- Here is a screen recording with this issue:
![thanks you pop up](https://user-images.githubusercontent.com/31244235/41668120-4ff69bbc-74b7-11e8-94bb-89351cacac8e.gif)

**Comment by groovecoder** [comment]
The pop-up is gone now.
