### ISSUE TITLE
The "Search" button is wrongly disabled if an email is selected from the autocomplete dropdown using the mouse/trackpad

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-server#218]
**[Affected versions]:**
- Firefox 61.0

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 27.06.2018) installed.
- Have the autocomplete dropdown populated with at least one valid email.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "https://fx-breach-alerts.herokuapp.com/" and focus the Email field.
3. Start writing characters from a previously used valid email.
4. Click the desired email from the autocomplete dropdown.
5. Press the "Enter" key or click the "Search" button and observe the behavior.

**[Expected result]:**
- You are redirected to the results page.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- You are only taken to the results page after pressing the Enter key or clicking the Search button a second time.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41971656-e15e35d2-7a17-11e8-9a7c-3a504b938502.gif)

**Comment by lesleyjanenorton** [comment]
Thanks @Softvision-MariusComan ! We've disabled autocomplete so this should be resolved.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Monitor" add-on (1.0 custom built on 29.06.2018) installed, on the latest Firefox release (61.0). Now, the autocomplete dropdown is no longer displayed.
Verified on Windows 10 x64.
