### ISSUE TITLE
Waitlist Survey Issues

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#2218]
Issue: Survey link is full. 

STR: 

- From my personal account: https://monitor.firefox.com/user/dashboard
- Follow link to: "Remove my data" (https://monitor.firefox.com/remove-my-data) 
- After joining the wait list, I click the "answer a few questions about this service" link (https://survey.alchemer.com/s3/6275633/Data-Removal-Service-Waitlist)  and get redirected to a quota fail
https://s.cint.com/Survey/QuotaFull

<img width="813" alt="image" src="https://user-images.githubusercontent.com/2692333/126512341-04f29734-ceb3-4b83-abb1-7d59666735d1.png">

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
