### ISSUE TITLE
Add Discourse link/logo to footer

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#222]
Per discussion earlier today on Slack... If we end up creating a Discourse channel for Firefox Monitor, it'd be nice to promote it in the site footer for easier discovery.

Similar if we think we want a FirefoxMonitor Twitter account. 🤷‍♀️

**Comment by groovecoder** [comment]
send.firefox.com only has Twitter (FxTestPilot), GitHub, and qsurvey.mozilla.com links. Closing this Discourse-specific issue. We can open a new issue if/when we decide what feedback channel(s) to use.
