### ISSUE TITLE
Add Protocol Base File to CSS chain 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#2225]
Protocol is currently not added to the `app.scss` build chain. We need to turn it on – however, it overwrites some of the other styles. We'll need to adjust all over the site to make sure it maintains current appearances. 

TODO: 
- [ ] Replace color variables with [Protocol colors](https://protocol.mozilla.org/fundamentals/color.html) 
- [ ] Replace spacing variables with [Protocol tokens](https://protocol.mozilla.org/fundamentals/tokens.html) 
- [ ] Replace typography with [Protocol fonts](https://protocol.mozilla.org/fundamentals/typography.html) (See #2223)

## Success: 
- [ ] The site looks the same as it does now but the base Protocol file is loaded into `app.css`

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
