### ISSUE TITLE
Add a banner to Firefox Monitor that educates users about exposed IP addresses

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#2235]
PRD: https://docs.google.com/document/d/1uuOPVRLABRvaG7ofxFTDaRT0BwUFNhVQK4bVFOpXPy8/edit?usp=sharing

**Comment by tcinotto** [comment]
@lesleyjanenorton just wanted to flag you so you're aware of this idea! Feel free to add into the PRD

**Comment by toufali** [comment]
PR #2284 opened. Still outstanding:
- Guardian integration for VPN Protected status
  - test user IP against protected servers
  - fallback when server array is blank or Guardian connection failed
- K8 integration for MaxMind location database
  - City/State/Country review needed for locales outside of US
- "Protected" version of banner
- Analytics: return Monitor page name variable
- Localization: support locales that use VPN

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
