### ISSUE TITLE
Set protected status on production branch

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/blurts-server#225]
The production branch on this repository is not protected against force pushes. This setting is recommended as part of [Mozilla's Guidelines][guidelines_url] for a Sensitive Repository.

**Anyone with admin permissions for this repository can correct the setting using [this URL][protect_url].**

If you have any questions, or believe this issue was opened in error, please contact [us][email] and mention SOGH0001 and this repository.

Thank you for your prompt attention to this issue.
--Firefox Security Operations team

[guidelines_url]: https://wiki.mozilla.org/GitHub/Repository_Security
[protect_url]: https://github.com/mozilla/blurts-server/settings/branches
[email]: <mailto:secops+github@mozilla.com?subject=SOGH0001+Question+re+mozilla/blurts-server>

**Comment by nhnt11** [comment]
master and SHIELD_STUDY branches are now protected against force push and deletion. @moz-hwine, let me know if that's sufficient to close this issue. I'll look into enabling further protection features after the weekend.

**Comment by moz-hwine** [comment]
Thanks for the prompt handling!

> I'll look into enabling further protection features after the weekend.

Just to clarify, we're not looking for additional lockdown at this time :) If you do choose to go ahead, please be aware of the [known issues](https://wiki.mozilla.org/GitHub/Repository_Security#Problems_and_Options) and the linked [tips and tricks](https://wiki.mozilla.org/GitHub/Repository_Security/Problems_and_Options) page. (Additions welcome).
