### ISSUE TITLE
Log missing breaches?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#227]
Looks like HIBP released a new breach on July 1, 2018, but it isn't in our https://github.com/mozilla/blurts-addon/blob/master/src/breaches.json or on the server.

Not sure if we have logging for missing `/breach=${Name}` routes. The chances of a user randomly typing a HIBP breach into the address bar is probably extremely low, but would be interesting if we ever get malformed breach query params or whatnot.
But if we're just redirecting to `/` if a breach with the specified name isn't found, maybe this isn't getting logged as a 404 or anything.

**Comment by pdehaan** [comment]
I only noticed this because I grabbed the latest breaches.json via a **blurts-utils** lib I was trying to create.
I was trying to scrape all the breach details pages and take screenshots, but found that we the latest breaches.json didn't match the ones on the add-on/server, so trying to scrape the `.account` element fails because the missing breach redirects to the homepage.

**Comment by Micheletto** [comment]
> Looks like HIBP released a new breach on July 1, 2018, but it isn't in our https://github.com/mozilla/blurts-addon/blob/master/src/breaches.json or on the server.

To make the rollout faster and easier we skipped having an update process for breaches.  I'll load the new ones manually.

**Comment by groovecoder** [comment]
The breaches are now loaded at server start-up, and we have https://github.com/mozilla/blurts-server/issues/245 to track work to refresh them.
