### ISSUE TITLE
Resize all breach logos to 150x150?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#2273]
Currently we have a bunch of different image dimensions in ./public/img/logos/*.png.
Not sure if it is worth it to try and keep everything at a consistent 150&times;150.

I wrote this terrible code, but it's terrible because I'm not validating the image sizes first, so it might be resizing images that are already 150&times;150, or resizing smaller images from 64&times;64 and stretching them so they look pixelated.

I think when I did a quick spot check, almost every image size was increased, so there might be more optimization needed, or else there is a better tool (Photoshop or whatever) that has better resizing algorithms. But it was an interesting Friday project I have been thinking about for a couple weeks, and wanted to play w/ **image-js**.

```js
/* eslint-disable */

const fg = require("fast-glob");
const { Image } = require("image-js");

main("./public/img/logos/*.png");

async function main(dir) {
  const logos = await fg([dir]);
  for (const logo of logos) {
    await resize(logo)
      .catch((err) => {
        console.error(logo, err.message);
        process.exitCode = 1;
      });
  }
}

async function resize(logo, width = 150) {
  const image = await Image.load(logo);
  // resize (keeping current aspect ratio) and overwrite original image.
  return image.resize({ width }).save(logo);
}
```

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
