### ISSUE TITLE
Feature request: manually mark breaches as fixed once you've dealt with them

### ISSUE THREAD

**Issue by xhaavardx** [mozilla/blurts-server#2288]
It would be extremely helpful if there was a way to hide or checkmark breaches you've already dealt with, as it gets quite difficult to keep track of over time.

**Comment by pdehaan** [comment]
@xhaavardx If you're logged in, you should see a "Resolve this breach" link in your dashboard for each breach, I believe:

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/133962858-9b4eb2e9-4572-42b8-ad4b-108c06b01e6d.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
