### ISSUE TITLE
Update description and URL on repo homepage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#229]
![mozilla_blurts-server__prototyping_for_upcoming_breach_alerts_feature_in_firefox](https://user-images.githubusercontent.com/557895/42337542-fb9aca12-803b-11e8-96a8-e928dc6b5276.png)

Not sure if we want to possibly ~~steal~~ borrow the description from the blurts-addon repo's [src/manifest.json](https://github.com/mozilla/blurts-addon/blob/00fad2c4cecf83be5adb1f41d4bc39106ac59040/src/manifest.json#L5) file...

> Have your accounts been leaked or stolen in a data breach? Find out with Firefox Monitor, an experimental service created by Mozilla.

**Comment by groovecoder** [comment]
Updated. https://github.com/mozilla/blurts-server
