### ISSUE TITLE
State name is not in fact required to get the review window after clicking “Start Data Removal”

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2298]
**Build:**
Dev;

**Affected platforms:**
Windows 10 64-bit;

**Prerequisites:**
Have a Firefox Account created;

**Steps to reproduce:**
1. Navigate to https://monitor-v2.herokuapp.com/user/remove-data ;
2. Fill up all the required information except the “State” field;
3. Click on the “Start Data Removal” button;
4. Observe the results;

**Expected result:**
- The user is prompted to fill in the “State” field;

**Actual result:**
- The user is not prompted to fill in the “State” field, and the review box displays a layout issue;

**Notes:**
- The user receives the review box and a confirmation that the removal process has begun but it doesn’t actually start;
- Returning to the dashboard the user is prompted to enter their credentials again;
![image](https://user-images.githubusercontent.com/85748693/135086280-33dfaa67-e70a-49de-93d5-a89c08ac492a.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
