### ISSUE TITLE
Disable email input field while searching for breaches?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#231]
Currently it looks like clicking the "Search" button clears the input field, and sets the search button into an indeterminate spinner while the search is performed.

![monitor-disabled](https://user-images.githubusercontent.com/557895/42341661-a92c3c7c-8048-11e8-94db-d097ab51c574.gif)

Probably best to not clear the text field, and just disable it while doing a search.

**Comment by lesleyjanenorton** [comment]
nice catch! will update
