### ISSUE TITLE
Mark breaches as unverified?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#232]
Reading through the HIBP FAQ and tripped over this URL, https://haveibeenpwned.com/account/test@example.com

Looks like that page shows 9 "(unverified)" breaches. If you search https://monitor.firefox.com for the same "test@example.com" address, I see the same breaches, but we aren't flagging them as unverified.

**Comment by groovecoder** [comment]
Also fixed in https://github.com/mozilla/blurts-server/pull/235 by filtering out these breaches from breach results?

**Comment by pdehaan** [comment]
Yeah, we're currently suppressing unverified breaches from the results, so I think it's safe to close this issue.
