### ISSUE TITLE
Include requested format or example in form or "Please match the requested format." tooltip

### ISSUE THREAD

**Issue by g-k** [mozilla/blurts-server#2327]
**Build:** Dev
 
**Steps to reproduce:**

1. For Monitor Kanary, log in using an existing account.
2. Go to “Exposures” menu and scroll down to the form.
3. Enter "abc" in the first name field. Leave other fields blank. Click Start Data Removal button.
4. Observe the above tooltip in the screenshot below:

<img width="639" alt="Screen Shot 2021-10-11 at 11 35 42 AM" src="https://user-images.githubusercontent.com/226605/136817512-8b777138-6e62-461f-9080-1152acf75737.png">
 
**Expected result:** Form or tooltip includes information about how to enter a valid name like an example for the expected format.

Middle initial and last name fields are similarly impacted and for a numeric input the `City` field does not display a tooltip at all.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
