### ISSUE TITLE
Equal "=" sign displayed in Removal status info dialog's title

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/blurts-server#2366]
**Build:**
Dev;

**Affected platforms:**
Windows 10 64-bit;

**Steps to reproduce:**

1. For Monitor Kanary, log in with an existing account.
2. Expand one of the website cards and click the Removal status "?" icon.
3. Observe the title of the dialog.

**Actual result:**
Equal "=" sign is displayed in the title.

**Expected result:**
No equal "=" sign is displayed.

![= sign displayed](https://user-images.githubusercontent.com/79697848/140500903-cc476ee0-af6f-41c7-aac0-3418dd703d06.PNG)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
