### ISSUE TITLE
Email form input field disabled on browser back navigation

### ISSUE THREAD

**Issue by chrismore** [mozilla/blurts-server#238]
Steps to reproduce:

1) Go to https://monitor.firefox.com/ in Firefox (issue doesn't exist in Chrome)

2) Enter in any valid email address into the form

3) Click search

4) Click back button in browser

5) Try to enter in another email address

Expected results:

Ability to focus the input form and enter in a new email address

Actual results:

Input form contains disabled="" as seen below:

<input class="input-group-field email-to-hash hide-caret" name="email" placeholder="" aria-label="Enter Email Address" tabindex="0" autocomplete="off" disabled="" type="email">

**Comment by lesleyjanenorton** [comment]
@nhnt11 about to take a look but I'm guessing you are right. will push up a patch shortly.

**Comment by lesleyjanenorton** [comment]
@nhnt11 @chrismore just curious - which version of firefox are you guys using? I'm not able to recreate this locally or at monitor.firefox.com.

**Comment by chrismore** [comment]
@lesleyjanenorton I am running Fx61 release channel on OSX.

**Comment by nhnt11** [comment]
I'm on the latest 63.0 Nightly.

**Comment by lesleyjanenorton** [comment]
@nhnt11 @chrismore thanks guys. I still can't recreate in any version of Firefox but WAS able to recreate in Safari and will have a patch up soon.
