### ISSUE TITLE
Monitoring and optional forwarding auto-disabling for Firefox Private Relay email addresses

### ISSUE THREAD

**Issue by NamesNetworkNic** [mozilla/blurts-server#2384]
Having Firefox Monitor user's list of watched email addresses automatically sync with their Private Relay email addresses would be a great bonus for users of both services.

Additionally, an option for forwarding to be disabled for any or certain email addresses if they get leaked could be helpful for security.

_I expect the former is already being worked on, but I couldn't find an issue in regards to this, so I made one myself for completeness' sake._

xo - Lovejoy

**Comment by branrickman** [comment]
I came to the issues page to suggest just this- It would be fantastic if relay could be plugged in to this breach monitoring system.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
