### ISSUE TITLE
IP Address Banner for Mozilla VPN has is not translated in Malay [ms]

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2386]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10, 64-bit;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Have the browser’s preferred language for displaying pages and the languages used to display menus, messages, and notifications set to Malay [ms];
- Have the Mozilla VPN installed;
- Be signed in into the Mozilla VPN;

#### Steps to reproduce:
1. Go to the testing site;
2. Open the IP address banner;
3. Observe the text;
4. Switch on the Mozilla VPN;
5. Refresh the testing site;
6. Open the IP address banner and observe the text again;

#### Expected result:
- The text of the banner should be translated into Malay [ms];

#### Actual result:
- The text is not translated to Malay [ms] and defaults to the last language used;

#### Notes:
- From what I found out, Malay [ms] is the language used for Malaysia [my];
- Attached media:
![10MY ms3](https://user-images.githubusercontent.com/85748693/143597962-4adb1246-1998-47e6-863e-b95c82e8aceb.png)
![10MY ms0](https://user-images.githubusercontent.com/85748693/143597968-213a8c44-377d-4fe0-b7c4-63038ff15edd.png)
![10MY ms1](https://user-images.githubusercontent.com/85748693/143597974-e61a94cb-e105-463b-b8e6-301ac6623f8e.png)

**Comment by toufali** [comment]
It appears Malay contributors on Pontoon are currently too sparse to accomplish this.
