### ISSUE TITLE
Add anchor links to headings on /security-tips

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/blurts-server#2388]
It would be great to be able to link folks directly to certain sections on monitor.firefox.com/security-tips, such as "How to create strong passwords" or "5 myths about password managers" .etc.

**Comment by katiechurchwell** [comment]
Can I work on this?

**Comment by amychurchwell** [comment]
@katiechurchwell are you still looking for good first bugs?

**Comment by katiechurchwell** [comment]
@amychurchwell always!

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
