### ISSUE TITLE
Add Circle-CI or Travis-CI

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#24]
We probably also want to add Circle-CI or Travis-CI git hooks so we can run linting/tests/[**nsp**](http://npm.im/nsp) on a per-PR basis.

**Comment by bhavyaagg** [comment]
Hello,
If no one is currently working on this can I take up this issue?

**Comment by groovecoder** [comment]
Please wait until https://github.com/mozilla/blurts-server/pull/25 is merged, and @pdehaan re-submits his ESLint pr.

**Comment by bhavyaagg** [comment]
Sure @groovecoder . Thank you :)
