### ISSUE TITLE
Make sure FxA login says "Firefox Monitor"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#241]
Spotted locally when testing a PR.
We should probably try and get that changed to something more user-facing like "Firefox Monitor".

![sign_in_to_continue_to_blurts](https://user-images.githubusercontent.com/557895/43021852-05f3cfb0-8c1a-11e8-957a-94a58147c8d7.png)

Tested on the Heroku dev site, and it says "Sign in to continue to blurts-heroku".

**Comment by lesleyjanenorton** [comment]
Placeholder! Will be replaced with something respectable once we get the new spec.

**Comment by groovecoder** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1488567
