### ISSUE TITLE
Update to CircleCI v2 API

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#246]
Re: https://github.com/mozilla/blurts-server/blob/master/circle.yml

I just got an email from "The CircleCI Team" saying:

> Last month, we pointed you toward resources to help you migrate active projects from CircleCI 1.0 to 2.0 with the [Migration Center](http://go.circleci.com/Q0MH0GM0Zn2GW0k120044I0). 
>
> [With only 30 days left until CircleCI 1.0 sunsets](https://circleci.com/sunset1-0/), we want to ensure you have everything you need to help you with any active projects that still need to migrate to 2.0. Our team has been busy creating resources and new features to help make it easier:

More info in the CircleCI Blog at https://circleci.com/blog/sunsetting-1-0/ and https://circleci.com/docs/2.0/migration-intro/

**Comment by pdehaan** [comment]
Per our CircleCI build pages:

> "This project is currently running on CircleCI 1.0 which will no longer be supported after **August 31, 2018**. Please start migrating this project to CircleCI 2.0."

Aug 31 is this Friday.

**Comment by groovecoder** [comment]
Forgot to include the issue # in my commit, but https://github.com/mozilla/blurts-server/pull/306 fixes this.
