### ISSUE TITLE
Can't add a new email

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/blurts-server#2500]
Steps to reproduce: 

- Go to monitor https://monitor.firefox.com/ and log in
- Scroll down to the "Want to add another email?" section
- Input another email into the field
- Click Send Verification Link

Expected behavior:
New email added

Actual behavior: 
I get the following error message: EmailUtils.getVerificationUrl is not a function

Original report: https://twitter.com/Kn0p3XX/status/1493284278284824583

**Comment by UliMand** [comment]
I can confirm this error with the same message.

"EmailUtils.getVerificationUrl is not a function".

**Comment by maxxcrawford** [comment]
Resolved by https://github.com/mozilla/blurts-server/pull/2502

Please try again and let us know if you have any issues adding another email!

**Comment by UliMand** [comment]
Thank you. It works now.

One question: Only five e-mail addresses can be entered in the monitor?

**Comment by maxxcrawford** [comment]
> Thank you. It works now.
> 
> One question: Only five e-mail addresses can be entered in the monitor?

Yes! See [this comment/issue](https://github.com/mozilla/blurts-server/issues/2106#issuecomment-989261240) for more information regarding the account limits.
