### ISSUE TITLE
Use SES for emails

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#251]
On local machines and the heroku dev instance, we are using mailgun for emails.

For staging & prod we will need to use SES. To use SES, we will need to:

1. [x] Change the SMTP config to SES (See [bug 1480435](https://bugzilla.mozilla.org/show_bug.cgi?id=1480435))
2. [x] Specify a configuration set with an SMTP header: `X-SES-CONFIGURATION-SET: <ConfigSet>` (See [docs](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-configuration-sets-in-email.html))
3. [x] Add a `/ses/notification` endpoint to handle email bounce notifications and delete those users from our subscribers
4. [ ] Add authentication (HTTP basic auth or digital signature verification) to `/ses/notification`

**Comment by groovecoder** [comment]
@Micheletto - please let me know what SES SMTP values we can try ASAP.
```
SMTP_HOST=""
SMTP_PORT=
SMTP_USERNAME=""
SMTP_PASSWORD=""
```

**Comment by pdehaan** [comment]
> Add a `/ses-bounce` endpoint to handle email bounce notifications and delete those users from our subscribers

How many bounced emails would we allow before removing a user from the subscribers table? 1? 4?

**Comment by groovecoder** [comment]
I'm leaving this issue open because I still need to add authentication to the endpoint. Either HTTP basic auth (has been problematic) or digital signature verification. I'll update the description.
