### ISSUE TITLE
webhint issues (was: Referrers leaked)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#257]
Saw this tool/site via a bug report in a different repo...
https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fmonitor.firefox.com%2F

The site text seems a bit generic, but seems to highlight that we're potentially leaking some referrerer info, and using some 3rd party services (like Google Analytics).

Not sure if any other automated tools report similar things, but I can try [**webhint**](https://www.npmjs.com/package/hint) (formerly **sonarwhal**) or **lighthouse**.

**Comment by pdehaan** [comment]
Actually, I did try running the **sonarwhal** linter against this project a while back (see https://github.com/pdehaan/blurts-sonar and https://github.com/mozilla/blurts-server/issues/141#issuecomment-394522741), but it doesn't look like it catches referrer stuff.

And because this took me far too long to figure out the diffs between **sonarwhal** and **hint**, here's my new config and dependencies:

### package.json

```js
{
  "name": "hintrc-test",
  "version": "1.0.0",
  "author": "Peter deHaan <peter@deseloper.com> (https://about.me/peterdehaan)",
  "devDependencies": {
    "@hint/configuration-web-recommended": "1.0.1",
    "@hint/formatter-stylish": "1.0.0",
    "hint": "3.0.1"
  },
  "keywords": [],
  "license": "WTFPL",
  "main": "index.js",
  "scripts": {
    "hint": "hint",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}
```

### .hintrc

```js
{
  "extends": [
    "web-recommended"
  ],
  "formatters": ["stylish"],
  "ignoredUrls": [
    {
      "domain": "code.cdn.mozilla.net",
      "hints": ["*"]
    },
    {
      "domain": "www.google-analytics.com",
      "hints": ["*"]
    }
  ],
  "hints": {
    "content-type": "off",
    "http-cache": "off",
    "http-compression": "off",
    "no-friendly-error-pages": "warning",
    "no-html-only-headers": "off",
    "sri": "off",
    "validate-set-cookie-header":  "off",
    "x-content-type-options": "off"
  }
}
```

```sh
$ npm run hint -- "https://monitor.firefox.com/" "https://monitor.firefox.com/?breach=Adobe"

> hintrc-test@1.0.0 hint /Users/pdehaan/dev/tmp/del/hintrc-test
> hint "https://monitor.firefox.com/" "https://monitor.firefox.com/?breach=Adobe"

https://monitor.firefox.com/
line 1  col 1   Error    Start tag seen without seeing a doctype first. Expected “<!DOCTYPE html>”.  html-checker
line 8  col 74  Warning  The “type” attribute is unnecessary for JavaScript resources.               html-checker
✖ Found 1 error and 1 warning

https://monitor.firefox.com/?breach=Adobe
line 1  col 1   Error    Start tag seen without seeing a doctype first. Expected “<!DOCTYPE html>”.  html-checker
line 8  col 74  Warning  The “type” attribute is unnecessary for JavaScript resources.               html-checker
✖ Found 1 error and 1 warning

✖ Found a total of 2 errors and 2 warnings
```

**Comment by groovecoder** [comment]
Re-purposing this issue to be more of a "webhint lint" issue.

I'm happy to have @psiinon weigh in on our Referrer Policy. My thoughts ...

We don't set a Referrer Policy, so the browser will use the default `no-referrer-when-downgrade` which prevents referrers leaking over insecure connections. And we use CSP to enforce secure connections only to the strict set of 2 external hosts for all resources.

Our URLs do not contain any sensitive data - email addresses are only `POST`ed, and verification tokens are UUID values.

Is it worth fuzz-crawling some URLs on the site to make sure nothing is leaking out thru Referrer urls?

**Comment by psiinon** [comment]
Do we use the referrer header at all?
If not why not set "Referrer-Policy: no-referrer" just to be sure?

**Comment by groovecoder** [comment]
Because we *do* actually want referrers sent to Google Analytics.

**Comment by psiinon** [comment]
Thats a good enough reason :)

**Comment by pdehaan** [comment]
Unreleated to the referer issue, but here's the latest [**webhint**](https://webhint.io/scanner/3ec452a4-4d7c-4501-b176-bda0857202f1) report from their online scanner. Not sure if any of these are really actionable or worth fixing before we go live, but somebody with more knowledge than I should probably be the one to audit the list and decide what is worth escalating.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
