### ISSUE TITLE
404: Page Not Found after refreshing /user/add page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#258]
https://github.com/mozilla/blurts-server/blob/c344f3ad863aa95aab93048818203174b5e995ce/routes/user.js#L23

### Steps to reproduce:
1. Sign up for newsletter.
1. Accidentally refresh the https://fx-breach-alerts.herokuapp.com/user/add page.

### Actual results:

![user-add-404](https://user-images.githubusercontent.com/557895/43983585-32e48a90-9cb0-11e8-8a14-6459da02ddec.png)

Also note that all the images are 404ing on the 404 page.

**Comment by pdehaan** [comment]
It may also be a good time to look through server logs and see if we have any high incidents of 404s or 500s or anything else unexpected.

**Comment by groovecoder** [comment]
This may be a good self-contained issue for @nhnt11 if he wants to get back into the back-end code.

**Comment by nhnt11** [comment]
Thanks, assigned myself to look at tomorrow.

**Comment by groovecoder** [comment]
We could just call this fixed ... the `/user/add` call is an ajax call now, so the user won't get themselves into the refresh situation anymore. They would have to manually visit `/user/add` to get the 404, which I don't think we need to fix.
