### ISSUE TITLE
Font size and style differences between Stage and Production (details in Notes section)

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2584]
Testing site:
- https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/ ;

Platforms affected:
- Windows 10, 64-bit;

Browsers tested on:
- Firefox, latest version;

Prerequisites:
- Have a Monitor account;
- Have a separate tab or window with the Production site viewing the same place as on Stage;

Steps to reproduce:
1. While not signed in, navigate to the Monitor homepage on Stage;
2. Scroll up and down and compare with Production;
3. Sign into the Monitor site, both on Stage and Production;
4. Scroll up and down and compare with Production
5. Repeat step 4 for the Breaches and Security Tips pages;

Expected result:
- There should be no different font sizes and styles;

Actual result:
- There are different font sizes and styles;;

Notes:
- General:
    - The four links in the Monitor site footer;
- On the “Home” page (signed OUT):
- “See if you’ve…” title;
- Subtitle below;
- “Enter Email Address” placeholder text;
- “Latest breach added” frame’s date and compromised data;
- Titles of the cycling ads (holds up for the Signed in view as well);
- Titles and subtitles of the “Sign up for breach monitoring with a Firefox Account.” frame;
- On the “Home” page (signed IN):
    - “Breach Summary” title;
    - “Email Addresses” title;
    - Email addresses listed below;
    - Titles of the cycling ads (holds up for the Signed Out view as well);
    - “Want to add another email?” title;
    - “Enter Email Address” placeholder text;
- On the “Breaches” page:
    - “All breaches in Firefox Monitor” title;
    - The “Have I Been Pwned” link below the “Search Breaches” search field;
    - Results of the “Breach added” and “Compromised data” fields in all breach cards;
- On the “Security Tips” page:
    - “Security tips to protect yourself from hackers” title;
    - All titles and subtitles, including the bookmarks for each tip;
    - Most of the contents of the “Password do’s and don’ts” table;
- See attached media:
Breaches:
![breaches](https://user-images.githubusercontent.com/85748693/172187819-3d50ca24-4e1d-42ca-b489-3826f3c5cac6.gif)
Security tips:
![sectips](https://user-images.githubusercontent.com/85748693/172187897-cb097fa4-9aa7-4544-964f-953caa9f6c2e.gif)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
