### ISSUE TITLE
“Take back control of your personal data.” presents differences between Stage and Production

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2585]
Testing site:
- https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/ ;

Platforms affected:
- Windows 10, 64-bit;

Browsers tested on:
- Firefox, latest version;

Prerequisites:
- Be signed into a Monitor account;
- Have a separate tab or window with the Production site viewing the same place as on Stage;

Steps to reproduce:
1. Navigate to the Monitor Home page;
2. Scroll down to the “Take back control of your personal data.” section;
3. Compare with Production;

Expected result:
- There are no differences;

Actual result:
- Stage displays a “Read More Security Tips” button which is not present of Production;
- Stage displays different text below the section’s title;

Notes:
- See attached media:
Stage:
![image](https://user-images.githubusercontent.com/85748693/172189105-f25cce18-6767-4fc9-9a07-d22ba624c267.png)

Production:
![image](https://user-images.githubusercontent.com/85748693/172189309-f488a3db-d4c2-4e95-bb4c-bcca44883474.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
