### ISSUE TITLE
The “LATEST BREACH ADDED” box is not displaying the site’s icon/image

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2586]
Testing site:
- https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/ ;

Platforms affected:
- Windows 10, 64-bit;

Browsers tested on:
- Firefox, latest version;

Prerequisites:
- Do NOT be signed in into a Monitor account;

Steps to reproduce:
1. Navigate to the Monitor Home page;
2. Observe the “LATEST BREACH ADDED” box;

Expected result:
- The box displays the site’s icon/image (gray globe);

Actual result:
- The box does not display any image for the site in question;

Notes:
- I suspect there might be a chance this issue is present only for sites that are displayed with this default image;
- On the “Breaches” page, all sites are displayed with an image;
- See attached media:
Stage:
![image](https://user-images.githubusercontent.com/85748693/172190513-7b951aa5-8b28-4a8b-a7b8-240332003af4.png)

Production:
![image](https://user-images.githubusercontent.com/85748693/172190635-322af463-c60f-4b78-9a9c-4b0f7bcf5008.png)

**Comment by AOiegas** [comment]
I just want to add that the image is missing from the breach details page as well.
![image](https://user-images.githubusercontent.com/85748693/172347285-49ca087a-635f-4d53-b144-89fdf2886651.png)

**Comment by BPolattie** [comment]
How to bypass gmail password

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
