### ISSUE TITLE
“Firefox Monitor Terms & Privacy” page tab displays a wrong name/title

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2587]
Testing site:
- Stage: https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/ ;
- Production;

Platforms affected:
- Windows 10, 64-bit;

Browsers tested on:
- Firefox, latest version;

Prerequisites:
- N/A;

Steps to reproduce:
1. Navigate to the Monitor Home page;
2. Scroll down to the bottom of the page;
3. In the page footer, click on the “Terms & Privacy” link;
4. Hover the cursor over the freshly opened link and observe its name and tooltip;

Expected result:
- The tab and tooltip should display “Firefox Monitor Terms & Privacy — Mozilla”;

Actual result:
- The tab and tooltip displays “Firefox Monitor Terms &amp Privacy — Mozilla”;

Notes:
- This is present on Production as well;
- See attached media:
![image](https://user-images.githubusercontent.com/85748693/172345581-6935a48f-c03d-4061-a415-c0cbb2c40781.png)

**Comment by Amod02-prog** [comment]
Hi, I would like to work on this issue.

**Comment by Amod02-prog** [comment]
Hi , I would like to work on this issue . Can you point to the files of the website mentioned in the issue in the comment.

**Comment by Vinnl** [comment]
Hi @Amod02-prog, @toufali can confirm, but I think that this issue does not originate with code in this repository, but instead is handled in a Content Management System somewhere that we don't have access to, so unfortunately resolving it will involve finding the right people and asking them to fix it, which isn't really possible to do for non-employees...

**Comment by pdehaan** [comment]
Ah, good catch @Vinnl!

Yeah, the Terms &amp;amp; Privacy page is served from https://www.mozilla.org/en-US/privacy/firefox-monitor/?utm_campaign=fx_monitor_downloads&utm_content=site-footer-link&utm_medium=referral&utm_source=monitor.firefox.com which means this would be a [Bedrock](https://github.com/mozilla/bedrock) issue.
My guess is that they'd just need to add a ["safe" filter](https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#safe) somewhere in that Django template layout pipeline.

**Comment by jwhitlock** [comment]
I've added a Bedrock issue: https://github.com/mozilla/bedrock/issues/12129

**Comment by toufali** [comment]
Agreed -- thanks y'all!  Closing this ticket.
