### ISSUE TITLE
The “Breaches” page displays a background image that has a different color/hue than on Production

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2588]
Testing site:
- https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/ ;

Platforms affected:
- Windows 10, 64-bit;

Browsers tested on:
- Firefox, latest version;

Prerequisites:
- Have a separate tab or window with the Production site viewing the same place as on Stage;

Steps to reproduce:
1. Navigate to the Monitor “Breaches” page;
2. Switch between the Stage version and the Production version repeatedly and compare the color/hue of the background image;

Expected result:
- The background image should have the same color/hue;

Actual result:
- The background image has a different color/hue than on Production;

Notes:
- See attached media:
![difcol](https://user-images.githubusercontent.com/85748693/172374969-2160bd56-c483-4387-a998-fe5c996db661.gif)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
