### ISSUE TITLE
“Data Removal” tab is not highlighted when a user is in that tab

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2594]
Testing site:
- https://monitor-v2.herokuapp.com/brokers ;

Platforms affected:
- Windows 10, 64-bit;

Browsers tested on:
- Firefox, latest version;

Prerequisites:
- Be signed in into a Monitor account;

Steps to reproduce:
1. Navigate to the Monitor testing site;
2. Click on the “Data Removal” tab;
3. Observe the Monitor site Header;

Expected result:
- The “Data Removal” tab is highlighted;

Actual result:
- The “Home” tab is highlighted instead;

Notes:
- See attached media:
![image](https://user-images.githubusercontent.com/85748693/174612652-571573b6-fd29-4d34-98d0-da21f2f270aa.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
