### ISSUE TITLE
“Data Removal” and “Security Tips” tabs are highlighted faulty on hover at 100% zoom

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2595]
Testing site:
- https://monitor-v2.herokuapp.com/user/dashboard ;

Platforms affected:
- Windows 10, 64-bit;

Browsers tested on:
- Firefox, latest version;

Prerequisites:
- Be signed in into a Monitor account;
- Have the site zoom level set at 100% (default);

Steps to reproduce:
1. Navigate to the Monitor testing site;
2. Hover cursor over the “Data Removal” and “Security Tips” tabs;
3. Observe the highlighting effect;

Expected result:
- The highlight is displayed correctly (probably under the second word of the tab name);

Actual result:
- The highlight is displayed under the first word of the tab name overlapping with the second word below;

Notes:
- See attached media:
![mntrtabs](https://user-images.githubusercontent.com/85748693/174619159-4bb7c712-c730-4637-9040-831606d0792c.gif)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
