### ISSUE TITLE
Add method to bypass CI tasks for a PR

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#2604]
I kinda wish we had a method to bypass CI tasks for a PR/commit.
In the case of new logos we don't really need to run the full CI suite and can probably save on some CircleCI resources and/or $$.

_Originally posted by @pdehaan in https://github.com/mozilla/blurts-server/issues/2603#issuecomment-1178267884_

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
