### ISSUE TITLE
[Unresolved breach notification] The “Feel free to change your preferences at any time here.” link does not redirect to the preferences page

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2619]
Testing site:
- https://fx-breach-alerts.herokuapp.com/;
- https://fx-breach-alerts.herokuapp.com/email-l10n/email-2022-mockup; 

Platforms affected:
- Windows 10, 64-bit;

Browsers tested on:
- Firefox, latest version;

Prerequisites:
- Be signed in into a Monitor account;
- Have a Unresolved breach notification email received;

Steps to reproduce:
1. Open the Unresolved breach notification email;
2. Scroll down to the bottom of the email;
3. Click on the “here” hyperlink from the “Feel free to change your email preferences at any time here.” text;

Expected result:
- Clicking on the link redirects the user to their Monitor account’s preferences page (https://fx-breach-alerts.herokuapp.com/user/preferences);

Actual result:
- Clicking on the link redirects the user to their Monitor account’s dashboard (https://fx-breach-alerts.herokuapp.com/user/dashboard);

Notes:
- The message containing the link indicates clearly preferences, but the actual redirect might confuse a user;
- See attached media:
![prefs](https://user-images.githubusercontent.com/85748693/186447436-c43cb8c7-7c83-4a02-9b62-b509d4592790.gif)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
