### ISSUE TITLE
[Unresolved breach notification] The email’s image is not displayed in Gmail app on Android

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2620]
Testing site:
- https://fx-breach-alerts.herokuapp.com/;
- https://fx-breach-alerts.herokuapp.com/email-l10n/email-2022-mockup; 

Platforms affected:
- Android 11;

Browsers tested on:
- N/A;

Prerequisites:
- Be signed in into a Monitor account;
- Have a Unresolved breach notification email received;
- Have the Gmail app installed on the Android device;

Steps to reproduce:
1. On the android device, open the Gmail app;
2. Open the Unresolved breach notification email;
3. Observe the contents of the email;

Expected result:
- The contents of the email should be displayed without issues;

Actual result:
- The email’s image is not displayed;

Notes:
- See attached media:
![image](https://user-images.githubusercontent.com/85748693/186449088-4ebd15c7-262c-4acb-ab89-1a399d6405ad.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
