### ISSUE TITLE
[Unresolved breach notification] The Firefox Monitor logo could be displayed better in dark mode

### ISSUE THREAD

**Issue by AOiegas** [mozilla/blurts-server#2621]
Testing site:
- https://fx-breach-alerts.herokuapp.com/;
- https://fx-breach-alerts.herokuapp.com/email-l10n/email-2022-mockup; 

Platforms affected:
- Android 11;
- Windows 10;

Browsers tested on:
- Firefox, latest release;

Prerequisites:
- Be signed in into a Monitor account;
- Have a Unresolved breach notification email received;
- Have the Gmail app installed on the Android device;
- Have the dark mode option enabled for the inbox;
- Have the Dark Reader browser add-on installed and enabled (desktop);

Steps to reproduce:
1. Open the inbox that received the email from the prerequisites;
2. Open the Unresolved breach notification email;
3. Observe the contents of the email;

Expected result:
- The contents of the email should be displayed without issues;

Actual result:
- The Firefox Monitor logo is displayed with a white background;

Notes:
- The white background contrasts strongly with the dark theme;
- See attached media:
Android with dark theme enabled:
![image](https://user-images.githubusercontent.com/85748693/186450552-bd150e66-7860-46ea-990a-754b58e341d0.png)
Windows 10 with the Dark Reader add-on enabled:
![image](https://user-images.githubusercontent.com/85748693/186450717-44594d44-2365-453d-9863-2920dddd6900.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
