### ISSUE TITLE
Serve images (and other statics) straight from nginx; ideally with CDN

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#264]
Most likely code.cdn.mozilla.net. We will need to coordinate with Ops (@Micheletto?) to set up the CDN mirroring.

Consider creating a new helper in `hbs-helpers.js` ...

```js
hbs.registerHelper("staticDomain", function() {
  if (AppConstants.NODE_ENV === "production") {
    return AppConstants.CDN_DOMAIN;
  } else {
    return AppConstants.SERVER_URL;
  }
}
```

Then it can be used in the templates:

```html
<script src="{{ staticDomain }}/js/monitor.js"></script>
<link rel="stylesheet" src="{{ staticDomain }}/css/app.css">
<img src="{{ staticDomain }}/img/..." />
```

**Comment by pdehaan** [comment]
And we should also use the CDN for stage verification (so we dont verify the site in Stage but then fails once it goes live to the mass public).

I didn't see any hardcoded image URLs in the CSS file.

**Comment by pdehaan** [comment]
Actually, how does this work?
How would we separate it so that when we do a stage/production deploy, the local assets aren't on the server (so that we aren't deploying a bunch of unused assets)

Not sure if production builds should just not deploy the [/public/ folder](https://github.com/mozilla/blurts-server/tree/master/public), but maybe we don't want to host the favicons and social media icons on a CDN vs locally.

**Comment by groovecoder** [comment]
When clients request assets from code.cdn.mozilla.net, the CDN servers will respond directly if they have the assets in their cache, or will pass the request thru to our origin server if they don't.

So, our stage & production environments should continue to serve the assets as the origin server to the CDN.

**Comment by groovecoder** [comment]
Updated title ... we at least want to serve the static assets directly from nginx without hitting the node.js process. Ideally we will also add CDN in front of nginx, but the nginx part is the most important.

**Comment by groovecoder** [comment]
I think @Micheletto has finished this as of Friday?

**Comment by groovecoder** [comment]
The images are served via nginx now. Moving this to launch week milestone for the CDN part, if we can make it happen this week that will be great.

**Comment by groovecoder** [comment]
Images are now being served properly with `Cache-Control` header that allows `ETag/If-None-Match` negotiation for `304` responses.

Moving out of launch week fix-ups.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
