### ISSUE TITLE
Add telegraf metrics

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/blurts-server#2652]
Some metrics would be useful to emit from the monitor server and from scripts. On other S&P projects, these are captured by a local `telegraf` agent, forwarded to a cloud InfluxDB server, and displayed with Graphana.

Some potential metrics:

* Total Subscribers and Emails (Gauges) - A PostgreSQL query returns the current number, and a second query returns the number over time. These could be migrated to InfluxDB to reduce DB load
* Monthly breach emails sent / to send - These appear in the logs, but could be emitted as metrics for visibility and alerts.

This may not be a compelling set of metrics to add this new feature. We're currently getting a lot of data from Cloudwatch and custom PostgreSQL queries, and another data source may not be worth the effort to implement it.

After a 5-minute search, this looks like a popular NodeJS metrics project:

https://github.com/brightcove/hot-shots

We'd need to coordinate with SRE to ensure `telegraf` is available, with required configuration in environment variables.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
