### ISSUE TITLE
Move server files into a subdirectory

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#266]
Just a weird thought while looking through the directory structure, but currently we have a bunch of code amongst the documentation, and numerous config files.

Not sure if moving a bunch of the root-level files and folders into some nested "src/" folder would make things easier to find, and possibly make it easier to optimize some CSS/JS/SVG/PNG files before deploying into some "dist/" folder or something.

Initially, I was thinking maybe moving the following files/folders may make sense:

- __controllers/**__
- __db/**__
- __public/**__
- __routes/**__
- __views/**__
- app-constants.js
- email-utils.js
- hbs-helpers.js
- hibp.js
- middleware.js
- server.js
- sha1-utils.js

That'd still leave the following files in the root directory:

- __loadtests/**__
- __scripts/**__
- __src/**__ (assuming we move the files above into a new **src/** directory)
- __tests/**__
- .dockerignore
- .env-dist
- .eslintignore
- .eslintrc.js
- .gitignore
- .htmllintrc
- .npmignore
- .stylelintrc
- .travis.yml
- Dockerfile
- LICENSE
- README.md
- api.md (probably kill this file)
- circle.yml (ref: #246; "Update to CircleCI v2 API")
- package-lock.json
- package.json

Of course, this would be pretty disruptive refactoring, so maybe not worth the effort/headache.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
