### ISSUE TITLE
Run Twitter and OpenGraph meta tag validators

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#267]
A few tools for validating the meta tags for https://fx-breach-alerts.herokuapp.com/ (since the OG and Twitter meta tags aren't on Prod yet):

1. https://cards-dev.twitter.com/validator oddly says "Unable to render Card preview" 
1. https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ffx-breach-alerts.herokuapp.com%2F
1. https://opengraphcheck.com/result.php?url=https%3A%2F%2Ffx-breach-alerts.herokuapp.com%2F#.W3xZ2ZNKhTY
1. http://iframely.com/debug?uri=https%3A%2F%2Ffx-breach-alerts.herokuapp.com%2F

We also may need to try dynamically setting the server URL for the `og:url` and `og:image` since those are currently hardcoded to production and not the current server. This means we cannot verify the OG/Twitter metadata until the assets land on prod.

It'd also be nice to come up with a solution for turning the description into a variable so we don't need to repeat it for `<meta name="description" ...>`, `<meta property="og:description" ...>`, and `<meta name="twitter:description ...>` (since the 3 aren't currently in sync already).

https://github.com/mozilla/blurts-server/blob/5cb8a1cc8467dd45b0201c05b2729184fcfad2cf/views/layouts/default.hbs#L6-L13

**Comment by lesleyjanenorton** [comment]
Just changed the og:url and og:image urls to match the Heroku server for testing this. I'm not super familiar with twitter cards so I'm curious to see what this will look like.
