### ISSUE TITLE
Monitor a domain

### ISSUE THREAD

**Issue by BirdInFire** [mozilla/blurts-server#2682]
i would like to ask if it's possible to monitor an domain instead of one mail (with DNS validation), like that when people like me who have his own domain, i can add the monitoring on the full domain to not to have to create a new monitor every time i make a email address for a services.

**Comment by jwhitlock** [comment]
You may be interested in Domain Search, provided by haveibeenpwned.com, our source for breach data - https://haveibeenpwned.com/DomainSearch
