### ISSUE TITLE
issue with German VPN banner

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/blurts-server#2684]
Screenshot from the German Firefox Monitor home page:

<img width="1002" alt="Bildschirm­foto 2022-10-26 um 23 28 06" src="https://user-images.githubusercontent.com/1100614/198141923-761658ca-304a-49c9-9f28-599cda926f69.png">

Please see the text in the banner. It has to be "Bleiben" not "Bleibe`<line break>`n". That's not possible in German. It's caused by this rule:

```
[data-ad-unit="3"] > article h2 {
  word-break: break-word;
}
```

By the way: `word-break: break-word` is deprecated and shouldn't be used anyway, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break).

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
