### ISSUE TITLE
Slight breach detail rendering differences between search results and details page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#274]
### Steps to reproduce:
1. Go to https://fx-breach-alerts.herokuapp.com/
1. Enter email address of "test@example.com" and click the Search button (see **Figure 1** below).
1. Go to https://fx-breach-alerts.herokuapp.com/?breach=LinkedIn (see **Figure 2** below).

### Screenshots:

![image](https://user-images.githubusercontent.com/557895/44482743-148f1e00-a5fe-11e8-831d-0855ea950a75.png)
**Figure 1:** Via search on Homepage.

---

![image](https://user-images.githubusercontent.com/557895/44482809-43a58f80-a5fe-11e8-901c-6a027e721999.png)
**Figure 2:** Direct link to breach.

**Comment by lesleyjanenorton** [comment]
Closing since this is the old UI.
