### ISSUE TITLE
Refactor AppConstants to more gracefully handle missing env vars

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#275]
```throw new Error(`Required environment variable was not set: ${v}`);``` makes spinning up a new environment very flaky. 😢 We may want to relax it a bit.

**Comment by pdehaan** [comment]
+1 to switching to something like [**convict**](https://www.npmjs.com/package/convict) to handle env vars and configs.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
