### ISSUE TITLE
id attribute value must be unique

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#282]
via aXe a11y linter... Looks like we may have a few instances of `id=""` attributes in the shared SVG partials.

https://github.com/mozilla/blurts-server/blob/8313d57950a6f3a17a1f0fc5d4041c5a43fbf00e/views/partials/password_tip_svg.hbs#L5

https://github.com/mozilla/blurts-server/blob/8313d57950a6f3a17a1f0fc5d4041c5a43fbf00e/views/partials/what_to_do_svg.hbs#L4

Also a few recycled `id=""` values buried in the line SVG content at https://github.com/mozilla/blurts-server/blob/97ecbea527e91128a3070903a256087a3bd448ca/tips.js

![image](https://user-images.githubusercontent.com/557895/44548844-175c4280-a6d4-11e8-9780-fef226b37f2f.png)

**Comment by groovecoder** [comment]
Should be fixed in latest master.(?)
