### ISSUE TITLE
Round the PwnCount to match blurts-addon?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#284]
Currently in pending PR, but might be nice to keep add-on and server consistent: https://github.com/mozilla/blurts-addon/pull/97/files#diff-bfac755d67e6a6e5ab3abcceb7826be0

```js
// Round the PwnCount:
// If < 100k: keep as is; e.g. 12,345 -> 12,345
// If < 1M: round to nearest 100k; e.g. 234,567 -> 200,000
// If < 1B: round to nearest millions; e.g. 123,456,789 -> 123 million
// If >= 1B: round to nearest billions; e.g. 9,123,456,789 -> 9 billion
```

/cc @nhnt11

**Comment by lesleyjanenorton** [comment]
I asked about this and the decision as of a few weeks ago was that we would use the sharp number in the website. Just sent a message to verify that is still the case though.

**Comment by lesleyjanenorton** [comment]
Word from UI/UX is to leave the listing in the website as is so unless there is a dissenting opinion I move to close.
