### ISSUE TITLE
Inject LogoImg property into breaches?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#287]
Small nit, but the `src="/img/logos/{{ Name }}.{{ LogoType }}"` pattern is starting to feel a bit dirty. Not sure if we should just inject a `LogoImg` property or something onto each breach object (similar to how we overwrite the `breach.Description` below). That way it'd just be `src="/img/logos/{{ LogoImg }}"`

Not sure if the latest add-on still uses the logos, so may not be a useful tweak downstream.

https://github.com/mozilla/blurts-server/blob/c70a6b0f1f4362b2a17665e4e4acc4f1b22ec125/views/partials/breach_listing.hbs#L3

https://github.com/mozilla/blurts-server/blob/c70a6b0f1f4362b2a17665e4e4acc4f1b22ec125/views/partials/featured_breach.hbs#L5

---

https://github.com/mozilla/blurts-server/blob/c70a6b0f1f4362b2a17665e4e4acc4f1b22ec125/hibp.js#L45-L49

**Comment by groovecoder** [comment]
We can re-open this to address this if it starts causing bugs.
