### ISSUE TITLE
Optimize HIBP breach processing

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#290]
See https://github.com/mozilla/blurts-server/pull/285#discussion_r212669511 ...

> We seem to have quite a few functions that loop through the entire list of breaches. How about doing a single loop in HIBP.js when we fetch breaches, and storing all the stuff we need there so that we don't have to keep looping later?

**Comment by EMMLynch** [comment]
We done optimization to how processing works in general. I'm going to close this out. We are tracking processing and can open a new task if needed.
