### ISSUE TITLE
The “Lanwar” and “Fashion Nexus” logos are missing 

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#295]
[Affected versions]:
- Latest Nightly 63.0a1
- Beta 62.0b20
- Release 61.0.2

[Affected platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
- Launch Firefox.
- Navigate to https://blurts-server.stage.mozaws.net
- Scan the following email address: test@test.com
- Observe the “Compromised Accounts” section.

[Expected result]:
- The “Lanwar” and “Fashion Nexus” logos are properly displayed.

[Actual result]:
- The “Lanwar” and “Fashion Nexus” logos are missing, only the site title is displayed.

[Regression range]:
- Not a regression.

[Additional notes]:
- other websites logos could be affected by this issue, but I only encountered it on the above websites, so far.

![screenshot - showing the issue](https://user-images.githubusercontent.com/24842369/44651088-10457500-a9f1-11e8-803e-7e89477c8901.png)
See the screenshot

**Comment by pdehaan** [comment]
Lanwar added in 
https://github.com/mozilla/blurts-server/pull/280/files#diff-f2730f3529a367b7af897c380bde48b2

**Comment by CiprianGeorgiu** [comment]
After doing more exploratory testing around this issue, we've noticed that other logos are missing for the following websites: Funny Games, SpyFone and League of Legends. Scanned with test@test.com email address.

Could it be possible to add logos as well for the above websites?

**Comment by pdehaan** [comment]
I think most of these were added in #280 https://github.com/mozilla/blurts-server/pull/280/commits/c55ce1e82794acc6e5328181502f476dda9b217e

BIN  public/img/logos/AdultFanFiction.png
BIN  public/img/logos/FunnyGames.png
BIN  public/img/logos/Lanwar.png
BIN  public/img/logos/LeagueOfLegends.png
BIN  public/img/logos/LightsHope.svg
BIN  public/img/logos/MyFHA.svg
BIN  public/img/logos/Pemiblanc.svg

Not sure about "SpyFone". I'm not seeing that breach at https://fx-breach-alerts.herokuapp.com/?breach=SpyFone, but it's definitely at https://haveibeenpwned.com/PwnedWebsites#SpyFone ("Date added to HIBP: 24 August 2018").

**Comment by pdehaan** [comment]
These should have been fixed via #302, but I'm not seeing them on the Heroku site, which is baffling:

https://fx-breach-alerts.herokuapp.com/?breach=lanwar
https://fx-breach-alerts.herokuapp.com/?breach=MyFHA

/cc @groovecoder Why would these breaches be missing from the dev server?

**Comment by groovecoder** [comment]
Uplift from Slack ...
@pdehaan because our heroku app is pointed at Troy’s stage.haveibeenpwned.com/api/v2 and our stage server is pointed at Troy’s production haveibeenpwned.com/api/v2

**Comment by pdehaan** [comment]
I guess that means we can't verify breach logos until stage.hibp API gets updated with all breaches, or we uplift blurts-server to stage.
