### ISSUE TITLE
Same email address added/used in multiple accounts does not sync actions

### ISSUE THREAD

**Issue by say-yawn** [mozilla/blurts-server#2956]
# About the Issue
I have a FX account A that I added another email address X on that I later used the email address X to create another FX Account B.

# Bugs
1. On Monitor for FX account A has a breach resolved for email address X that did not sync with actions on Account B with email address X's breach report.

# Feature Request
1. When FX Account B was created, FX Account B has helpful text/info about the email address X being monitored in another account
2. When I deleted the account on the service that Monitor reported a breach in, there is no way to indicate that I have deactivated/deleted the account. Having deactivate/delete account would be helpful action to resolve breach and storing the said action will taken will be helpful in the future.
3. Option to remove the email address X's monitoring on FX Account A with FX Account B that uses email address X as primary email address for the account.

**Comment by mansaj** [comment]
Thanks for opening the issue @say-yawn! We've actually discussed this exact scenario prior to the refresh launch and Tony was ok with this edge case. I'll link him to this thread

**Comment by mansaj** [comment]
Created a JIRA ticket for this to keep track. Thanks @say-yawn!
