### ISSUE TITLE
Add a security.txt file?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#300]
Actually, this is interesting... Saw https://securitytxt.org/ cited in the Contribute.json GitHub issues.

> **security.txt**
> A proposed standard which allows websites to define security policies.

Looks like Troy has one at https://haveibeenpwned.com/security.txt. Not sure if we should similarly add one (and possibly direct people to Troy directly if they want to disclose anything).

🤷‍♀️

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
