### ISSUE TITLE
Replace nsp w/ npm audit

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#305]
Ref: https://github.com/mozilla/blurts-server/pull/304#issuecomment-417147527

Per https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting, **nsp** is on life support. We should replace it w/ <kbd>$ npm audit</kbd> sooner rather than later. 

Not blocking this issue, but we'll also need to tweak our CI for #246 since our Circle-CI V1 pipeline builds may also start misbehaving once that API is gone and buried.

**Comment by groovecoder** [comment]
I made this change temporarily in my local and it seemed easy and straight-forward.
