### ISSUE TITLE
Prettier Formatting / Cleanup All TS/JS files 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#3055]
Yeah, we agreed to switch to Prettier for formatting (it's more complete, and doesn't show up as warnings before it's been formatting), since we're creating many new files anyway. So TS files are formatted by Prettier, while existing files are left as-is.

When the migration is complete, we might still want to do a mega-formatting commit for the remaining files.

_Originally posted by @Vinnl in https://github.com/mozilla/blurts-server/pull/3049#discussion_r1196885689_

**Comment by Vinnl** [comment]
And we'll want to update the `lintstagedrc.js`:

```diff
-  "*.{ts,tsx,jsx,scss}": "prettier --write",
-  // While we're migrating to Next.js, regular .js and .css files are still
-  // likely to be the non-Next.js app. Thus, we scope those to /src/app:
-  "src/app/**/*.{ts,tsx,js,jsx,scss,css,md}": "prettier --write",
-  "*.md": "prettier --write",
+  "*.{ts,tsx,js,jsx,scss,css}": "prettier --write",
```
