### ISSUE TITLE
Implement Intro page from mock-ups

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#31]
Breach Alert UX on Drive: https://drive.google.com/file/d/1AuhQCFHOsNduMF_Sne32mCMfMeaTFuVJ/view?usp=sharing

Including:

* [x] Input field for the user to input their email address
* [x] Button to search breaches for their email address
* [x] Button to subscribe to email notifications if their email address is included in a future breach

**Comment by groovecoder** [comment]
[BreachAlert_Webpage_UX.pdf](https://github.com/mozilla/blurts-server/files/1741801/BreachAlert_Webpage_UX.pdf)

**Comment by pdehaan** [comment]
Ref: #53 (which added wireframe UI)

**Comment by groovecoder** [comment]
Done.
