### ISSUE TITLE
The “Firefox Monitor” is still selected after you click on “Go back one page”

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#317]
[Affected versions]:
- Firefox 62.0
- Firefox 63.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Go to this link: https://fx-breach-alerts.herokuapp.com/
2. Write an email address in the scan section and click on "Search".
3. Click on "Firefox Monitor".
4. Then click on "Go back one page". 

[Expected result]:
- The "Monitor Firefox" is not selected / highlighted.

[Actual result]:
- The "Monitor Firefox" is still selected / highlighted. 

[Regression]:
- I don't think this is a regression.

[Notes]:
- Please look at the attached gif.
![peek 2018-09-03 17-04](https://user-images.githubusercontent.com/42799381/44991023-8d498f00-af9b-11e8-88bc-d58f0d956231.gif)

**Comment by lesleyjanenorton** [comment]
Closing since this references the previous UI.
