### ISSUE TITLE
Clicking outside the "Subscribe to Firefox Monitor" pop-up makes the “Must be a valid email” warning message highlighted

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#318]
[Affected versions]:
- Firefox 62.0
- Firefox 63.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Go to this link: https://fx-breach-alerts.herokuapp.com/
2. Click on "Subscribe".
3. Without writing anything click on "Submit".
4. Click outside the "Subscribe to Firefox Monitor" pop-up.
5. Click on "Subscribe" again.

[Expected result]:
- The text "Must be a valid email" from the tooltip is not highlighted.

[Actual result]:
- The text "Must be a valid email" from the tooltip is highlighted.

[Regression]:
- I don't think this is a regression.

[Notes]:
- Please look at the attached gif.
![peek 2018-09-03 17-16](https://user-images.githubusercontent.com/42799381/44991578-2b8a2480-af9d-11e8-8639-1fd74f91b9c8.gif)

**Comment by CiprianGeorgiu** [comment]
This issue is no longer repro on https://fx-breach-alerts.herokuapp.com/, under Win 10 x64, macOS 10.13 and Ubuntu 16.04. Verified as fixed on 62.0 (20180830143136).
