### ISSUE TITLE
Facebook and Twitter buttons are wrongly highlighted and they slide to the sides when they are out of focus

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#319]
[Affected versions]:
- Firefox 62.0
- Firefox 63.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Prerequisites]:
- Subscribe with a valid email and confirm the subscription.

[Steps to reproduce]:
1. Access the confirmation link from your email. 
2. Click on the Facebook page.
3. Access the confirmation link from the first step 1 and observe the Facebook button. 

[Expected result]:
- The button is not highlighted and it doesn't change it's place when it's out of focus.

[Actual result]:
- The button is highlighted with a blue rectangle behind the logo image and it's changing it's location when is out of focus.

[Regression]:
- I don't think this is a regression.

[Notes]:
- Please look at the attached gif.

![peek 2018-09-03 17-31](https://user-images.githubusercontent.com/42799381/44992192-3a71d680-af9f-11e8-98c9-84ac1e51683c.gif)

**Comment by CiprianGeorgiu** [comment]
Verified as fixed on 62.0 (20180830143136) under macOS 10.13, Windows 10 x64 and Ubuntu 16.04 x64.
