### ISSUE TITLE
Facebook and Twitter buttons don’t redirect to the desired pages only by pressing in the middle of the button

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#320]
[Affected versions]:
- Firefox 62.0
- Firefox 63.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Prerequisites]:
- Subscribe with a valid email and confirm the subscription.

[Steps to reproduce]:
1. Access the confirmation link from your email.
2. Click on the bottom or top part of the Facebook button.

[Expected result]:
- Facebook button redirects the user to the "Share on Facebook" page. 

[Actual result]:
- The button doesn't do anything only if it's clicked right in the middle. 

[Regression]:
- I don't think this is a regression.

[Notes]:
- Please look at the attached gif.
![peek 2018-09-03 17-36](https://user-images.githubusercontent.com/42799381/44992496-06e37c00-afa0-11e8-921d-42d03a7031bb.gif)

**Comment by CiprianGeorgiu** [comment]
Verified as fixed on 62.0 (20180830143136) under Windows 10 x64, macOS 10.13 and Ubuntu 16.04 x64.
