### ISSUE TITLE
You can subscribe with an email that contains a typo 

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#321]
[Affected versions]:
- Firefox 62.0
- Firefox 63.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Access this link: https://fx-breach-alerts.herokuapp.com/
2. Click on the "Subscribe" button.
3. In the email field write an email address that contains a typo (e.g. test@gmsil.com). 

[Expected result]:
- An error that the email address is invalid or asking if the user wanted to write "@gmail.com" is displayed.

[Actual result]:
- The subscription is done successfully. 

[Regression]:
- I don't think this is a regression.

[Notes]:
- Please look at the attached gif.

![peek 2018-09-03 17-45](https://user-images.githubusercontent.com/42799381/44992857-35ae2200-afa1-11e8-8394-1b3c0a111c8d.gif)

**Comment by pdehaan** [comment]
I believe fxa-content-server uses [**mailcheck**](
https://www.npmjs.com/package/mailcheck) to check for some domain typos. We could sync up with them and see how that’s working out, or if they have any other suggestions.
