### ISSUE TITLE
Update Coverage Badge in README

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/blurts-server#3215]

**Comment by nox1134** [comment]
Hi @maxxcrawford! I'd like to take this issue! Can you elaborate more on this?

**Comment by Vinnl** [comment]
Hi @nox1134, I think this issue outdated now - our coverage appears to be 100%, though it's not in reality. (Personally, I also believe the true number is uninformative.) So I'll close this for now, sorry.
