### ISSUE TITLE
The title does not fit to the body in the result page

### ISSUE THREAD

**Issue by xavier-ottolini** [mozilla/blurts-server#3226]
In Firefox Monitor, I entered my personal e-mail address. I clicked on the "Vérifier mes fuites de données" button (it means en English : check my data leaks).

Result
Title : Nous avons détecté <my e-mail address> dans 1 fuite de données
(means en English: We have found <my e-mail address> in 1 data leak)
Body : Bonne nouvelle ! Aucune fuite de données connue n’a été trouvée. Restez en sécurité en vous inscrivant aux alertes lors de nouvelles fuites de données. Nous continuerons à surveiller cette adresse e-mail et vous informerons si elle apparaît dans une nouvelle fuite de données.
Means in English : Good news! No known data leaks have been found. Stay safe by signing up for new data leak alerts. We will continue to monitor this e-mail address and inform you if it appears in a new data leak

Expected result:
The body should display the web site where the data leak occured.
![Screenshot 2023-07-18 at 05-43-02 Firefox Monitor](https://github.com/mozilla/blurts-server/assets/34165346/9e1b1400-0ba3-4b55-95e4-63fd5a94ceb0)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
