### ISSUE TITLE
"Thank you for your feedback" message is not displayed after the user unsubscribes

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#332]
[Affected versions]:
- Firefox 62.0
- Firefox 63.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Prerequisites]:
You have to be subscribed to Firefox Monitor and have the Unsubscribe page loaded. 

[Steps to reproduce]:
1. Click on the "Unsubscribe" button. 

[Expected result]:
- The user is redirected to "Unsubscribe Confirmation Survey" and then a "Thank you for your feedback" message is displayed.
- https://mozilla.invisionapp.com/share/CBNKNFNJ8E6#/screens/317396218

[Actual result]:
- The user is redirected to the Firefox Monitor home page.

[Regression]:
- I don't think this is a regression.

**Comment by lesleyjanenorton** [comment]
@obotisan @CiprianGeorgiu this is fixed in #312 . Should I notify you when that PR gets merged so this can be retested?

**Comment by obotisan** [comment]
Yes, please. We didn't notice.
Thank you.

**Comment by CiprianGeorgiu** [comment]
Verified fixed on 62.0 under Windows 10 x64, macOS 10.13 and Ubuntu 16.04 x64.
