### ISSUE TITLE
The button “Show More” does not respect the spec’s name

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#333]
[Affected versions]:
- Firefox 62.0
- Firefox 63.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Prerequisites]:
Subscribe with a valid email and confirm the subscription.

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Scan a compromised account.
3. Inspect the “Show More” button.

[Expected result]:
- The button is named "Show 5 More".
- https://mozilla.invisionapp.com/share/CBNKNFNJ8E6#/screens/316184919https://mozilla.invisionapp.com/share/CBNKNFNJ8E6#/screens/316184919

[Actual result]:
- The button is named “Show More” instead of “Show 5 more” as written in the UI spec.

[Regression]:
 - I don't think this is a regression.

**Comment by lesleyjanenorton** [comment]
@obotisan thanks for this, "Show More" is actually now the expected text for this button so I am closing this issue.
