### ISSUE TITLE
The “Verify your subscription” dialog is different from the one in the mock-ups (“Confirm your Account”)

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#334]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Provide a valid email address and click on the “Submit” button.
3. Inspect the “Verify your subscription” dialog.

[Expected result]:
- The dialog contains “...sent to email@email.com” string.
- The dialog contains the “Not in inbox or spam folder? Resend” link.

[Actual result]:
- The dialog does not contain “...sent to email@email.com” string.
- The dialog does not contain the “Not in inbox or spam folder? Resend” link.

[Regression]:
- I don't think this is a regression.

[Notes]:
Please look at the image: https://drive.google.com/file/d/1OCxmYgGpfFrksa9cMVqB--qOIoTK4M-9/view

**Comment by tcinotto** [comment]
Separate issues:
1. Resend button
2. Show email.

**Comment by CiprianGeorgiu** [comment]
@lesleyjanenorton Hi, is this issue supposed to be fixed, I am still seeing the same issue originally reported.
