### ISSUE TITLE
"Close” button inside the “Subscribe to Firefox Monitor” dialog does not have the correct hover state 

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#335]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Click on the Subscribe button.
3. Hover with the cursor over the "Close" button. 

[Expected result]:
- The "Close" button is highlighted with a darker blue color.

[Actual result]:
- The "Close" button is highlighted with a light grey color.

[Regression]:
- I don't think this is a regression.

[Notes]:
Please look at the image: 

![imgpsh_fullsize](https://user-images.githubusercontent.com/42799381/45099606-5f498380-b130-11e8-81d0-cfd8e5a6a0af.png)

**Comment by lesleyjanenorton** [comment]
Fixed in #378

**Comment by CiprianGeorgiu** [comment]
HI @lesleyjanenorton, I have verified this issue on herokuapp and now the "Close" button gets underlined when hovering over it. I just want to make sure that this is the right behavior since looking at the visual specs I can see a different hover state?
