### ISSUE TITLE
The focus in “Subscribe to Firefox Monitor” pop-up is not in the “Subscribe with Email Account” field

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#336]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Click on the “Subscribe” button.
3. Start writing something without clicking in the “Subscribe with Email Account” field. 

[Expected result]:
- The typed text appears in the “Subscribe with Email Account” field. 

[Actual result]:
- Nothing happens.

[Regression]:
- I don't think this is a regression.

**Comment by CiprianGeorgiu** [comment]
Verified fixed on 62.0, under macOS 10.13, Ubuntu 16.04 and Windows 10 x64.
