### ISSUE TITLE
The email report for breached/not breached accounts doesn't respect the UI spec

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#339]
[Affected versions]:
- Firefox 62.0

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox.
2. Go to https://fx-breach-alerts.herokuapp.com/
3. Subscribe with a valid email address (compromised or uncompromised).
4. Click on the "Verify your subscription" link in the Inbox.
5. Observe UI of the email report.

[Expected result]:
- The email report respects the UI spec: https://mozilla.invisionapp.com/share/CBNKNFNJ8E6#/screens/316184936 - breached 
https://mozilla.invisionapp.com/share/CBNKNFNJ8E6#/screens/316184937 - not breached

[Actual result]:
- The email report doesn't respect the UI spec: https://drive.google.com/file/d/1dLIPBDpxCf9soTQroOsm8SzMxUjsbflq/view - not breached

[Regression]:
- I don't think this is a regression.

**Comment by groovecoder** [comment]
I believe this is fixed on https://fx-breach-alerts.herokuapp.com/ now that https://github.com/mozilla/blurts-server/pull/381 and https://github.com/mozilla/blurts-server/pull/388 are merged?
