### ISSUE TITLE
Website logos and informative icons from the email report are not displayed 

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#340]
[Affected versions]:
- Firefox 62.0

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox.
2. Go to https://fx-breach-alerts.herokuapp.com/
3. Subscribe with a valid email address (compromised or uncompromised).
4. Click on the "Verify your subscription" link from Inbox.

[Expected result]:
- The website logos (in case of a brached email report) and the four icons (not breached) from the email report are properly displayed.

[Actual result]:
- The website logos are not displayed in the email report nor the four icons which inform the user about the steps should take for a secured account.
 -- screenshot for the website logos: https://drive.google.com/open?id=1O5bnARvFIGyabmQCeZQ6X9VfVPEvc5Di
 -- screenshot for the informative icons: https://drive.google.com/file/d/1eItvxF2RNkIYNeuI8_xlDfg2U28Fd9d3/view

[Regression]:
- Not a regression.

**Comment by pdehaan** [comment]
I think this was from https://github.com/mozilla/blurts-server/pull/323#issue-213018362

> Still Needed:
> - decision on what to put in place of logo images since thou shalt not send svgs to gmail.

Not sure if something like [**convert-svg-to-png**](https://www.npmjs.com/package/convert-svg-to-png) would work here. Basically when we grab new logos from HIBP servers, we'd need to convert any SVGs to PNGs (for better web+email interop), then delete the possibly now redundant SVGs, run all PNGs though **imagemin** optimizer, and... that may be it.

**Comment by groovecoder** [comment]
This is fixed on https://fx-breach-alerts.herokuapp.com/ with https://github.com/mozilla/blurts-server/pull/388 and https://github.com/mozilla/blurts-server/pull/381
