### ISSUE TITLE
Update channels to match with nimbus ids

### ISSUE THREAD

**Issue by yashikakhurana** [mozilla/blurts-server#3416]
Update FML channels [here](https://github.com/mozilla/blurts-server/blob/main/config/nimbus.yaml#L4-L5) and [here](https://github.com/mozilla/blurts-server/blob/main/config/nimbus.yaml#L19-L22) to `staging` and `production`

rename `beta` -> `staging` and `release` -> `production`

**Comment by rhelmer** [comment]
This is synchronized with https://mozilla-hub.atlassian.net/browse/MNTOR-2176 just FYI. Working on it in https://github.com/mozilla/blurts-server/pull/3420
