### ISSUE TITLE
The warning message remains displayed in the subscribe dialog after is reopened 

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#343]
[Affected versions]:
- Firefox 62.0

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Click on the "Subscribe" button.
3. Enter a random string in the email field.
4. Click the "Submit" button.
5. Close the subscribe dialog.
6. Reopen the subscribe dialog.

[Expected result]:
- The warning message does not remain displayed.

[Actual result]:
- The warning message remains displayed.

[Regression]:
- I don't think this is a regression.

[Additional info]:
- see screencast
![jv6diic](https://user-images.githubusercontent.com/24842369/45109420-2cab8500-b148-11e8-9169-b7c65ffbac0f.gif)

**Comment by lesleyjanenorton** [comment]
fixed in #378

**Comment by CiprianGeorgiu** [comment]
Verified fixed on 62.0, under macOS 10.13, WIn 10 x64 and Ubuntu 16.04 x64.
