### ISSUE TITLE
Add utm campaign params to all links to www.mozilla.org

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#344]
In `download_firefox_banner.hbs` we have `?utm_campaign=ffxmdownloads` in our link to www.mozilla.org.

https://github.com/mozilla/blurts-server/blob/master/views/partials/banners/download_firefox_banner.hbs#L10

We should add that to the other links as well. 

E.g., for the footer: `?utm_source=monitor&utm_medium=website&utm_campaign=ffxmdownloads&utm_content=footer-link` and for the emails: `?utm_source=monitor&utm_medium=email&utm_campaign=ffxmdownloads`

**Comment by groovecoder** [comment]
I'm calling this blocking because tracing our referral traffic to Firefox downloads & aDAU is a Big Important™ thing.

**Comment by peterGerman** [comment]
?utm_source=monitor.firefox.com&utm_medium=referral&utm_campaign=fx_monitor_downloads&utm_content=footer-link

?utm_source=email&utm_medium=email&utm_campaign=fx_monitor_downloads&content=[LuketoAddDescription - ie. monitor_welcome_email, subscribe_to_alerts, etc.]

**Comment by groovecoder** [comment]
Can we send the full domain in the `utm_source` ? I.e., `utm_source=https://monitor.firefox.com`

**Comment by peterGerman** [comment]
Could you remove it with regex? It would be more consistent with everything
in GA.
