### ISSUE TITLE
Emails: Add links to download Firefox

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#345]
Hmm ... the email seem like a great channel for continuing to reach other browser users. Should we include a "Download Firefox" section to them?

**Comment by chsiang** [comment]
Response from legal- We can’t include a download fx button in the emails. We can only send what we tell people they are signing up for.  We can’t send fx promotions unless we get their consent.
I'd recommend to keep the email simple for MVP and we can have download Firefox embedded into security tips when we have features directly tied to Firefox.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
