### ISSUE TITLE
Differences between dev and stage regarding the auto-populated message when clicking on the Tweet button

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#348]
[Affected versions]:
- latest Nightly 64.0a1
- Beta 63.0b3
- Release 62.0

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox.
2. Go to https://fx-breach-alerts.herokuapp.com/
3. Click on the "Tweet" button from the upper right side of the page.

[Expected result]:
- The following message is auto-populated in textarea: "Find out if your email addresses have been hacked at https://monitor.firefox.com." - as it happens on the stage website.

[Actual result]:
- The following message is auto-populated in textarea: " https://fx-breach-alerts.herokuapp.com".

[Regression]:
- Not a regression.

[Additional info]:
- see screenshot below.
![screenshot_2](https://user-images.githubusercontent.com/24842369/45118960-abadb700-b162-11e8-8a98-0985b4bcdc55.png)

**Comment by lesleyjanenorton** [comment]
hey @CiprianGeorgiu , unless I am mistaken this is the desired result. It's not until you actually click Tweet that the image and correct phrasing pops up. Currently, when I click the twitter button from https://fx-breach-alerts.herokuapp.com/ I see about the same screen you posted a shot of, but then when I click "Tweet" this is what turns up:
<img width="597" alt="screen shot 2018-09-08 at 7 47 35 pm" src="https://user-images.githubusercontent.com/22355127/45260008-5fe85100-b3a0-11e8-87e8-f9abfd4492fd.png">

**Comment by CiprianGeorgiu** [comment]
Thanks @lesleyjanenorton for the clarifications. In this case I will close this issue.
