### ISSUE TITLE
"Error: Token not found" is triggered on website if the user unsubscribes then verifies the subscription again 

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#353]
[Affected versions]:
- latest Nightly 64.0a1
- Beta 63.0b3
- Release 62.0

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox.
2. Go to https://fx-breach-alerts.herokuapp.com/
3. Subscribe with a email address.
4. Click on the "Verify Your Subscription" button from confirmation email.
5. Click on the "Unsubscribe" button from the confirmation email.
6. Click again the "Unsubscribe" button from the webpage.
7. Repeat step 4.

[Expected result]:
- "Confirmed! You're Subscribed" page is displayed or a message saying that the user is already subscribed.

[Actual result]:
- The following error is triggered on the page: `Error: Token not found
    at Object.verifyEmailHash (/app/db/DB.js:54:13)`

[Regression]:
- Not a regression.

[Additional info]:
- see screenshot:
![screenshot_4](https://user-images.githubusercontent.com/24842369/45122409-642c2880-b16c-11e8-95ee-25d4161594d3.png)

**Comment by groovecoder** [comment]
I can improve the error message and the display, but we can't verify the user after they've unsubscribed: when they unsubscribe, we remove all their data completely - including their verification token. And we don't want to keep any of their data after they unsubscribe.

**Comment by CiprianGeorgiu** [comment]
Verified fixed on 62.0, across platforms: Windows 10 x64, macOS 10.13 and Ubuntu 16.04 x64.
