### ISSUE TITLE
Tweet message is not properly posted on herokuapp

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#356]
[Affected versions]:
- latest Nightly 64.0a1
- Beta 63.0b3
- Release 62.0

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox.
2. Go to https://fx-breach-alerts.herokuapp.com/
3. Click on the "Tweet" button from the upper right side of the page.
4. Click on "Tweet" button in order to post the message.
5. Observe the tweet posted on website.

[Expected result]:
- The Firefox logo is properly displayed on Twitter and it contains the following message: "Have your accounts been leaked or stolen in a data breach? Find out at Firefox Monitor. Search our database and sign up for alerts."

[Actual result]:
- The tweet is not properly displayed on Twitter; the Firefox logo contains a placeholder and the message is: "Protect yourself from hackers".

[Regression]:
- This seems to be a regression since on stage is not repro.

[Additional info]:
- see screencast
![screenshot_1](https://user-images.githubusercontent.com/24842369/45148869-ec441980-b1d0-11e8-858c-c38b07dc56b4.png)

**Comment by CiprianGeorgiu** [comment]
I cannot seem to reproduce this bug anymore on https://fx-breach-alerts.herokuapp.com/ with 62.0 across platforms. Closing this as WFM.

**Comment by pdehaan** [comment]
Another interesting tool I found this morning:
https://social.pilcro.com/

Here's the current output w/ the dev Heroku site URL:

![https___social_pilcro_com-heroku](https://user-images.githubusercontent.com/557895/45569170-8b8d9000-b813-11e8-8d45-1b8ee17432d4.png)
