### ISSUE TITLE
The images are missing from the “Verify your subscription for Firefox Monitor” and "Your Firefox Monitor report" emails

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#359]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Click on the "Subscribe" button and write a valid email.
3. Inspect the “Verify your subscription for Firefox Monitor” email.

[Expected result]:
- The image for Firefox Monitor is displayed.
- There mail looks something like this:
![imgpsh_fullsize 1](https://user-images.githubusercontent.com/42799381/45160253-a9466e00-b1f1-11e8-8755-f2cb09942f61.png)

[Actual result]:
- The image for Firefox Monitor is missing.
- The email looks something like this:
![imgpsh_fullsize 2](https://user-images.githubusercontent.com/42799381/45160296-c8450000-b1f1-11e8-82a8-94d3936a6a8a.png)

[Regression]:
- I don't think this is a regression.

[Notes]:
- Also this issue appears in the "Your Firefox Monitor report" email with the logo for Mozilla. 

- When you subscribe with an email.
![imgpsh_fullsize 3](https://user-images.githubusercontent.com/42799381/45160547-6df86f00-b1f2-11e8-9a79-7722342f9cb9.png)

- When you subscribe with sync:
![imgpsh_fullsize 4](https://user-images.githubusercontent.com/42799381/45160550-70f35f80-b1f2-11e8-9541-f409e3d4a690.png)

- This happens both with gmail and yahoo accounts.

**Comment by groovecoder** [comment]
This should be fixed on https://fx-breach-alerts.herokuapp.com/ now that https://github.com/mozilla/blurts-server/pull/381 and https://github.com/mozilla/blurts-server/pull/388 are merged?
