### ISSUE TITLE
Add ESLint rule to prevent usage of process.env.foo

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#36]
Environment variable usage should be done via AppConstants.

**Comment by pdehaan** [comment]
Ref: [**no-process-env**](https://eslint.org/docs/rules/no-process-env)

**Comment by nhnt11** [comment]
Yeah, I made those specifically use process.env for now since they are debug flags and should not be mandatory to include in .env. We can probably modify app-constants.js to better handle debug flags.
