### ISSUE TITLE
 The breached accounts are not correctly arranged on the page if the browser is resized

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#362]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Provide a valid email address and click on the “Scan” button.
3. Resize the browser so that it has the minimum width. 
4. Click on "Show More" button.
5. Expend the browser again. 

[Expected result]:
- The breached accounts are correctly arranged on the page.

[Actual result]:
- The breached accounts are not correctly arranged on the page. 

[Regression]:
- I don't think this is a regression.

[Notes]:
Please look at the image:
 
![imgpsh_fullsize 6](https://user-images.githubusercontent.com/42799381/45163873-f29abb80-b1f9-11e8-9dda-20b919de729d.png)

**Comment by CiprianGeorgiu** [comment]
I cannot longer see this issue using the STR form description, but it seems that now, following the same steps I encounter another problem which is tracked in #398.

Since I filed another bug for the current behavior I will close this as verified fixed.
