### ISSUE TITLE
The "Show more" and "Subscribe" buttons are not correctly positioned in the page if the browser is resized

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#363]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Provide a valid email address and click on the “Scan” button.
3. Resize the browser so that it has the minimum width. 

[Expected result]:
- The "Show more" and "Subscribe" buttons are correctly positioned in the page.

[Actual result]:
- The "Show more" and "Subscribe" buttons are not correctly positioned in the page.

[Regression]:
- I don't think this is a regression.

[Notes]:
Please look at the image:
 
![imgpsh_fullsize 5](https://user-images.githubusercontent.com/42799381/45163449-232e2580-b1f9-11e8-9a0f-c7b98b315bed.png)

**Comment by e-pang** [comment]
i can't seem to reproduce this issue?
