### ISSUE TITLE
More technical detail please

### ISSUE THREAD

**Issue by nsweaney** [mozilla/blurts-server#374]
I understand the basics of how the account lookup works by talking to groovecoder, but there's nothing on the site that explains the technical details. My grandmother may not need that level of detail, but if I recommend this site to a client they should be able to review the process of what's exactly is being done. 

I'd suggest adding a simple link on the page somewhere that says something like "How this works" or "Technical Details" and then outline the process. Here are a few relevant data points off the top of my head:

1. What you're doing with the addresses, how they're being used, stored, etc, what exactly is the user signing up for when they provide their address. 
2. Where the compromised data comes from, how extensive it is, how recent it is, etc.
3. What the relationship is with HIBP, what access does it have to the provided addresses, what's the retention policy.
4. For the alerts, how often will that be checked, does mozilla send account data to HIBP regularly, or are the updates checked some other way, etc.

Some of that detail is probably also necessary for GDPR & other compliance requirements. folks have to affirmatively consent to specific use-cases for their data, and have to understand what they're consenting to.

**Comment by groovecoder** [comment]
Thanks @nsweaney. We'll triage this in our next triage meeting.

**Comment by groovecoder** [comment]
It was triaged as a "content" issue with "Normal" priority on Sep 10. As you can imagine, we're getting lots of feedback from lots of channels since launch last week, so it will take us a little bit to consolidate it all.

**Comment by jens1o** [comment]
Yeah, no pressure. :) I just wondered whether the meeting happened. I would have expected that you (for example) add an issue label with the priority after the meeting, so we know it's  triaged. :)

**Comment by groovecoder** [comment]
Been using the "QA: ___" labels as priority labels. That may change though ...

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
