### ISSUE TITLE
Log client-side errors to Google Analytics

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#384]
See https://github.com/mozilla/blurts-server/pull/378/files#r216159296

Possible implementation:
https://davidwalsh.name/track-errors-google-analytics

**Comment by pdehaan** [comment]
Is GA any better than using something like [Sentry](https://sentry.io/for/javascript/)?

**Comment by groovecoder** [comment]
Not necessarily ... just avoids another platform to check. I'll ask ops about deploying Sentry for stage & prod.

**Comment by EMMLynch** [comment]
We are using Sentry for this now.
