### ISSUE TITLE
Define (and hopefully automate) process for uploading PNG logos

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#387]
Many email clients do not display SVGs.

In https://github.com/mozilla/blurts-server/pull/381 we add PNGs for existing breach logos so that the Report emails will display them.

But we need a process for uploading PNG logos for new breaches so the breach notification emails will render them nicely.

Some options:
* Ask Troy to publish PNG logos for all breaches; copy them to our own service (s3?) when we are notified of a new breach
* Fetch and convert SVG logos to PNGs whenever we are notified of a new breach

**Comment by pdehaan** [comment]
@lesleyjanenorton How are you handling logos for new breaches currently?
What tool(s) were you using to convert from GIF/JPG/SVG into PNG?

**Comment by lesleyjanenorton** [comment]
Currently, I'm grabbing them from HIBP as needed. Tools and processes for converting have been many and varied and inefficient. The last batch was combination of Inkscape, Photoshop, Illustrator, and TinyPNG.

**Comment by pdehaan** [comment]
![](https://i.giphy.com/media/l2QE1bH4wvCE8CcTK/giphy.gif)

**Comment by lesleyjanenorton** [comment]
exactly

**Comment by groovecoder** [comment]
Filed https://github.com/mozilla/blurts-server/issues/402 for a default breach site icon to use.

**Comment by pdehaan** [comment]
Here was my CLI script for downloading all the logos from HIBP.
Verified w/ the new `LogoPath` API and @lesleyjanenorton's fancy RegExp for extracting filenames from the full path.

```js
const fs = require("fs");
const path = require("path");
const got = require("got");

downloadLogos();

async function downloadLogos(outputDir="./public/img/logos") {
  const breaches = await downloadBreaches();
  const logos = new Set();
  for (const breach of breaches) {
    // Add the logos to a set so they are deduped and we don't have to download
    // "List.png" and "Email.png" more than once (saves about 14 requests).
    logos.add(breach.LogoPath);
  }
  for (const logo of logos) {
    const filename = /[^/]*$/.exec(logo)[0];
    const outputFile = path.join(outputDir, filename);
    // Only download the image if it doesn't already exist on disk. Not super
    // efficient since it will cause about 325 disk IO operations on each sync.
    // Possibly better to check the `ModifiedDate` to see if this is a new
    // breach since the last sync.
    if (!fs.existsSync(outputFile)) {
      console.log(`Downloading ${outputFile}...`);
      await downloadLogo(logo, outputFile);
    } else {
      // console.log(`Skipping ${outputFile}`);
    }
  }
}

async function downloadBreaches(server="https://haveibeenpwned.com/api/v2/breaches") {
  const res = await got.get(server, {json: true});
  return res.body;
}

async function downloadLogo(logoUrl, outputFile) {
  return await got.stream(logoUrl)
    .pipe(fs.createWriteStream(outputFile));
}
```

**Comment by lesleyjanenorton** [comment]
closing in favor of #1469
