### ISSUE TITLE
Automatically populate email address in subscribe modal

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#395]
If the user clicks subscribe after a scan, it would be nice to auto-fill the email address they just scanned. We can stash the email in sessionStorage at scan-time and use that to populate the textbox when the modal is shown.

**Comment by groovecoder** [comment]
Closed in https://github.com/mozilla/blurts-server/pull/396

**Comment by groovecoder** [comment]
Re-opening, as #396 didn't merge to master, and we need to consider our "Your email will not be stored." before we make this change.

**Comment by lesleyjanenorton** [comment]
Closing since the modal will soon be disappearing and we are now populating the scanned email in the FxA flow.
