### ISSUE TITLE
Add eslint rule to enforce trailing commas in object definitions

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#40]
PRESERVE ALL THE BLAME

**Comment by pdehaan** [comment]
I think that'd be the [`comma-dangle`](https://eslint.org/docs/rules/comma-dangle) rule.
Seems infinitely customizable, but this may be a good starting point:

```js
"comma-dangle": ["error", {arrays: "always-multiline", objects: "always-multiline"}],
```

Or there is the less strict `"only-multiline"` option as well.

**Comment by nhnt11** [comment]
Let's do `only-multiline`. Want to take this? :)

**Comment by pdehaan** [comment]
@nhnt11 Submitted #44, which also added **eslint-plugin-node** plugin, which should catch deprecated APIs (assuming Node 8+ support, per new package.json `engines` version).
