### ISSUE TITLE
Incorrect Firefox mobile download links

### ISSUE THREAD

**Issue by e-pang** [mozilla/blurts-server#405]
Mobile download links should lead to respective app stores as opposed to www.mozilla.org/en-US/firefox/

**Comment by groovecoder** [comment]
Are we still going to try to change the links to go straight to the app stores?

**Comment by e-pang** [comment]
yes, if possible that would be great!

**Comment by lesleyjanenorton** [comment]
Closing since these links are no longer on the website.
