### ISSUE TITLE
There is no space left between the resend link and close button in "Verify Your Subscription" dialog 

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#409]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Ubuntu 16.04 x64

[Prerequisites]:
- have the "Verify Your Subscription" dialog open

[Steps to reproduce]:
1. Inspect the "Verify Your Subscription" dialog 

[Expected result]:
- There is a space left between "Not in inbox or spam folder? Resend" and "Close" button.

[Actual result]:
- There is no space left between "Not in inbox or spam folder? Resend" and "Close" button.

[Regression]:
- I think this is a regression.

[Additional info]:
- See screenshot below
![capturesfs](https://user-images.githubusercontent.com/24842369/45486311-49a51100-b763-11e8-8044-0c9ed5cac7d3.png)
- Note that this issue will be fixed in #407

**Comment by lesleyjanenorton** [comment]
Thanks Ciprian, this will be fixed when #407 gets merged.

**Comment by lesleyjanenorton** [comment]
Fixed in #407 and verifiable on the heroku page.
