### ISSUE TITLE
"Scan Another Email" button does not match the specs name

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#413]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Ubuntu 16.04 x64

[Prerequisites]:
- have Firefox Monitor report displayed

[Steps to reproduce]:
1. Inspect the "Scan Another Email" button.

[Expected result]:
- The "Scan Another Email" button is named "Scan another email in Firefox Monitor".

[Actual result]:
- The "Scan Another Email" is not named "Scan another email in Firefox Monitor".

[Regression]:
- I think this is a regression.

**Comment by lesleyjanenorton** [comment]
Also fixed in #407

**Comment by lesleyjanenorton** [comment]
Fixed in #407 and verifiable on Heroku page.

**Comment by pdehaan** [comment]
This is what I see in the email from the Heroku site:

<img width="1044" alt="blurts" src="https://user-images.githubusercontent.com/557895/45766514-a46bbc00-bbec-11e8-8b2d-1dacd5161c7f.png">
