### ISSUE TITLE
"Terms and Privacy" doesn’t have a valid link

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#427]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Go to the bottom of the page.
3. Click on "Terms and Privacy".

[Expected result]:
- The "Terms and Privacy" page is opened.

[Actual result]:
- A "404: Page Not Found" error page is opened.

[Regression]:
- I think this is a regression.

[Notes]:
Please look at the image:
![123](https://user-images.githubusercontent.com/42799381/45760812-95f4c300-bc33-11e8-9208-057154ad9cf0.png)

**Comment by pdehaan** [comment]
Cindy Hsiang to follow up on the exact URL.

**Comment by groovecoder** [comment]
This will be fixed when bedrock teams pushes it live: https://github.com/mozilla/bedrock/issues/6205

**Comment by groovecoder** [comment]
This is fixed now. https://www.mozilla.org/en-US/privacy/firefox-monitor/ is up.
