### ISSUE TITLE
Add new icon/favicon

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#436]
Saw the new logo on Slack, but not 100% certain all the places we need to update it (so that QA can have a list of things to verify -- ie: emails, social meta tags, etc).

**Comment by lesleyjanenorton** [comment]
So the instructions from Cherry were 1.) to use the new logo (icon on almost-white circle) throughout (emails, social media images, website etc). 

New logo :
<img width="300" alt="screen shot 2018-09-20 at 9 39 19 pm" src="https://user-images.githubusercontent.com/22355127/45857419-2ad3eb00-bd1e-11e8-8782-a6d6dc8c9149.png">

And 2.) replace the existing favicon with the new icon on a transparent background and no white circle. 
<img width="125" alt="screen shot 2018-09-20 at 9 45 53 pm" src="https://user-images.githubusercontent.com/22355127/45857567-ee54bf00-bd1e-11e8-827d-37bc7dc00615.png">

Things for QA to verify would be: 
-The new icon appears next to Firefox Monitor in the website header and email headers. 
-The reworked site image appears with the new icon on social media shares.
-The new favicon appears in the tab.

**Comment by groovecoder** [comment]
This is fixed by https://github.com/mozilla/blurts-server/pull/437
