### ISSUE TITLE
Delay showing "Resend email" link for X seconds?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#447]
When subscribing to Breach Alerts, you get a dialog box saying "Not in inbox or spam folder? Resend", which will presumably resend the confirmation email. Not sure if we want to use some CSS+JS to delay displaying that link for X seconds/minutes to avoid people getting too impatient and trying to resend an email instead of waiting 30 seconds for it to arrive in their inbox.

![firefox_monitor](https://user-images.githubusercontent.com/557895/45976674-4714a800-bffc-11e8-8d63-03a355929fa6.png)

**Comment by lesleyjanenorton** [comment]
Closing since this is the old UI.
