### ISSUE TITLE
"Enter Email Address" vs "Enter email"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#453]
Just noticed the placeholders are different for the "Enter Email Address" field when doing a scan vs "Enter email" when signing up for the newsletter.

![firefox_monitor](https://user-images.githubusercontent.com/557895/45997584-f9785980-c054-11e8-9f1a-a7b254e532a4.png)

**Comment by lesleyjanenorton** [comment]
This is in keeping with the spec - do we want to update these to be the same?

**Comment by lesleyjanenorton** [comment]
Closing since there are no longer any instances of "Enter email".
