### ISSUE TITLE
var vs let vs const, oh my!

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#46]
We have [arguments against `const`](https://github.com/mozilla/blurts-server/pull/38#discussion_r167476992) and arguments for `const`, let's have a 🔪 and 🔫 fight and settle this once and for all and see if we can find an ESLint rule that will support whatever we go with.

So this is a "needs discussion" but now shouldn't be a blocker on the current open PR.

**Comment by groovecoder** [comment]
If only one of them can be enforced via `eslint` that will probably make up my mind. @pdehaan do you know if `eslint` can support one of these and not the other?

**Comment by nhnt11** [comment]
I believe the prefer-const rule can do this. Happy to submit a PR when I'm
back at my desk.

**Comment by pdehaan** [comment]
Only one I'm aware of is [`prefer-const`](https://eslint.org/docs/rules/prefer-const), which will try and make everything a `const` if it is never reassigned. Plus, it will try and make every `for..in` and `for..of` loop a `const` (which isn't a problem, but IIRC Firefox had a bug about that a long time ago, although is a Node-only app for now). Although we _could_ override specific instances by littering `// eslint-disable-next-line prefer-const` if we wanted.

**Comment by pdehaan** [comment]
@nhnt11 I enabled `prefer-const` in #47, but then stupidly threw a bunch of other unrelated tweaks in the PR while I was at it.

**Comment by pdehaan** [comment]
Does anybody have any mild/strong objections to our current `let` vs `const` decisions, or can we close this issue?

**Comment by nhnt11** [comment]
Let's close this.
