### ISSUE TITLE
https://monitor.firefox.com/scan is blank on new email

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/blurts-server#462]
The page is blank when i put a new, never seen email.
after a few minutes of reloading it eventually returns the data instead of just a blank page.

I tried with different unique / never used emails

**Comment by groovecoder** [comment]
We have a rate limit on the `/scan` endpoint to prevent abuse. We're increasing it now, and may need to keep increasing it for launch day splash + growth.

We will also consider adding some client-side rate limit code with a friendlier UX.

**Comment by groovecoder** [comment]
Increasing the rate limit helped with the 429 errors. Investigating more options too ...

![screen shot 2018-09-25 at 3 30 52 pm](https://user-images.githubusercontent.com/71928/46041380-3e919f80-c0d8-11e8-9d47-83cd4ca2c4a7.png)

**Comment by groovecoder** [comment]
The fixes are holding. Closing this. 
![screen shot 2018-09-25 at 3 53 25 pm](https://user-images.githubusercontent.com/71928/46043456-b4e4d080-c0dd-11e8-9fc8-4040fa8fe625.png)
