### ISSUE TITLE
Link password manager names to their respective sites?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#463]
Ref: https://github.com/mozilla/blurts-server/pull/123#pullrequestreview-124151790

Currently we seem to be displaying password manager names in two places.

![firefox_monitor](https://user-images.githubusercontent.com/557895/46041370-7217fe00-c0c7-11e8-957a-d478f0fde091.png)

**Figure 1:** /tips.js:27

https://github.com/mozilla/blurts-server/blob/c7560a146198b3fdc4266be2ddcaa2de57da7745/tips.js#L27

![blurts-results](https://user-images.githubusercontent.com/557895/46041531-d9ce4900-c0c7-11e8-8456-8ba54148b9b5.png)

**Figure 2:** /views/partials/what_to_do.hbs:14

https://github.com/mozilla/blurts-server/blob/cd378493ddad5f380187ca49bf35fa6c6986796d/views/partials/what_to_do.hbs#L14

We also recently had a request (ref: #459) to add Bitwarden to the list. I feel like it'd be a nice touch/courtesy to add `<a href="">` links to each of those sites. We could open them in new tabs using `target="_blank"` and do noopener and noreferrer and nofollow or whatever else we think makes sense. But we could also add some GA around the outbound links to try and see how many people are actively going out to those sites using the links.
Currently users have to copy/paste and type the product name into Gmail/Bing/AskJeeves and try and find the official site, which is kind of a drag.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
