### ISSUE TITLE
Implement error codes

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#464]
To help with error handling and mozlog, we should implement app-specific error codes & messages. E.g.,

`controllers/hibp.js`:
```js
const HIBP_ERRORS = {
  "100": {code: 100, message: "HIBP notify endpoint requires valid authorization token."},
  "101": {code: 101, message: "HIBP notify endpoint requires breachName, hashPrefix, and hashSuffixes."},
  "102": {code: 102, message: "Unrecognized breach."},
}
```
Then we could export to make them available to other code ...
```js
module.exports = {
  notify,
  breaches,
  HIBP_ERRORS
}
```
and we can `mozlog` e.g., ... 
`server.js`:
```js
log.error("error", HIBP_ERRORS.100}
```
or in `middleware.js` ...
```js
log.error("error", HIBP_ERRORS.102, stack: err.stack});
```

**Comment by pdehaan** [comment]
Wow, curious if `HIBP_ERRORS.102` syntax would work, or be a syntax/linting error.
Or, if we use something more verbose, like `HIBP_ERRORS.InvalidAuthToken` For the keys
