### ISSUE TITLE
Publish HIBP breach data to Remote Settings service

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#465]
See https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=66655528 for getting access to publish to kinto-settings/Remote Settings.

See https://kinto.readthedocs.io/en/latest/tutorials/first-steps.html for docs on publishing.

**Comment by pdehaan** [comment]
From Slack chat today:

@pdehaan says:
> @groovecoder is the plan to have the server use the same Kinto/RemoteSettings endpoint as the add-on? or is that a V2/future thing?

@groovecoder:
> Interesting … do you know if Remote Settings supports web(site) clients?

@pdehaan: 
> Not sure. I was reading https://remote-settings.readthedocs.io/ and thought RemoteSettings was just a wrapper around Kinto. But maybe it isnt that simple.

> I just figured if it was possible, it may be easiest to all pull the breach data from the same bucket so things are always in sync, and the add-on doesn’t know about a breach before the server.

@nhnt11:
> great idea I think. To be fair, the way it's set up now, the server is the one that has chances of knowing about breaches before the addon. We don't have automation in place to update the kinto collection yet. But I think it would be a good long term setup to make a bot that syncs kinto, and the addon as well as the server can rely on kinto as the source of truth. We don't need to change much, I think. The kinto endpoint serves the data as JSON very similar to HIBP. One change we'll need to make is the actual data we're storing on kinto- currently it omits stuff like data classes that the website depends on.

---

I know [**mozilla/notes**](https://github.com/mozilla/notes) uses [**kinto-http**](https://github.com/Kinto/kinto-http.js/blob/master/README.md), but not sure about if RemoteSettings and kinto-http are interchangeable.

**Comment by groovecoder** [comment]
We could do this in [hibp.js](https://github.com/mozilla/blurts-server/blob/master/controllers/hibp.js) when HIBP sends us breach load callbacks.

**Comment by groovecoder** [comment]
Based on today's meeting, we will add this script to our repo and have Ops set up a scheduled job to run it.

**Comment by sandysage** [comment]
@nhnt11 now that the FxA integration has landed, can we pick this back up? I _believe_ we have some working code that would address this. Is there already a branch or pull request?

**Comment by groovecoder** [comment]
This is done early last month.
