### ISSUE TITLE
Firefox Monitor could also check email aliases

### ISSUE THREAD

**Issue by madb1lly** [mozilla/blurts-server#467]
Hi,

I used this today - oh dear, poor me! A very useful tool thanks. Here's a suggestion to improve it even more:

I tested and found that Firefox Monitor does not consider standard email alias constructions for webmail services like Gmail and Hotmail. E.g. the Gmail methods of entering a "." in the username or "+something" are not checked by Firefox Monitor.

Can this functionality be added? I don't mean searching every permutation, that would be impossible, but at search "u.sername", "us.ername", etc and for "username+".

Thanks for considering :)

**Comment by ryanwinchester** [comment]
Yes, I use `myname+sitename@example.com` for almost every site I sign up for. 🤐

**Comment by groovecoder** [comment]
This would be quite difficult. The emails are looked up via hash - we don't have the breach datasets with plaintext email addresses.

Even if haveibeenpwned.com had a wildcard API, we wouldn't be able to use it with k-Anonymous hash range queries. 😢

**Comment by ryanwinchester** [comment]
Could you strip the `+foo` section of the email in both the query and in the datasets*?

*_(I know this is probably kind of stupid and would probably be an unreasonable amount of work, and you'd probably want both versions still, but would be helpful, and thought I'd ask anyway)_

**Comment by madb1lly** [comment]
Hi Firefox Monitor team, what is the progress on this? I'm using +tags for all new accounts now where possible and I can't realistically add them all to Firefox Monitor. I know I'm not the only one so an update would be nice :)
Cheers

**Comment by madb1lly** [comment]
Ah, that's unfortunate. And without knowing how the upstream source is structured we can't really help can we?

Your suggestion for automatically adding to Firefox Monitor via Lockwise is a great one. In first use if it could upload all current logins it would be even better! Is this already on the roadmap?

**Comment by groovecoder** [comment]
Since scans and subscriptions are based on hash range queries, we can't predictably and reliably scan or subscribe `+` aliases or other address schemes like various `.` characters. Closing this issue unless/until our breach data endpoint supports such a feature.

**Comment by madb1lly** [comment]
Hi @groovecoder,
Thank you for the update and explanation, which makes sense.
If Firefox Monitor could (optionally) automatically add these aliases to the checklist that would be great. You said there is a combined roadmap for Lockwise and Monitor, so is this or a similar feature included in the near future?
Cheers :)

**Comment by groovecoder** [comment]
Sorry, not in the near future. Every form of every email address has to be scanned & subscribed separately, so generating scans & subscriptions for every permutation of `.` and `+` characters would exponentially increase our storage, bandwidth, and number of API calls.

**Comment by madb1lly** [comment]
Hi @groovecoder maybe I didn't explain myself properly. 

I mean, each time Lockwise records a new unique email address being used (treat all aliases and subaddressing as a new address) then give the customer the option to add it to Firefox Monitor. This wouldn't cover every possible permutation, only those ones which Lockwise identifies being used.

Cheers :)

**Comment by groovecoder** [comment]
Oh, yes, we have dicussed a feature like that. I've filed 2 bugs for it:

https://bugzilla.mozilla.org/show_bug.cgi?id=1604823
https://bugzilla.mozilla.org/show_bug.cgi?id=1604820

**Comment by madb1lly** [comment]
Upvoted! Thanks for the links 🙂
