### ISSUE TITLE
Make a nicer rate-limited error page

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#468]
Ops is sending 429 responses with empty content to users who hit the rate limit on scans. We should give them a static HTML page to send with the 429 responses.

**Comment by mheubusch** [comment]
Proposed error message: Monitor is fast, but not that fast. Please wait a few seconds and try again.

**Comment by pdehaan** [comment]
Sorry, what was the logic around this?
A specific user is scanning `X` different addresses with `Y` searches per `Z` minutes and then gets put into a 429 penalty box?

**Comment by groovecoder** [comment]
@pdehaan yeah - there's a rate limit on the `/scan` endpoint to prevent abusive actors from using it to execute massive and fast account enumeration. I suspect the clients actually receiving these 429's are non-GUI clients, so they're unlikely to actually see this.

This is just the message some real users might see.

**Comment by groovecoder** [comment]
This is now live on prod!

**Comment by pdehaan** [comment]
Is there a way I can force myself to get that 429 page? Is there a direct page URL or something in /dist/ I can view on prod?

**Comment by groovecoder** [comment]
https://monitor.firefox.com/429.html

or you can reload `/scan` really fast to trip the rate limit.
