### ISSUE TITLE
 Firefox Monitor results inconclusive

### ISSUE THREAD

**Issue by fethomm** [mozilla/blurts-server#472]
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Steps to reproduce:**
I checked an email address on monitor.firefox.com. 

**Actual results:**

The address came out clear. Then I registered the same address with the service and after confirming, got an email, saying the address was compromised. I reproduced the diverging result by registering the same address again (which should not even work afaic) Results were inconclusive again.

**Expected results:**

Both results should have been the same, either compromised, or not.

**Comment by groovecoder** [comment]
Thanks for the feedback @fethomm. When you sign up you get a "full report" including sensitive breaches.

We only include the sensitive breaches in the email report, so we don't disclose sensitive breaches on the public results.

**Comment by pdehaan** [comment]
Ah, great issue!
Currently the discrepancy between the web scan and email report are intentional, but we should probably improve the web messaging to make this a lot clearer.

Currently if I search a email address with zero breaches, the website tells me:

> **So far, so good**
> Your account did not appear in our basic scan. That's good news, but data breaches can happen any time and there is still more you can do. Subscribe to Firefox Monitor for a full report, alerts when new breaches happen, and tips on protecting your passwords.

And the output from a scan with breached accounts says:

> **This might be a problem**
> Your accounts were compromised in the following breaches.

I believe in both cases we should probably make it more obvious that the website doesn't include sensitive breach information and other results that are included in the full email report.
I'll file a separate issue for the UI/UX team to come up with some additional words to make our intentions/results more transparent.

**Comment by pdehaan** [comment]
Submitted #475; __"Make it more obvious that the "basic" web scan doesn't include the full results"__ to make the distinction between a "basic scan" and "full report" a bit more obvious.

**Comment by gaby2300** [comment]
I checked an email address on monitor.firefox.com. Some of my accounts appeared to be compromised so I changed their passwords.
The weird thing was that accounts I never had were also compromised. 
Should I open a new issue?

**Comment by pdehaan** [comment]
@gaby2300 Interesting. Yes, create a new issue for that and include as much information as possible and we can investigate. Thanks!

**Comment by groovecoder** [comment]
@gaby2300 you may have seen the issue in this bug: https://github.com/mozilla/blurts-server/issues/479

**Comment by gaby2300** [comment]
@groovecoder yes, I think it may be the following case:
https://www.troyhunt.com/why-am-i-in-a-data-breach-for-a-site-i-never-signed-up-for/  
Should I add a comment to that bug then?

**Comment by groovecoder** [comment]
Yes please add a comment and a 👍 to that issue.

**Comment by gaby2300** [comment]
@groovecoder I am sorry, what does the thumb up icon mean in this case and how do I add it?
