### ISSUE TITLE
Change breach notification email image to real image

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#473]
Noticed this while testing the breach notification on stage ...

![screen shot 2018-09-26 at 3 53 07 pm](https://user-images.githubusercontent.com/71928/46108734-5898b400-c1a4-11e8-8a5d-e68e18d403d3.png)

It may take some trickery, but I think we can do this:

1. Change the img `src` to be what the *real* breach image url will be when we upload it
2. Configure nginx to default to serve `/public/img/email_images/missing-logo-icon.png` instead of `404`s from `/public/img/logos`

That way, users who open the email before we upload the breach image will see `missing-logo-icon.png`, but users who open the email after we upload the breach image will see the breach image.

**Comment by Shivansh2407** [comment]
What needs to be done here?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
