### ISSUE TITLE
Respond with 401 status code on /hibp/notify

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#474]
STR:
`curl -v --data "" -H "Content-Type: application/json" -H "Authorization: Bearer unsafe-default-token-for-dev" https://blurts-server.stage.mozaws.net/hibp/notify`

Expected Results:
```
< HTTP/1.1 401 Unauthorized
...
{"message":"HIBP notify endpoint requires valid authorization token."}
```
Actual Results:
```
< HTTP/1.1 500 Internal Server Error
...
{"message":"HIBP notify endpoint requires valid authorization token."}
```

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
