### ISSUE TITLE
Make it more obvious that the "basic" web scan doesn't include the full results

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#475]
Ref: #472 

Currently if I search a email address with zero breaches, the website tells me:

> **So far, so good**
> Your account did not appear in our basic scan. That's good news, but data breaches can happen any time and there is still more you can do. Subscribe to Firefox Monitor for a full report, alerts when new breaches happen, and tips on protecting your passwords.

And the output from a scan with breached accounts says:

> **This might be a problem**
> Your accounts were compromised in the following breaches.

I believe in both cases we should probably make it more obvious that the website doesn't include sensitive breach information and other results that are included in the full email report.
I'll file a separate issue for the UI/UX team to come up with some additional words to make our intentions/results more transparent.

**Comment by lesleyjanenorton** [comment]
Agreed. I wonder whether it would be more beneficial/harmful to tell users when they do have breached accounts that aren't listed on the website and then explain that we have filtered out not only sensitive breaches, but breaches that are classified as retired, spam, or unverified as well. That way they aren't immediately implicated as having 'sensitive' breached accounts, and aren't given a false sense of security either.

**Comment by pdehaan** [comment]
Yeah, I agree (with you agreeing with me).

I still feel like we have a pretty huge sense of false confidence when we tell people they are "safe" after doing a "basic" scan (which I don't think I can recall if we ever explain what a "basic" scan is).

Not sure if a gross comparison chart would help. Like, which scans are included in a "basic" vs "advanced" scan.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
