### ISSUE TITLE
Consider: let subscribers verify by reply

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#478]
We are seeing a number of users reply to their verification emails. Should we consider letting users verify their subscription by replying?

**Comment by pdehaan** [comment]
Interesting idea...

/cc @rfk @davismtl @jrgm @vladikoff 
Is this something FxA server account verification supports or something you've considered? Or what happens in FxA when a user replies to the verification email? http://restmail.net/mail/peterdddd (looks like you're sending verification emails from accounts@firefox, but I can't remember if that is monitored or a black hole).

**Comment by davismtl** [comment]
That is a very interesting idea that I believe is worth exploring. (while remaining vague on any timelines)

My only concern is that I worry that auto-responders or other soft bounced emails could potentially accidentally verify an email address. Perhaps there is a solution around this or there is actually nothing to worry about but I wanted to call out the first thing that comes to mind.

**Comment by groovecoder** [comment]
The engineering effort here outweighs the benefits - at least for now. 

Instead, we'll localize the verification email messages, and try to improve website messaging during sign-up to address those users who may be replying as a way to verify.
