### ISSUE TITLE
Consider removing verified=false and/or fabricated=true breaches from full report

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#479]
At least one user replied frustrated that we included unverified and fabricated breaches in their full report. We should consider removing them, or explaining them.

(See https://haveibeenpwned.com/FAQs#UnverifiedBreach and https://haveibeenpwned.com/FAQs#FabricatedBreach)

**Comment by gaby2300** [comment]
I checked an email address on monitor.firefox.com. Some of my accounts appeared to be compromised so I changed their passwords.
The weird thing was that accounts I never had were also compromised. 
 I think it may be the following case:
https://www.troyhunt.com/why-am-i-in-a-data-breach-for-a-site-i-never-signed-up-for/

**Comment by pdehaan** [comment]
+1 to including the breach information, but explaining the different types in the email and possibly putting them in separate sections:

1. Verified+Sensitive
1. Unverified
1. Fabricated

**Comment by gaby2300** [comment]
@pdehaan I agree.

**Comment by groovecoder** [comment]
This was done in https://github.com/mozilla/blurts-server/commit/239ad66a0c335d52f063db39299d2b84928e3242
