### ISSUE TITLE
Make eligible for HSTS preloading

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#480]
See https://hstspreload.org/?domain=monitor.firefox.com

In our code, we need to add preload and max-age=31536000 to Strict-Transport-Security header.

We also need to watch https://bugzilla.mozilla.org/show_bug.cgi?id=1494431 and https://bugzilla.mozilla.org/show_bug.cgi?id=1494664 to see when *.firefox.com is ready for domain-wide preloading inclusion.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
