### ISSUE TITLE
Add a CI job for validating Nimbus FML

### ISSUE THREAD

**Issue by brennie** [mozilla/blurts-server#4809]
A recent commit (9a793b9925dafa6b91b66e072e8bf1b7fea00f40) contained FML errors that were caught in the @mozilla/experimenter by the job that pulls in the manifests from all our supported projects. (see [circleci logs](https://app.circleci.com/pipelines/github/mozilla/experimenter/41558/workflows/30fc565b-a50d-4799-9d9d-12d00e068528/jobs/210007#step-106-87237_247))

To prevent FML errors from being committed, you can use the `nimbus-cli fml -- validate` command to validate your FML files.

The nimbus-cli can be downloaded and installed via the following snippet:

```
mkdir -p /tmp/nimbus-cli/
curl --proto '=https' --tlsv1.2 -sSf -o "/tmp/nimbus-cli/install.sh" "https://raw.githubusercontent.com/mozilla/application-services/main/install-nimbus-cli.sh"
bash /tmp/nimbus-cli/install.sh --directory /tmp/nimbus-cli/
```

then validate your configuration with:

```
/tmp/nimbus-cli/nimbus-cli fml -- validate ./config/nimbus.fml
```

**Comment by ReneDrengen** [comment]
> A recent commit ([9a793b9](https://github.com/mozilla/blurts-server/commit/9a793b9925dafa6b91b66e072e8bf1b7fea00f40)) contained FML errors that were caught in the @mozilla/experimenter by the job that pulls in the manifests from all our supported projects. (see [circleci logs](https://app.circleci.com/pipelines/github/mozilla/experimenter/41558/workflows/30fc565b-a50d-4799-9d9d-12d00e068528/jobs/210007#step-106-87237_247))
> 
> To prevent FML errors from being committed, you can use the `nimbus-cli fml -- validate` command to validate your FML files.
> 
> The nimbus-cli can be downloaded and installed via the following snippet:
> 
> ```
> mkdir -p /tmp/nimbus-cli/
> curl --proto '=https' --tlsv1.2 -sSf -o "/tmp/nimbus-cli/install.sh" "https://raw.githubusercontent.com/mozilla/application-services/main/install-nimbus-cli.sh"
> bash /tmp/nimbus-cli/install.sh --directory /tmp/nimbus-cli/
> ```
> 
> then validate your configuration with:
> 
> ```
> /tmp/nimbus-cli/nimbus-cli fml -- validate ./config/nimbus.fml
> ```

[pipelineweebui.txt](https://github.com/user-attachments/files/17046080/pipelineweebui.txt)
