### ISSUE TITLE
you must define foreground with background together ever

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [mozilla/blurts-server#488]
![bad](https://user-images.githubusercontent.com/14617699/46264840-c557d980-c529-11e8-9a42-1fef527e2abc.png)

**Comment by c-e-p-x-u-o** [comment]
![bad](https://user-images.githubusercontent.com/14617699/46265001-3b107500-c52b-11e8-97c9-8f46e5689b1a.png)

**Comment by pdehaan** [comment]
@c-e-p-x-u-o which browser/OS are you using?

**Comment by c-e-p-x-u-o** [comment]
This is Thunderbird 60.0 (64-bit) on debian sid GTK_THEME=Adwaita:dark
But what does it matter?

**Comment by pdehaan** [comment]
Oh, I was just curios since I hadn’t seen it in Firefox, Chrome, or Safari on Mac/Win. But now we can try confirming it on a similar configuration when we tweak the CSS.

**Comment by pdehaan** [comment]
Ref: #152
