### ISSUE TITLE
Create views/error-429.html from HBS templates?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#491]
Re: https://github.com/mozilla/blurts-server/blob/master/views/error-429.html

Currently error-429.html is just an expertly crafted HTML document. Which means if we change our headers/footers/markup, we'll need to do it in two places now, so the 429 page stays in sync (if we care).

It may be nice if we could build that HTML page using our existing HBS files and just pipe the output to ./views/error-429.html at server startup so things stay slightly DRYer.

**Comment by pdehaan** [comment]
I got this far, but for some reason it isn't inputting the `{{ message }}` properly.

```js
const {ExpressHandlebars} = require("express-handlebars");

const hbs = new ExpressHandlebars({
  extname: ".hbs",
  layoutsDir: `${__dirname}/views/layouts`,
  defaultLayout: "default"
});

const opts = {
  cache: false,
  data: {
    message: "Welcome to 429 prison!",
  },
  layout: "default"
};

hbs.renderView("./views/error.hbs", opts, (err, data) => {
  if (err) {
    return console.error(err);
  }
  console.log(data);
});
```

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
