### ISSUE TITLE
Update Monitor Report email based on first user feedback

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#496]
Recipient of Monitor Report emails are asking what to do next. We should condense some of our "What to do" content from the site into the monitor report email.

**Comment by groovecoder** [comment]
May also need to categorize breaches in the report:

* Sensitive
* Regular verified
* Unverified
* Fabricated
* Spam lists

**Comment by pdehaan** [comment]
Huge +1 to categorizing.
Not sure if your list above was sorted, but I'd recommend swapping the first two (Regular verified => Sensitive) and the rest of the ordering looks sane.

Also, having some clear descriptions of what each type means before the group would be super helpful (although that may be captured in a separate bug already).
