### ISSUE TITLE
Clean out and prevent duplicate subscriber records

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#502]
To keep UX simple and prevent account enumeration, we have not prevented duplicate subscriber records. (When breaches are loaded, we [only send 1 email alert to each subscriber.](https://github.com/mozilla/blurts-server/blob/bf446223ada3baeaf6ce2b3725aefa58d525206d/controllers/hibp.js#L53))

But, we can keep the UX simple and prevent account enumeration if we change `verifyEmailHash` to check for an existing verified subscriber record with the same email address. If it finds one, it can simply delete the unverified record and return the same response to the user: "Confirmed. You are subscribed"

Note: when we implement this, we should also remove existing duplicates.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
