### ISSUE TITLE
delay between Monitor results and new breach data

### ISSUE THREAD

**Issue by RosanneScholl** [mozilla/blurts-server#506]
Steps to reproduce:
- a new breach is uploaded to haveibeenpwned
- I go to the breached website right away after learning of the breach from the news
- I see the Monitor doorhanger and click on it
- I enter my email address

Actual results:
Monitor tells me that my email address is not part of the breach, but this is because the server has not yet updated the list of emails.

Expected results:
The doorhanger should not appear until Monitor is able to give me valid results.

**Comment by groovecoder** [comment]
This is fixed now - we reload breach data in the server as soon as get a breach subscription callback from HIBP.
