### ISSUE TITLE
Recommend specific tools to help users enable 2FA on their accounts

### ISSUE THREAD

**Issue by conorgil** [mozilla/blurts-server#510]
Echoing the comment I just made in another thread (https://github.com/mozilla/blurts-server/issues/463#issuecomment-427620305) I think that it is incredibly important to recommend and link to specific tools/services that people can use to make their accounts more secure.

Monitor recommends that people enable 2FA on their accounts, but currently it does not give any guidance about how to actually do that. There are many good resources whose goal is to help average internet users do just that. I think Monitor should link people directly to those tools so that there is a higher chance they will follow through and enable 2FA on their accounts.

1. [2FA Notifier](https://2fanotifier.org)
2. [TurnOn2FA](https://www.turnon2fa.com/)
3. [twofactorauhorg](twofactorauth.org)

I am the developer and maintainer of [2FA Notifier](https://2fanotifier.org), an open source browser extension for Firefox and Chrome that notifies people anytime they visit a website that supports 2FA. Plus, it helps people actually enable 2FA by linking them directly to the documentation for how to setup 2FA on that site. For more details, check out [an article](https://www.allthingsauth.com/2018/09/24/introducing-2fa-notifier-how-to-get-more-internet-users-to-enable-2fa-on-their-accounts/) I recently wrote about 2FA Notifier and the problem it solves that was published on the Okta Developer Blog.

I would love to see 2FA Notifier recommended as a tool to help people enable 2FA on their accounts.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
