### ISSUE TITLE
 “Scan another email in Firefox Monitor” border text is not properly displayed 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#513]
[Affected versions]:
- Firefox Release v13.2

[Affected platforms]:
- Iphone SE, iOS 11.0.1

[Steps to reproduce]:
1. Launch Firefox.
2. Navigate to https://fx-breach-alerts.herokuapp.com/
3. Sign up with a valid email address.
4. Confirm the subscription.
5. Inspect the “Scan another email in Firefox Monitor” text border from the email report sent.

[Expected result]:
- The “Scan another email in Firefox Monitor” text border is properly displayed.

[Actual result]:
- The “Scan another email in Firefox Monitor” text border is displayed on two rows and the border overlaps the text.

[Regression range]:
- I don’t think that this is a regression. I can also reproduce it on stage.

[Additional notes]:
- Not repro on Yahoo email.
- Not repro on Android, tested with Oneplus 5
- also repro on Safari and Chrome
- please see the screenshot below:

![img_0037](https://user-images.githubusercontent.com/43886441/46610290-fed4aa00-cb12-11e8-8c1c-61d1b3a30d39.PNG)

**Comment by lesleyjanenorton** [comment]
Thanks, should be fixed in #504

**Comment by lesleyjanenorton** [comment]
Closing as we've since changed the design of these emails.
