### ISSUE TITLE
[mobile iOS] Firefox icon from download banner is displayed as cut off on herokuapp

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#514]
[Affected versions]:
- Chrome
- Safari

[Affected platforms]:
- Iphone SE, iOS 11.0.1

[Steps to reproduce]:
1. Launch Chrome or Safari.
2. Navigate to https://fx-breach-alerts.herokuapp.com/
3. Scroll down the page to the download banner and inspect the Firefox icon.

[Expected result]:
- Firefox icon is properly displayed.

[Actual result]:
- Firefox icon appears as cut off on the right side.

[Regression range]:
- It seems to be a regression as I cannot repro on stage.

[Additional notes]:
- Not reproducible on android. I’m not sure if other Apple devices are affected since I’m not in possession of any other models at the moment.
- please see the screenshot below:

![img_0038](https://user-images.githubusercontent.com/43886441/46610410-5e32ba00-cb13-11e8-9250-8cc3f3ea33a6.PNG)

**Comment by lesleyjanenorton** [comment]
Thanks @GeorgiuCiprian  - what is the display size here? Thanks!

**Comment by GeorgiuCiprian** [comment]
hey @lesleyjanenorton It's 640 x 1136 pixels. It seems that it can be also reproduced via RDM in Chrome.
