### ISSUE TITLE
The "Firefox Monitor report" mail is not correctly displayed when a Windows 10 Integrated Mail is used

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#517]
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Windows 10 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Do the necessary steps in order for the "Confirmed! You're Subscribed" page to be displayed.
3. Confirm from the Windows 10 integrated Mail.
4. Look in the "Firefox Monitor report" mail. 

[Expected result]:
- The email address is white.
- All the icons are displayed.
- There are no white lines displayed at the bottom of the page.

[Actual result]:
- The email address is blue
- One icon is missing until the window is resized.
- There are two white lines displayed at the bottom of the page.

[Regression]:
- I don't think this is a regression. 

[Notes]:
- Please look at the pictures:
![imgpsh_fullsize 1](https://user-images.githubusercontent.com/42799381/46615744-abb62380-cb21-11e8-821e-4f0f40e231db.png)
![fm1](https://user-images.githubusercontent.com/42799381/46615751-b07ad780-cb21-11e8-8d82-9dee520612dd.png)

**Comment by lesleyjanenorton** [comment]
Should be fixed in #504 , #508 . Thanks!
