### ISSUE TITLE
The logo for Apollo's website is not properly rendered

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#518]
[Affected versions]:
- Chrome
- Safari

[Affected platforms]:
- Windows 10
- macOS 10.13
- Ubuntu 16.04

[Steps to reproduce]:
1. Launch Chrome or Safari.
2. Scan the following email address: test@gmail.com
3. Inspect the "Apollo"'s website logo.

[Expected result]:
- The logo for "Apollo"'s website is properly rendered.

[Actual result]:
- The logo for "Apollo"'s website is not rendered.

[Regression range]:
- I don't think that this is a regression.

[Additional info]:
- it doesn't seem to be reproducible on Firefox
- see image below
![screenshot_2](https://user-images.githubusercontent.com/43886441/46616384-22075580-cb23-11e8-8388-af758b7c525a.png)

**Comment by pdehaan** [comment]
These should have been added via #505, but that has not landed in stage or prod yet.

But you can see the logo on dev: https://fx-breach-alerts.herokuapp.com/?breach=Apollo
