### ISSUE TITLE
Add l10n launch languages to public/locale

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#524]
Launch languages are:

- Japanese (ja), 
- German (de), 
- Spanish (es-ES, es-MX, es-CL, es-AR), 
- French (fr), 
- Portuguese (pt-BR, pt-pt), 
- Russian (ru),
- Italian (it), 
- Chinese(zh-CN, zh-TW)

Need to add `.ftl` files for them in `/public/locale`.

**Comment by pdehaan** [comment]
@flodolo @stasm Do either of you have a list of top locales?

I can only remember https://data.firefox.com/dashboard/usage-behavior which lists the following top languages in a chart:

- en-US 
- de 
- fr 
- ru 
- es-ES 

... as well as the following regions in the dropdown list in the upper-right corner:

- Brazil
- China
- France
- Germany
- India
- Indonesia
- Italy
- Poland
- Russia
- United States

**Comment by groovecoder** [comment]
In https://github.com/mozilla/blurts-server/pull/486 we merged the `locales/en/*.ftl` files. I also added @mozilla-pontoon with write access to this repository.

So, as I understand it, Pontoon can/will add the languages to `locales/` as needed, right @flodolo ?

**Comment by flodolo** [comment]
> So, as I understand it, Pontoon can/will add the languages to `locales/` as needed, right @flodolo ?

Correct, Pontoon will add folders and files as soon as someone starts localizing.

**Comment by groovecoder** [comment]
Okay, then I'm calling this superseded by https://github.com/mozilla/blurts-server/issues/536. Copying the launch languages to that issue too.
