### ISSUE TITLE
Add numbers for "What to do next" in email

### ISSUE THREAD

**Issue by e-pang** [mozilla/blurts-server#530]
@lesleyjanenorton 

image assets can be found here on drive: https://drive.google.com/open?id=1JjU2CLTNP4pIKerpqmLgdfv2HIx0OwQF

<img width="377" alt="screen shot 2018-10-15 at 16 07 08" src="https://user-images.githubusercontent.com/30128313/46976574-de1ece00-d097-11e8-8f45-9a7beded3e1d.png">

Spec can be found here: https://e-pang.github.io/firefoxmonitor/#artboard24

**Comment by lesleyjanenorton** [comment]
Added in #543
