### ISSUE TITLE
i18n copy/text/messages of emails

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#533]
https://github.com/mozilla/blurts-server/pull/486 took care of i18n for the website copy. We need to go thru the email templates and copy and do the same thing.

Note: This may involve changing the functions in `hbs-helpers.js` from receiving a `req` parameter to receiving the `supportedLocales` parameter directly.

**Comment by lesleyjanenorton** [comment]
Side thought: when did I start referring to i18n as i20n?

**Comment by groovecoder** [comment]
We can close this now?

**Comment by groovecoder** [comment]
Confirmed with @lesleyjanenorton we can close.
