### ISSUE TITLE
Enable in-page localization on heroku

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#534]
https://github.com/mozilla/blurts-server/pull/486 added the ability to [enable in-page localization](https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website) on [the heroku site](https://fx-breach-alerts.herokuapp.com/).

We should follow-up to make sure the env var technique works and localizers can use it.

**Comment by Pike** [comment]
CC @mathjaz.

We briefly talked about this on irc.

Things to test:
* [ ] does plain-text detection work with fluent?
* [ ] if we had data-l10n-id attributes on the server-side-rendered DOM, would that help?

**Comment by groovecoder** [comment]
@Pike are those things meant for us - i.e., do they need code changes? Or is that meant for localizers to test?

**Comment by mathjazz** [comment]
@groovecoder These are on me.

**Comment by groovecoder** [comment]
Pulling this out of l10n launch milestone, unless someone thinks we need to ship with this?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
