### ISSUE TITLE
Add blurts-server to Pontoon

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#536]
Project name: Firefox Monitor
Repo url: https://github.com/mozilla/blurts-server/
Requested Locales: See https://github.com/mozilla/blurts-server/issues/524#issue-367964477 and here:

- Japanese (ja), 
- German (de), 
- Spanish (es-ES, es-MX, es-CL, es-AR), 
- French (fr), 
- Portuguese (pt-BR, pt-pt), 
- Russian (ru),
- Italian (it), 
- Chinese(zh-CN, zh-TW)

In-page localization URL: https://fx-breach-alerts.herokuapp.com/

**Comment by flodolo** [comment]
Is it OK go land in the master branch, or should we use a branch to avoid polluting the history?

You will also need to grant write-access to [Pontoon's bot](https://github.com/mozilla-pontoon)

**Comment by flodolo** [comment]
> You will also need to grant write-access to [Pontoon's bot](https://github.com/mozilla-pontoon)

Never mind, saw that you already did it in #524

**Comment by groovecoder** [comment]
How hard is it to change pontoon from landing in master to landing in a branch? If it's not hard to change later, I'm okay landing straight into master now. If it pollutes history too much we can change/fix it later?

**Comment by flodolo** [comment]
> How hard is it to change pontoon from landing in master to landing in a branch? If it's not hard to change later, I'm okay landing straight into master now. If it pollutes history too much we can change/fix it later?

It's just one field in the project config, and we can change it later if needed. To give you an idea, there's going to be one commit per language every 20 minutes (if there are changes).

This is the history of the [l10n branch for the add-on](https://github.com/mozilla/blurts-addon/commits/l10n), which is much smaller (a locale is done quickly).

**Comment by groovecoder** [comment]
Thanks for the info. Let's land in the master branch for now.

**Comment by groovecoder** [comment]
In addition, after landing in master branch, localizers should be able to see their changes live within the 5-10m it takes Heroku to auto-deploy from `master`.

**Comment by pdehaan** [comment]
Interesting... re: master vs branches:

If we have pontoon commit to a branch, would it be possible to skip CI checks? I can't imagine that if we're committing *.ftl files, we would get any benefit from running the linting and <kbd>$ npm test</kbd> checks (although I guess Travis-CI only takes 1-2 minutes and Circle-CI takes another 1 minute -- so maybe it doesn't save us enough time for the micro optimization to be worth it).

But it may be nice to run the following on locale PRs to see if it catches any helpful warnings:

```sh
$ compare-locales l10n.toml . `ls locales`
```

**Comment by flodolo** [comment]
Good point: one of the reasons the Test Pilot team moved to a branch is that automation for deployment was problematic. 

Imagine 20/30 commits happening, and every one of them is triggering CI, the deployment is less than reliable. A timed deployment would work (vs per commit), assuming that's even possible.

**Comment by flodolo** [comment]
[Tested a commit from stage](https://github.com/mozilla/blurts-server/commit/25ae05fb3080ad4d8695ec2f946ecdbd9e6173bf), works as expected.

At this point I'll wait for the green light about copy to enable it on production.

**Comment by flodolo** [comment]
Project is [enabled](https://pontoon.mozilla.org/projects/firefox-monitor-website/). 

Side note: from now on, any change to strings (including adding or removing attributes) [will require a new message ID](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Changing_existing_strings). You add it to the English FTL file, and Pontoon will do the rest, including removing the obsolete string the first time it pushes an update to a locale.
