### ISSUE TITLE
A few l10n errors when running compare-locales

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#540]
I'm getting the following errors when running <kbd>$ compare-locales</kbd>. Not sure if I don't have it configured correctly, or there are a couple errors/warnings we need to address:

```sh
$ compare-locales l10n.toml . `ls locales`

locales/en
  app.ftl
      ERROR: Unparsed content "user-unsubscribed-title {-product-name} : Unsubscribed" from line 48 column 1 to line 48 column 55
      WARNING: Parser error in en-US
      ERROR: Unparsed content "signup-with-fxa - Sign Up with {-brand-name} Account" from line 107 column 1 to line 107 column 53
      WARNING: Parser error in en-US
  data-classes.ftl
      ERROR: Unparsed content "school-grades-(class-levels) = School grades (class levels)" from line 96 column 1 to line 96 column 60
      WARNING: Parser error in en-US
en:
errors            3
unchanged       226
unchanged_w    1175
0% of entries changed
```

---

**UPDATE:** Ah, I think we're missing some `=` in some strings:

https://github.com/mozilla/blurts-server/blob/2cfcffd4b54a7e2b1b34ae9921c1f590b160b93d/locales/en/app.ftl#L48

https://github.com/mozilla/blurts-server/blob/2cfcffd4b54a7e2b1b34ae9921c1f590b160b93d/locales/en/app.ftl#L107

And in the case of this one, I think it's choking on the excessive "(" and ")" in the IDs:

https://github.com/mozilla/blurts-server/blob/2cfcffd4b54a7e2b1b34ae9921c1f590b160b93d/locales/en/data-classes.ftl#L96

_Originally posted by @pdehaan in https://github.com/mozilla/blurts-server/pull/537#issuecomment-431165930_

--- 

I think in the case of `school-grades-(class-levels)`, the problem is coming from:
https://github.com/mozilla/blurts-server/blob/2cfcffd4b54a7e2b1b34ae9921c1f590b160b93d/hbs-helpers.js#L21-L32

We probably need a better algorithm/function that replaces any non a-Z0-9 with a hyphen or something. 

It looks like we're currently only doing a `'` (single quote) to (empty string) conversion as well as converting a space to a hyphen. Oddly looks like we're only calling `.toLowerCase()` in one of the branches, which may be suspicious too.

Maybe something like https://github.com/blakeembrey/param-case logic.

**Comment by groovecoder** [comment]
On fresh `master` I ran:
```
compare-locales l10n.toml . `ls locales`
...
en:
unchanged       233
unchanged_w    1326
0% of entries changed
it:
missing         225
missing_w      1316
unchanged         8
unchanged_w      10
0% of entries changed
```

So no more errors after https://github.com/mozilla/blurts-server/pull/539 was merged?

**Comment by pdehaan** [comment]
Yeah, I cannot reproduce on current `master` (<kbd>$ git rev-parse --short HEAD # 8105f7a</kbd>).
