### ISSUE TITLE
Run compare-locales in travis-ci

### ISSUE THREAD

**Issue by Pike** [mozilla/blurts-server#541]
@pdehaan mentioned this in a couple PRs, it'd be great to run compare-locales in automation.

I think it makes sense to just run that in general, one for the validation mode, and one for the l10n check.

**Comment by groovecoder** [comment]
Thanks @Pike. I submitted https://github.com/mozilla/blurts-server/pull/544 which runs the validation in Travis to help make sure we don't merge any invalid `.ftl` changes.

What do you mean by "the l10n check"? I could run:
```
compare-locales l10n.toml . `ls locales`
```
And just make sure it returns with `0`?

**Comment by Pike** [comment]
`compare-locales --validate l10n.toml .`

reports errors in en-US as actual errors, while they're just warnings if you run them across locales.

en-US validation and l10n validation cannot be run in one go right now, so you want both, eventually.

**Comment by groovecoder** [comment]
Ah okay so I can just add 2 calls to `compare-locales`? One with `--validate` and one without?

**Comment by pdehaan** [comment]
@groovecoder Can we close this now that #544 was merged, or is there further tasks to do?

**Comment by groovecoder** [comment]
Yup. I had it open to remind me we should do something like https://github.com/mozilla/blurts-server/issues/550. But now we have https://github.com/mozilla/blurts-server/issues/550 open for that.
