### ISSUE TITLE
Consider reducing or eliminating markup from .ftl files

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#542]
To make strings & messages easier for translators, and to potentially reduce the number of times we use `{{{ ... }}}`, we should consider auditing the .ftl messages with HTML markup to see if we can reduce or eliminate HTML markup from our .ftl files.

**Comment by groovecoder** [comment]
Pulling this out of l10n launch milestone, unless someone thinks we need to ship with this?

**Comment by lesleyjanenorton** [comment]
Closing as #oldAsDirt and I think we've reached consensus on markup in the FTL files anyway.
