### ISSUE TITLE
Don't 302 to https on dockerflow endpoints

### ISSUE THREAD

**Issue by oremj** [mozilla/blurts-server#545]
For healthchecks to work properly, then should answer via http.

**Comment by groovecoder** [comment]
Thanks for the heads-up @oremj. Is this a critical blocker? I.e., health-checks are failing completely? Or just not working "properly"?

**Comment by oremj** [comment]
It's not critical, there is a workaround in place, but it's a bit of a hack.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
