### ISSUE TITLE
RTL language support?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#569]
I believe the current plan is to ship w/ all locales that have at least 80% translations in Pontoon: https://pontoon.mozilla.org/projects/firefox-monitor-website/

Not sure how many of these are RTL. I'm trying to diff these lists against http://www.i18nguy.com/temp/rtl.html and https://www.w3.org/International/questions/qa-scripts#directions, and I think possibly the following are RTL and may need some extra testing on the site to make things flow in the correct direction:

- Malay (ms): 100%
- Urdu (ur): 73.4%
- Hebrew (he): 66.9%

Current supported locales are: 

| LOCALE | NAME | PROGRESS | IS RTL?
|:-------|:-----|---------:|:-------:|
| cs     | Czech | 100% | 
| cy     | Welsh | 100% | 
| de     | German | 100% | 
| en-CA  | English (Canada) | 100% | 
| es-AR  | Spanish (Argentina) | 100% | 
| fy-NL  | Frisian | 100% | 
| id     | Indonesian | 100% | 
| it     | Italian | 100% | 
| ms     | Malay | 100% | ✔️ 
| nl     | Dutch | 100% | 
| pt-BR  | Portuguese (Brazil) | 100% | 
| sv-SE  | Swedish | 100% | 
| zh-CN  | Chinese (China) | 100% | 
| zh-TW  | Chinese (Taiwan) | 100% | 
| fr     | French | 96.20% | 
| sk     | Slovak | 94.68% | 
| ru     | Russian | 81.37% | 

<details>
<summary><code>$ npx pdehaan/pontoonql firefox-monitor-website 80 | jq '[.[] | {locale: .locale.code, name: .locale.name, progress: .progress}]'</code></summary>

```json
[
  {
    "locale": "fy-NL",
    "name": "Frisian",
    "progress": 100
  },
  {
    "locale": "ms",
    "name": "Malay",
    "progress": 100
  },
  {
    "locale": "nl",
    "name": "Dutch",
    "progress": 100
  },
  {
    "locale": "en-CA",
    "name": "English (Canada)",
    "progress": 100
  },
  {
    "locale": "de",
    "name": "German",
    "progress": 100
  },
  {
    "locale": "sv-SE",
    "name": "Swedish",
    "progress": 100
  },
  {
    "locale": "cs",
    "name": "Czech",
    "progress": 100
  },
  {
    "locale": "id",
    "name": "Indonesian",
    "progress": 100
  },
  {
    "locale": "pt-BR",
    "name": "Portuguese (Brazil)",
    "progress": 100
  },
  {
    "locale": "cy",
    "name": "Welsh",
    "progress": 100
  },
  {
    "locale": "zh-TW",
    "name": "Chinese (Taiwan)",
    "progress": 100
  },
  {
    "locale": "es-AR",
    "name": "Spanish (Argentina)",
    "progress": 100
  },
  {
    "locale": "it",
    "name": "Italian",
    "progress": 100
  },
  {
    "locale": "zh-CN",
    "name": "Chinese (China)",
    "progress": 100
  },
  {
    "locale": "fr",
    "name": "French",
    "progress": 96.1977186311787
  },
  {
    "locale": "sk",
    "name": "Slovak",
    "progress": 94.67680608365019
  },
  {
    "locale": "ru",
    "name": "Russian",
    "progress": 81.36882129277566
  }
]
```
</details>

<br>
 
... And here are the locales which are close (60%+):

| LOCALE | NAME | PROGRESS | IS RTL?
|:-------|:-----|---------:|:-------:|
| pt-PT | Portuguese (Portugal) | 78.71% | 
| sq | Albanian | 78.71% | 
| ja | Japanese | 76.43% | 
| ur | Urdu | 73.38% | ✔️ 
| es-ES | Spanish (Spain) | 72.24% | 
| sl | Slovenian | 69.20% | 
| he | Hebrew | 66.92% | ✔️

**Comment by groovecoder** [comment]
@flodolo - can you point us to some tools or techniques to help (translators) test RTL languages on the heroku site?

**Comment by groovecoder** [comment]
@pdehaan do you think we can close this issue and open individual issues as RTL translators find bugs or errors in the flow of content?

**Comment by pdehaan** [comment]
Yeah, as long as the translators have been testing on the Heroku site and haven't noticed Hebrew or other RTL locales being horrifically broken, I'm fine with closing this.

**Comment by pdehaan** [comment]
And a **huge** thanks to the awesome team of localizers! Here's the latest stats for everything over 60%.

Looks like we have 20 locales at 100%, and another 3 between 80%-99%, and another 4 between 60%-79%. 👏 

```sh
$ npx pdehaan/pontoonql firefox-monitor-website 60 | jq '[.[] | {locale: .locale.code, name: .locale.name, progress: .progress}]'

[
  { "locale": "cs", "name": "Czech", "progress": 100 },
  { "locale": "cy", "name": "Welsh", "progress": 100 },
  { "locale": "de", "name": "German", "progress": 100 },
  { "locale": "en-CA", "name": "English (Canada)", "progress": 100 },
  { "locale": "es-AR", "name": "Spanish (Argentina)", "progress": 100 },
  { "locale": "es-ES", "name": "Spanish (Spain)", "progress": 100 },
  { "locale": "fy-NL", "name": "Frisian", "progress": 100 },
  { "locale": "id", "name": "Indonesian", "progress": 100 },
  { "locale": "it", "name": "Italian", "progress": 100 },
  { "locale": "ja", "name": "Japanese", "progress": 100 },
  { "locale": "ms", "name": "Malay", "progress": 100 },
  { "locale": "nl", "name": "Dutch", "progress": 100 },
  { "locale": "pt-BR", "name": "Portuguese (Brazil)", "progress": 100 },
  { "locale": "ru", "name": "Russian", "progress": 100 },
  { "locale": "sk", "name": "Slovak", "progress": 100 },
  { "locale": "sv-SE", "name": "Swedish", "progress": 100 },
  { "locale": "tr", "name": "Turkish", "progress": 100 },
  { "locale": "uk", "name": "Ukrainian", "progress": 100 },
  { "locale": "zh-CN", "name": "Chinese (China)", "progress": 100 },
  { "locale": "zh-TW", "name": "Chinese (Taiwan)", "progress": 100 },
  { "locale": "fr", "name": "French", "progress": 96.1977186311787 },
  { "locale": "sq", "name": "Albanian", "progress": 95.43726235741445  },
  { "locale": "hu", "name": "Hungarian", "progress": 83.26996197718631 },

  { "locale": "pt-PT", "name": "Portuguese (Portugal)", "progress": 78.70722433460075 },
  { "locale": "ur", "name": "Urdu", "progress": 73.38403041825094 },
  { "locale": "sl", "name": "Slovenian", "progress": 72.6235741444867 },
  { "locale": "he", "name": "Hebrew", "progress": 66.92015209125475 }
]
```

**Comment by flodolo** [comment]
@ItielMaN
Heads-up: if you find RTL layout problems with the Firefox Monitor website, feel free to file issues in this repository.
