### ISSUE TITLE
Remove superfluous notFound route

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#578]
https://github.com/mozilla/blurts-server/pull/568 added an extra `notFound` route that we don't need. We should clean it up.

**Comment by lesleyjanenorton** [comment]
This notFound redirects all uncaught URL misshaps prefaced with /email-l10n/ back to "/email-l10n", instead of "/" but maybe it's overkill?

**Comment by groovecoder** [comment]
Ah, I tried some with `/email-l10n*` but not `/email-l10n/*`

**Comment by groovecoder** [comment]
Don't think this is an issue, as @lesleyjanenorton points out this new route catches some other urls.
