### ISSUE TITLE
es-MX has some layout issues

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#581]
STR:
1. Set language preference to es-MX
2. Visit https://fx-breach-alerts.herokuapp.com/

Expected results:
Text should wrap fine with the `max-width`

Actual results:
<img width="999" alt="screen shot 2018-11-07 at 7 02 23 am" src="https://user-images.githubusercontent.com/71928/48142717-28900680-e262-11e8-96f5-9068930b39aa.png">

**Comment by lesleyjanenorton** [comment]
Looks like the span surrounding Firefox Monitor (string id is -product-name-nowrap)  is not closed in the es-MX .ftl file.  @flodolo can I edit the app.ftl for es-MX to close the `<span>` tag, or will this create headache/additional issues?

**Comment by flodolo** [comment]
if it's an error like broken markup, you can edit the .ftl directly, and it will sync back into Pontoon

**Comment by flodolo** [comment]
(I looked at the string and assumed it was a layout issue, didn't even think it could be the term with a broken span…)

**Comment by pdehaan** [comment]
For my own future reference:

https://github.com/mozilla/blurts-server/blob/bdafb46426834708702970fd4043b45720d6278d/locales/es-MX/app.ftl#L7

Not sure how I could build a linter that could check .ftl files for invalid HTML [yet]. But it looks like only a handful of strings have HTML markup in them.

---

Also, on the topic of es-MX, it looks like we may have translated "Have I Been Pwned", and not sure we should have:

```
# String IDs beginning with "-product" and "-brand" should remain in English.
# They should not be:
# - Declined to adapt to grammatical case.
# - Transliterated.
# - Translated.
...
-brand-HIBP = He sido Pwned
```

And a bit of grep magic, tells me that it may be in a couple other locales as well (if it's a problem, which I suspect it is since it's not a string but a brand name):

```sh
$ git grep '^\-brand-HIBP' locales | grep -v "= Have I Been Pwned"

locales/es-MX/app.ftl:-brand-HIBP = He sido Pwned
locales/id/app.ftl:-brand-HIBP = Apakah Akun Saya Sudah Diterobos
locales/ru/app.ftl:-brand-HIBP =
locales/sq/app.ftl:-brand-HIBP = Ma Kanë Kallur?
locales/ur/app.ftl:-brand-HIBP = کیا مجھے دھوکھا دیا گیاہے
```

**Comment by lesleyjanenorton** [comment]
@flodolo I just pushed up a branch with the updates but I can delete it if it would be better to update the strings through Pontoon.

**Comment by flodolo** [comment]
I just fixed all the brand names, commits are happening right now from Pontoon.

Note that Russian is correct though
https://pontoon.mozilla.org/ru/firefox-monitor-website/app.ftl/?search=brand-HIBP&string=191845

They're adding variants to adapt the associated noun to the grammar case. That's one way to work around the brand name not being modifiable.

**Comment by flodolo** [comment]
> @flodolo I just pushed up a branch with the updates but I can delete it if it would be better to update the strings through Pontoon.

For es-MX is fine (it's a technical bit), for the brand I prefer to see ownership of the change in Pontoon, Also, as explained Russian shouldn't be changed, it's correct as is, and reverting it would break quite badly.

**Comment by lesleyjanenorton** [comment]
@flodolo gotcha, thanks!

**Comment by pdehaan** [comment]
Looks like es-MX was the only missing/invalid HTML:

```sh
$ node ftl-html-lint.js

./locales/es-MX/app.ftl
  - [E042] tag-close: "-product-name-nowrap = <span class="nowrap">{?}"
```

That is, if "The World's Worst FTL htmllint Tooling!(tm)" is accurate (which it probably isn't, but it is arguably incrementally better than what we had 4 minutes ago):

```js
"use strict";

/* eslint-disable node/no-unpublished-require, node/no-extraneous-require, no-console */

const readFileSync = require("fs").readFileSync;
const promisify = require("util").promisify;

const {parse} = require("fluent-syntax");
const _glob = require("glob");
const lint = require("htmllint");

const glob = promisify(_glob);

main("./locales/*/app.ftl");

async function main(g) {
  try {
    const locales = await glob(g);
    for (const locale of locales) {
      await lintLocale(locale);
    }
  } catch (err) {
    console.error(err);
    process.exitCode = 1;
  }
}

async function lintLocale(p) {
  const strings = ftlToJson(p);
  for (const item of strings) {
    if (item.type === "GroupComment") return;

    // The "ru" translation has a non-standard `-brand-HIBP` which was causing
    // `item.value.elements` to be null and throw errors when calling `.map()`.
    if (!Array.isArray(item.value.elements)) return;

    // If there was no simple text `el.value` it seems to be some ftl variable, so
    // just replace it with a silly "{?}" placeholder because what does life matter.
    const str = item.value.elements.map(el => el.value || "{?}").join("");
    const errors = await lint(str + "\n");
    if (errors.length) {
      console.log(p);
      errors.forEach(err => {
        console.error(`  - [${err.code}] ${err.rule}: "${item.id.name} = ${str}"`);
      });
    }
  }
}

function ftlToJson(p) {
  const str = readFileSync(p, "utf-8");
  return parse(str).body;
}
```
