### ISSUE TITLE
Migration Related SQL Statements

### ISSUE THREAD

**Issue by Micheletto** [mozilla/blurts-server#593]
Please provide a procedure, and related SQL statements, to find and insert users that sign up to the service during the interim when it is migrated between Cloud providers.

**Comment by groovecoder** [comment]
Okay, this is complex but I need to write this down before I lose my command & SQL history ...

What I did on my local:

1. `pg_dump blurts > blurts_dump.sql` - creates snapshot from existing DB
2. `psql blurts2 < blurts_dump.sql` - loads snapshot into new DB
3. Sign up a new subscriber (i.e., into `blurts` DB)
4. Update my `DATABASE_URL` to use `blurts2` DB
5. Sign up a new subscriber (i.e., into `blurts2` DB), so now I have the state where a subscriber is left "standed" back on `blurts` db
6. `psql blurts`
   * `ALTER TABLE subscribers RENAME TO old_subscribers;`
   * `ALTER TABLE subscribers_id_seq RENAME TO old_subscribers_id_seq;`
   * `ALTER INDEX subscribers_pkey RENAME TO old_subscribers_pkey;`
   * `ALTER INDEX subscribers_verification_token_unique RENAME TO old_subscribers_verification_token_unique;`
   * `ALTER INDEX subscribers_created_at_index RENAME TO old_subscribers_created_at_index;`
   * `ALTER INDEX subscribers_sha1_idx RENAME TO old_subscribers_sha1_idx;`
7. `pg_dump blurts -t old_subscribers > blurts_dump.sql` - get another snapshot, this time it's just the `old_subscribers` table, which includes the "stranded" subscriber added in Step 3
8. `psql blurts2 < blurts_dump.sql` - loads snapshot into the new DB, but this time the table is named `old_subscribers`
9. `INSERT INTO subscribers (sha1, email, verification_token, verified, created_at, updated_at, fx_newsletter, signup_language) SELECT os.sha1, os.email, os.verification_token, os.verified, os.created_at, os.updated_at, os.fx_newsletter, os.signup_language FROM old_subscribers os WHERE os.verification_token NOT IN (SELECT verification_token FROM subscribers);`
   * See `INSERT 0 1` (note: the `1` here should be however many records were left stranded)
10. Rejoice - for even in death, you have become children of Thanos.
