### ISSUE TITLE
QA and loadtesting on new QA location.

### ISSUE THREAD

**Issue by Micheletto** [mozilla/blurts-server#598]
Please assure the quality of the new stage environment for Fx Monitor located in GCP at the following address: http://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net

Please make sure that load testing is party of the battery of checks performed against the site.  The infrastructure and resource limits are sufficiently different to warrant some response time analysis between the present site and GCP.

**Comment by groovecoder** [comment]
Thanks for the issue @Micheletto. Looks like the code here is from Oct 19. During/after tonight's deploy can you also update this environment to 3.1.0 for the QA & load testing?

**Comment by pdehaan** [comment]
FWIW, I quickly ran this through Google Lighthouse and things looked good:

https://googlechrome.github.io/lighthouse/viewer/?gist=43e47782d7e43faf7f4c0b913b5974a5

![lighthouse_report_viewer](https://user-images.githubusercontent.com/557895/48515427-83eb6700-e815-11e8-91be-56f2b2aaf618.png)

... which is slightly better (at least for "Best Practices", see below)

![firefox_monitor](https://user-images.githubusercontent.com/557895/48515534-d3ca2e00-e815-11e8-9931-86293fffad46.png)

![firefox_monitor](https://user-images.githubusercontent.com/557895/48515578-ef353900-e815-11e8-877a-0d1be8967abe.png)

---

And I think you can even scan sites directly now using Google's https://web.dev/ site, although I don't find the results as informative as they are within Lighthouse.

**Comment by GeorgiuCiprian** [comment]
> @GeorgiuCiprian - can you plan to give this new environment a QA run between Nov 19-29 ?

Hey @groovecoder!

Yes, we can commit to run a testing session on that timeline, meanwhile can you please fie a request with PI and send it to pi-request@mozilla.com (if this process is not very familiar to you, please take a look of an example below [1])? Then, I will ask to take the ownership, since I have some context about this project, already. Thanks! 

[1] https://mana.mozilla.org/wiki/display/PI/PI+Request

**Comment by groovecoder** [comment]
Emailed the PI request and cc'd you @GeorgiuCiprian and @Micheletto.

**Comment by groovecoder** [comment]
This is done.
