### ISSUE TITLE
Add /__version__ endpoint to Heroku dev/l10n server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#599]
It'd be nice if `__version__` also worked on heroku, so we could see which state of l10n is deployed. That question came up in the l10n slack channel, CC @nukeador , @flodolo

_Originally posted by @Pike in https://github.com/mozilla/blurts-server/issues/179#issuecomment-436219980_

**Comment by pdehaan** [comment]
Looks like these were removed from Heroku in PR #271

**Comment by groovecoder** [comment]
@Pike - would the commit ID work here? I.e., not the tag like `v3.1.0` but the commit ID like `055029d0826c44c45bd0451e493b6f1cb0090aa7` ?

**Comment by groovecoder** [comment]
If so, we could try [Dyno Metadata](https://devcenter.heroku.com/articles/dyno-metadata) to do this.

**Comment by Pike** [comment]
Yes, revision would be great. Also, I guess that dev doesn't deploy tagged versions only anyway?

**Comment by groovecoder** [comment]
Right, we push `master` and feature branches to heroku.

**Comment by groovecoder** [comment]
@Pike is there a certain format we should use? https://monitor.firefox.com/__version__ uses a JSON format standard to Firefox services, but in Heroku we could make it respond with something that works specifically for your purposes.

**Comment by Pike** [comment]
Standard format works great for me. Producing that on my own sites, too, so I know what to expect

**Comment by Pike** [comment]
Sweet, verified via https://fx-breach-alerts.herokuapp.com/__version__.
