### ISSUE TITLE
Sign up for alerts service does not work on the new GCP stage environment 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#619]
[Affected versions]:
- latest Beta 64.0b11

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/
2. Click on the "Get your Report" button.
3. Enter a valid email address and click the "Sign up" button.

[Expected result]:
- The "Verify your subscription to Firefox Monitor" confirmation mail is received, and the user is subscribed to the service, after clicking the "Verify My Email" button.

[Actual result]:
- The "Verify your subscription to Firefox Monitor" confirmation mail is not received, therefore the user can't sign up for alerts using the service.

[Regression]:
- Seems to be a an issue with the new GCP environment stage, since the issue is not repro on production (https://monitor.firefox.com/) and old stage (https://blurts-server.stage.mozaws.net/).

**Comment by groovecoder** [comment]
@GeorgiuCiprian - I think we've got the stage environment set up for QA testing now. I ran thru scans, sign-ups, verifications, reports, and breach alerts in English and German.

**Comment by GeorgiuCiprian** [comment]
@groovecoder Thank you for letting us know!

Given the fact that this steps have been covered through our test plan last week, and we didn't encounter the issue anymore (it was tracked in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1510455), I think we can close this.
