### ISSUE TITLE
Make max DB connections configurable?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#62]
https://github.com/mozilla/blurts-server/blob/683eff6837e15e1cf117c3ceb8c0e21a64502cd9/subscribers.js#L5-L7

Ref: https://github.com/mozilla/blurts-server/pull/48/files#r171956899:

> Hmm, this would be nice, yes, but I'm going to procrastinate on it because:
>
> - This is not immediately important.
> - Getting numerical values from the environment means using `parseInt()`, and that seems like a prime surface area for bugs and failures.
> - We should probably first improve AppConstants to also know what type each value is supposed to be and automate the `parseInt()`s.

Not sure if something like Mozilla's [**node-convict**](https://github.com/mozilla/node-convict) would be useful here for config+env management w/ schema validation.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
