### ISSUE TITLE
"Error Cannot read property 'filter' of undefined" when scanning compromised emails

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#620]
[Affected versions]:
- latest Beta 64.0b11

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/
2. Enter a compromised email in the "Enter Email Address" field, e.g. test@gmail.com.
3. Click the "Search Your Email" button.

[Expected result]:
- Compromised accounts are properly displayed.

[Actual result]:
- The following error is displayed: `Error
Cannot read property 'filter' of undefined`

[Regression]:
- Seems to be a an issue with the new GCP environment stage, since the issue is not repro on production (https://monitor.firefox.com/) and old stage (https://blurts-server.stage.mozaws.net/).

**Comment by groovecoder** [comment]
@GeorgiuCiprian - I think we've got the stage environment set up for QA testing now. I ran thru scans, sign-ups, verifications, reports, and breach alerts in English and German.

**Comment by GeorgiuCiprian** [comment]
@groovecoder Thank you for letting us know!

Given the fact that this steps have been covered through our test plan last week, and we didn't encounter the issue anymore (it was tracked in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1508401), I think we can close this.
