### ISSUE TITLE
Update Icon colours in address bar/doorhanger

### ISSUE THREAD

**Issue by e-pang** [mozilla/blurts-server#622]
@nhnt11 Are we able to have a different colour for dark theme? 
Also, I think the colour needs to be updated for the default theme as well - it looks a little dark (could be wrong though!)

Here's what the colours should be:

Light Theme:
grey 90 (#0c0c0d)
60% opacity

Dark Theme:
grey 10 (#f9f9fa)
60% opacity

**Comment by pdehaan** [comment]
Moved to **blurts-addon** repo; https://github.com/mozilla/blurts-addon/issues/137
