### ISSUE TITLE
 Swedish user receives Firefox Monitor emails in Russian

### ISSUE THREAD

**Issue by rtanglao** [mozilla/blurts-server#630]
We have a report on SUMO of Swedish user getting Firefox Monitor emails in Russian!hope this is the right place for this issue!

Anybody else seen this? 

"I got my first Firefox monitor report today, in Russian!
I live in Sweden. 
yes, my IP-address shows that I connect in Sweden. Country: Sweden State/Region: Stockholm County"

Full details:
https://support.mozilla.org/en-US/questions/1241519

**Comment by lesleyjanenorton** [comment]
@rtanglao do you know if there have been any recent reports of this still occurring? I'm thinking we corrected this in #692.
