### ISSUE TITLE
Add UTM tags to "Scan Another Email in Firefox Monitor" email CTA

### ISSUE THREAD

**Issue by chrismore** [mozilla/blurts-server#636]
We should add specific UTM parameters to the breach alert email about scanning another email as that is a clear signal of a user getting value and they want more value.

It would be interesting to find out how many loops the average user goes through over time where a loop would be defined as signing up for monitor, getting a breach alert email, and then setting up another email. I would imagine after you set up one email, get value that you likely probably set up other emails (if they have them) to scan.

**Comment by sandysage** [comment]
@lesleyjanenorton Let's try to get this landed in with the FxA integration feature work so we have as much visibility as possible going into the transition, if not sooner.
