### ISSUE TITLE
Update share-by-email-message to include utm params on the link?

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#637]
https://github.com/mozilla/blurts-server/blob/af8a29dfa16cc8f044231c8bf334ba8596d1286a/locales/en/email-strings.ftl#L88

If we can add `utm_*` params to this link, we can measure how effective this feature is at driving goals.

**Comment by groovecoder** [comment]
@lesleyjanenorton can we revive this now that we've added some more utm params all over the place? 😄

**Comment by lesleyjanenorton** [comment]
Closing since our share-by-email-message is now extinct.
