### ISSUE TITLE
The error " This email address is not subscribe to Firefox Monitor" is displayed even if the user didn't go through all the steps to unsubscribe

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#639]
[Affected versions]:
- latest Beta 64.0b14

[Affected Platforms]:
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/
2. Sign up for Firefox Monitor and confirm your email.
3. From the report mail click on the unsubscribe link.
4. From the Unsubscribe from Firefox Monitor page click on "Unsubscribe" button.

[Expected result]:
- A page with the options why you want to unsubscribe from Firefox Monitor is displayed. 

[Actual result]:
- The error " This email address is not subscribe to Firefox Monitor" is displayed on the screen. 

[Regression]:
- Seems to be a an issue with the new GCP environment stage, since the issue is not repro on production (https://monitor.firefox.com/) and old stage (https://blurts-server.stage.mozaws.net/).

[Additional note]:
- The email report is sent. I just think that it's an issue of just not going through all the steps.

**Comment by obotisan** [comment]
I think this issue might be intermittent, because I can't reproduce it anymore. If I fond why this issue was reproducing, I will a comment with additional info.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
