### ISSUE TITLE
The dashed rectangle for Github is almost double in size as the others

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#642]
[Affected versions]:
- latest Beta 64.0b14

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/
2. Press Tab from the keyboard until the focus in on the Github symbol at the bottom of the page. 

[Expected result]:
- The dashed rectangle has the same dimensions as the others.

[Actual result]:
- The dashed rectangle is almost double in size as the others.

[Regression]:
- Seems to be a an issue with the new GCP environment stage, since the issue is not repro on production (https://monitor.firefox.com/) and old stage (https://blurts-server.stage.mozaws.net/).

[Additional Info]:
- Please look at the attached image. 
![screen shot 2018-11-29 at 14 34 10](https://user-images.githubusercontent.com/42799381/49222673-28100900-f3e5-11e8-9c9c-f32ff0aeaeab.png)

**Comment by lesleyjanenorton** [comment]
Closing since this is in reference to the previous UI.
