### ISSUE TITLE
The button for "Not in inbox or spam folder? Resend." is beneath the "Close" button

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#643]
[Affected versions]:
- latest Beta 64.0b14

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/
2. Click on "Get Your Report".
3. Write a valid email and click on "Sign Up".
4. On the "Verify Your Subscription" pop-up navigate using Tab from the keyboard.  

[Expected result]:
- The button for "Not in inbox or spam folder? Resend." is on top of the "Close" button.
or
- There is a space between these two buttons. 

[Actual result]:
- The button for "Not in inbox or spam folder? Resend." is beneath the "Close" button.

[Regression]:
- This is a regression. Because this issue was already fixed and verified on older versions. 

[Additional Info]:
- Please look at the attached image. 
![screenshot issue](https://user-images.githubusercontent.com/42799381/49223370-3d863280-f3e7-11e8-91b1-0f03d69f61c1.png)

**Comment by lesleyjanenorton** [comment]
Closing since this feature will no longer exist post-Firefox Accounts integration and redesign.
