### ISSUE TITLE
The  "Verify Your Subscription" pop-up is changing dimensions

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#644]
[Affected versions]:
- latest Beta 64.0b14

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/
2. Click on "Get Your Report".
3. Write a valid email and click on "Sign Up".
4. Click on "Not in inbox or spam folder? Resend." button. 
5. On the "Verify Your Subscription" pop-up navigate using Tab from the keyboard.  

[Expected result]:
- The pop-up is not changing dimensions.

[Actual result]:
- The  "Verify Your Subscription" pop-up is changing dimensions. 

[Regression]:
- I don't think this is a regression because I can reproduce it on https://monitor.firefox.com/ and on https://blurts-server.stage.mozaws.net/, too.

[Additional Info]:
- Please look at the attached gif.
![screencast issue 1](https://user-images.githubusercontent.com/42799381/49224592-7bd12100-f3ea-11e8-9f07-fec7a4525b53.gif)

**Comment by lesleyjanenorton** [comment]
@obotisan I am closing this since we are implementing a major site redesign and this feature will no longer exist. Thank you for filing!
