### ISSUE TITLE
The text for the email is not arranged correctly if it's shared via Yahoo

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#655]
[Affected versions]:
- FIrefox 63.0.3

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate tohttps://fx-breach-alerts.herokuapp.com/
2. Click on "Get Your Report" and write a valid email.
3. Go to your email inbox and verify your subscription. 
4. Hover over the "Email" button and select Yahoo. 

[Expected result]:
- In a new tab yahoo mail is opened. 
- The text in the email has this format:
" Hi,
Firefox has a free service where you can check to see if you’ve been
part of a data breach. Here’s how it works:
1. Go to https://monitor.firefox.com and search your email.
2. See if your online accounts have been exposed in a data breach.
3. Get tips from Firefox Monitor about what to do next."

[Actual result]:
- In a new tab yahoo mail is opened. 
- The text in the email has this format:
" Hi, Firefox has a free service where you can check to see if you’ve been part of a data breach. Here’s how it works: 1. Go to https://monitor.firefox.com and search your email. 2. See if your online accounts have been exposed in a data breach. 3. Get tips from Firefox Monitor about what to do next."

[Regression]:
- It's not a regression.

[Additional Info]:
- Please look at the attached image. 
![imgpsh_fullsize 2](https://user-images.githubusercontent.com/42799381/49444771-d4346400-f7d8-11e8-948a-fe572d80a886.png)

- This doesn't happen with gmail, Outlook and Thunderbird.

**Comment by lesleyjanenorton** [comment]
Closing since this feature will no longer exist post-Firefox Accounts integration and redesign.
