### ISSUE TITLE
The "Email" share button is bigger than the other two in some languages (e.g. French, Spanish)

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#657]
[Affected versions]:
- FIrefox 63.0.3

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Prerequisite]:
- In about:preferences change the language to French [fr].

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Click on "Get Your Report" and write a valid email.
3. Go to your email inbox and verify your subscription. 
4. On the "Your Firefox Monitor report is on its way" page and observe the page.   

[Expected result]:
- The word "email" is written on it.
- The button from email is the same dimensions as the others.

[Actual result]:
- The word "Adresse electronique" is written on it.
- The button from email is almost double the size.

[Regression]:
- It's not a regression.

[Additional Info]:
- Please look at the attached image. 
![imgpsh_fullsize](https://user-images.githubusercontent.com/42799381/49443071-1313eb00-f7d4-11e8-8062-6f064665138a.png)
- This also happens for Spanish, too.

**Comment by lesleyjanenorton** [comment]
Closing since this feature will no longer exist post-Firefox Accounts integration and redesign.
