### ISSUE TITLE
Navigating the page with Tab key is hard to see where the focus is on some buttons

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#658]
[Affected versions]:
- FIrefox 63.0.3

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate tohttps://fx-breach-alerts.herokuapp.com/
2. Click on "Get Your Report" and write a valid email.
3. Go to your email inbox and verify your subscription. 
4. On the "Your Firefox Monitor report is on its way" page try to navigate using Tab key.   

[Expected result]:
- You can see the dashed line when it's over the three buttons: "Email", "Share" and "Tweet". 

[Actual result]:
- It's really hard to see the dashed line when it's over the three buttons: "Email", "Share" and "Tweet". 

[Regression]:
- It's not a regression.

**Comment by lesleyjanenorton** [comment]
closing in favor of #1518
