### ISSUE TITLE
Add a /stats route which shows cumulative data classes statistics?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#664]
I seem to recall that @groovecoder had a handy [but private] gist showing how often email addresses or passwords or other data classes were leaked... That'd make a very interesting page on the Monitor site (and we've already translated all those strings, so shouldn't be a big l10n penalty).

Out of personal curiosity, I wrote the following gist since I wasn't sure how **groovecoder** was generating his list: https://gist.github.com/pdehaan/87862aa8255f928eee246dd663bf9072

Not sure if we'd potentially only want to show the top 10 leaked items or top 50 or all of them (currently we have around 114, which is a bit of a long list).

---

**UPDATE:** Current top 10:

| DATA CLASS | ACCOUNTS |
|:-----------|---------:|
| email addresses | 5,681,943,442
| passwords | 4,421,453,985
| names | 1,595,193,779
| usernames | 1,552,623,570
| ip addresses | 1,088,228,360
| physical addresses | 999,704,223
| phone numbers | 818,575,256
| dates of birth | 666,078,273
| genders | 596,293,028
| job titles | 492,316,791

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
