### ISSUE TITLE
Romanian missing from production website

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#670]
According to the __version__ file, production is running v3.1.8, but there's no trace of Romanian, even if I pointed out several times that it was ready to be enabled on production.

Is 3.1.8 indeed in production? Is the prod deployment/tagging procedure missing a step about adding locales to production?

**Comment by groovecoder** [comment]
In addition to the new files, we need to add `ro` to the `SUPPORTED_LOCALES` environment variable on prod (and stage) so the code will activate the language.

I'll write up better prod tag+bug+deploy procedure docs that include setting `SUPPORTED_LOCALES` to include all language codes above 80%.

Is there an API, script, or some other tool we can use to get a comma-separated list of locale codes that are above 80% translated? (I think @pdehaan may have started something like that?)

**Comment by flodolo** [comment]
> Is there an API, script, or some other tool we can use to get a comma-separated list of locale codes that are above 80% translated? (I think @pdehaan may have started something like that?)

Likely this https://github.com/pdehaan/pontoonql

**Comment by pdehaan** [comment]
Yeah, I hacked together **pontoonql** to scrape the translation %%s from GraphQL and then filter the results.

In fact, this should give us a sorted array of locales with at least 80% translated strings:

```sh
$ npx pdehaan/pontoonql firefox-monitor-website 80 | jq 'sort_by(.locale.code) | [.[] | .locale.code]'

[
  "cs",
  "cy",
  "da",
  "de",
  "en-CA",
  "es-AR",
  "es-CL",
  "es-ES",
  "es-MX",
  "fr",
  "fy-NL",
  "hu",
  "id",
  "it",
  "ja",
  "ms",
  "nl",
  "pt-BR",
  "pt-PT",
  "ro",
  "ru",
  "sk",
  "sl",
  "sq",
  "sv-SE",
  "tr",
  "uk",
  "vi",
  "zh-CN",
  "zh-TW"
]
```

Also, per #609, I think it'd be pretty useful if we exposed the server's `process.env.SUPPORTED_LOCALES` somehow, so we can easily see which locales are enabled on stage/production.

**Comment by pdehaan** [comment]
Also, if it's easier, I wrapped **pontoonql** in a _really basic(tm)_ Express wrapper: https://pontoonql.now.sh/firefox-monitor-website/80, where the path format is: **/:product/:pct?** and the optional **:pct?** defaults to 80%.

**Comment by flodolo** [comment]
Any chance to fix Romanian in the meantime?

**Comment by groovecoder** [comment]
Heya. I'll plan to do a production deployment tomorrow for this. Sorry for the delay.

**Comment by groovecoder** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1518509 to do a deploy today with all new languages available: da, es-CL, ia, ro, vi

**Comment by pdehaan** [comment]
I'm seeing Romanian (ro) translations on the stage site (version: v3.1.9). 
It isn't live at the production https://monitor.firefox.com site yet (which is still v3.1.8), but should be soon.

Pretty sure that is Romanian. Seems to match the .ftl files at

https://github.com/mozilla/blurts-server/blob/46abfc79b9c07fdd33023da5effcb0125953662c/locales/ro/app.ftl#L60

Screenshots for homepage and breach details at:

- Home: https://github.com/pdehaan/blurts-puppeteer-l10n/blob/v2/shots/desktop/README.md#ro
  ![](https://github.com/pdehaan/blurts-puppeteer-l10n/raw/v2/shots/desktop/ro.png)

- Breach: https://github.com/pdehaan/blurts-puppeteer-l10n/blob/v2/shots/desktop-breach/README.md#ro
  ![](https://github.com/pdehaan/blurts-puppeteer-l10n/raw/v2/shots/desktop-breach/ro.png)

**Comment by pdehaan** [comment]
v3.1.9 is live on production, and I confirmed Romanian is showing up and matches the screenshot above from stage.

Closing.
