### ISSUE TITLE
Require a Firefox Account for new Monitor registrations

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#677]
When I want to know if my email address has been used in a breach, I need to create an account to get the full Monitor report, ongoing reports, and additional Monitor value.

## Acceptance criteria

* Should have the ability to create a Firefox Account from the Monitor website
* Should have the ability to sign into Firefox Monitor with my Firefox Account
* Should have the ability to sign out of Firefox Monitor, but stay signed into my FxA for other properties (eg addons, pocket, lockbox)
* Should have the ability to see when I'm signed in

## Design/frontend requirements

* Update the header to include option to register or sign in
* Update the header to include the FxA profile if signed in
* Create navigation for the FxA account (starting with dropdown navigation with just "log out" to start)

**Comment by groovecoder** [comment]
Is this still "needs: UX"? I think we've gotten everything we need for this, and it's just about done in #702
