### ISSUE TITLE
Use basic scan email address to prepopulate a new Fx Account email

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#681]
After I've tried Monitor, with a basic scan, I want to easily create an account to get a full report and additional Monitor value.

## Acceptance criteria
* Should capture the email address used in a basic scan form field
* Should use that email address to prepopulate a new FxA registration or sign in
* If the 'email' is already completed on the FxA side, should _not_ use the basic scan email

**Comment by sandysage** [comment]
@groovecoder @lesleyjanenorton I'm not sure this is even possible. But if we can, it'd be nice to make that 'sign in' or registration as easy as we can.

**Comment by groovecoder** [comment]
@lesleyjanenorton and I discussed, and she's got a branch that:

1. Stores the plaintext email address in local client-side storage
2. Only when the user clicks "Sign up", get the plaintext email out of the local client-side storage to send to FxA

Still need to test this one:
> If the 'email' is already completed on the FxA side, should not use the basic scan email

I'm not sure we can know if the user already has their email on the FxA side, and if we put anything in `email=` url parameter, it seems like it will override the existing FxA session.

**Comment by sandysage** [comment]
@groovecoder @lesleyjanenorton Can we also make sure that the email address is editable in the case that we prepopulate it?

**Comment by groovecoder** [comment]
@sandysage - if the UX in the above screenshots is acceptable, this issue will be done when the FxA udpates PR is merged.

**Comment by sandysage** [comment]
@groovecoder @lesleyjanenorton Yes, this flow works for me!
