### ISSUE TITLE
Use unminified resources in localhost/dev

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#698]
When I open the Firefox debugger on localhost, I can only select the `app.min.js` source which is hard to debug.

Could we serve the un-minified sources for localhost? Or maybe use [source maps](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map)?

**Comment by lesleyjanenorton** [comment]
Fixed as of the V2 launch.
