### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by g33xter** [mozilla/blurts-server#7]
Is this compatible with FireFox Quantum ver. 57? Because this add-on showing error that, this is  compatible with minVersion: 58.0a1. add-on maxVersion: 59.0a1

**Comment by nhnt11** [comment]
This has not been tested on Firefox 57 and hence does not support it in the install.rdf. If you really want to try it on 57, you can manually change the minVersion line in install.rdf and give it a shot. Please let me know if you'd like more help with this, and/or to submit a pull request if it works fine on 57.

**Comment by g33xter** [comment]
Okay. I'd try and let you know. Thanks for the info tho.
