### ISSUE TITLE
Analytics for Security Operations

### ISSUE THREAD

**Issue by Micheletto** [mozilla/blurts-server#708]
The cloud services operations security team would like access to (or information from) Google Analytics about typical user behavior to be used in abuse detection and filtering.  Information of use may include things such as a typical session behavior, and the distribution of scans per session.

**Comment by groovecoder** [comment]
@lesleyjanenorton can you help @Micheletto get access to GA and introduce him to our GA guru?

**Comment by lesleyjanenorton** [comment]
Followed up on this bug today and will push for getting this resolved by the end of the week.

**Comment by groovecoder** [comment]
I think @Micheletto now has access to GA! Closing.
