### ISSUE TITLE
Investigate how often a user changes their FxA primary email

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#709]
I'm not sure what we should do in this case. My first idea ...

When a user changes their FxA primary email, automatically update their Monitor subscription to the new primary email address, and remove the old one.

But this definitely needs UX and product consideration. @sandysage ?

**Comment by tcinotto** [comment]
@sandysage will check metrics on how often users change their primary email. Is this is a small edge case?

**Comment by tcinotto** [comment]
This is built as designed.

**Comment by sandysage** [comment]
cc @irrationalagent

**Comment by irrationalagent** [comment]
@sandysage had [this lying around](https://sql.telemetry.mozilla.org/queries/51275) does that help? seems like it doesn't happen very often

**Comment by RibbitTM** [comment]
Good luck, I have a new one every month and use completely duff creds and by the time it's all tracked I just do it again, just out of personal experience

**Comment by sandysage** [comment]
Based on what Leif provided, this is infrequent (someone changing their primary email address).

Right now we're not going to spend any effort to change their Fx Monitor subscription to mirror what is given in FxA (refresh to the updated email address). 

To come back to this effort when we develop the multiple emails feature.

**Comment by groovecoder** [comment]
Just a note to close the loop here ... we're not planning to re-open this issue, but I *am* planning to fix it while I fix https://github.com/mozilla/blurts-server/issues/816
