### ISSUE TITLE
When a user deletes their FxA, delete their Monitor records + data

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#710]
FxA currently broadcasts account deletions to an SQS queue. We will need to either:

* Connect directly to the SQS queue from Monitor code with credentials (like we do with SES)
* See if FxA is using SNS to publish to SQS; if so we can ask to get into their SNS flow
* Ask FxA to create an https callback feature for account deletions

**Comment by shane-tomlinson** [comment]
> See if FxA is using SNS to publish to SQS; if so we can ask to get into their SNS flow

We do! Let me find out the URL and what needs to happen there.

> Ask FxA to create an https callback feature for account deletions

This is the medium-term plan.

**Comment by shane-tomlinson** [comment]
cc @jbuck

**Comment by shane-tomlinson** [comment]
@groovecoder, @jbuck told me that [SNS can publish to an HTTPS endpoint](https://docs.aws.amazon.com/sns/latest/dg/sns-http-https-endpoint-as-subscriber.html). If you have an endpoint that can accept SNS formatted notifications, we can start sending messages there.

**Comment by groovecoder** [comment]
Thanks @shane-tomlinson, we don't have one yet, but I'll look at those docs and use this issue to either create a new one, or update our existing `/ses/notification` endpoint to a more generic `/sns/notification` endpoint to handle both SES and FxA messages. Thanks.

**Comment by groovecoder** [comment]
@shane-tomlinson can you configure the stable.dev.lcip.org SNS to publish to https://blurts-server-review.herokuapp.com/ses/notification? I've set our review app the log those messages, and I want to see if it comes across in a way I can handle.

**Comment by groovecoder** [comment]
Note: depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1525264
