### ISSUE TITLE
Consider implementing ToS;DR

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#715]
Installed the DDG Privacy Essentials add-on in Chrome (https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg/related) and it's flagging https://monitor.firefox.com/ as a B+

![](https://user-images.githubusercontent.com/557895/51713120-d3a09880-1fe5-11e9-82b6-291d22d85b54.png)

![](https://user-images.githubusercontent.com/557895/51713140-e4510e80-1fe5-11e9-8518-5d4de5b63575.png)

**Comment by groovecoder** [comment]
Looks like to fix this, we need someone to go thru https://edit.tosdr.org/ for monitor.firefox.com. @sandysage ? someone else?

**Comment by pdehaan** [comment]
This feels very confusing and misleading. Like, every single site I've seen (including GitHub here, and the main Mozilla site, and everything else I've browsed is) getting a "B+", making the rating virtually meaningless.

**Comment by groovecoder** [comment]
I'm changing this issue to be about ToS;DR.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
