### ISSUE TITLE
Support UR content experiment

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#718]
Based on [the UR proposal provided](https://docs.google.com/document/d/1UDYJKmq_87P90MXBC5yFDBdP6gYZoLGeSLtcWRAqpqE/edit#heading=h.vkycj4ml1cc5), we want to learn

1. How someone interprets (or can explain) what they've read about a breach
2. How they feel about what they've read
3. What would they do about it (actionability)

Comprehension of breaches, and how tone and varied language about describing breaches affects comprehension. And, secondarily, how does comprehension impact people's inclination to act/react.

## Requirements

* Should include new text either above or below the existing text or removing text
* Should allow for 1 conditional parameter on data class (eg password was involved in breach)

parent of #719

**Comment by sandysage** [comment]
Can we start by investigating Google Analytics Optimize for how we can provide 6 prototypes around messaging?

**Comment by lesleyjanenorton** [comment]
The six prototypes are live on the review server and can be viewed [here.](https://blurts-server-review.herokuapp.com/?prototype=6) To view the different prototypes, change the number following `/?prototype=` from the hompage.

**Comment by pdehaan** [comment]
Not sure if you want me to comment yet, vs waiting for a Pull Request, but...

I did notice some missing content on the /scan/user_dashboard URL if you happen to be logged in via FxA (I think I was ?prototype=4 here).

![firefox_monitor___scan_results](https://user-images.githubusercontent.com/557895/53846093-827ab180-3f60-11e9-8974-28ca109e989e.png)

vs this screenshot for ?prototype=1 (but not logged in):

![firefox_monitor___scan_results](https://user-images.githubusercontent.com/557895/53846152-b9e95e00-3f60-11e9-8e28-8e942e1dc2e1.png)

**Comment by sandysage** [comment]
The work to support this UR spike is now complete. If there is follow up work we'll create another epic.
