### ISSUE TITLE
Display the display name instead of the primary email address

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#723]
When logged into Monitor via FxA, we're currently displaying the email address, and not the user's chosen "Display Name" (where I'm changing these on https://stable.dev.lcip.org/settings).

![firefox_monitor___scan_results](https://user-images.githubusercontent.com/557895/51997777-3ffb1c00-246c-11e9-9878-8c662756ea1b.png)

_Originally posted by @lesleyjanenorton in https://github.com/mozilla/blurts-server/pull/722#issuecomment-458816462_

**Comment by jsavory** [comment]
I'm thinking that we should leave this as the email address actually. It helps tie the address to the content a little better since that is the main account that we are scanning.

**Comment by tcinotto** [comment]
Will be resolved in V2.
