### ISSUE TITLE
Update copyright year in footer?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#725]
Randomly spotted on the site, not sure if it needs updating to **2019** or not...

> Portions of this content are Ⓒ **1998-2018** by individual mozilla.org contributors. 
Content available under a Creative Commons license.

https://github.com/mozilla/blurts-server/blob/ecc85281efd054343d7f9dc9e862805a36d367b1/locales/en/app.ftl#L243-L246

**Comment by lesleyjanenorton** [comment]
@flodolo Should we create a new string with the updated year for this?

**Comment by flodolo** [comment]
AFAIK copyright is valid for a long time, even if it says 2018. You might want to use a variable for the end year at that point. Also, we shouldn't really be using the HTML entity for ©
