### ISSUE TITLE
Change some 5xx errors to 4xx errors.

### ISSUE THREAD

**Issue by Micheletto** [mozilla/blurts-server#727]
The following errors result in 5xx status codes that might be better served as 4xx level errors:

- Unsubscribe errors:
> Error: error-not-subscribed
>     at getUnsubscribe (/app/controllers/user.js:90:11)
>     at <anonymous>

- Invalid Tokens

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
