### ISSUE TITLE
Avatar not showing

### ISSUE THREAD

**Issue by e-pang** [mozilla/blurts-server#731]
Default profile avatar is being shown even though one exists 

https://cl.ly/bb6b83452d5f

**Comment by pdehaan** [comment]
@e-pang Is the avatar set on https://stable.dev.lcip.org/settings?

**Comment by e-pang** [comment]
it was not, was not aware of this. Thanks!

**Comment by groovecoder** [comment]
Closing unless/until we can reproduce an avatar from  https://stable.dev.lcip.org/settings is missing.
