### ISSUE TITLE
[mobile] Download Firefox banners shouldn't appear on Firefox for Andoid/iOS.

### ISSUE THREAD

**Issue by e-pang** [mozilla/blurts-server#732]

**Comment by pdehaan** [comment]
Ref: #714 (possibly for iOS)
Although I don't see anythig in that PR that refers to "Android".

**Comment by e-pang** [comment]
@pdehaan sorry I should have mentioned I was only able to test for iOS (since I don't have android device). If it appears on Fennec we should remove it there as well. If not, then everything is good! :)

**Comment by lesleyjanenorton** [comment]
Closing this since we no longer have a Download Firefox banner.
