### ISSUE TITLE
Redirect mozilla.org/firefoxmonitor to monitor.firefox.com?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#737]
For some reason, https://www.techspot.com/news/75246-mozilla-integrates-have-pwned-firefox.html popped up today in my Flipboard/Twitter feed (despite being 7 months old).

The one thing that jumped out at me was the URL in the address bar; https://www.mozilla.org/firefoxmonitor (which 404s).

![](https://static.techspot.com/images2/news/bigimage/2018/06/2018-06-26-image-2.png)

Seems minor, but I also noticed the HIBP site using the same image (with the same 404ing URL): https://www.troyhunt.com/were-baking-have-i-been-pwned-into-firefox-and-1password/#mozillaandfirefoxmonitor

Not sure how easy or worthwhile it'd be to redirect mozilla.org/firefoxmonitor to monitor.firefox.com, or if mozilla.org can give us any stats on how many people see the 404 page for /firefoxmonitor route to see if it's even worth fixing.

**Comment by groovecoder** [comment]
This might need to be an issue in https://github.com/mozilla/bedrock/ ?

**Comment by groovecoder** [comment]
bedrock team can decide if they are getting enough visits to /firefoxmonitor to set up a redirect.
