### ISSUE TITLE
Missing word in one of the new FxA strings

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/blurts-server#741]
It looks like a word is missing in this string `fxa-what-to-do-blurb-2`

`Hackers may try to that same password and your email to get into other accounts. ` should probably be `Hackers may try to *reuse* that same password and your email to get into other accounts.`

**Comment by lesleyjanenorton** [comment]
@flodolo Can we update this string and keep the existing ID or should I add the corrected string in with a new ID?

**Comment by flodolo** [comment]
I think it's safer to have a new ID. The meaning of the existing sentence wasn't completely clear, no clue what translations they could have added.

**Comment by lesleyjanenorton** [comment]
Sounds good, thank you. Should the string with the missing word be deleted from the ftl file or left as is?

**Comment by flodolo** [comment]
Remove it from en-US, Pontoon will remove it from other locales on the first sync.

**Comment by lesleyjanenorton** [comment]
Will do, thanks!

**Comment by pdehaan** [comment]
Verified in https://fx-breach-alerts.herokuapp.com/__version__:

```json
{
  "commit": "ef5e38158634c7783f5ac625fbca4d81408eb1a6", 
  "version": "ef5e38158634c7783f5ac625fbca4d81408eb1a6",
  "source": "https://github.com/mozilla/blurts-server"
}
```

![firefox_monitor___scan_results](https://user-images.githubusercontent.com/557895/52446297-7414b380-2ae2-11e9-9a77-569dcba9cc56.png)
