### ISSUE TITLE
Remove `text-transform: capitalize;` from localized pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/blurts-server#744]
On a few areas, `text-transform: capitalize;` introduces capitalization mistakes in (most) locales.

![image](https://user-images.githubusercontent.com/1294206/52310464-66084b00-299b-11e9-99c6-5d5e3acfdcdc.png)

`text-transform: capitalize;` should be either removed completely or applied to en-US only with a CSS selector.

**Comment by pdehaan** [comment]
```sh
$ git grep -in "text-transform:"

public/css/app.css:928:  text-transform: capitalize;
public/css/fxa.css:489:  text-transform: capitalize;
public/css/fxa.css:1098:  text-transform: capitalize;
```

https://github.com/mozilla/blurts-server/blob/cd2b25af63165e871fb4d6893219a6f08d763778/public/css/app.css#L927-L929

https://github.com/mozilla/blurts-server/blob/cd2b25af63165e871fb4d6893219a6f08d763778/public/css/fxa.css#L488-L490

https://github.com/mozilla/blurts-server/blob/cd2b25af63165e871fb4d6893219a6f08d763778/public/css/fxa.css#L1097-L1099
