### ISSUE TITLE
$FeaturedBreach showing up in 'fr' locale for featured breach

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#745]
https://github.com/mozilla/blurts-server/blob/cd2b25af63165e871fb4d6893219a6f08d763778/locales/fr/app.ftl#L74

![blank_skitch_document](https://user-images.githubusercontent.com/557895/52316663-64c22880-2971-11e9-986e-9c9887a7fe2c.png)

[Apollo_fr.pdf](https://github.com/mozilla/blurts-server/files/2834593/Apollo_fr.pdf)

**Comment by pdehaan** [comment]
@flodolo @pike @stasm Is there any way to use `compare-locales` or some other l10n tool to find .ftl typos like `$FeaturedBreach` vs `$featuredBreach`?

**Comment by Pike** [comment]
Not yet, but that'd be good to add. [Filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1525514) and CCed you.

**Comment by TheoChevalier** [comment]
Fixed the issue in Pontoon in the meantime (machine-translation change that went unnoticed during review)

**Comment by pdehaan** [comment]
Closing. This was fixed via 86144b7fd8b5c9a4866a8c1cd570c326dd37d696

If I get some time this week I'll see if I can write some lazy .ftl linter that checks variable names against the "en" reference locale.
I had a FTL HTML linter (https://github.com/pdehaan/ftl-htmllint/) which may get me most of the way there. I'll just have to confirm it works with the latest **fluent-syntax** and see how much code I can remove since it looks pretty suboptimal at the moment.
