### ISSUE TITLE
Unparsed $breachName when searching via featured breach page in zh-CN

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#753]
![firefox_monitor](https://user-images.githubusercontent.com/557895/52450800-674b8c00-2af1-11e9-86b1-182015a2ab6a.png)

### Steps to reproduce:
1. Switch browser language to zh-CN (required restart in Nightly).
1. Go to https://fx-breach-alerts.herokuapp.com/?breach=Apollo
1. Enter your email address and search again.

I think this is the zh-CN locale string in question:

https://github.com/mozilla/blurts-server/blob/5aace968dc92215766da83434c2b171cd05fd887/locales/zh-CN/app.ftl#L257-L261

And here's the reference en locale string:

https://github.com/mozilla/blurts-server/blob/5aace968dc92215766da83434c2b171cd05fd887/locales/en/app.ftl#L340-L346

Note how "en" uses `$breachCount` in the strings, but "zh-CN" uses `$breachName`.

**Comment by lesleyjanenorton** [comment]
@flodolo can I update this file to use `{ $breachCount }` instead of { $breachName } or would that have negative repercussions in Pontoon?

**Comment by flodolo** [comment]
> @flodolo can I update this file to use `{ $breachCount }` instead of { $breachName } or would that have negative repercussions in Pontoon?

I've unapproved it in Pontoon, and left a suggestion, because I want them to double check that translation.
https://github.com/mozilla/blurts-server/commit/8e1583c69d2b8cab10724d7364f3b63c8a29c2c2

**Comment by lesleyjanenorton** [comment]
@flodolo thank you! and thanks for catching @pdehaan !

**Comment by flodolo** [comment]
Looks like they landed my suggestions as is in https://github.com/mozilla/blurts-server/commit/d363173e111e5cf6728e02b649d2f9b68fde1d5c#diff-5b3e4d35d0acb4c99902849277afc478

**Comment by lesleyjanenorton** [comment]
@flodolo awesome, thank you!
