### ISSUE TITLE
The image from your account is not displayed

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/blurts-server#766]
Environments: 
-Windows 10;
-Android;

Prerequisites:
Make sure you have a valid account for FM and you have an image for this account.

Steps to reproduce:
1. Log-in on FM page(https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/);
2. Pay attention to your account information:

Expected results:
your email and image are correctly displayed.

Actual results:
Your email is correctly displayed but the image is not displayed.

![screenshot_3](https://user-images.githubusercontent.com/40264165/52704788-0b1db780-2f8a-11e9-844f-97000e4c4448.png)

**Comment by groovecoder** [comment]
Thanks @sv-sdeiac. How did you set the image on the account? Did you use the "Manage Firefox Account" link in the Monitor drop-down? Because that's hard-coded to the wrong FxA site until https://github.com/mozilla/blurts-server/pull/762 is deployed to stage.

**Comment by sv-sdeiac** [comment]
Hi, after further discussions with @groovecoder I understand that the change image is implemented only on the stage server of "manage your account"(stable.dev.lcip.org). When the FM is live, the implementation will be integrated also on the accounts.firefox.com.
I will let this issue open till the release to be sure about the fix, thanks.

**Comment by tcinotto** [comment]
Hi @sv-deiac would you be able to review on the stage server that this is fixed prior to release?

**Comment by sv-sdeiac** [comment]
Hi, I can confirm this issue is fixed on https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/ using Windows 10 and Android. 
Due to that, I'll close this issue, thanks.

**Comment by sv-sdeiac** [comment]
Hi, I come with a new update for this issue. 
If you change the image by going on the https://stable.dev.lcip.org/settings, the avatar is not changed even if I refresh the page. The only way to see the new one is to sign-out and re-login. 
@groovecoder Do you know something about these things?
