### ISSUE TITLE
Add app icon for Monitor in Devices&Apps section

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/blurts-server#769]
Prerequisites: on https://stable.dev.lcip.org/settings/clients log in with a FxA account. 

Steps to reproduce:
1. Log in here https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net with the same FxA account used in prerequisites;
2. Go to Manage Account -> Devices&Apps section (https://stable.dev.lcip.org/settings/clients);
3. Pay attention to the icon next to Firefox Monitor Trusted;

Expected results:
Firefox Monitor icon is displayed.

Actual results: the app icon is not displayed. 

![2019_02_14_13_02_08_firefox_accounts_devices_apps_firefox_nightly](https://user-images.githubusercontent.com/24588037/52782913-e47a8200-3058-11e9-8166-08617502c2b7.png)

**Comment by groovecoder** [comment]
Good catch. I bet this requires a change on FxA side? @mozilla/fxa-admins ?

**Comment by pdehaan** [comment]
![firefox_accounts__devices___apps](https://user-images.githubusercontent.com/557895/52883559-4a7e0c80-3120-11e9-84c5-faa2ebf946c3.png)

We'll also need to make sure it's set for production. Probably not worth bothering w/ Heroku/dev env unless it's just copy-pasting an img src.

**Comment by jbuck** [comment]
It'll need a PR similar to https://github.com/mozilla/fxa-content-server/pull/5959

**Comment by shane-tomlinson** [comment]
This can be closed here, I opened https://github.com/mozilla/fxa-content-server/issues/6971.
