### ISSUE TITLE
Account name not centered on iOS if we try to Sign In

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/blurts-server#770]
Environment 
iOS - iPhone SE(12.0.1)

Steps to reproduce:
1. Create an account for FM;
2. Log out;
3. Tap on "Sign in";

Actual results: the email field is autocompleted but the name is not centered on the screen.
Expected results: the email field is autocompleted and no visual issues are displayed.

Screenshot:
![img_0059](https://user-images.githubusercontent.com/24588037/52800198-f02f6e00-3083-11e9-9113-b247c73f0382.PNG)

**Comment by pdehaan** [comment]
@vladikoff @ryanfeeley: This feels like an upstream FxA thing. Is this an fxa-content-server or an fxa-profile-server issue?

**Comment by vladikoff** [comment]
cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
This is an FxA issue, I thought the icon was supposed to shrink and the gutter was supposed to more or less go away for small screens.

**Comment by pdehaan** [comment]
Closing in favor of upstream https://github.com/mozilla/fxa-content-server/issues/6965

Thanks everybody!
