### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/blurts-server#778]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/blurts-server/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by pdehaan** [comment]
@groovecoder @lesleyjanenorton It doesn't look like this repo uses the [wiki](https://github.com/mozilla/blurts-server/wiki), not sure if we should just disable it.

**Comment by pdehaan** [comment]
Wiki deleted. Closing issue.
