### ISSUE TITLE
A scanned email is kept while you want to sign in to FM

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#779]
[Affected versions]:
- Firefox 65.0.1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to  http://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net
2. Scan a valid email (type an email in the "Eneter Email Address" field).
3. Click on “Firefox monitor” button (in order to get to the main page)
4. Click on the “Sign up” button.

[Expected result]:
- The fields in the Sign in page are blank. 

[Actual result]:
- The email you scanned is automatically filled in the Sign in page.  

[Regression]:
- N/A

[Additional Notes]:
- This issue happens even if you are not logged into sync.
- This issue doesn't reproduce if you use the "Go back one page" button to navigate to the main page.

**Comment by lesleyjanenorton** [comment]
This is as-designed and was meant to streamline the sign in flow from scanning an email to signing up. Leaving this open for further commentary since this has already been a point of confusion for others.

**Comment by sandysage** [comment]
This is intentional behavior. If we find further reports, from users engaging the service and not testing it like we have been, then we'll revisit this flow. Closing for now.
