### ISSUE TITLE
While signing in with an account, the password for a previous account is kept

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#780]
[Affected versions]:
- Firefox 65.0.1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Prerequisites]:
- Sign in with a valid account (A) and save the email and password in the doorhanger. 

[Steps to reproduce]:
1. Navigate to  http://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net
2. Log out from the account A. 
3. Click on sign in and try to sign in with a different account (B).

[Expected result]:
- The fields in the Sign in page are blank. 

[Actual result]:
- The password field is populated with the password from account A.  

[Regression]:
- N/A

[Additional Notes]:
- This issue wouldn't be that strange if there wasn't a different page to load for typing the password. 
- And the thing that makes this a real issue is that you can actually see the previous password (if you click on the eye symbol).

**Comment by groovecoder** [comment]
I think this is a bug with https://stable.dev.lcip.org/signup - not something we can fix on the Monitor side. @mozilla/fxa-core ?

**Comment by jrgm** [comment]
Was the browser set up with config to treat stable.dev.lcip.org as the fxa accounts domain, or was it just the default config.

Regardless, `stable.dev.lcip.org`'s `dockerd` did restart itself (and all the containers) during it's scheduled weekly refresh, but it appears to have come back up correctly and automated tests are (mostly) all passing.

**Comment by rfk** [comment]
> Sign in with a valid account (A) and save the email and password in the doorhanger.

It's specifically an issue with password-autofill on the FxA login form; I suggest migrating this to an issue at https://github.com/mozilla/fxa-content-server/issues for discussion, although I can't think of an obvious quick fix.
