### ISSUE TITLE
Visual issues with "Breach data provided by Have I Been Pwned" on small display size

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/blurts-server#783]
Environment: iOS - iPhone SE (12.0.1)

Steps to reproduce:
1. Access https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/ and click on the "Sign In" button.
2. Sign In with a valid email address (breached).
3. Scroll the page until "Breach data provided by Have I Been Pwned" is displayed.

Actual results:   
- "Breach data provided by Have I Been Pwned" not centered;
- No padding between "Breach data provided by Have I Been Pwned" and "See Full Report".

Expected results: space is added between them and the content is centered. 

Screenshot: 
![2019_02_18_18_13_49_image_1_1_ jpg_photos](https://user-images.githubusercontent.com/24588037/52963640-03567c80-33a9-11e9-8212-c6d404f42fb6.png)

**Comment by lesleyjanenorton** [comment]
This should have been fixed in #750, but it looks like those updates have not yet made it to the stage server. Please verify these issues have been fixed at https://fx-breach-alerts.herokuapp.com/.

**Comment by SorinaFlorean** [comment]
Tested on https://fx-breach-alerts.herokuapp.com/ and looks like the issue is fixed.
