### ISSUE TITLE
The breach <number> is not bolded when displaying results on the page

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#786]
[Affected versions]:
- Firefox 65.0.1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to  http://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net
2. Scan a compromised account, e.g. test@gmail.com.

[Expected result]:
- The <number> of compromised accounts is displayed with a bold style.

[Actual result]:
- The <number> of compromised accounts has a normal style not bolded.

[Regression]:
- N/A

[Additional notes]:
- please observe the screenshot with the issue below:

![bold2](https://user-images.githubusercontent.com/43886441/53005854-be7c2580-343c-11e9-9d2a-41c5251ed869.png)

**Comment by pdehaan** [comment]
One thing I did notice today is that "zero" is not bold if you magically weren't involved in a breach. Not sure if that's worth a follow up bug or if it's "good enough"(tm) for now.

via https://fx-breach-alerts.herokuapp.com/scan

```js
{
  commit: "f5c4b5e88e1df37b19125eff19b2fea0bf497ea8",
  version: "f5c4b5e88e1df37b19125eff19b2fea0bf497ea8",
  source: "https://github.com/mozilla/blurts-server"
}
```

![firefox_monitor___scan_results](https://user-images.githubusercontent.com/557895/53130570-87cb0b80-351f-11e9-9f30-815101c0aea8.png)

![firefox_monitor___scan_results](https://user-images.githubusercontent.com/557895/53130652-b943d700-351f-11e9-8bff-397a1d76b6a5.png)

**Comment by GeorgiuCiprian** [comment]
I can confirm that the compromised number has a bold style on [stage.](https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/) Tested with 67.0a1 under Windows 10 x64.
