### ISSUE TITLE
Difference between UI specs and stage regarding the uncompromised accounts  

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#788]
[Affected versions]:
- Firefox 65.0.1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to  http://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net and Sign in with a valid account.
2. Scan an uncompromised account, e.g. cipgeo@gmail.com.

[Expected result]:
- The "So far, so good" text is displayed after the "This email appeared in zero data breaches."
- The "zero" string is changed with the "0" number.

[Actual result]:
- The "So far, so good" text is NOT  displayed after the "This email appeared in zero data breaches."
- The "zero" string is NOT changed with the "0" number.

[Regression]:
- N/A

[Additional notes]:
- please observe the screenshot with the issue below:
![image](https://user-images.githubusercontent.com/43886441/53028882-6b23ca80-3470-11e9-8614-b37f2af74526.png)

**Comment by lesleyjanenorton** [comment]
Closing since this bug is in reference to the previous UI.
