### ISSUE TITLE
Lazy load breach logos when doing a /scan?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#790]
This may be a bit of a stretch, but I noticed while doing a scan of "test@gmail.com" that there are 136 breaches, and we load all the logos immediately (151 network requests | 1.5 MB transferred | Finished: 5.85 s | DOMContentLoaded: 1.79 s), even though only 4 breach logos are immediately visible, and the remaining 132 logos are hidden behind the "Show all" button.

Not sure if we want to try [lazy loading](https://www.sitepoint.com/five-techniques-lazy-load-images-website-performance/) those 132 images so we aren't making all those network requests up front.

Looking at the network log a bit more, it seems like 140/151 requests are for images (962 KB of 1.5 MB total; the FiraSans-*.woff fonts take up a fairly significant 333 KB of the total page size). But if we look at 962 KB from 140 images, that's roughly 6.87 KB per image, or very roughly 907 KB of images which may not need to be loaded immediately).

**Comment by pdehaan** [comment]
@lesleyjanenorton I'm 99% certain that you did this already for the logged out state (and maybe the logged in version as well). Can you confirm/close?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
