### ISSUE TITLE
Broken image displayed for the account avatar if the user deletes the Account picture 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#794]
[Affected versions]:
- Firefox 65.0.1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to http://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net and Sign in with a valid account.
2. Go to https://stable.dev.lcip.org/settings and change the default "Account picture" to any other one.
3. Click on the "Change" button from https://stable.dev.lcip.org/settings and clear the image set at the above step.
3. Refresh the http://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net website.

[Expected result]:
- The "Account picture" is reverted to the default image. 

[Actual result]:
-  The "Account picture" is reverted to broken image.

[Regression]:
- N/A

[Additional notes]:
- Note that after the user signs out from the website then signs in again, the default image is properly displayed.

- please observe the screenshot with the issue below:
![image](https://user-images.githubusercontent.com/43886441/53078722-812b9c80-34fd-11e9-936f-942222988c55.png)

**Comment by groovecoder** [comment]
Hmm ... this would also require pinging FxA on every page-load, unless we can get a callback on all profile data updates?

**Comment by lesleyjanenorton** [comment]
I can no longer reproduce this - please reopen if this is still an issue. thanks!
