### ISSUE TITLE
Add breach AddedDate to front end UI?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#804]
The latest breach, [MyFitnessPal](https://fx-breach-alerts.herokuapp.com/?breach=MyFitnessPal), was just added to HIBP but we only seem to display the "Breach date" (Jan 1 2017; 782 days ago).

Not sure if it'd be better to add another date to the UI which is the date that the breach was disclosed and added to the site:

https://fx-breach-alerts.herokuapp.com/?breach=MyFitnessPal

![firefox_monitor](https://user-images.githubusercontent.com/557895/53200645-ea331300-35d6-11e9-8869-9ca06c81d305.png)

https://haveibeenpwned.com/PwnedWebsites#MyFitnessPal

![have_i_been_pwned__pwned_websites](https://user-images.githubusercontent.com/557895/53200852-747b7700-35d7-11e9-84bc-3095720bd4a6.png)

Looking at the latest 10 breaches, it looks like the Breach Date vs the Added Date can be pretty different:

| # | NAME | BREACH DATE | ADDED DATE | DIFF (days) |
|--:|:-----|:-----------:|:----------:|-----:|
| 1 | MyFitnessPal | 12/31/2016 | 2/21/2019 | 782
| 2 | MyHeritage | 10/25/2017 | 2/20/2019 | 483
| 3 | EyeEm | 2/27/2018 | 2/15/2019 | 354
| 4 | devkitPro | 2/2/2019 | 2/10/2019 | 9
| 5 | Collection 1 | 1/6/2019 | 1/16/2019 | 10
| 6 | FaceUP | 12/31/2012 | 1/13/2019 | 2204
| 7 | Dangdang | 5/31/2011 | 1/10/2019 | 2781
| 8 | BannerBit | 12/28/2018 | 1/8/2019 | 11
| 9 | BlankMediaGames | 12/27/2018 | 1/1/2019 | 6
| 10 | GoldSilver | 10/20/2018 | 12/27/2018 | 68

For giggles, I wrote https://hibp.now.sh/ which renders the latest HIBP breach data using Vue.js and displays the BreachDate-vs-AddedDate diff.

**Comment by pdehaan** [comment]
Fun stat: avg breach date -> added date seems to be 503.622 days

And the 12 slowest breach responses are:

| TITLE | BREACH DATE | ADDED DATE | DIFF |
|:------|------------:|-----------:|-----:|
Baby Names | 10/23/2008 | 10/23/2018 | 10.01y
gPotato | 7/11/2007 | 9/24/2016 | 9.21y
Elance | 12/31/2008 | 2/17/2017 | 8.14y
MySpace | 6/30/2008 | 5/30/2016 | 7.92y
Foxy Bingo | 4/3/2008 | 11/21/2015 | 7.64y
Dangdang | 5/31/2011 | 1/10/2019 | 7.62y
Money Bookers | 12/31/2008 | 11/30/2015 | 6.92y
7k7k | 12/31/2010 | 9/26/2017 | 6.74y
17173 | 12/27/2011 | 4/27/2018 | 6.34y
League of Legends | 6/10/2012 | 7/28/2018 | 6.13y
Zoosk | 12/31/2010 | 2/7/2017 | 6.11y
FaceUP | 12/31/2012 | 1/13/2019 | 6.04y

&mdash; via https://github.com/pdehaan/monitor-breaches-axios

**Comment by sandysage** [comment]
This is being addressed in the new design work. Closing this issue as we're reconsidering the entire experience around breach dates.
