### ISSUE TITLE
Reset user sessions when they click "Unsubscribe"

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#805]
We currently call `req.session.reset()` when a user submits an unsubscribe survey answer. Since some users don't submit survey answers,  we should call `req.session.reset()` when a signed in user clicks the unsubscribe button on the first page of the unsub flow.

**Comment by sandysage** [comment]
This is related to #816

**Comment by groovecoder** [comment]
This is now fixed - we reset the session on unsubscribe and on "Remove Firefox Monitor"
