### ISSUE TITLE
Record the number of breaches a scan returns

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/blurts-server#807]
Via conversation with @changecourse, this data could be used to show the value of monitor to potential users (e.g. "Users of monitor were found to have had on average XX breaches"), and might inform other design issues.

Of course, if we were to consider collecting such measures we would want to be very careful and get review from policy. This could be ripe for an application of [differential privacy](https://privacytools.seas.harvard.edu/differential-privacy)

**Comment by sandysage** [comment]
@lesleyjanenorton let's plan to take a count of the number of times a listing appears on the page
