### ISSUE TITLE
Odd flash of a modal on page load [Chrome only?]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#809]
I wasn't able to reproduce this in Firefox yet, but in Chrome I occasionally see a flash of a modal looking thing during page load. Not sure if it's just the weird split second from the DOM rendering and some CSS maybe not getting applied yet, but it can be somewhat noticeable and jarring.

https://monitor.firefox.com/

Best I can figure is that it's this element that's flashing in briefly before being hidden:
 
https://github.com/mozilla/blurts-server/blob/c6c4c30b8c39c48e8f6c1ea58cb98ed076964361/views/partials/subscribe_modal/subscribe_modal_wrapper.hbs#L1-L6

**Comment by lesleyjanenorton** [comment]
Closing since this modal is now a thing of the past.
