### ISSUE TITLE
Refresh FxA profile data on page-loads

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#816]
Based on Vijay's findings in the [Monitor and FxA Integration](https://docs.google.com/document/d/12Fah9i1tYZLiPwUIUpjslfY1dpKZIyI7b6N4Uv0GzQw/edit#heading=h.lxh3sysaocd7), after someone deletes their account, the profile information is still available on Monitor for 15 minutes - When a user deletes their Firefox Account, their Monitor login session remains valid until it expires in 15 minutes.

We want to get this addressed so that the FxA profile information is updated more frequently - on page load. With a timeout of 500ms or 1s.

**Comment by sandysage** [comment]
Let's also use this ticket to update both the avatar image AND the email address.

**Comment by groovecoder** [comment]
Fix for this started in https://github.com/mozilla/blurts-server/pull/1352 but I'm not 100% sure I'm happy with the approach yet.
