### ISSUE TITLE
Sign up for Alerts button on all scan results

### ISSUE THREAD

**Issue by betsymi** [mozilla/blurts-server#823]
Is is possible to have the same button copy on all scan results? Right now we have "Sign up for Alerts" on zero results, but would like it to read the same for users who have 1+ results.

**Comment by betsymi** [comment]
![screenshot_2019-03-07 find out if you ve been part of a data breach 1](https://user-images.githubusercontent.com/43555492/53972193-f41f4080-40c3-11e9-8449-e26d0ea07291.png)
![screenshot_2019-03-07 find out if you ve been part of a data breach](https://user-images.githubusercontent.com/43555492/53972194-f41f4080-40c3-11e9-86cd-0c1036237a2b.png)

**Comment by lesleyjanenorton** [comment]
Definitely possible. Should the "Sign Up" button appear anywhere other than the Sign Up Banner?

**Comment by betsymi** [comment]
We can keep the Sign Up button on the banner as-is (attaching for reference. This can stay). I'm proposing the Sign up for Alert change only for when it that button appears at the top of the page in search results because if you have several breaches, the whole banner gets pretty buried. [](url)

**Comment by betsymi** [comment]
![screenshot_2019-03-08 find out if you ve been part of a data breach](https://user-images.githubusercontent.com/43555492/54043090-5eea7d80-4191-11e9-8c76-5a31efba5239.png)

**Comment by tcinotto** [comment]
Won't be fixed.
