### ISSUE TITLE
Unable to scan another email address when viewing /scan/full_report

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#838]
There is a "Want to check another email?" block on the [/scan/user_dashboard](https://monitor.firefox.com/scan/user_dashboard) URL, but there isn't seemingly a way to scan from the [/scan/full_report](https://monitor.firefox.com/scan/full_report) (when logged in via FxA).

Looks like the only way to search another email is to go back to the homepage (which redirects back to the /scan/user_dashboard).

## Witness me!

![Firefox_Monitor___Scan_Results](https://user-images.githubusercontent.com/557895/54243416-989aeb80-44e5-11e9-8bd3-1209d0a09814.png)
**Figure 1:** /scan/full_dashboard

![Firefox_Monitor___Scan_Results](https://user-images.githubusercontent.com/557895/54243373-5ffb1200-44e5-11e9-8a02-a4f639f40a17.png)
**Figure 2:** /scan/user_dashboard

**Comment by lesleyjanenorton** [comment]
This is "as designed" (https://e-pang.github.io/fm_fxa/#artboard18) but I think this page could benefit from the addition of a "Scan Another Email" form.

**Comment by pdehaan** [comment]
Yeah, we probably want to reconsider this UX. I thought I almost needed to log out of FxA in order to search a different email.

**Comment by sandysage** [comment]
@pdehaan we agree. This is getting holistically considered in our V2 designs. As such I'm hesitant to make changes now given the upcoming updates. Closing for now.
