### ISSUE TITLE
Use "Summary with Large Image" Twitter card. 

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#839]
Rec from Marketing via Slack: 
We should update our Twitter meta tags to use the "Summary Card with Large Image" format instead of the current "Summary Card" format. As hinted in the description, the "Summary Card with Large Image" format means a bigger picture, and more Twitter-feed real estate for each share.

**Comment by pdehaan** [comment]
via https://cards-dev.twitter.com/validator


### Before:

![Card_Validator___Twitter_Developers](https://user-images.githubusercontent.com/557895/54461136-fcf9bd00-4728-11e9-8720-5c34fad2a003.png)

### After:

![Card_Validator___Twitter_Developers](https://user-images.githubusercontent.com/557895/54461166-0c790600-4729-11e9-9c94-d60392e15158.png)
