### ISSUE TITLE
Forward UTM parameters to FxA login/registration from referrals to the landing page

### ISSUE THREAD

**Issue by zerokarmaleft** [mozilla/blurts-server#844]
SUMO is cross-promoting Monitor, and proper attribution (`utm_source`, `utm_medium`, `utm_campaign`, `utm_content`, and `utm_term`) needs to get forwarded to the FxA signup form on the landing page. This would support cross-promotion from other referral sources in the future as well.

**Comment by groovecoder** [comment]
@sandysage - is this an FxA funnel fix we want to release before 2.0?

**Comment by zerokarmaleft** [comment]
The moz.org team is doing similar work -- discussion at https://github.com/mozilla/bedrock/issues/6854 may be helpful.

**Comment by irrationalagent** [comment]
We should forward utm_* parameters, but not `entrypoint`.

**Comment by sandysage** [comment]
As part of this effort we also want to know when someone comes back to the Monitor site/service from our own emails.

**Comment by irrationalagent** [comment]
@lesleyjanenorton  So we were trying to track the logins on the monitor website that are coming from the new toolbar menu item that promotes monitor (this just moved up to beta 70 last week). the new menu item should be passing utm_source = `fxa-toolbar`, which if iiuc given *should* now be forwarded to FxA when the user starts the FxA flow on the website. however our metrics seem to indicate that this is not happening and I also cannot get the forwarding to work locally, see gif: 
![out](https://user-images.githubusercontent.com/5625313/64553908-8284b100-d2f7-11e9-8a1e-d28545842c2e.gif)

thoughts?
cc @davismtl

**Comment by irrationalagent** [comment]
from @groovecoder in slack:
aaaaaah ….. that sounds like a bug then. Sounds like we just need to activate the same utm_*-preserving code on the big CTA buttons as the sign-in button. 

So from my understanding, we need to forward the utms via the CTAs on the /scan page as well. forwarding seems to work for the sign in button.

**Comment by ddurst** [comment]
@groovecoder or @lesleyjanenorton please add an `effort` label to this when you get a chance.

**Comment by lesleyjanenorton** [comment]
> from @groovecoder in slack:
> 
> > aaaaaah ….. that sounds like a bug then. Sounds like we just need to activate the same utm_*-preserving code on the big CTA buttons as the sign-in button.
> 
> So from my understanding, we need to forward the utms via the CTAs on the /scan page as well. forwarding seems to work for the sign in button.

Do we need to pass UTMs captured on the landing page to the `/scan` results page? Or do we just need to capture and pass along UTM values sent directly to the `/scan` route by a referring site?
