### ISSUE TITLE
Send email notification to mailing list when a new breach is uploaded

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#845]
Per discussions around the breach playbook, right now we send a manual email to let stakeholders know there is a new breach.

To reduce the risk of failure here, I'd like to automate this process so that everyone is informed whenever a new breach is uploaded.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
