### ISSUE TITLE
Consider making HIBP.getBreachByName case-insensitive

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#860]
If we get a HIBP callback message with an incorrectly-capitalized breach name, we call HIBP.getBreachByName with it, and currently throw an ["Unrecognized breach" error](https://sentry.prod.mozaws.net/operations/firefox-monitor/issues/4948733/).

We should consider if we can make the code more flexible.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
