### ISSUE TITLE
Include a useful "comment" when putting new breaches into Kinto

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-server#865]
Currently our script doesn't make a "comment" along with its review request, and from what I saw when I approved the last one, the Kinto UI just shows the comment of the previous "commit" IIRC. We should see if we can use this "comment" field to include information that's useful.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
