### ISSUE TITLE
There are vulnerable dependencies which exceed the selected threshold and scope

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#867]
Seen in https://travis-ci.org/mozilla/blurts-server/jobs/523550074 failure:

> blurts-server@0.0.1 lint:audit /home/travis/build/mozilla/blurts-server
> `npm-audit-ci-wrapper -t 'high'`

> There are vulnerable dependencies which exceed the selected threshold and scope:

| DEPENDENCY | ADVISORY | REMEDIATION |
|:-----------|:---------|:------------|
| handlebars@4.1.0 | [/advisories/755](https://www.npmjs.com/advisories/755)<br/>(high >= high) | For handlebars 4.1.x upgrade to 4.1.2 or later.<br/>For handlebars 4.0.x upgrade to 4.0.14 or later.
| tar@4.4.1 | [/advisories/803](https://www.npmjs.com/advisories/803)<br/>(high >= high) | Upgrade to version 4.4.2 or later.
| js-yaml@3.11.0 | [/advisories/813](https://www.npmjs.com/advisories/813)<br/>(high >= high) | Upgrade to version 3.13.1.

**Comment by pdehaan** [comment]
Ref: #582

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
