### ISSUE TITLE
[v2] Some /breaches logos have undefined img sources

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#870]
https://monitor-v2.herokuapp.com/breaches

I noticed a few 404s on some logos. For example, for some reason the "EverybodyEdits" breach has an `<img src="undefined" />`:

https://monitor-v2.herokuapp.com/img/logos/EverybodyEdits.png
https://monitor-v2.herokuapp.com/img/logos/DemonForums.png
https://monitor-v2.herokuapp.com/img/logos/MoreleNet.png

```html
<img alt=""
    class="breach-logo"
    data-srcset="/img/logos/EverybodyEdits.png"
    src="undefined"
    srcset="/img/logos/EverybodyEdits.png">
```

Since breach logos are manually updated+merged and we need to wait for a prod uplift, we should probably look at a better fallback to a placeholder image (since the 404 page seems to be a 6.83k penalty).

**Comment by pdehaan** [comment]
Also, the /breaches page seems to be about 450 KB of raw HTML (plus another 266 KB of fonts, 32 KB of CSS and 12 KB of JS). Not sure that there's anything we can do about the HTML size to be more mobile friendly.

I can't immediately think of anything, since the images are already being lazy loaded, and it's just lots of data for 330ish breaches that need to be rendered in the DOM.
We could look at minifying the HTML, but that may or may not save lots of bandwidth.

Once the v2 site is more finalized, I can rerun the Google Lighthouse and webhint.io, AxE, etc.

**Comment by pdehaan** [comment]
Another odd thing is that in my Firefox browser, the broken images resolve in 160-230ms, whereas in Google Chrome, the missing images block page rendering for about 13 seconds which causes the total page load time to be 15.71s.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
