### ISSUE TITLE
[v2] breach filtering isn't working

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#871]
https://monitor-v2.herokuapp.com/breaches

Tried in Firefox release and Chrome, and filtering seems to return an empty list. The "Show All Breaches" button seems to display all the results, but toggling any breach category seems to return 0 results and not display any errors in the devtools console.
I'm 70% certain this used to work and possibly broke recently.

**Comment by lesleyjanenorton** [comment]
Closing- we're back up and filtering now.
