### ISSUE TITLE
Intermittent CSRF errors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#872]
From Slack channel. Not sure what we can do [if anything] to fix this, but it is something I get all the time. Hitting "back" and trying again doesn't work unless you do back+refresh.

> **Q:** Guessing there is already a bug for this but a coworker keeps getting an "invalid csrf token" error so wanted to mention. They say it's fine for Chrome, but not in Firefox :disappointed:

> **A:** This is frustrating! It happens to me all the time when I've been idling on the site. I've drafted error message copy for this for V2. In the meantime, shoot this over to your coworker.
>
> Session timed out
> Select your browser’s back button, reload the page, and try again.
>
> Hopefully that clears it up for them.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
