### ISSUE TITLE
Improve fuzzy finder on "All Breaches..." page.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#877]
Add a "fuzzy find" input so that user's can filter breaches by breach name.

**Comment by pdehaan** [comment]
What fields would we try and search/filter?
I have this rough functionality on my old https://hibp.now.sh/ HIBP viewer. I think I was searching+filtering based on `breach.Name`, `breach.Title`, or `breach.Domain` (but it may also make sense to support `breach.Description`). I also had some functionality to filter by leaked data class, but not sure if that'd make sense or be useful to real world users.

```js
    filteredBreaches() {
      switch (this.q) {
        case "search":
          return this.sortedBreaches.filter(breach => {
            const v = this.value.toLowerCase();
            return (
              breach.Name.toLowerCase().includes(v) ||
              breach.Title.toLowerCase().includes(v) ||
              breach.Domain.toLowerCase().includes(v)
            );
          });
```

**Comment by lesleyjanenorton** [comment]
The initial ask was just to be able to find breaches by their name, but idk how helpful that really is. Changing the issue title and leaving this open for further deliberation.
