### ISSUE TITLE
Add en-us ftl spell checker?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#884]
One of my dumbest ideas yet, but it may just be crazy enough to work.

https://www.npmjs.com/package/markdown-spellcheck checks for typos in a .md Markdown file and stores the custom dictionary entries in a .spelling file.

The good news is that "markdown" is a pretty vague format, so we can spellcheck .ftl files without too many issues:

```sh
$ npx markdown-spellcheck -n -a -x --en-us ./locales/en/email-strings.ftl -r
```

**NOTE:** The <kbd>-r</kbd> flag is for "report mode". If you remove it, the script will run in "interactive mode" and let you manually correct typos or add words to your dictionary.

Other flags are:

- **Ignore numbers** (<kbd>-n</kbd>, <kbd>--ignore-numbers</kbd>)
   Ignores numbers like 1.2 and 1,2.4.
- **Ignore acronyms** (<kbd>-a</kbd>, <kbd>--ignore-acronyms</kbd>)
   Ignores acronyms like NPM. Also ignores numbers. Does not ignore single letters e.g. U.
- **No suggestions** (<kbd>-x</kbd>, <kbd>--no-suggestions</kbd>)
   Suggestions are slow at present, so use this to remove them.

But the main problem is that it really hates the key=value syntax in the .ftl files since it expects that the keys (ie: "layout-social") are valid dictionary words:

```ini
layout-social = Social
```

The following little script will scan a directory of .ftl files, and copy all the key values into a .spelling file:

```js
const fs = require("fs");

const {parse} = require("fluent-syntax");
const glob = require("glob").sync;

main();

async function main() {
  const ftlDist = fs.readFileSync(".spelling-dist", "utf-8");
  const files = glob("./locales/en/*.ftl");
  const keys = files.reduce((acc, file) => acc.concat(` - ${file}`, fetchFtlKeys(file), "\n"), []);
  console.log(keys.concat(ftlDist).join("\n").trim());
}

function fetchFtlKeys(file) {
  const ftl = fs.readFileSync(file, "utf-8");
  const keys = [];
  parse(ftl).body.forEach(item => {
    switch (item.type) {
      case "Message":
      case "Term":
        keys.push(item.id.name);
        break;
      case "GroupComment":
        // ignore
        break;
      default:
        console.log(`UNKNOWN TYPE: ${item.type}`);
        break;
    }
  });
  return keys.sort();
}
```

Where the .spelling-dist file is:

```ini
 - ./locales/en/app.ftl
blog.mozilla.org
emailHash
ssw0rd
1Password
LastPass
Dashlane
Bitwarden
featuredBreach
breachCount
hibp-link
userEmail
2x
breachName
mozilla.org
cyber
Aggregator
aggregator
aggregators
primaryEmail
 - ./locales/en/data-classes.ftl
worths
 - ./locales/en/email-strings.ftl
amongst
mozilla
```

Anyways... Interesting idea. Not sure if it's worth the engineering effort to spellcheck .ftl files or not.

**Comment by pdehaan** [comment]
@flodolo @Pike Do either of you know if we've ever considered .ftl spellchecking before? Wasn't sure if this is something already existing in the wild and I'm not aware of it.

**Comment by Pike** [comment]
I had thought about spell-checking ages ago, in a different context.

Setting up hunspell, or requiring it in general, I'm not sure. Maybe at some point, as something optional?

It might be interesting to include the typos from the android linters (originally wikipedia data), that I linked to in https://bugzilla.mozilla.org/show_bug.cgi?id=1544695. In terms of spellchecking, that's basically a blacklist vs a whitelist ;-)

For the impls you found, that implementation builds on `hunspell-spellchecker`, which is done by gitbook. I'd not invest in stuff gitbook has done :-/ . Also, that's a re-implementation of hunspell in js, and I don't know how feature-compat that is. Surely not kept up-to-date with hunspell itself.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
