### ISSUE TITLE
Update l10n linter to `moz-l10n-lint`

### ISSUE THREAD

**Issue by Pike** [mozilla/blurts-server#888]
I've updated `compare-locales --validate l10n.toml .` to `moz-l10n-lint l10n.toml`.

That's going to grow more features soon, and has better output.

I suggest to migrate to that.

Nit that might be nice to fix along, I made `l10n.toml` work w/out a `locales` field, and that has a different meaning now than `locales = []`. So I suggest to either remove the entry, or make the locale list right.

**Comment by pdehaan** [comment]
I believe this was fixed via #895 

https://github.com/mozilla/blurts-server/blob/4dbce511ccc96746a9be6815c4dabdd91ef1df4b/.travis.yml#L41-L47
