### ISSUE TITLE
Verifying a secondary email takes me to account creation

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#891]
When I go to verify my secondary email address for Monitoring, the email verification link takes me to: https://accounts.firefox.com/signup

**Comment by groovecoder** [comment]
I was able to reproduce this by "crossing container boundaries" when going from https://monitor-v2.herokuapp.com/user/dashboard to mail.google.com. I.e., ...

1. Open https://monitor-v2.herokuapp.com/user/dashboard in regular Firefox tab
2. Add email address "luke...@gmail.com"
3. Open https://mail.google.com/ in my "Personal" container
4. Click "Verify My Email" in Gmail in Personal container tab
(Bug) 5. https://monitor-v2.herokuapp.com/user/dashboard opens in a "Personal" container tab, which has no active login session to https://monitor-v2.herokuapp.com/user/dashboard, so [our `_requireSessionUser` function redirects it to accounts.firefox.com](https://github.com/mozilla/blurts-server/blob/monitor_v2/controllers/user.js#L15-L20).

I'll make the code throw a better "must be signed in" error message in this case.

But @sandysage - can you confirm if you were also using Containers when you encountered this bug?

**Comment by betsymi** [comment]
Copy for this error message:

**You must be signed in to your Firefox Account.**
To finish verifying this email for Firefox Monitor, you must be signed in under your primary account email.
