### ISSUE TITLE
Localize breach descriptions?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#893]
Per https://monitor-v2.herokuapp.com/breach-details/MyFitnessPal overview:

> This is a make-believe breach overview for the MyFitnessPal breach, which occurred on February 1, 2018 and was added to our database on February 21, 2019. **I am waiting for an epiphany as to how these should be localized.**

Not sure that this is epiphany worthy, but not sure if this may be as "simple" as creating a new descriptions.ftl file with the `breach.Name` as the key and the `breach.Description` as the value.

```js
"use strict";

const got = require("got").get;

main();

async function main() {
  const res = await got("https://monitor.firefox.com/hibp/breaches", {json: true});
  const ftl = res.body.reduce((acc, breach) => {
    acc.push(`${breach.Name} =\n    ${breach.Description.trim()}`);
    return acc;
  }, []);
  console.log(ftl.join("\n\n"));
}
```

A few potential gotchas:

1. Not sure if breach names w/ hyphens will be valid FTL identifiers (5 possible errors):
    ```js
    if (/[^\w]/gi.test(breach.Name)) {
      console.log(breach.Name);
    }
    /* OUTPUT:
      Mac-Torrents
      PSX-Scene
      R2-2017
      Reverb-Nation
      Xbox-Scene
    */
    ```

2. The output _may_ not be 100% translator friendly (re: nested HTML tags/attributes):
    ```ini
    VerificationsIO =
        In February 2019, the email address validation service <a href="https://securitydiscovery.com/800-million-emails-leaked-online-by-email-verification-service" target="_blank" rel="noopener">verifications.io suffered a data breach</a>. Discovered by <a href="https://twitter.com/mayhemdayone" target="_blank" rel="noopener">Bob Diachenko</a> and <a href="https://twitter.com/vinnytroia" target="_blank" rel="noopener">Vinny Troia</a>, the breach was due to the data being stored in a MongoDB instance left publicly facing without a password and resulted in 763 million unique email addresses being exposed. Many records within the data also included additional personal attributes such as names, phone numbers, IP addresses, dates of birth and genders. No passwords were included in the data. The Verifications.io website went offline during the disclosure process, although <a href="https://web.archive.org/web/20190227230352/https://verifications.io/" target="_blank" rel="noopener">an archived copy remains viewable</a>.
    ```
    Note sure if there is any HTML tweaking that we'd need to do (like adjusting link `rel="noopener"` and `target="_blank"` values), or if we remove the link's `href=""` value if we're doing some FTL overlay stuff (or if that only applies to React+Fluent).
    I'd be a bit cautious to remove all HTML from the descriptions since it may make some descriptions less readable/actionable, but maybe not.
    But if we do want to sanitize all the incoming HTML in breach descriptions, it seems pretty trivial

```js
"use strict";

const got = require("got").get;
const _sanitizeHtml = require("sanitize-html");

main();

async function main() {
  const res = await got("https://monitor.firefox.com/hibp/breaches", {json: true});
  const ftl = res.body.reduce((acc, breach) => {
    acc.push(`${breach.Name} =\n    ${sanitizeHtml(breach.Description)}`);
    return acc;
  }, []);
  console.log(ftl.join("\n\n"));
}

function sanitizeHtml(markup) {
  return _sanitizeHtml(markup, {allowedTags: []});
}
```

Looks like the only HTML tags currently in HIBP are `<a>` and a handful of `<b>`, `<em>`, and `<i>` tags:

- `<em>`: [8tracks](https://haveibeenpwned.com/api/v2/breach/8tracks)
- `<em>`: [Adobe](https://haveibeenpwned.com/api/v2/breach/Adobe)
- `<em>`: [AdultFanFiction](https://haveibeenpwned.com/api/v2/breach/AdultFanFiction)
- `<em>`: [Collection1](https://haveibeenpwned.com/api/v2/breach/Collection1)
- `<i>`: [Estonia](https://haveibeenpwned.com/api/v2/breach/Estonia)
- `<b>`: [Estonia](https://haveibeenpwned.com/api/v2/breach/Estonia)
- `<em>`: [FLVS](https://haveibeenpwned.com/api/v2/breach/FLVS)
- `<em>`: [Sony](https://haveibeenpwned.com/api/v2/breach/Sony)

Current breach description HTML tag stats:
```js
{ a: 496, b: 1, em: 6, i: 1 }
```

I did a quick scan of the linked domains (282 unique domains) and didn't see anything _too_ scandalous (mostly just links to the breached site, or sometimes links to sensitive breach domains), but we definitely may want to tweak the HTML to include `rel="nofollow noopener noreferrer"` and follow safety protocols when linking to random 3rd party sites.

<details>
<summary>link checker</summary>

```js
"use strict";

const got = require("got").get;
const _sanitizeHtml = require("sanitize-html");

main();

async function main() {
  const res = await got("https://monitor.firefox.com/hibp/breaches", {json: true});
  const ftl = res.body.reduce((acc, breach) => {
    acc.push(`${breach.Name} =\n    ${sanitizeHtml(breach)}`);
    return acc;
  }, []);
  // console.log(ftl.join("\n\n"));
  console.log(tagStats);
  // console.log(JSON.stringify(links, null, 2));
  console.log([...domains].sort());
}

const tagStats = {a:0, b:0, em:0, i:0};
const links = [];
const domains = new Set();

function sanitizeHtml(markup) {
  return _sanitizeHtml(markup.Description, {
    exclusiveFilter: (frame) => {
      tagStats[frame.tag] += 1;
      if (frame.tag === "a") {
        const linkDomain = frame.attribs.href && new URL(frame.attribs.href).hostname.replace(/^www\./, "");
        domains.add(linkDomain);
        links.push({
          breachName: markup.Name,
          linkText: frame.text,
          linkHref: frame.attribs.href,
          linkDomain
        });
      }
      return false;
    }
  });
}

```
</details>

**Comment by lesleyjanenorton** [comment]
I'm actually not sure why we aren't using the descriptions in this next iteration. Previously, I think the feeling was that they 1.) contained some HTML and 2.) would be too much to localize. What we now however is a never-to-be-localized, standard issue paragraph which reads:

<i> "On January 1, 2018, `breach.Title`  suffered a breach. Once the breach was discovered and verified it was added to our database on `breach.AddedDate`." </i>

...which is not terribly informative. Given that we don't intend to localize our new generic overview blurb, maybe we can use the breach descriptions from HIBP even if they can't be localized?

**Comment by pdehaan** [comment]
> Given that we don't intend to localize our new generic overview blurb, maybe we can use the breach descriptions from HIBP even if they can't be localized?

What was the rationale for a generic, standard issue paragraph which we won't localize?

/cc @flodolo

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
