### ISSUE TITLE
What To Do Next images broken on email from firefox-monitor-dev

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#894]
This just appeared in my inbox and noticed we had some broken images:

![Your_Firefox_Monitor_report_-_peterdehaan_gmail_com_-_Gmail](https://user-images.githubusercontent.com/557895/57485875-aa88d880-7261-11e9-9110-b0ca0539ebaa.png)

![Your_Firefox_Monitor_report_-_peterdehaan_gmail_com_-_Gmail](https://user-images.githubusercontent.com/557895/57485769-744b5900-7261-11e9-9300-36f672be5c6f.png)

**Comment by lesleyjanenorton** [comment]
Closing since this is now fixed.
