### ISSUE TITLE
Visiting /user/preferences without a session triggers an application error

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#901]
I'm not logged in to FxA on monitor-v2, but I seem to be getting an application error when visiting https://monitor-v2.herokuapp.com/user/preferences (but not the homepage of the server, which makes me think the server is alive).

_Originally posted by @pdehaan in https://github.com/mozilla/blurts-server/issues/890#issuecomment-491422996_

---

**UPDATE:** Same w/ https://fx-breach-alerts.herokuapp.com/user/dashboard link that Tony just shared in Slack channel. Heroku bombs on that page if I'm not signed in.

**Comment by lesleyjanenorton** [comment]
Closing - we're now redirecting users to the `/oauth` flow.
