### ISSUE TITLE
[v2] Monitor v2 says I was in 7 breaches, but only displays 6

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#902]
Was checking if I was in the appartoo breach via https://monitor-v2.herokuapp.com/, entered "peter@test.com" and got the following: 

![Firefox_Monitor___Scan_Results](https://user-images.githubusercontent.com/557895/57560250-69b0c280-733a-11e9-9e1d-fa6ffe747b8f.png)

Also, on wider viewports, that last row's columns are misaligned.

Same results if you generically scan from the homepage:

![Firefox_Monitor___Scan_Results](https://user-images.githubusercontent.com/557895/57560295-99f86100-733a-11e9-8fcc-a82f2666ec5e.png)

**Comment by lesleyjanenorton** [comment]
How wide of a viewport? I wasn't able to recreate the margining/sizing issues on my laptop. The rest of it should be good after afc71f0b400e7151120e9c76dd0b92875d629d29

**Comment by pdehaan** [comment]
I think it's breaking on viewports that are over 1200px wide:

![Firefox_Monitor___Scan_Results](https://user-images.githubusercontent.com/557895/57578224-b086e100-743c-11e9-8dea-2760068f7a48.png)

**Comment by pdehaan** [comment]
I think this is broken on the logged in https://fx-breach-alerts.herokuapp.com/user/dashboard page still (but can confirm it works on the non-logged in variant).

![fx-breach-alerts herokuapp com_user_dashboard](https://user-images.githubusercontent.com/557895/57657534-70d10e00-7590-11e9-8b76-c4b56e25b248.png)
