### ISSUE TITLE
[v2] Breach cards stretch to fill space

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#903]
# Steps to reproduce

1. Go to https://monitor-v2.herokuapp.com/breaches
2. Select "Sensitive Breaches" and "Data Aggregator Breaches".
3. Scroll to bottom.

## Actual results
Last card is 100% width instead of 33% width.

![All_the_breaches](https://user-images.githubusercontent.com/557895/57578428-22f9c000-7441-11e9-827d-4c7361b6a830.png)

If you select all breaches, the last 2 cards are 50% each:

![All_the_breaches](https://user-images.githubusercontent.com/557895/57578431-43297f00-7441-11e9-827a-e7fc5d9e21bb.png)

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
