### ISSUE TITLE
[v2] Breach filters can get inconsistent between top filters and floating filters

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#904]
### Steps to reproduce

1. Go to https://monitor-v2.herokuapp.com/breaches
1. Filter by "Sensitive Breaches" and verify that the filter is highlighted (See figure 1 below).
1. Scroll to bottom.
1. Scroll back to the top to see the floating filters and compare w/ the filters in step 2 above (See figure 2 below).

### Actual results

![All_the_breaches](https://user-images.githubusercontent.com/557895/57578463-d2369700-7441-11e9-93eb-82280cbd6648.png)
**Figure 1:** Filtered breaches at top of page.

![All_the_breaches](https://user-images.githubusercontent.com/557895/57578465-eaa6b180-7441-11e9-9d97-1328f3c8ca65.png)
**Figure 2:** Sticky filtered breaches after scrolling.

**Comment by lesleyjanenorton** [comment]
No longer an issue post #956
