### ISSUE TITLE
[v2] Filtered breaches should show all breaches if no filters are active

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#905]
### Steps to reproduce

1. Go to https://monitor-v2.herokuapp.com/breaches
1. Deselect all filters.

### Actual results
Page is 99% empty.

![All_the_breaches](https://user-images.githubusercontent.com/557895/57578501-8c2e0300-7442-11e9-8371-1c7a35634f0e.png)

### Expected results
Page should default to showing "All Breaches" if the "Website Breaches", "Sensitive Breaches" and "Data Aggregator Breaches" filters are all deselected.

**Comment by lesleyjanenorton** [comment]
Fixed / no longer an issue in #956
