### ISSUE TITLE
[v2] At least 3 different styles for breach cards

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#906]
### Steps to reproduce

1. Look at "LATEST BREACH ADDED" on homepage: https://monitor-v2.herokuapp.com/
1. Look at master breach list: https://monitor-v2.herokuapp.com/breaches
1. Check for breaches (test@test.com) via homepage: https://monitor-v2.herokuapp.com/

### Actual results
Each page shows the breach results slightly differently. I expect some difference from the "LATEST BREACH ADDED" on homepage, but there are slight differences in each place where we show a breach:

1. homepage latest breach (see **Fig 1** below):
  - breach.Title
  - breach reported date
  - breach compromised accounts
2. /breaches page (see **Fig 2** below):
  - breach.Title
  - breach reported date
  - breach compromised accounts
  - breach compromised data
3. /scan page (via searching test@test from homepage -- see **Fig 3** below):
  - breach.Title
  - breach reported date
  - breach compromised data

---

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/57578559-a1eff800-7443-11e9-9bb3-e93c9ab03a18.png)
**Fig 1:** LATEST BREACH ADDED via homepage.

---

![All_the_breaches](https://user-images.githubusercontent.com/557895/57578601-5be76400-7444-11e9-8281-d5aacd999b11.png)
**Fig 2:** All breaches via /breaches page. 3 columns, jazzy color in header.

--- 

![Firefox_Monitor___Scan_Results](https://user-images.githubusercontent.com/557895/57578613-8fc28980-7444-11e9-81cd-e7e2773eee2c.png)
**Fig 3:** Search results for test@test.com via homepage search. 2 columns.

**Comment by lesleyjanenorton** [comment]
Closing since we have more or less the same breach card across all of the places now.
