### ISSUE TITLE
Security Tips page text is difficult to read

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#907]
https://monitor-v2.herokuapp.com/security-tips#how-hackers-work

![Security_Tip_Page_Title_Needed](https://user-images.githubusercontent.com/557895/57636385-e1ab0280-755d-11e9-9f78-c13f5c1ce2bf.png)

I _think_ the problem is that we have the following rule:

```css
.security-tips {
  color: var(--grey1);
}
```

... but the page contents are a sibling of the `.security-tips` content (in the `<section>` tag), so the `--grey1` coloring does not get applied:

```html
<main class="container clear-header security-tips bg-ink-light ">...</main>
<section class="container bg-ink-light">...</section>
```

If I copy the `<section>` into the sibling `<main>` tag, everything looks right.

**Comment by lesleyjanenorton** [comment]
"Difficult to read" is putting it nicely. This page has been completely reworked in last commits to #898
