### ISSUE TITLE
Conslidate use of fluent with "Firefox Monitor"

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#912]
As commented in https://github.com/mozilla/blurts-server/pull/898#discussion_r283448539, we sometimes put `"Firefox Monitor"` and sometimes put `req.fluentFormat("Firefox Monitor")`

Let's make them as consistent as possible.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
