### ISSUE TITLE
Adjust copy for Unsubscribe for Secondary Email

### ISSUE THREAD

**Issue by betsymi** [mozilla/blurts-server#913]
Slightly modified unsubscribe copy. If user clicks unsubscribe link for any email that is not their primary email. 

**Unsubscribe this email from Firefox Monitor alerts.**
You’ll no longer receive Firefox Monitor alerts for **emailaddress@email.com.** Your Firefox Account will remain active, and you may receive other account-related communications to your primary email. Manage Firefox Account…

BUTTON
Unsubscribe

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
