### ISSUE TITLE
Need text for when a breach list search has no results

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#919]
## Steps to reproduce

1. Go to https://fx-breach-alerts.herokuapp.com/breaches
2. Search for a random string, like "qwerty".

### Actual results
"empty" results page

### Expected results
A friendly error message saying something like "No matches found, please try again".
Uncertain if we should pre-populate the search form with the current search query.

**Comment by lesleyjanenorton** [comment]
It's in there, just needs to be implemented. String ID is`no-results-blurb`. This is on my list for tomorrow, along with the other filtering quirks.

**Comment by groovecoder** [comment]
Thanks for filing all these @pdehaan. I'm going thru and adding the "bug" label and Project to the ones we need to make sure to fix for launch.

**Comment by pdehaan** [comment]
> I'm going thru and adding the "bug" label and Project to the ones we need to make sure to fix for launch.

Awesome, thanks! It's super helpful if you can flag all the issues that we want to fix for the v2 launch in a milestone or project column, or even just a single label so QA can get a sense of how many issues are left before launch to see if we're 98% of the way there, or 42%. 🍻

**Comment by lesleyjanenorton** [comment]
Fixed in #956
