### ISSUE TITLE
Odd search filtering after doing a search

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#920]
## Steps to reproduce:
1. Go to https://fx-breach-alerts.herokuapp.com/breaches
2. Search for "be" (should be 4 results).
3. Filter the results by clicking the "Sensitive" or "Website" toggles a few times each.

### Actual results:
After the 2st or 3th click on the category filter buttons, certain results will disappear. On subsequent button presses, the filtered items don't return. So if you had 4 results, click on "Sensitive Breaches" twice, 2 results will disappear. Clicking again won't bring back the 2 missing sensitive breaches. Now if you do the same 2 clicks on "Website Breaches", those last 2 results disappear leaving you with a blank page. Only way to see results again is to refresh or click on the "Show all" button.

**Comment by lesleyjanenorton** [comment]
Fixed in #956
