### ISSUE TITLE
/breaches and /user/dashboard pages dont have HIBP citations

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#922]
## Steps to reproduce

1. Go to https://fx-breach-alerts.herokuapp.com/breaches
2. Scroll to the bottom of the page.
3. Log in and go to https://fx-breach-alerts.herokuapp.com/user/dashboard
4. Scroll to the bottom of the page.

### Actual results
No "Have I Been Pwned" citation.

---

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/57736054-83644980-765b-11e9-983c-ae9bb4f2d38b.png)
&mdash; 🔴 https://fx-breach-alerts.herokuapp.com/breaches

---

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/57736428-beb34800-765c-11e9-9f98-1153fe9af358.png)
&mdash; 🔴 https://fx-breach-alerts.herokuapp.com/user/dashboard

---

![https___fx-breach-alerts_herokuapp_com_breach-details_MySpace](https://user-images.githubusercontent.com/557895/57736234-0dacad80-765c-11e9-9c0c-29021896dad4.png)
&mdash; ✅ https://fx-breach-alerts.herokuapp.com/breach-details/MySpace

**Comment by lesleyjanenorton** [comment]
Fixed in #956 and #957
