### ISSUE TITLE
Replace breach logo images with favicons or other more uniformly squarish images.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#930]
This lovely 'breach card' (see attached) has been designed for us to use everywhere on the site, but our current logos are unpredictably sized, often white (disappear on white backgrounds), and are often horizontally oriented (would appear very squished on this card). We need to replace our current logo images with something more uniform. Images must be 1.) large enough to look right on the breach detail pages, 2.) Small enough to not be "soul-crushing" and 3.) of approximately equal height and width. Favicons have been suggested. 

Tried so far:
1.) Scraping from "Google Favicon Snatcher"
Result: Unusable, low quality, tiny images. Bad all around.

2.) Scraping from api.faviconkit.com (endpoints look like this: `https://api.faviconkit.com/www.breachDomain.com/192` where 192 can be subbed for whichever site-image size you're going for). 
Result: Got rate limited, but the images were mostly fantastic.
<img width="448" alt="Screen Shot 2019-05-14 at 10 35 34 PM" src="https://user-images.githubusercontent.com/22355127/57746915-e3c5ac00-7698-11e9-8802-856e2a4380d7.png">

**Comment by pdehaan** [comment]
It may be worth reaching out to the Activity Stream team or Pocket to see how they handle this for Top Sites, etc. We obviously don't want to rely on faviconkit at runtime and pointing to 3rd party domains, but we may need to see if scraping the icons and storing them locally or in Kinto/S3 is allowed.

In the meantime, I'll see if I can write a quick scraper with throttling to see if I can avoid rate limiting for the 363 current logos to see what the hit/miss rate is for favicons. I signed up for the service and checked out the website, but didn't see an obvious statement/FAQ about what the rate limits were or if I can generate an API key to increase a limit.

**Comment by lesleyjanenorton** [comment]
THANK YOU! Let me know how it goes. I also signed up to join the Beta, and I also couldn't locate anything pertaining to usage restrictions or guidelines.

**Comment by pdehaan** [comment]
OK, a few more updates before I forget my status.

Here's my starter code (I'll move it into a clean repo shortly and update this comment), but currently it's just a 403/429 factory.

<details>
<summary>Clicko expando!</summary>

```js
const fs = require("fs");
const path = require("path");

const axios = require("axios");

const client = axios.create({
  baseURL: "https://api.faviconkit.com/",
  responseType: "stream"
});

main();

async function main(breach) {
  const breaches = await axios.get("https://monitor.firefox.com/hibp/breaches");
  console.log(breaches.data.length);

  for (const breach of breaches.data.splice(29, 3)) {
    await fetchFavicon(breach);
  }
}

async function sleep(ms=1000) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function fetchFavicon(breach, size=144, timeout=2500) {
  if (!breach.Domain) return;
  try {
    const faviconPath = path.join(__dirname, "favicons", `${breach.Name}.png`);
    const faviconUrl = `https://api.faviconkit.com/?url=${breach.Domain}&size=${size}`;
    console.log(`Fetching ${faviconUrl} to ${faviconPath}`);
    const ico = await axios.get(faviconUrl);
    ico.data.pipe(fs.createWriteStream(faviconPath));
  } catch (err) {
    switch (err.response.status) {
      case 403:
      case 429:
      case 502:
        console.error(`[${err.response.status}] on ${breach.Name} :: ${breach.Domain} :: `); // ${err.data.responseUrl}`);
        console.error(err.response.data);
        break;
      default:
        console.error(err.response.status, err.message);
    }
  }
  await sleep(timeout);
}
```
</details>

I reached out to https://faviconkit.com/ and asked about getting an API key to hopefully improve quota limits. I haven't heard back yet, but I'll let you know when/if I do and can share the API key with you for testing purposes.

I was trying to remember what we did for ActivityStream "back in the day(tm)". I think initially we were using https://embed.ly/extract for the prototype. Eventually we moved to our own repos of [manually managed?] icons and colors, per https://github.com/mozilla/tippy-top-sites-deprecated. I cant remember if that was deprecated in favor of [**page-metadata-parser**](https://github.com/mozilla/page-metadata-parser), or if they switched to some other solution using [**fathom**](https://github.com/mozilla/fathom). I can try digging into it a bit more later this evening.
The thing about fathom and page-metadata-parser, is that they'd return the page's metadata. So if the target domains only list a 16x16 favicon, that's what we'd get back. It wouldn't create high-res icons or anything consistent for you, only return what the site provides. But we may get lucky and some of the sites could potentially have apple iOS icons or other fancy icons. I'm also pretty sure some of the HIBP domains are probably 404ing (or don't have a breach Domain to begin with), so we won't have 100% success, but hopefully a good enough start.

**Comment by lesleyjanenorton** [comment]
Sounds great, thank you so much for looking into this! I also wondered about scraping for apple iOS/other fancies first. I need to finish up rebuilding these cards, working out those filtering quirks, and working out some of the other UI issues today and then will also do some digging on this.

**Comment by pdehaan** [comment]
No real updates. Never heard back from my email to faviconkit.com re: API keys.

When the server does work, it doesn't always generate the high-res icons you request. For example, the Appartoo domain logo comes back as a 16x16 favicon looking thing, so it looks pretty terrible when it gets stretched to 144x144. So I'm guessing the service is either trying to extract higher res icons from from other metadata, or is hardcoding some high quality icons for the top tier sites.
https://api.faviconkit.com/appartoo.com/144

---

I did try using our [**page-metadata-parser**](http://npm.im/page-metadata-parser) npm module to extract optimal favicons, but you cant always guarantee a site is still live, or the favicon is any bigger than the 16x16 favicon.ico.

This takes forever to finish (363 breaches) and doesn't actually finish (which is why I rewrite the OUTPUT.json file after every loop instead of just waiting for the script to finish):

```js
const fs = require("fs");

const domino = require("domino");
const got = require("got");
const {getMetadata} = require("page-metadata-parser");

main();

async function main() {
  const breaches = await getBreaches();
  const data = [];
  let idx = 1;
  for (const breach of breaches) {
    const preMS = Date.now();
    try {
      const metadata = await scrape(breach);
      console.log(`${idx}/${breaches.length} -- ${breach.Title} (time: ${duration(preMS)}s)`);
      data.push({
        name: breach.Name,
        domain: breach.Domain,
        metadata
      });
    } catch (err) {
      console.error(`${idx}/${breaches.length} -- ${breach.Title} :: ${err.message} (time: ${duration(preMS)}s)`);
      data.push({
        name: breach.Name,
        domain: breach.Domain,
        err: err.message
      });
    }
    idx += 1;
    fs.writeFileSync("OUTPUT.json", JSON.stringify(data, null, 2));
  }
}

function duration(startMS, endMS=Date.now()) {
  return ((endMS - startMS) / 1000).toFixed(2);
}

async function getBreaches() {
  const res = await got.get("https://monitor.firefox.com/hibp/breaches", {json: true});
  return res.body;
}

async function scrape(breach) {
  if (!breach.Domain) {
    throw new Error(`${breach.Name} doesn't have a domain`);
  }
  const url = `http://${breach.Domain}`;
  try {
    const response = await got.get(url, {timeout: 2000, retry: 1});
    const html = await response.body;
    const doc = domino.createWindow(html).document;
    return getMetadata(doc, url);
  } catch (err) {
    throw new Error(`${breach.Name}: ${err.message}`);
  }
}
```

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
