### ISSUE TITLE
Consider changing copy for "Global Communication" preference to "Send breach alerts to the affected email address."

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#933]
While working on #931 I saw the code has 2 different strings for the first option under "Global Communication" ...

"Send breach alerts to the affected email address."
"Email me if one of my email addresses below appears in a data breach."

[The InVision screen mock-up](https://mozilla.invisionapp.com/d/main#/console/17259755/360139917/comments) indicates using the latter string, which is what we're doing ...

![image](https://user-images.githubusercontent.com/71928/57790514-82d1be80-7700-11e9-8177-283a6819ec27.png)

But it seems like we should be using the former string. I.e., no matter which option is picked, we are going to "Email if one of the addresses below appears in a data breach", and the preference for the user is much more clear when using the former string.

![image](https://user-images.githubusercontent.com/71928/57790681-db08c080-7700-11e9-9393-9feff1d85ca2.png)

**Comment by betsymi** [comment]
The second option is much more clear. 

Send breach alerts to the affected email address
Send all breach alerts to lcrouch@mozilla.com

Does that clear things up?

**Comment by groovecoder** [comment]
Yes, thanks. I'm dropping the "needs:UX" label and pulling this into the project for prioritization of V2 work.

**Comment by lesleyjanenorton** [comment]
@flodolo The feeling is that the first option under "Global Communication" is unclear. The copy has since been revised and I'm not sure how we should proceed. Would it be better to add this new string in now and wait until after launch, once it's had a chance to be localized, to implement it? Or should we wait until after launch to introduce the new string?

**Comment by flodolo** [comment]
> Or should we wait until after launch to introduce the new string?

I'd prefer to avoid creating unnecessary noise. It all depends on how long you can wait to have this though, once exposed you'll need to wait a few more days to expose it to production.

**Comment by lesleyjanenorton** [comment]
@flodolo I think we'd like to have it as soon as possible, but would certainly like to avoid creating additional noise. When do you think we'd be able to add this without causing too much grief?

**Comment by flodolo** [comment]
I see two options:
- You expose the string right now (I mean, literally now), and decide if you can use it a couple of days before release, based on how many languages are done.
- June 5th.

If we really need, let's land it, but every hour counts.

**Comment by groovecoder** [comment]
IMO we really need it - the "send all alerts to a single email inbox" feature makes no sense without this change. And it's one of the features we're including in the Monitor section(s) of Trailhead blog posts.
