### ISSUE TITLE
Expose “Signed in as:” string

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/blurts-server#936]
Sorry for piling up issues, but I just realized this string in the menu was missing in the .ftl file

<img width="205" alt="Capture d’écran 2019-05-15 à 18 48 27" src="https://user-images.githubusercontent.com/1294206/57797627-be8d7800-7742-11e9-8e38-5e31e81a359e.png">

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/blurts-server/blob/d0a65ce180555590dc89de5ec2c2dcd8cab49bec/views/partials/header/fxa-menu.hbs#L7
