### ISSUE TITLE
Localize “Enter Email Adress” placehoder

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/blurts-server#937]
I’m pretty sure there’s no dedicated string for this placeholder, but the good news if that you should be able to reuse `scan-placeholder` from the homepage as it’s the very same context.

![Screenshot_2019-05-15 Vérifiez si vous êtes concerné⋅e par une fuite de données](https://user-images.githubusercontent.com/1294206/57798224-2db79c00-7744-11e9-80e5-7c27efa4abd2.png)

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/blurts-server/blob/d0a65ce180555590dc89de5ec2c2dcd8cab49bec/views/partials/forms/add-another-email-form.hbs#L3
