### ISSUE TITLE
Consolidate get[Subscriber|EmailAddresses]By___ functions into a single get[Subscriber|EmailAddresses] function

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#942]
While adding an `email_addresses` property to the `subscriber` object returned by our `getSubscriberBy__` functions, I realized we should refactor all of our `getSubscriberBy__` functions into a single `getSubscriber` function.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
