### ISSUE TITLE
Can’t change email preferences from Firefox Account

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#952]
**Affected versions:**
- Firefox 67.0

**Affected Platforms:**
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

**Steps to reproduce:**
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Sign in with a valid account. 
3. Click on the profile picture and select Firefox Account.
4. Look down the page and click on "Change..." button from the "Email preferences" section.

**Expected result:**
- The email preferences are displayed. 

**Actual result:**
- An error is displayed on the page. 

**Additional Notes:**
- If you try to make this change from sync the issue is not reproducing. 
- Please look at the attached gif:
![email preferences ](https://user-images.githubusercontent.com/42799381/57933399-e9eca000-78c5-11e9-9d81-070841508340.gif)

**Comment by groovecoder** [comment]
Another bug on the Firefox Account side. @mozilla/fxa-qa - can this be copied over to the right repo?
