### ISSUE TITLE
After you change the profile image the "Go back a page" button doesn't work

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#953]
**Affected versions:**
- Firefox 67.0

**Affected Platforms:**
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

**Steps to reproduce:**
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Sign in with a valid account. 
3. Click on the profile picture and select Firefox Account.
4. Click on "Change..." button from the "Account picture" section.
5. Change picture and click on "Done".
6. From the URL bar, click on "Go back a page button". 

**Expected result:**
- The email preferences are displayed. 

**Actual result:**
- An error is displayed on the page. 

**Additional Notes:**
- This issue is not reproducing when you remove the image. 
- Please look at the attached gif:
![change image](https://user-images.githubusercontent.com/42799381/57934382-48b31900-78c8-11e9-9ec7-21df1e1b3e02.gif)

**Comment by groovecoder** [comment]
This is an error on the Firefox Accounts side. @mozilla/fxa-qa might be able to file this in the right repo.
