### ISSUE TITLE
In Firefox Account, letters like “g”, “q” and "y" have the bottom part cut off. 

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#954]
**Affected versions:**
- Firefox 67.0

**Affected Platforms:**
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

**Steps to reproduce:**
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Sign in with a valid account. 
3. Click on the profile picture and select Firefox Account.
4. Look at the email address. 

**Expected result:**
- The letters are all displayed correctly. 

**Actual result:**
- The bottom part of the letters "g", "q" and "y" is cut off.  

**Additional Notes:**
- If you to sync the issue is not reproducing. 
- Please look at the image:
![pic13](https://user-images.githubusercontent.com/42799381/57934969-6b91fd00-78c9-11e9-94fc-31b48d1e1dd5.png)

**Comment by groovecoder** [comment]
Is this on the https://stable.dev.lcip.org/settings page? If so, it's probably another bug on the Firefox Account side.

**Comment by groovecoder** [comment]
This is on the FxA side. Pinging @mozilla/fxa-core to check it out.
