### ISSUE TITLE
"See if you were in this breach" is mis-leading

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#959]
STR:

1. Go to home page
2. Under "Latest breach added", click "See if you were in this breach" (e.g., OGUsers)
3. Land on breach details page for the breach (e.g., http://localhost:6060/breach-details/OGUsers)

Expected results:
There should be a scan form on the page so I can see if I was in the breach.

Actual results:
No scan form on the page?

**Comment by betsymi** [comment]
It can go to breach alert promo, e.g. https://fx-breach-alerts.herokuapp.com/?breach=OGUsers
