### ISSUE TITLE
Missing date label on /breaches page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#965]
## STR:

1. Go to https://fx-breach-alerts.herokuapp.com/breaches
2. Scroll through breaches.

### Actual results:
We display the date twice, but I'm not sure if it's a BreachDate or AddedDate.

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58112227-ef890500-7ba7-11e9-925e-f4831342416c.png)

---

**UPDATE:** I'm guessing it's the "Breach reported" date, since that's what we show on the homepage's "Latest Breach Added" block:

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58112292-10e9f100-7ba8-11e9-858c-a7f9a0632dcb.png)

... and on the logged in version:

![Firefox_Monitor](https://user-images.githubusercontent.com/557895/58112436-5e665e00-7ba8-11e9-9f79-1d3c809dcccf.png)

**Comment by betsymi** [comment]
Confirmed that added date is correct. Here is design spec for reference. 

![image](https://user-images.githubusercontent.com/43555492/58123611-d6954980-7bd1-11e9-9fa8-1587fa64baec.png)
