### ISSUE TITLE
Missing string for "must-be-signed-in"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#966]
## STR:
1. Log into Monitor in browser A.
1. Add a secondary email address.
1. Log into email for secondary address in browser B.
1. Click verification link.

### Actual results:

Clicking the verification link (https://fx-breach-alerts.herokuapp.com/user/verify?token=blah-blah-blah) takes you to a sparse page that just says "Error" and apparently a missing "must-be-signed-in"  string in the app.ftl file:

![https___fx-breach-alerts_herokuapp_com_user_verify_token_30591d48-16c0-4b90-a16c-4220e551c4c0](https://user-images.githubusercontent.com/557895/58113842-4e03b280-7bab-11e9-8306-34df06acc5ce.png)

**Comment by pdehaan** [comment]
I just hit this in production, where:
1. I was logged into dev.
2. Realized I was on the wrong server.
3. Modified the URL from Heroku to https://monitor.firefox.com/user/dashboard
4. Got the above "must-be-signed-in" page since I wasn't signed into production earlier, only dev server.

Would be nice to get the missing string added. Not sure if we should automatically redirect non-logged in users back to the homepage. But not sure if that may cause some potential weird endless redirect loop.

**Comment by betsymi** [comment]
**You must be signed in to your Firefox Account.**
To finish verifying this email for Firefox Monitor, you must be signed in under your primary account email.
