### ISSUE TITLE
On breach detail page, add colon after What to do after a data breach:

### ISSUE THREAD

**Issue by betsymi** [mozilla/blurts-server#969]
To be consistent with **What data was compromised:** and **Additional information, including:**, add colon after **What to do after a data breach:**

![image](https://user-images.githubusercontent.com/43555492/58124070-f37e4c80-7bd2-11e9-886e-165dab298c61.png)

**Comment by lesleyjanenorton** [comment]
@flodolo can I manually update this string for en locales?

**Comment by flodolo** [comment]
Given how late this is, yes. Otherwise we would lose all existing translations.
