### ISSUE TITLE
White pixel is displayed on the upper left side of the website

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#977]
**Affected versions:**
- Firefox 67.0

**Affected Platforms:**
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

**Steps to reproduce:**
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Click on the "Find Out" button.
3. Inspect the upper left part of the website.

**Expected result**:
- No white pixel is displayed on the website (upper left part).

**Actual result:**
- A white pixel appear on the upper left side of the website.

**Additional notes**:
- please observe the following screenshot:
![image](https://user-images.githubusercontent.com/43886441/58155730-28df7480-7c7d-11e9-9132-438bb5aabf08.png)

**Comment by pdehaan** [comment]
Great eyes! I think this is fixed via pending #975 PR.

**Comment by lesleyjanenorton** [comment]
Fixed in #975

**Comment by GeorgiuCiprian** [comment]
This is verified as fixed on Firefox 67.0 using herokuapp. Tested on across platforms: Win 10 x64, macOS 10.13 and Ubuntu 16.04 x64.
