### ISSUE TITLE
The email address is cut off in the profile dashboard if the FF window is resized 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#978]
**Affected versions:**
- Firefox 67.0

**Affected Platforms:**
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

**Steps to reproduce:**
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Sign in with a valid account to Firefox Monitor.
3. Resize the https://fx-breach-alerts.herokuapp.com/user/dashboard page to its minimum size or to half of its default size.

**Expected result**:
- The email address is properly displayed.

**Actual result:**
- The email address appear as cut off.

**Additional notes**:
- please observe the following screenshot:

![image](https://user-images.githubusercontent.com/43886441/58162072-233c5b80-7c8a-11e9-8ab8-18a7447df07f.png)

**Comment by SorinaFlorean** [comment]
This is reproducible also on Android devices, both portrait and landscape mode.

**Comment by GeorgiuCiprian** [comment]
This is verified as fixed on Firefox 67.0 using herokuapp. Tested on across platforms: Win 10 x64, macOS 10.13 and Ubuntu 16.04 x64.
