### ISSUE TITLE
The text below the "Sign up for Alerts" button has the font too small compared to the specs

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#979]
**Affected versions:**
- Firefox 67.0

**Affected Platforms:**
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

**Steps to reproduce:**
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Scroll down the page to the "Sign up for Alerts" button.
3. Inspect the "Firefox browser not required for a Firefox Account. You may receive info about Mozilla services." text.

**Expected result**:
- The text has a more readable size font, it seems to be at 8px currently; maybe a 10px would look better?

**Actual result:**
- The text is hardly readable, it has a very small size compared to the specs.

**Additional notes**:
- please observe the following comparison:
- current behavior with the font size at **8px.**
![image](https://user-images.githubusercontent.com/43886441/58170046-0eb48f00-7c9b-11e9-9b35-d38addfa8708.png) 
- expected behavior with the font size at **10px.**
![image](https://user-images.githubusercontent.com/43886441/58170277-a1552e00-7c9b-11e9-9470-adb78ee3b137.png)

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/blurts-server/blob/c25f2ab1b3f286e1fdd10abfef84610cf5cdc1af/public/css/sign-up-banner.css#L89-L90
