### ISSUE TITLE
Extra space between "." and the breached website

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/blurts-server#981]
**Affected versions:**
- Firefox 67.0

**Affected Platforms:**
- Windows 10 x64
- macOS 10.13
- Ubuntu 18.04 x64

**Steps to reproduce:**
1. Navigate to https://fx-breach-alerts.herokuapp.com/?breach=adobe
2. Scan the following email address: test@gmail.com

**Expected result**:
- There's no extra space between "Adobe" and ".". 

**Actual result:**
- There's an extra space between "Adobe" and ".". 

**Additional notes**:
- please see the screenshot:
![image](https://user-images.githubusercontent.com/43886441/58175035-e7b08a00-7ca7-11e9-9c4d-de12001d55a1.png)

**Comment by pdehaan** [comment]
I did some looking this morning, and I _think_ this is coming from the `function fluentNestedBold(id, args) {...}` function, which is adding leading+trailing spaces around the `<span>` tag, which is adding the space and occasionally cause the period to be orphaned on it's own line (ref: #980).

https://github.com/mozilla/blurts-server/blob/dc321a47aa68eb4718795f9e433fb8b46f0b8b67/template-helpers/hbs-helpers.js#L72-L74

**Comment by lesleyjanenorton** [comment]
Fixed in #983

**Comment by GeorgiuCiprian** [comment]
This is verified as fixed on Firefox 67.0 using herokuapp. Tested on across platforms: Win 10 x64, macOS 10.13 and Ubuntu 16.04 x64.
