### ISSUE TITLE
Remove Monitor does not seem to remove the service from the Account client list

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#992]
I signed into monitor (https://fx-breach-alerts.herokuapp.com/) and confirmed the "blurts-heroku" is added to the list: https://stable.dev.lcip.org/settings/clients

I then opted to "remove Monitor". When I return to this client list, I still see "blurts-heroku" in the list even after refreshing several times
![Screenshot_2019-05-23 Firefox Accounts Devices apps(1)](https://user-images.githubusercontent.com/850418/58272428-b9848600-7d4b-11e9-8eb4-4c9b7b904a37.png)

**Comment by sandysage** [comment]
The ideal here would be to show Monitor as a service that is no longer connected versus removing it from the list.

For the upcoming release, I just need to confirm that if someone removes Monitor that they will not continue to get Monitor emails from us. We can always come back to how this shows up in the list post-launch

**Comment by groovecoder** [comment]
I'm 99% sure there's not a way to show Monitor as a service that is no longer connected. @mozilla/fxa-core ?

Also @mozilla/fxa-core - I'll start debugging our call to `/v1/destroy` with the `refresh_token` param, but do you know if we should expect a delay between the time we call `/v1/destroy` and when our app is removed from this list?

**Comment by rfk** [comment]
> as a service that is no longer connected.

This state does not (currently) exist in FxA, although we've talked about similar things in the past.

> I'll start debugging our call to /v1/destroy with the refresh_token param, but do you know if
> we should expect a delay between the time we call /v1/destroy and when our app is removed
> from this list?

Hrm...calling `destroy` on the `refresh_token` might still leave some `access_token`s active, and you will remain the list until those tokes expire, which I think currently takes a couple of days. If you *also* call `destroy` on any `access_token`s when you're finished using them, you should disappear from the list.

**Comment by rfk** [comment]
(I think it would be reasonable for FxA to revoke all `access_token`s issued by a `refresh_token` automatically when that token is destroyed, but it doesn't right now)

**Comment by groovecoder** [comment]
Can you file that as an issue in the right repo for us? Until then, I'll look at making our revoke destroy the access tokens too.

**Comment by rfk** [comment]
Related question - if a user signed in to Monitor twice (say on two different machines) then do you end up with two separate refresh tokens?

**Comment by rfk** [comment]
> Can you file that as an issue in the right repo for us?

The good news is there's only a single FxA repo these days; I filed it here:

  https://github.com/mozilla/fxa/issues/1249
