### ISSUE TITLE
Consider adding the email address to the unsubscribe page

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#994]
Maybe between the `pref-section-headline` and `subhead` ?

![image](https://user-images.githubusercontent.com/71928/58276507-3f5cfd00-7d5d-11e9-8c55-5f19ad98a426.png)

**Comment by groovecoder** [comment]
Note: without the email address, the user may not be sure which email address they're about to unsubscribe.

**Comment by pdehaan** [comment]
Bonus points if we can do this without changing any strings or causing any l10n impact.

**Comment by betsymi** [comment]
Not possible to do this without a string change. Change headline to:

Unsubscribe [email] from Firefox Monitor?

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
